- AlphaWallet/Settings/Types/Constants.swift
- AlphaWallet/Transfer/Controllers/TransactionConfigurator.swift
> Display congested/high gas warning for Ethereum mainnet again, at 130Gwei

- AlphaWalletTests/Extensions/URLTests.swift
- modules/AlphaWalletCore/AlphaWalletCore/WebImageURL.swift
> Fix web image URL override issue '=s' is missing #3933

- AlphaWallet/Market/Coordinators/ImportMagicLinkCoordinator.swift
- AlphaWallet/Settings/Types/RPCServers.swift
> Remove `labelForCurrencyDrops` from ImportMagicLinkCoordinator #3924

- AlphaWallet/TokenScriptClient/Models/AssetAttributeSyntaxValue.swift
- AlphaWallet/Tokens/Types/TokenHolder.swift
> Refactor `traitsAssetInternalValueValue` with `traitsValue` #3936

- AlphaWallet/Market/Coordinators/ImportMagicLinkCoordinator.swift
- AlphaWallet/Tokens/Coordinators/GetERC20BalanceCoordinator.swift
- AlphaWallet/Tokens/Coordinators/GetERC721BalanceCoordinator.swift
- AlphaWallet/Tokens/Coordinators/GetERC721ForTicketsBalanceCoordinator.swift
- AlphaWallet/Tokens/Coordinators/GetERC875BalanceCoordinator.swift
- AlphaWallet/Tokens/Coordinators/GetNativeCryptoCurrencyBalanceCoordinator.swift
> Remove `CallbackQueueProvider` protocol, remove GetERC875BalanceCoordinator callback implementation #3939

- AlphaWallet/TokenScriptClient/Models/EventsDataStore.swift
- AlphaWallet/Tokens/Helpers/TokenAdaptor.swift
- AlphaWalletTests/TokenScriptClient/FakeEventsDataStore.swift
> Refactor TokenAdaptor with replacing single instance `XMLHandler` #3935

- AlphaWallet/Tokens/Collectibles/Coordinators/TokensCardCollectionCoordinator.swift
- AlphaWallet/Tokens/Coordinators/SingleChainTokenCoordinator.swift
- AlphaWallet/Tokens/ViewControllers/TokenInstanceActionViewController.swift
- AlphaWallet/Tokens/ViewControllers/TokenInstanceViewController.swift
- AlphaWallet/Tokens/ViewControllers/TokensCardViewController.swift
- AlphaWallet/Transactions/Coordinators/TokensCardCoordinator.swift
> Remove unused IsReadOnlyViewController.isReadyOnly #3929

- AlphaWallet/Activities/Coordinators/ActivitiesCoordinator.swift
- AlphaWallet/InCoordinator.swift
> Remove unused tokensStorages, assetDefinitionStore, analyticsCoordinator dependencies from ActivitiesCoordinator #3951

- AlphaWallet/Activities/ActivitiesService.swift
> Move activitiesForThisCard filtering for aETHMinted event into loop, to avoid double filtering of array #3953

- AlphaWallet/Activities/ActivitiesService.swift
- AlphaWallet/TokenScriptClient/Models/EventsActivityDataStore.swift
> Replace .getRecentEvents with .getRecentEventsSortedByBlockNumber for related events for each card. #3955

- AlphaWallet/Tokens/ViewControllers/TokenInstanceViewController.swift
> Fix crash when send non fungible #3959

- AlphaWallet/Browser/Coordinators/QRCodeResolutionCoordinator.swift
- AlphaWallet/Core/Coordinators/PaymentFlowFromEip681UrlResolver.swift
- AlphaWallet/Tokens/Collectibles/ViewControllers/TokensCardCollectionViewController.swift
- AlphaWallet/Tokens/Coordinators/TokensCoordinator.swift
- AlphaWallet/Tokens/ViewControllers/TokenInstanceViewController.swift
- AlphaWallet/Tokens/ViewControllers/TokensCardViewController.swift
- AlphaWallet/Transactions/Coordinators/TokensCardCoordinator.swift
- AlphaWallet/Transfer/Types/TransactionType.swift
- AlphaWallet/Transfer/ViewControllers/SendViewController.swift
> Refactor `TransactionType` initializer for each `fungible` and `nonFungible` token types #3961

- AlphaWallet/Core/Views/ButtonsBar/ButtonsBar.swift
> Added missing disabledButtonTitleColor attribute to ButtonsBar static variables

- AlphaWallet/TokenScriptClient/Coordinators/EventSourceCoordinator.swift
- AlphaWallet/TokenScriptClient/Coordinators/EventSourceCoordinatorForActivities.swift
- AlphaWallet/TokenScriptClient/Models/EventsActivityDataStore.swift
- AlphaWallet/TokenScriptClient/Models/EventsDataStore.swift
- AlphaWalletTests/TokenScriptClient/FakeEventsDataStore.swift
> Remove Promise from `add(events:)` functions #3957

- AlphaWallet/Tokens/Coordinators/GetInterfaceSupported165Coordinator.swift
> Remove unused version of function `getInterfaceSupported165` #3968

- AlphaWallet/TokenScriptClient/Coordinators/EventSourceCoordinator.swift
- AlphaWallet/Tokens/Logic/Erc1155TokenIdsFetcher.swift
> Reduce amount of map functions for promises #3970

- AlphaWallet/TokenScriptClient/Models/EventsActivityDataStore.swift
- AlphaWallet/TokenScriptClient/Models/EventsDataStore.swift
- AlphaWallet/Tokens/Types/TokensDataStore.swift
> Add guard checks for empty arrays when write to realm #3978

- AlphaWallet/TokenScriptClient/Models/EventsActivityDataStore.swift
- AlphaWallet/TokenScriptClient/Models/EventsDataStore.swift
- AlphaWallet/Tokens/Types/TokensDataStore.swift
- AlphaWallet/Transactions/Storage/TransactionsStorage.swift
> Replace multiple filters in EventsActivityDataStore, EventsDataStore with single predicate #3981

- AlphaWallet/Activities/ActivitiesService.swift
- AlphaWallet/Foundation/Subscribable.swift
- AlphaWallet/TokenScriptClient/Models/AssetAttributesCache.swift
- AlphaWallet/TokenScriptClient/Models/CallForAssetAttributeCoordinator.swift
- AlphaWallet/TokenScriptClient/Models/XMLHandler.swift
- modules/AlphaWalletAddress/AlphaWalletAddress/ThreadSafeDictionary.swift
> Make CallForAssetAttributeCoordinator, XMLHandler nonThreadSafe #3984

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet/Localization/en.lproj/Localizable.strings
- AlphaWallet/Localization/es.lproj/Localizable.strings
- AlphaWallet/Localization/fi.lproj/Localizable.strings
- AlphaWallet/Localization/ja.lproj/Localizable.strings
- AlphaWallet/Localization/ko.lproj/Localizable.strings
- AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings
- AlphaWallet/Settings/Coordinators/SettingsCoordinator.swift
- AlphaWallet/Settings/ViewControllers/AdvancedSettingsViewController.swift
- AlphaWallet/Settings/ViewControllers/ToolsViewController.swift
- AlphaWallet/Settings/ViewModels/AdvancedSettingsViewModel.swift
- AlphaWallet/Settings/ViewModels/ToolsViewModel.swift
> Move troubleshooting tools into new Settings > Advanced > Tools

- AlphaWalletTests/Extensions/URLTests.swift
> Delete or fix commented out test related to WebImageURL #3943

- AlphaWallet/Core/Device.swift
- AlphaWallet/KeyManagement/DefaultsWalletAddressesStore.swift
- AlphaWallet/Tokens/Coordinators/TokensCoordinator.swift
- AlphaWallet/Tokens/Types/TokensDataStore.swift
> Remove warnings #3983

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet/AppCoordinator.swift
- AlphaWallet/Browser/Coordinators/DappBrowserCoordinator.swift
- AlphaWallet/Browser/Coordinators/DappRequestSwitchCustomChainCoordinator.swift
- AlphaWallet/Browser/Coordinators/DappRequestSwitchExistingChainCoordinator.swift
- AlphaWallet/Browser/Types/DappCommand.swift
- AlphaWallet/InCoordinator.swift
- AlphaWallet/Settings/Types/Constants.swift
- AlphaWallet/Settings/Types/RPCServers.swift
- AlphaWallet/WalletConnect/Coordinator/WalletConnectCoordinator.swift
- AlphaWallet/WalletConnect/Providers/v1/Types/SingleServerWalletConnectSession.swift
- AlphaWallet/WalletConnect/Providers/v1/WalletConnectV1Provider.swift
- AlphaWallet/WalletConnect/Providers/v2/WalletConnectV2Provider.swift
- AlphaWallet/WalletConnect/Providers/v2/WalletConnectV2Types.swift
- AlphaWallet/WalletConnect/Types/JSONRPC_2_0.swift
- AlphaWallet/WalletConnect/Types/WalletConnect.swift
- AlphaWallet/WalletConnect/Types/WalletConnectActionType.swift
- AlphaWallet/WalletConnect/Types/WalletConnectRequestConverter.swift
- AlphaWallet/WalletConnect/Types/WalletConnectServerRequest.swift
- AlphaWallet/WalletConnect/WalletConnectServer.swift
- AlphaWallet/WalletConnect/WalletConnectServerProvider.swift
- AlphaWalletTests/Coordinators/AppCoordinatorTests.swift
- AlphaWalletTests/Coordinators/InCoordinatorTests.swift
- AlphaWalletTests/Settings/ConfigTests.swift
- AlphaWalletTests/Settings/Coordinators/SettingsCoordinatorTests.swift
>     Integrate support `wallet_switchEthereumChain` and `wallet_addEthereumChain` calls for WalletConnect

- AlphaWallet/Tokens/Types/TokenObject.swift
> Display symbol name instead of token name if name is longer than symbol #3891

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet/KeyManagement/DefaultsWalletAddressesStore.swift
- AlphaWallet/KeyManagement/EtherKeystore.swift
- AlphaWallet/KeyManagement/JsonWalletAddressesStore.swift
- AlphaWallet/KeyManagement/WalletAddressesStore.swift
> Update WalletStoreType according name convention #4027

- AlphaWallet/KeyManagement/DefaultsWalletAddressesStore.swift
- AlphaWallet/KeyManagement/EtherKeystore.swift
- AlphaWallet/KeyManagement/JsonWalletAddressesStore.swift
- AlphaWallet/KeyManagement/WalletAddressesStore.swift
> Add walletsPublisher to walletAddressesStore #4032

- AlphaWallet/Activities/ViewModels/DefaultActivityCellViewModel.swift
- AlphaWallet/Core/Helpers/BlockieGenerator.swift
- AlphaWallet/Core/PopularTokens/PopularTokensCollection.swift
- AlphaWallet/Tokens/Collectibles/ViewModels/NonFungibleRowViewModel.swift
- AlphaWallet/Tokens/Collectibles/ViewModels/TokensCardCollectionInfoPageViewModel.swift
- AlphaWallet/Tokens/Collectibles/Views/NonFungibleRowView.swift
- AlphaWallet/Tokens/Types/NonFungibleFromJson.swift
- AlphaWallet/Tokens/Types/TokenHolder.swift
- AlphaWallet/Tokens/Types/TokenObject.swift
- AlphaWallet/Tokens/ViewModels/EthTokenViewCellViewModel.swift
- AlphaWallet/Tokens/ViewModels/FungibleTokenViewCellViewModel.swift
- AlphaWallet/Tokens/ViewModels/NonFungibleTokenViewCellViewModel.swift
- AlphaWallet/Tokens/ViewModels/OpenSea/OpenSeaNonFungibleTokenViewCellViewModel.swift
- AlphaWallet/Tokens/ViewModels/OpenSeaNonFungibleTokenCardRowViewModel.swift
- AlphaWallet/Tokens/ViewModels/TokenInstanceInfoPageViewModel.swift
- AlphaWallet/Tokens/ViewModels/WalletTokenViewCellViewModel.swift
- AlphaWallet/Tokens/Views/OpenSea/OpenSeaNonFungibleTokenCardRowView.swift
- AlphaWallet/Transactions/ViewModels/ActivityViewModel.swift
- AlphaWallet/Transfer/ViewModels/SendHeaderViewViewModel.swift
- AlphaWallet/UI/TokenObject+UI.swift
- AlphaWallet/UI/Views/AmountTextField.swift
- modules/AlphaWalletCore/AlphaWalletCore/WebImageURL.swift
> If there's a significant impact to using GoogleContentSize.s750 for all images hosted by Google #3944

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet/Activities/Coordinators/ActivitiesCoordinator.swift
- AlphaWallet/Browser/Coordinators/DappBrowserCoordinator.swift
- AlphaWallet/Core/ViewModels/InCoordinatorViewModel.swift
- AlphaWallet/Extensions/UINavigationController.swift
- AlphaWallet/InCoordinator.swift
- AlphaWallet/Settings/Coordinators/SettingsCoordinator.swift
- AlphaWallet/Style/AppStyle.swift
- AlphaWallet/Tabs.swift
- AlphaWalletTests/Coordinators/InCoordinatorTests.swift
- AlphaWalletTests/Core/ViewModels/InCoordinatorViewModelTests.swift
> Reduce incoordinator size, move Tabs model to separate file #4024

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet/Core/Coordinators/TokensFilter.swift
- AlphaWallet/Tokens/Coordinators/AddHideTokensCoordinator.swift
- AlphaWallet/Tokens/Coordinators/SelectTokenCoordinator.swift
- AlphaWallet/Tokens/Coordinators/TokensCoordinator.swift
- AlphaWallet/Tokens/Types/TokenCollection.swift
- AlphaWallet/Tokens/ViewControllers/SelectTokenViewController.swift
- AlphaWallet/Tokens/ViewControllers/TokensViewController.swift
- AlphaWallet/Tokens/ViewModels/AddHideTokensViewModel.swift
- AlphaWallet/Tokens/ViewModels/SelectTokenViewModel.swift
- AlphaWallet/Tokens/ViewModels/TokensViewModel.swift
> Rename FilterTokensCoordinator with TokensFilter #4042

- AlphaWallet/Tokens/ViewControllers/TokensViewController.swift
Especially useful during development + simulator
Press cmd+f:
> Add cmd+f keyboard shortcut in Wallet tab to trigger search

- AlphaWallet/Settings/Coordinators/PingInfuraCoordinator.swift
> Infura Error on iOS #3870

- AlphaWallet/Core/CoinTicker/CoinTickersFetcher.swift
- AlphaWallet/Core/Coordinators/WalletBalance/WalletBalanceCoordinator.swift
> Fetching prices for chains: Avax, Fantom, bnb #3888

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet/Core/Helpers/RestartQueueHandler.swift
- AlphaWallet/InCoordinator.swift
> Move processRestart queue to separate class, reduce in coordinator size #4051

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet.xcworkspace/xcshareddata/swiftpm/Package.resolved
- AlphaWallet/AppCoordinator.swift
- AlphaWallet/InCoordinator.swift
- AlphaWallet/Settings/Types/Constants.swift
- AlphaWallet/WalletConnect/Coordinator/WalletConnectCoordinator.swift
- AlphaWallet/WalletConnect/Providers/v1/WalletConnectV1Provider.swift
- AlphaWallet/WalletConnect/Providers/v2/WalletConnectV2Provider.swift
- AlphaWallet/WalletConnect/WalletConnectServer.swift
- AlphaWallet/WalletConnect/WalletConnectServerProvider.swift
- AlphaWalletTests/Settings/ConfigTests.swift
> Support for update WalletConnect v2 SDK #3989

- AlphaWallet/Settings/ViewModels/SettingsViewModel.swift
> Middle truncate the address even when there's no ENS in Settings > Change / Add Wallet. #4050

- AlphaWallet/WalletConnect/Types/EIP712TypedData.swift
> Remove force unwrap when encodeType(primaryType for `EIP712Domain` and `EIP712Domain` is missing in typed data #4057

- AlphaWallet/InCoordinator.swift
- AlphaWallet/TokenScriptClient/Coordinators/EventSourceCoordinator.swift
- AlphaWallet/TokenScriptClient/Coordinators/EventSourceCoordinatorForActivities.swift
- AlphaWallet/Tokens/Coordinators/TokensCoordinator.swift
> Delay subscribing for tokens updates for events creating #4066

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet/Alerts/ViewControllers/EditPriceAlertViewController.swift
- AlphaWallet/AppCoordinator.swift
- AlphaWallet/Core/TokenBalanceService.swift
- AlphaWallet/Export/Coordinators/PromptBackupCoordinator.swift
- AlphaWallet/InCoordinator.swift
- AlphaWallet/Market/Coordinators/ImportMagicLinkCoordinator.swift
- AlphaWallet/Sell/ViewControllers/EnterSellTokensCardPriceQuantityViewController.swift
- AlphaWallet/Tokens/ViewControllers/SelectTokenViewController.swift
- AlphaWallet/Tokens/ViewControllers/TokenViewController.swift
- AlphaWallet/Tokens/ViewControllers/TokensViewController.swift
- AlphaWallet/Tokens/ViewModels/TokenViewControllerViewModel.swift
- AlphaWallet/Transactions/Storage/Session.swift
- AlphaWallet/Transactions/ViewControllers/TransactionViewController.swift
- AlphaWallet/Transfer/ViewControllers/SendViewController.swift
- AlphaWallet/Transfer/ViewControllers/TransactionConfirmationViewController.swift
- AlphaWallet/Transfer/ViewModels/ConfigureTransactionViewModel.swift
- AlphaWallet/Transfer/ViewModels/SendViewModel.swift
- AlphaWalletTests/Factories/WalletSession.swift
- AlphaWalletTests/Transfer/ViewControllers/SendViewControllerTests.swift
> Rename `BalanceCoordinator` with `TokenBalanceService` #4070

- AlphaWallet/Alerts/Views/PriceAlertsPageView.swift
- AlphaWallet/Tokens/Coordinators/TokensCoordinator.swift
- AlphaWallet/Tokens/ViewControllers/TokensViewController.swift
- AlphaWallet/Tokens/ViewModels/TokensViewModel.swift
> Remove unused serverToAddCustomTokenOn, move views heights calculations to view model for tokens screen, move Section type to view viewmodel #4084

- AlphaWallet/AppCoordinator.swift
- AlphaWallet/AppDelegate.swift
- AlphaWallet/Core/Coordinators/WalletBalance/WalletBalanceCoordinator.swift
- AlphaWallet/KeyManagement/EtherKeystore.swift
- AlphaWallet/KeyManagement/Keystore.swift
- AlphaWalletTests/Coordinators/AppCoordinatorTests.swift
- AlphaWalletTests/Factories/FakeEtherKeystore.swift
- AlphaWalletTests/Factories/FakeKeystore.swift
> Remove unused setUpEventSourceCoordinatorForActivities #4086

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet/Accounts/Coordinators/AccountsCoordinator.swift
- AlphaWallet/Accounts/ViewControllers/AccountsViewController.swift
- AlphaWallet/AppCoordinator.swift
- AlphaWallet/Core/Coordinators/WalletBalance/WalletBalanceService.swift
- AlphaWallet/Core/TokenBalanceService.swift
- AlphaWallet/InCoordinator.swift
- AlphaWallet/Settings/Coordinators/SettingsCoordinator.swift
- AlphaWallet/Tokens/Coordinators/TokensCoordinator.swift
- AlphaWallet/Tokens/ViewControllers/TokensViewController.swift
- AlphaWalletTests/Coordinators/InCoordinatorTests.swift
- AlphaWalletTests/Coordinators/TokensCoordinatorTests.swift
- AlphaWalletTests/Settings/ConfigTests.swift
- AlphaWalletTests/Settings/Coordinators/SettingsCoordinatorTests.swift
> Rename WalletBalanceCoordinatorType with WalletBalanceService #4096

- AlphaWallet/InCoordinator.swift
> Remove unused setUpEventSourceCoordinatorForActivities #4094

- AlphaWallet/Core/Coordinators/WalletBalance/WalletBalanceFetcher.swift
- AlphaWallet/Core/Coordinators/WalletBalance/WalletBalanceService.swift
- AlphaWallet/Settings/Types/Config.swift
> Replace subscribableEnabledServers with serversPublisher #4068

- AlphaWallet/Transfer/ViewControllers/SendViewController.swift
- AlphaWallet/Transfer/ViewModels/SendViewModel.swift
> Move allFundsFormattedValues to send view model #4110

- AlphaWallet/Transfer/ViewControllers/SendViewController.swift
- AlphaWallet/Transfer/ViewModels/SendViewModel.swift
> Move convertMaybeScientificAmountToBigInt to send view model #4112

- AlphaWallet/Transfer/ViewControllers/SendViewController.swift
- AlphaWallet/Transfer/ViewModels/SendViewModel.swift
> Move send amount validation to view model #4108

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet/Core/CoinTicker/CoinTickersFetcher.swift
- AlphaWallet/Lists/SpamTokens.swift
Closes #4121
Longer term solution in the future: https://github.com/AlphaWallet/tokens/issues/2
> Add hardcoded list of spam tokens (of 1 at the moment). Remove price for tokens in the list 

- AlphaWallet/Settings/Types/Constants+Credentials.swift
- AlphaWallet/Settings/Types/Constants.swift
> Remove remaining references to Stathat since we don't use it anymore

- AlphaWallet/Accounts/Coordinators/AccountsCoordinator.swift
- AlphaWallet/Accounts/ViewControllers/AccountsViewController.swift
- AlphaWallet/Accounts/ViewModels/AccountViewModel.swift
- AlphaWallet/Accounts/ViewModels/AccountsViewModel.swift
- AlphaWallet/Accounts/ViewModels/WalletSummaryViewModel.swift
- AlphaWallet/Accounts/Views/AccountViewCell.swift
- AlphaWallet/Accounts/Views/WalletSummaryTableViewCell.swift
- AlphaWallet/Accounts/Views/WalletSummaryView.swift
- AlphaWallet/Alerts/ViewControllers/EditPriceAlertViewController.swift
- AlphaWallet/Core/Coordinators/WalletBalance/WalletBalanceFetcher.swift
- AlphaWallet/Core/Coordinators/WalletBalance/WalletBalanceService.swift
- AlphaWallet/Core/TokenBalanceService.swift
- AlphaWallet/Core/Types/WalletSummary.swift
- AlphaWallet/Export/Coordinators/PromptBackupCoordinator.swift
- AlphaWallet/InCoordinator.swift
- AlphaWallet/Market/Coordinators/ImportMagicLinkCoordinator.swift
- AlphaWallet/Sell/ViewControllers/EnterSellTokensCardPriceQuantityViewController.swift
- AlphaWallet/Tokens/ViewControllers/TokenViewController.swift
- AlphaWallet/Tokens/ViewControllers/TokensViewController.swift
- AlphaWallet/Tokens/ViewModels/TokenViewControllerViewModel.swift
- AlphaWallet/Transfer/Coordinators/TransactionConfirmationCoordinator.swift
- AlphaWallet/Transfer/ViewControllers/SendViewController.swift
- AlphaWallet/Transfer/ViewControllers/TransactionConfirmationViewController.swift
- AlphaWallet/Transfer/ViewModels/TransactionConfirmationViewModel.swift
- AlphaWalletTests/Factories/WalletSession.swift
- AlphaWalletTests/Settings/Coordinators/SettingsCoordinatorTests.swift
- AlphaWalletTests/Transfer/ViewControllers/SendViewControllerTests.swift
> Remove Subscribable from TokenBalanceService #4106

- AlphaWallet/Activities/Types/ActivitiesFilterStrategy.swift
- AlphaWallet/Core/SwapToken/SwapTokenService.swift
- AlphaWallet/InCoordinator.swift
- AlphaWallet/Tokens/Coordinators/SingleChainTokenCoordinator.swift
- AlphaWallet/Tokens/ViewControllers/TokenViewController.swift
- AlphaWallet/Tokens/ViewModels/TokenViewControllerViewModel.swift
- AlphaWallet/Transactions/Coordinators/ReplaceTransactionCoordinator.swift
- AlphaWallet/Transfer/Controllers/TransactionConfigurator.swift
- AlphaWallet/Transfer/Coordinators/PaymentCoordinator.swift
- AlphaWallet/Transfer/Coordinators/SendCoordinator.swift
- AlphaWallet/Transfer/Types/TransactionType.swift
- AlphaWallet/Transfer/ViewControllers/SendViewController.swift
- AlphaWallet/Transfer/ViewControllers/TransactionConfirmationViewController.swift
- AlphaWallet/Transfer/ViewModels/ConfigureTransactionViewModel.swift
- AlphaWallet/Transfer/ViewModels/SendHeaderViewViewModel.swift
- AlphaWallet/Transfer/ViewModels/SendViewModel.swift
- AlphaWallet/Transfer/ViewModels/TransactionConfirmationViewModel.swift
In the future, this can also be used to refactor code that handles existing transactions that are pre-built
> Add a `.prebuilt` transaction type. For upcoming native swap support

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet/Core/Coordinators/WalletBalance/WalletBalanceFetcher.swift
- AlphaWallet/Core/Types/NFTBalanceViewModel.swift
- AlphaWallet/Models/Balance.swift
> Prepend current token balance value when subscribe for new updates #4134

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet/Core/Coordinators/WalletBalance/PrivateBalanceFetcher.swift
- AlphaWallet/Core/Coordinators/WalletBalance/WalletBalanceFetcher.swift
- AlphaWallet/Core/Coordinators/WalletBalance/WalletBalanceService.swift
- AlphaWallet/Core/NFT/NFTProvider.swift
- AlphaWallet/Core/OpenSea/OpenSea.swift
- AlphaWallet/Core/OpenSea/OpenSeaNetworkProvider.swift
- AlphaWallet/Core/OpenSea/Types/OpenSeaNonFungible.swift
- AlphaWallet/InCoordinator.swift
- AlphaWallet/Tokens/Types/AddressAndRPCServer.swift
> Extend OpenSea provider with persistent caching #4137

- AlphaWallet/TokenScriptClient/Models/AssetDefinitionStore.swift
> Add Combine afternative methods for asset Signature and Body Changes #4143

- AlphaWallet/Activities/Views/ActivitiesView.swift
- AlphaWallet/Alerts/Views/PriceAlertsPageView.swift
- AlphaWallet/Settings/ViewControllers/SettingsViewController.swift
- AlphaWallet/Style/AppStyle.swift
- AlphaWallet/Tokens/ViewControllers/TokensCardViewController.swift
- AlphaWallet/Transactions/ViewControllers/TransactionsViewController.swift
> Move anArbitraryRowHeightSoAutoSizingCellsWorkIniOS10 to Metrics #4144

- AlphaWallet/Tokens/ViewControllers/TokensCardViewController.swift
> Replace account dependency with session.account in TokensCardViewController #4147

- AlphaWallet/Transactions/Coordinators/ReplaceTransactionCoordinator.swift
- AlphaWallet/Transfer/Collectibles/Coordinators/TransferCollectiblesCoordinator.swift
- AlphaWallet/Transfer/Coordinators/SendCoordinator.swift
- AlphaWallet/Transfer/Coordinators/TokenScriptCoordinator.swift
- AlphaWallet/Transfer/Coordinators/TransactionInProgressCoordinator.swift
- AlphaWallet/Transfer/Coordinators/TransferNFTCoordinator.swift
- AlphaWallet/Transfer/ViewControllers/TransactionInProgressViewController.swift
- AlphaWallet/WalletConnect/Controllers/TransactionInProgressCoordinatorBridgeToPromise.swift
> Rename transactionInProgressDidDismiss with didDismiss #4151

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet/Browser/Coordinators/DappBrowserCoordinator.swift
- AlphaWallet/Browser/Coordinators/DappRequestSwitchCustomChainCoordinator.swift
- AlphaWallet/Core/Helpers/DappRequestHandler.swift
- AlphaWallet/InCoordinator.swift
- AlphaWallet/WalletConnect/Coordinator/WalletConnectCoordinator.swift
> Wrap DappRequestSwitchCustomChainCoordinatorDelegate and DappRequestSwitchExistingChainCoordinatorDelegate to reduce in coordinator size #4061

- AlphaWallet/Tokens/Collectibles/Coordinators/TokensCardCollectionCoordinator.swift
- AlphaWallet/Tokens/ViewControllers/TokensCardViewController.swift
- AlphaWallet/Tokens/ViewModels/TokensCardViewModel.swift
- AlphaWallet/Transactions/Coordinators/TokensCardCoordinator.swift
> Remove unused dependency and propertis from TokensCardViewController and TokensCardViewModel #4149

- AlphaWallet/Activities/ViewControllers/ActivityViewController.swift
> Fix layout for activity view controller #4155

- AlphaWallet/Tokens/Coordinators/TokensCoordinator.swift
- AlphaWallet/Tokens/ViewControllers/TokensViewController.swift
> Remove unused dependencies from TokensViewController #4157

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet/Core/OpenSea/OpenSea.swift
- AlphaWallet/Core/OpenSea/OpenSeaNetworkProvider.swift
- AlphaWallet/Core/Views/GridStackView.swift
- AlphaWallet/Localization/en.lproj/Localizable.strings
- AlphaWallet/Localization/es.lproj/Localizable.strings
- AlphaWallet/Localization/fi.lproj/Localizable.strings
- AlphaWallet/Localization/ja.lproj/Localizable.strings
- AlphaWallet/Localization/ko.lproj/Localizable.strings
- AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings
- AlphaWallet/Tokens/Collectibles/ViewModels/NonFungibleTraitViewModel.swift
- AlphaWallet/Tokens/Collectibles/Views/NonFungibleTraitView.swift
- AlphaWallet/Tokens/Helpers/TokenInstanceViewConfigurationHelper.swift
- AlphaWallet/Tokens/ViewControllers/NonFungibleTokenViewController.swift
- AlphaWallet/Tokens/ViewModels/NonFungibleTokenViewModel.swift
> Display rarity for each trait in NFTs from OpenSea API #4053

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet/Core/Views/SelfSizingPanelLayout.swift
- AlphaWallet/InCoordinator.swift
- AlphaWallet/Settings/Coordinators/HelpUsCoordinator.swift
- AlphaWallet/Tokens/Coordinators/ClaimPaidOrderCoordinator.swift
- AlphaWallet/Transactions/Coordinators/ReplaceTransactionCoordinator.swift
- AlphaWallet/Transfer/Collectibles/Coordinators/TransferCollectiblesCoordinator.swift
- AlphaWallet/Transfer/Coordinators/SendCoordinator.swift
- AlphaWallet/Transfer/Coordinators/TokenScriptCoordinator.swift
- AlphaWallet/Transfer/Coordinators/TransactionConfirmationCoordinator.swift
- AlphaWallet/Transfer/Coordinators/TransferNFTCoordinator.swift
- AlphaWallet/Transfer/ViewControllers/SendTransactionErrorViewController.swift
- AlphaWallet/Transfer/ViewControllers/TransactionConfirmationViewController.swift
- AlphaWallet/WalletConnect/Controllers/TransactionConfirmationCoordinatorBridgeToPromise.swift
- Podfile
- Podfile.lock
> Replace modal presentation for confimation view controller #4120

- AlphaWallet/AppCoordinator.swift
- AlphaWallet/InCoordinator.swift
- AlphaWallet/KeyManagement/DefaultsWalletAddressesStore.swift
- AlphaWallet/KeyManagement/EtherKeystore.swift
- AlphaWallet/KeyManagement/JsonWalletAddressesStore.swift
- AlphaWallet/KeyManagement/WalletAddressesStore.swift
- AlphaWallet/Settings/Coordinators/SettingsCoordinator.swift
- AlphaWalletTests/Factories/FakeTransactionsStorage.swift
- AlphaWalletTests/Settings/Coordinators/SettingsCoordinatorTests.swift
> resetFetchingState doesn't get called when remove wallet in accounts view controller #4159

- AlphaWallet/AppCoordinator.swift
- AlphaWallet/InCoordinator.swift
- AlphaWallet/Settings/Coordinators/SettingsCoordinator.swift
> Remove unused method delegate?.didUpdateAccounts(in: self) #4171

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet/Tokens/JSON/TokenGroupIdentifier.swift
- AlphaWallet/Tokens/JSON/tokens.json
- AlphaWalletTests/Tokens/TokenGroupIdentifierTest.swift
> Created TokenGroupIdentifier and tests, added tokens.json file.

- AlphaWallet/Core/Helpers/BlockieGenerator.swift
- AlphaWallet/Core/OpenSea/OpenSea.swift
- AlphaWallet/Core/OpenSea/OpenSeaNetworkProvider.swift
- AlphaWallet/Tokens/Collectibles/ViewModels/TokensCardCollectionInfoPageViewModel.swift
- AlphaWallet/Tokens/Collectibles/Views/TokensCardCollectionInfoPageView.swift
- AlphaWallet/Tokens/ViewControllers/NonFungibleTokenViewController.swift
> Replace hardcoded references to .main with approprate server in let baseURL = getBaseURLForOpensea(for: .main) #4175

- AlphaWallet/AppCoordinator.swift
> Remove unused code #4177

- AlphaWallet/AppCoordinator.swift
> Rename selectedWalletSessionsSubject with walletSessionsSubject #4179

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet/Activities/ActivitiesService.swift
- AlphaWallet/AppCoordinator.swift
- AlphaWallet/InCoordinator.swift
- AlphaWallet/Notifications/LocalNotificationService.swift
- AlphaWallet/Notifications/NotificationService.swift
- AlphaWallet/Notifications/PushNotificationsService.swift
- AlphaWallet/Notifications/TransactionNotificationService.swift
- AlphaWallet/Notifications/Types/LocalNotification.swift
- AlphaWallet/Settings/Types/Config.swift
- AlphaWallet/Tokens/Types/TransactionsFilterStrategy.swift
- AlphaWallet/Transactions/Coordinators/SingleChainTransactionDataCoordinator.swift
- AlphaWallet/Transactions/Coordinators/SingleChainTransactionEtherscanDataCoordinator.swift
- AlphaWallet/Transactions/Coordinators/TransactionDataCoordinator.swift
- AlphaWallet/Transactions/Storage/TransactionsStorage.swift
- AlphaWallet/Transactions/Types/TransactionsTracker.swift
- AlphaWalletTests/Coordinators/AppCoordinatorTests.swift
- AlphaWalletTests/Coordinators/InCoordinatorTests.swift
> Notification appear in loop after receving ether #4161

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet/Core/CoinTicker/CoinTickersFetcher.swift
- AlphaWallet/Core/CoinTicker/CoinTickersFetcherCache.swift
- AlphaWallet/Core/CoinTicker/Types/TickerId.swift
- AlphaWallet/Core/CoinTicker/Types/TickerIdFilter.swift
- AlphaWallet/Core/CoinTicker/Types/TokenMappedToTicker.swift
- AlphaWallet/Core/Coordinators/WalletBalance/WalletBalanceFetcher.swift
- AlphaWallet/Settings/Types/Config.swift
- AlphaWalletTests/Coordinators/InCoordinatorTests.swift
> Replace tickersSubscribable with tickersPublisher #4185

- AlphaWallet/Core/Coordinators/WalletBalance/PrivateBalanceFetcher.swift
> Fix updatePolicy for refreshBalance(updatePolicy: #4189

- AlphaWallet/Core/Types/ERC20BalanceViewModel.swift
- AlphaWallet/Core/Types/NativecryptoBalanceViewModel.swift
> Not displaying crypto rate for xDai #4183

- AlphaWallet/Wallet/ViewControllers/VerifySeedPhraseViewController.swift
Closes #3907
After #4088
https://user-images.githubusercontent.com/1050309/158505021-48d73670-aca1-4596-bd37-402164bcd42f.mp4
> Enable clear button in verify seed screen after user taps the last word

- AlphaWallet/UI/RoundedBackground.swift
> Adjusted RoundedBackground to just completely cover the view.

- AlphaWallet.xcodeproj/project.pbxproj
Closes #4031
TestCases have been added back to the project.
> Added StringValidatorTestCases and StringValidatorRuleTestCases back into project

- AlphaWallet/AppCoordinator.swift
- AlphaWallet/Browser/Coordinators/QRCodeResolutionCoordinator.swift
- AlphaWallet/Core/Coordinators/PaymentFlowFromEip681UrlResolver.swift
- AlphaWallet/Core/Coordinators/WalletBalance/WalletBalanceFetcher.swift
- AlphaWallet/InCoordinator.swift
- AlphaWallet/Tokens/Coordinators/TokensCoordinator.swift
- AlphaWallet/Tokens/Types/TokensDataStore.swift
- AlphaWallet/Wallet/Coordinators/WalletCoordinator.swift
- AlphaWalletTests/Factories/FakeTokensDataStore.swift
> Remove all token objects when delete wallet #4207

- AlphaWallet/Tokens/Coordinators/SingleChainTokenCoordinator.swift
- AlphaWallet/Tokens/Coordinators/TokensCoordinator.swift
- AlphaWallet/Tokens/Types/TokensDataStore.swift
- AlphaWallet/Tokens/ViewModels/AddHideTokensViewModel.swift
- AlphaWalletTests/Tokens/TokensDataStoreTest.swift
> Remove unused methods #4209

- AlphaWallet/Tokens/Types/TokenCollection.swift
- AlphaWallet/Tokens/Types/TokensDataStore.swift
- AlphaWallet/Transactions/Storage/TransactionsStorage.swift
> Move token filtering on background queue, make changeset objects freezed to make them threadsafe #4211

- AlphaWallet/Settings/Types/RPCServers.swift
> Tweak chain color and icon for Polygon testnet #4217

- AlphaWallet/Transfer/Coordinators/TransactionConfirmationCoordinator.swift
> Add tap gesture for closing TransactionConfirmaction screen #4221

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet/Core/Coordinators/WalletBalance/WalletBalanceFetcher.swift
- AlphaWallet/InCoordinator.swift
- AlphaWallet/Tokens/Types/TokensDataStore.swift
- AlphaWallet/Transactions/EtherscanSingleChainTransactionProvider.swift
- AlphaWallet/Transactions/SingleChainTransactionProvider.swift
- AlphaWallet/Transactions/Storage/TransactionsStorage.swift
- AlphaWallet/Transactions/TokensFromTransactionsFetcher.swift
- AlphaWallet/Transactions/TransactionsService.swift
- AlphaWalletTests/Factories/FakeTransactionsStorage.swift
> Move tokens extraction from transaction in separate handler #4228

- AlphaWallet/BlockscanChat/BlockscanChatService.swift
> Tweak blockscan chat stop polling

- AlphaWallet/Core/Coordinators/WalletBalance/PrivateBalanceFetcher.swift
- AlphaWallet/Core/Coordinators/WalletBalance/WalletBalanceFetcher.swift
- AlphaWallet/TokenScriptClient/Coordinators/EventSourceCoordinator.swift
- AlphaWallet/TokenScriptClient/Coordinators/EventSourceCoordinatorForActivities.swift
- AlphaWallet/Tokens/Logic/Erc1155TokenIdsFetcher.swift
> Read `Config.Development.isAutoFetchingDisabled` and disable event fetching #4241

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet/Core/Types/RealmStore.swift
- AlphaWallet/InCoordinator.swift
- AlphaWallet/TokenScriptClient/Coordinators/EventSourceCoordinator.swift
- AlphaWallet/TokenScriptClient/Coordinators/EventSourceCoordinatorForActivities.swift
- AlphaWallet/TokenScriptClient/Models/AssetDefinitionStore.swift
- AlphaWallet/TokenScriptClient/Models/EventsActivityDataStore.swift
- AlphaWallet/Tokens/Types/TokensDataStore.swift
> Move setupWatchingTokenScriptFileChangesToFetchEvents right in events fetcher #4219

- AlphaWallet/Accounts/ViewControllers/AccountsViewController.swift
- AlphaWallet/Accounts/ViewModels/AccountsViewModel.swift
- AlphaWallet/Core/Coordinators/WalletBalance/PrivateBalanceFetcher.swift
- AlphaWallet/Core/Coordinators/WalletBalance/WalletBalanceFetcher.swift
- AlphaWallet/Core/Coordinators/WalletBalance/WalletBalanceService.swift
- AlphaWallet/Core/TokenBalanceService.swift
- AlphaWallet/InCoordinator.swift
- AlphaWallet/Tokens/ViewControllers/TokenViewController.swift
- AlphaWallet/Transactions/EtherscanSingleChainTransactionProvider.swift
- AlphaWallet/Transactions/Storage/Session.swift
- AlphaWallet/Transfer/ViewControllers/SendViewController.swift
- AlphaWallet/Transfer/ViewControllers/TransactionConfirmationViewController.swift
- AlphaWalletTests/Factories/WalletSession.swift
- AlphaWalletTests/Settings/Coordinators/SettingsCoordinatorTests.swift
- AlphaWalletTests/Transfer/ViewControllers/SendViewControllerTests.swift
> TokenViewController sometimes show 0 balance for native token even when Wallet tab has refreshed to show non-zero #4200

- AlphaWallet/ScrollableSegmentedControl/ScrollableSegmentedControl.swift
- AlphaWallet/Tokens/ViewControllers/TokensViewController.swift
Closes #3852
https://user-images.githubusercontent.com/1050309/161926939-c711f10a-16e7-4009-b41f-e3490d271d65.mp4
> Added code to ScrollableSegmentedControl to highlight a tab without animating

- AlphaWallet/Tokens/ViewModels/OpenSeaNonFungibleTokenCardRowViewModel.swift
@oa-s help see if code is still working correctly?
> Fix: invalid check for image URL because it was checking against a func pointer, which is always non-nil

- AlphaWallet.xcodeproj/project.pbxproj
Found in "Recovered Reference" folder
> Fix: project file reference

- AlphaWallet/Tokens/ViewControllers/AddHideTokensViewController.swift
> Make the background behind "Add/Hide Tokens" opaque #4253

- AlphaWallet.xcodeproj/project.pbxproj
- Podfile.lock
- modules/AlphaWalletAddress/AlphaWalletAddress.podspec
- modules/AlphaWalletAddress/AlphaWalletAddress/AlphaWallet.swift
- modules/AlphaWalletAddress/AlphaWalletAddress/Extensions/String+Extensions.swift
- modules/AlphaWalletAddress/AlphaWalletAddress/ThirdPartyAddress+Extension.swift
> Move more address-related functionality into AlphaWalletAddress pod

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet/AppCoordinator.swift
- AlphaWallet/ENS/ENSDelegateImpl.swift
- AlphaWallet/RPC/Commands/web3swift-pod/ENSReverseLookupEncode.swift
- AlphaWallet/RPC/Commands/web3swift-pod/GetENSInfoEncode.swift
- AlphaWallet/Settings/Types/Constants.swift
- AlphaWallet/Settings/Types/RPCServers.swift
- AlphaWallet/Tokens/Coordinators/ENSReverseLookupCoordinator.swift
- AlphaWallet/Tokens/Coordinators/GetENSOwnerCoordinator.swift
- AlphaWallet/Tokens/Coordinators/GetENSTextRecordsCoordinator.swift
- Podfile
- Podfile.lock
- modules/AlphaWalletENS/AlphaWalletENS.podspec
- modules/AlphaWalletENS/AlphaWalletENS/ABIs.swift
- modules/AlphaWalletENS/AlphaWalletENS/AlphaWalletENS.h
- modules/AlphaWalletENS/AlphaWalletENS/ENS.swift
- modules/AlphaWalletENS/AlphaWalletENS/ENSError.swift
- modules/AlphaWalletENS/AlphaWalletENS/ENSTextRecordKey.swift
- modules/AlphaWalletENS/AlphaWalletENS/Extensions/Address+Extensions.swift
- modules/AlphaWalletENS/AlphaWalletENS/Extensions/Data+Extensions.swift
- modules/AlphaWalletENS/AlphaWalletENS/Extensions/String+Extensions.swift
- modules/AlphaWalletENS/AlphaWalletENS/Logger.swift
- modules/AlphaWalletENS/LICENSE
Closes #4262
Depends and includes #4261
> Extract ENS to Cocoapod

- AlphaWallet.xcodeproj/project.pbxproj
Had accidentally disabled it recently
> Enable SwiftLint again

- AlphaWallet/Core/Helpers/BlockieGenerator.swift
- AlphaWallet/Core/UnstoppableDomains/AddressOrEnsResolution.swift
- AlphaWallet/Core/UnstoppableDomains/DomainResolutionService.swift
- AlphaWallet/Core/UnstoppableDomains/UnstoppableDomainsV2Resolver.swift
- AlphaWallet/Tokens/Coordinators/ENSReverseLookupCoordinator.swift
- AlphaWallet/Tokens/Coordinators/GetENSOwnerCoordinator.swift
- AlphaWallet/Tokens/Coordinators/GetENSTextRecordsCoordinator.swift
- AlphaWalletTests/Tokens/Coordinators/GetENSOwnerCoordinatorTests.swift
- Podfile.lock
- modules/AlphaWalletAddress/AlphaWalletAddress.podspec
- modules/AlphaWalletAddress/AlphaWalletAddress/AlphaWallet.swift
- modules/AlphaWalletAddress/AlphaWalletAddress/Extensions/Data+Extensions.swift
- modules/AlphaWalletENS/AlphaWalletENS/Extensions/Address+Extensions.swift
- modules/AlphaWalletENS/AlphaWalletENS/Extensions/Data+Extensions.swift
Vendors a little code which should be internal to the pod anyway
Depends on and includes: https://github.com/AlphaWallet/alpha-wallet-ios/pull/4273
> Remove dependency TrustWalletCore from AlphaWalletAddress pod

- AlphaWallet/Core/Ethereum/ABI/DecodedFunctionCall+Decode.swift
- Podfile
- Podfile.lock
- modules/AlphaWalletAddress/AlphaWalletAddress.podspec
- modules/AlphaWalletAddress/AlphaWalletAddress/Extensions/EthereumAddress+Extensions.swift
- modules/AlphaWalletAddress/AlphaWalletAddress/ThirdPartyAddress+Extension.swift
> Move code accessing EethereumAddress pod into AlphaWalletAddress pod so it's hidden in app codebase

- AlphaWallet/Core/Views/ButtonsBar/VerticalButtonsBar.swift
- AlphaWallet/Wallet/ViewControllers/ImportWalletViewController.swift
Closes #4089
https://user-images.githubusercontent.com/1050309/162683794-6970bce3-1484-46f5-8468-b4453fdbe765.mp4
> Changed style of import from cloud button to the correct secondary style

- AlphaWallet/Core/OpenSea/OpenSeaNetworkProvider.swift
> Make fetchCollectionsPage on background queue #4293

- AlphaWallet/Core/TokensAutodetector/TokensAutodetector.swift
> Remove double add token objects when autoDetectTransactedErc20AndNonErc20Tokens #4295

- AlphaWallet/Activities/ActivitiesService.swift
- AlphaWallet/InCoordinator.swift
- AlphaWallet/WalletConnect/View/WalletConnectSessionCell.swift
> Remove unused code #4301

- AlphaWallet/Core/Features.swift
> Enable firebase crash report enabled by default #4319

- AlphaWallet/Activities/ActivitiesService.swift
- AlphaWallet/Transactions/EtherscanSingleChainTransactionProvider.swift
- AlphaWallet/Transactions/Storage/TransactionsStorage.swift
> Make transaction store safe #4315

- AlphaWallet/AppCoordinator.swift
- AlphaWallet/Core/Initializers/MigrationInitializer.swift
- AlphaWallet/Tokens/Types/TokensDataStore.swift
- AlphaWallet/Transactions/Storage/TransactionsStorage.swift
> Remove all realm related files when remove wallet #4317

- AlphaWallet/TokenScriptClient/Coordinators/EventSourceCoordinatorForActivities.swift
- AlphaWallet/TokenScriptClient/Models/EventsActivityDataStore.swift
> Make events activity store safe #4321

- AlphaWallet/TokenScriptClient/Coordinators/EventSourceCoordinator.swift
- AlphaWallet/TokenScriptClient/Models/NonActivityEventsDataStore.swift
- AlphaWalletTests/TokenScriptClient/FakeEventsDataStore.swift
> make nonActivityEventsDataStore safe #4323

- AlphaWallet/EtherClient/TrustClient/Models/RawTransaction.swift
- AlphaWallet/Transactions/EtherscanSingleChainTransactionProvider.swift
- AlphaWallet/Transactions/Storage/Session.swift
- AlphaWallet/Transactions/TokensFromTransactionsFetcher.swift
> [Refactor] Move token provider to wallet session #4325

- AlphaWallet/Transactions/Storage/TransactionsStorage.swift
- AlphaWalletTests/Coordinators/InCoordinatorTests.swift
- AlphaWalletTests/Settings/Coordinators/SettingsCoordinatorTests.swift
- AlphaWalletTests/Transactions/Storage/TransactionsStorageTests.swift
> Fix Test suite #4331

- AlphaWallet/Core/TokensAutodetector/AutoDetectTokensOperation.swift
- AlphaWallet/Core/TokensAutodetector/AutoDetectTransactedTokensOperation.swift
- AlphaWallet/Core/TokensAutodetector/TokensAutodetector.swift
- AlphaWallet/InCoordinator.swift
- AlphaWallet/TokenScriptClient/Coordinators/EventSourceCoordinator.swift
- AlphaWallet/TokenScriptClient/Coordinators/EventSourceCoordinatorForActivities.swift
- AlphaWallet/Tokens/Coordinators/TokensCoordinator.swift
- AlphaWallet/Transactions/EtherscanSingleChainTransactionProvider.swift
- AlphaWallet/Transactions/TransactionsService.swift
> Fix memory leaks #4329

- Podfile
- Podfile.lock
> Update Kingfisher to 7.0 version #4335

- Makefile
Updated makefile to use --repo-update option when installing cocoapods
> Updated makefile to use —repo-update option when installing pods

- AlphaWallet/Accounts/Coordinators/AccountsCoordinator.swift
- AlphaWallet/Accounts/ViewControllers/AccountsViewController.swift
- AlphaWallet/Accounts/ViewModels/AccountViewModel.swift
- AlphaWallet/Accounts/ViewModels/AccountsViewModel.swift
- AlphaWallet/Accounts/Views/AccountViewCell.swift
- AlphaWallet/Core/Helpers/BlockieGenerator.swift
- AlphaWallet/Core/Views/BlockieImageView.swift
- AlphaWallet/Settings/Coordinators/SettingsCoordinator.swift
- AlphaWallet/Tokens/Coordinators/TokensCoordinator.swift
- AlphaWallet/Transactions/Coordinators/AlphaWalletProviderFactory.swift
> [Refactor] [AccountsViewModel] Move more logic to view model #4346

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet/Core/Types/SortTokensParam.swift
- AlphaWallet/Core/Views/WebImageView.swift
- AlphaWallet/Tokens/Types/AddressAndRPCServer.swift
- AlphaWallet/Tokens/ViewModels/TokensViewModel.swift
- AlphaWalletTests/Tokens/AddressAndRPCServerTests.swift
- AlphaWalletTests/modules/AlphaWalletAddress/AlphaWalletAddressTests.swift
- modules/AlphaWalletAddress/AlphaWalletAddress/AlphaWallet.swift
> Removes unnecessary `func ==()` implementations and a few Equatable(s) 

- AlphaWallet/Core/Coordinators/WalletBalance/WalletBalanceFetcher.swift
> Fix zero token balance #4362

- Makefile
Makes build_and_run_booted target use beautifier
> Makes build_and_run_booted target use beautifier

- AlphaWallet/Transfer/Coordinators/SignMessageCoordinator.swift
- AlphaWallet/Transfer/Coordinators/TransactionConfirmationCoordinator.swift
- AlphaWallet/Transfer/ViewControllers/SignatureConfirmationDetailsViewController.swift
- AlphaWallet/Transfer/ViewControllers/SignatureConfirmationViewController.swift
> [Refactor] Update sign message confirmation view to same design as TransactionConfirmation #4348

- AlphaWallet/Core/BuyToken/Ramp/Ramp.swift
- AlphaWallet/Core/CoinTicker/CoinTickersFetcher.swift
- AlphaWallet/Core/SwapToken/Oneinch/Oneinch.swift
- AlphaWallet/EtherClient/TrustClient/AlphaWalletService.swift
- AlphaWallet/Settings/Types/Config.swift
- AlphaWallet/Settings/Types/Constants.swift
- AlphaWallet/Transactions/EtherscanSingleChainTransactionProvider.swift
> [Refactor] Move base urls for AlphaWalletService to Constants #4353

- Podfile
- Podfile.lock
> Update web3swift library #4355

- AlphaWallet/Core/OpenSea/OpenSeaNetworkProvider.swift
> Not use OpenSea API when accessing Rinkeby

- AlphaWallet/Settings/Types/Constants+Credentials.swift
> Update Infura dev key

- AlphaWallet/Tokens/Coordinators/TokensCoordinator.swift
> Blockie image updates non on main thread #4370

- AlphaWallet/Tokens/Coordinators/SingleChainTokenCoordinator.swift
> Refactor addImportedToken(forContract function #4372

- AlphaWallet/Tokens/ViewControllers/TokensViewController.swift
> StatefulViewController isn't using for tokens view controller #4374

- AlphaWallet/Tokens/Coordinators/SingleChainTokenCoordinator.swift
- AlphaWallet/Tokens/Coordinators/TokensCoordinator.swift
> Remove unused code #4376

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet/ActiveWalletCoordinator.swift
- AlphaWallet/AppCoordinator.swift
- AlphaWallet/Core/Helpers/DappRequestHandler.swift
- AlphaWalletTests/Coordinators/AppCoordinatorTests.swift
- AlphaWalletTests/Coordinators/InCoordinatorTests.swift
> Rename inCoordinator into active wallet coordinator #4378

- AlphaWallet/Core/Types/NativecryptoBalanceViewModel.swift
> Fix calculation amount in fiat currency for (xdai) gnosis #4382

- AlphaWallet/Accounts/Coordinators/AccountsCoordinator.swift
- AlphaWallet/ActiveWalletCoordinator.swift
- AlphaWallet/AppCoordinator.swift
- AlphaWallet/Settings/Coordinators/SettingsCoordinator.swift
- AlphaWalletTests/Coordinators/AppCoordinatorTests.swift
- AlphaWalletTests/Coordinators/InCoordinatorTests.swift
> Refactor accounts coordinator #4380

- AlphaWallet/Analytics/Coordinators/AnalyticsService.swift
- AlphaWallet/Analytics/Coordinators/MixpanelCoordinator.swift
- AlphaWalletTests/Coordinators/AppCoordinatorTests.swift
- Podfile
- Podfile.lock
> Fix: upgrade Mixpanel SDK to fix "Segmentation Fault" when archiving

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet/Core/OpenSea/OpenSea.swift
- AlphaWallet/Tokens/ViewControllers/TokensViewController.swift
- AlphaWallet/WalletConnect/Coordinator/WalletConnectCoordinator.swift
- AlphaWallet/WalletConnect/Providers/v1/WalletConnectV1Provider.swift
- AlphaWallet/WalletConnect/Providers/v2/WalletConnectV2Provider.swift
- AlphaWallet/WalletConnect/Types/CombineLatestCollection.swift
- AlphaWallet/WalletConnect/Types/Storage.swift
- AlphaWallet/WalletConnect/Types/WalletConnect.swift
- AlphaWallet/WalletConnect/ViewController/WalletConnectSessionViewController.swift
- AlphaWallet/WalletConnect/ViewController/WalletConnectSessionsViewController.swift
- AlphaWallet/WalletConnect/WalletConnectServer.swift
- AlphaWallet/WalletConnect/WalletConnectServerProvider.swift
> [Refactor] Wallet Connect #4357

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet/Core/Views/ButtonsBar/VerticalButtonsBar.swift
- AlphaWallet/Extensions/NSLayoutConstraintExtension.swift
- AlphaWallet/Style/AppStyle.swift
- AlphaWallet/Wallet/ViewControllers/SeedPhraseBackupIntroductionViewController.swift
- AlphaWallet/Wallet/ViewControllers/ShowSeedPhraseViewController.swift
- AlphaWallet/Wallet/ViewControllers/VerifySeedPhraseViewController.swift
> Aligned bottoms of buttons in back up sequence

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet/Tokens/Coordinators/GetIsERC1155ContractCoordinator.swift
- AlphaWallet/Tokens/Helpers/CachedERC1155ContractDictionary.swift
- AlphaWalletTests/Tokens/CachedERC1155ContractDictionaryTestCase.swift
- AlphaWalletTests/Tokens/Coordinators/GetIsERC1155ContractCoordinatorTestCase.swift
- AlphaWalletTests/Utilities/urlUtilities.swift
> Added code to persist cache for GetIsERC1155ContractCoordinator

- AlphaWallet/ActiveWalletCoordinator.swift
- AlphaWallet/Transactions/EtherscanSingleChainTransactionProvider.swift
- AlphaWallet/Transactions/SingleChainTransactionProvider.swift
- AlphaWallet/Transactions/TransactionsService.swift
> Reload balance after transaction has sent #4394

- AlphaWallet/Activities/ActivitiesService.swift
> Fix crash on update activity #4413

- AlphaWallet/Accounts/Views/AccountViewCell.swift
> Remove unused code #4416

- AlphaWallet/Activities/ActivitiesService.swift
> Fix crash when trying to get session of unavailable server #4418

- AlphaWallet/Core/Helpers/ReportService.swift
> Disable Firebase when running test suite #4424

- AlphaWallet/Core/Core.swift
- AlphaWallet/Core/Helpers/DeviceChecker.swift
> Disable jailbreak warning when macos

- AlphaWallet/Tokens/Types/TokensDataStore.swift
> Suppose to fix crash when update nft balance #4429

- AlphaWallet/Accounts/ViewControllers/AccountsViewController.swift
- AlphaWallet/Accounts/Views/AccountViewCell.swift
> Fix broken account info selection when long press on account cell #4432

- AlphaWallet/Settings/Coordinators/ServersCoordinator.swift
- AlphaWallet/Tokens/Coordinators/ClaimPaidOrderCoordinator.swift
- AlphaWallet/Transactions/Coordinators/ReplaceTransactionCoordinator.swift
- AlphaWallet/Transfer/Collectibles/Coordinators/TransferCollectiblesCoordinator.swift
- AlphaWallet/Transfer/Coordinators/SendCoordinator.swift
- AlphaWallet/Transfer/Coordinators/SignMessageCoordinator.swift
- AlphaWallet/Transfer/Coordinators/TokenScriptCoordinator.swift
- AlphaWallet/Transfer/Coordinators/TransactionConfirmationCoordinator.swift
- AlphaWallet/Transfer/Coordinators/TransferNFTCoordinator.swift
- AlphaWallet/Transfer/ViewModels/TransactionConfirmationTableHeaderViewModel.swift
- AlphaWallet/Transfer/ViewModels/TransactionConfirmationViewModel.swift
- AlphaWallet/Transfer/Views/TransactionConfirmationHeaderView.swift
- AlphaWallet/WalletConnect/Coordinator/WalletConnectToSessionCoordinator.swift
- AlphaWallet/WalletConnect/ViewController/WalletConnectToSessionViewController.swift
- AlphaWallet/WalletConnect/ViewModel/WalletConnectToSessionViewModel.swift
> Show chain icon in WalletConnect new session confirmation dialog #3629

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet/WalletConnect/Coordinator/WalletConnectCoordinator.swift
- AlphaWallet/WalletConnect/ViewController/WalletConnectSessionsViewController.swift
- AlphaWallet/WalletConnect/ViewModel/WalletConnectSessionsViewModel.swift
> Tweak appearence of empty wallet connect sessions when cancel connection request #4434

- AlphaWallet/TokenScriptClient/Models/AssetAttributeToJavaScriptConvertor.swift
- AlphaWallet/Transactions/Coordinators/TokensCardCoordinator.swift
> Fix: TokenScript view not loading when the token values include double quotes "

- AlphaWallet/Core/Core.swift
- AlphaWallet/Core/Helpers/ReportService.swift
> Disable Firebase unless running as AlphaWallet (i.e. not a fork)

- AlphaWallet/Core/OpenSea/OpenSea.swift
> [Refactor] OpenSea provider #4443

- AlphaWallet/Core/Views/BlockieImageView.swift
- AlphaWallet/Core/Views/WebImageView.swift
- AlphaWallet/Tokens/ViewControllers/TokensViewController.swift
> ENS avatar shown differently on simulator and device (and both are wrong) #4405

- AlphaWallet/Accounts/ViewControllers/AccountsViewController.swift
- AlphaWallet/Accounts/ViewModels/AccountViewModel.swift
- AlphaWallet/Accounts/ViewModels/AccountsViewModel.swift
- AlphaWallet/Accounts/Views/AccountViewCell.swift
- AlphaWallet/Accounts/Views/WalletSummaryView.swift
- AlphaWallet/Core/Coordinators/WalletBalance/WalletBalanceFetcher.swift
- AlphaWallet/Core/Coordinators/WalletBalance/WalletBalanceService.swift
- AlphaWallet/Core/Helpers/BlockieGenerator.swift
- AlphaWallet/Tokens/ViewControllers/TokensViewController.swift
> improve displaying accounts view #4436

- AlphaWallet/Tokens/Helpers/TokenInstanceViewConfigurationHelper.swift
> "Total Sales" and "Total Supply" should be whole numbers, not fractions for ERC721 #4451

- AlphaWallet/Activities/ActivitiesService.swift
- AlphaWallet/Activities/Coordinators/ActivitiesCoordinator.swift
- AlphaWallet/Activities/ViewControllers/ActivityViewController.swift
- AlphaWallet/TokenScriptClient/Models/Activity.swift
- AlphaWallet/Tokens/Types/TokenObject.swift
- AlphaWallet/Tokens/ViewControllers/TokenViewController.swift
- AlphaWallet/Tokens/ViewControllers/TokensCardViewController.swift
- AlphaWalletTests/Activitities/FakeActivitiesService.swift
> [Refactor] Replace subscribable with AnyPublisher in ActivitiesServiceType #4467

- AlphaWallet/Activities/ActivitiesService.swift
- AlphaWallet/TokenScriptClient/Coordinators/EventSourceCoordinator.swift
- AlphaWallet/Tokens/Collectibles/Coordinators/TokensCardCollectionCoordinator.swift
- AlphaWallet/Tokens/Collectibles/ViewModels/TokensCardCollectionInfoPageViewModel.swift
- AlphaWallet/Tokens/Coordinators/SelectTokenCoordinator.swift
- AlphaWallet/Tokens/Coordinators/TokensCoordinator.swift
- AlphaWallet/Tokens/Helpers/TokenAdaptor.swift
- AlphaWallet/Tokens/Types/TokenObject.swift
- AlphaWallet/Tokens/ViewControllers/SelectTokenViewController.swift
- AlphaWallet/Tokens/ViewControllers/TokensViewController.swift
- AlphaWallet/Tokens/ViewModels/EthTokenViewCellViewModel.swift
- AlphaWallet/Tokens/ViewModels/FungibleTokenViewCellViewModel.swift
- AlphaWallet/Tokens/ViewModels/NonFungibleTokenViewCellViewModel.swift
- AlphaWallet/Tokens/ViewModels/OpenSea/OpenSeaNonFungibleTokenViewCellViewModel.swift
- AlphaWallet/Tokens/ViewModels/TokensCardViewModel.swift
- AlphaWallet/Tokens/ViewModels/WalletTokenViewCellViewModel.swift
- AlphaWallet/Transactions/Coordinators/TokensCardCoordinator.swift
- AlphaWalletTests/Tokens/Helpers/TokenAdaptorTest.swift
> NFTs in Collectibles tab should show openseadata["collection"]["name"] if available #4450

- AlphaWallet/Core/Types/RealmStore.swift
- AlphaWallet/TokenScriptClient/Models/EventsActivityDataStore.swift
- AlphaWallet/TokenScriptClient/Models/NonActivityEventsDataStore.swift
- AlphaWallet/Tokens/Collectibles/Coordinators/TokensCardCollectionCoordinator.swift
- AlphaWallet/Tokens/Types/TokenObject.swift
- AlphaWallet/Tokens/Types/TokensDataStore.swift
- AlphaWallet/Transactions/Coordinators/TokensCardCoordinator.swift
- AlphaWallet/Transactions/Storage/TransactionsStorage.swift
> Fix some crashes related to realm #4454

- AlphaWallet/ActiveWalletCoordinator.swift
- AlphaWallet/Activities/Coordinators/ActivitiesCoordinator.swift
- AlphaWallet/Activities/ViewControllers/ActivitiesViewController.swift
- AlphaWallet/Activities/Views/ActivitiesView.swift
- AlphaWallet/TokenScriptClient/Coordinators/FetchAssetDefinitionsCoordinator.swift
- AlphaWallet/TokenScriptClient/Models/AssetAttributesCache.swift
- AlphaWallet/TokenScriptClient/Models/AssetDefinitionStore.swift
- AlphaWallet/Tokens/Collectibles/Coordinators/TokensCardCollectionCoordinator.swift
- AlphaWallet/Tokens/ViewControllers/TokenViewController.swift
- AlphaWallet/Tokens/ViewControllers/TokensCardViewController.swift
- AlphaWallet/Transactions/Coordinators/TokensCardCoordinator.swift
- AlphaWallet/Transactions/Views/ActivityPageView.swift
- AlphaWallet/Transfer/Coordinators/TokenScriptCoordinator.swift
> Move fetchXMLs to background queue, remove singleton from `AssetDefinitionStore` #4456

- AlphaWallet/Core/Coordinators/WalletBalance/WalletBalanceFetcher.swift
- AlphaWallet/Core/Coordinators/WalletBalance/WalletBalanceService.swift
- AlphaWallet/Tokens/Types/TokensDataStore.swift
- AlphaWalletTests/Factories/WalletSession.swift
- AlphaWalletTests/Transfer/ViewControllers/SendViewControllerTests.swift
> Realm access on incorrect thread crash #4475

- AlphaWallet/Core/NFT/OpenSea/OpenSea.swift
- AlphaWallet/Core/TokenBalanceService.swift
> Remove unused code, remove comment #4484

- AlphaWallet/Tokens/Views/OpenSea/OpenSeaNonFungibleTokenViewCell.swift
- AlphaWallet/UI/TokenImageView.swift
> Hide token label when display placeholder image, or load image via url #4463

- AlphaWallet/Transactions/EtherscanSingleChainTransactionProvider.swift
> Move promise callback to background for EtherscanSingleChainTransactionProvider #4458

- AlphaWallet/Core/Views/BlockieImageView.swift
- AlphaWallet/Core/Views/WebImageView.swift
> Tweak web image #4471

- AlphaWallet/Core/Coordinators/WalletBalance/WalletBalanceFetcher.swift
- AlphaWallet/Core/Coordinators/WalletBalance/WalletBalanceService.swift
- AlphaWallet/Market/OrderHandler.swift
- AlphaWalletTests/Factories/WalletSession.swift
- AlphaWalletTests/Market/OrderSigningTests.swift
- AlphaWalletTests/Transfer/ViewControllers/SendViewControllerTests.swift
> Test broken with: SendViewControllerTests.testBalanceUpdates() #4481

- AlphaWallet/Tokens/Helpers/TokenAdaptor.swift
> [Refactor] Extract getFirstMatchingEvent to separate function for TokenAdaptor #4487

- AlphaWallet/Tokens/Coordinators/TokensCoordinator.swift
- AlphaWallet/Tokens/ViewControllers/TokensViewController.swift
> [Refactor] Refactor TokensViewController #4495

- AlphaWallet.xcodeproj/project.pbxproj
Made the intention of the "Run script" clearer.
> Renamed “Run Script” build phase to “Upload debug symbols to Crashlytics"

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet/ActiveWalletCoordinator.swift
- AlphaWallet/Tokens/Collectibles/Coordinators/NFTCollectionCoordinator.swift
- AlphaWallet/Tokens/Coordinators/SingleChainTokenCoordinator.swift
> [Refactor] Rename TokensCardCoordinator NFTCollectionCoordinator #4503

- AlphaWallet/Browser/ViewControllers/BrowserViewController.swift
- AlphaWallet/Settings/Types/RPCServers.swift
> Fix Klaytn web urls

- AlphaWallet/Notifications/TransactionNotificationService.swift
> Fix: crash when prompted for wallet backup when received eth. Was updating UI in background thread

- AlphaWallet/Core/NFT/Enjin/Enjin.swift
- AlphaWallet/Core/NFT/OpenSea/OpenSea.swift
> Fix bad access for enjin, and openSea providers #4514

- AlphaWallet/TokenScriptClient/Coordinators/AssetDefinitionStoreCoordinator.swift
- AlphaWallet/TokenScriptClient/Models/AssetAttribute.swift
- AlphaWallet/TokenScriptClient/Models/AssetDefinitionDiskBackingStore.swift
- AlphaWallet/TokenScriptClient/Models/XMLHandler.swift
- AlphaWallet/Tokens/ViewControllers/VerifiableStatusViewController.swift
> Make access to XMLHandler threadsafe, move static func to functional #4510

- AlphaWallet/TokenScriptClient/Coordinators/EventSourceCoordinator.swift
- AlphaWallet/TokenScriptClient/Coordinators/EventSourceCoordinatorForActivities.swift
> Move fetching events to background queue #4512

- AlphaWallet/Activities/ActivitiesService.swift
- AlphaWallet/TokenScriptClient/Models/CallForAssetAttributeCoordinator.swift
> Fix bad access when update activity #4516

- AlphaWallet/AppCoordinator.swift
> [Refactor] Rename walletSessionsSubject with sessionsSubject #4533

- AlphaWallet/ActiveWalletCoordinator.swift
- AlphaWallet/Transactions/TransactionsService.swift
> [Refactor] move removeUnknownTransactions() to TransactionsService and perform on background queue #4518

- AlphaWallet/TokenScriptClient/Coordinators/EventSourceCoordinator.swift
- AlphaWallet/TokenScriptClient/Coordinators/EventSourceCoordinatorForActivities.swift
> [Refactor] extract check for config.development.isAutoFetchingDisabled for event fetchers #4523

- AlphaWallet/Alerts/ViewControllers/EditPriceAlertViewController.swift
- AlphaWallet/Core/Coordinators/Alerts/PriceAlertDataStore.swift
- AlphaWallet/Core/Coordinators/Alerts/PriceAlertService.swift
- AlphaWallet/Tokens/ViewControllers/TokenViewController.swift
> [Refactor] Replace subscribable and promises with Combine for alert service #4540

- AlphaWallet/AppCoordinator.swift
> [Refactor] Rename function showTransactionsIfNeeded to showActiveWalletIfNeeded #4538

- AlphaWallet/Core/CoinTicker/CoinTickersFetcher.swift
- AlphaWallet/Core/CoinTicker/Types/TickerIdFilter.swift
- AlphaWallet/Core/CoinTicker/Types/TokenMappedToTicker.swift
- AlphaWallet/Core/Coordinators/WalletBalance/WalletBalanceFetcher.swift
- AlphaWalletTests/Coordinators/InCoordinatorTests.swift
> Remove grouping tokens while fetching tickers, move xdai to predefined ticker ids #4536

- AlphaWallet/Core/Coordinators/WalletBalance/WalletBalanceFetcher.swift
> Make balanceFetchers threadsafe #4525

- AlphaWallet/Core/Views/ButtonsBar/VerticalButtonsBar.swift
- AlphaWallet/Localization/en.lproj/Localizable.strings
- AlphaWallet/Localization/es.lproj/Localizable.strings
- AlphaWallet/Localization/fi.lproj/Localizable.strings
- AlphaWallet/Localization/ja.lproj/Localizable.strings
- AlphaWallet/Localization/ko.lproj/Localizable.strings
- AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings
- AlphaWallet/Wallet/Coordinators/WalletCoordinator.swift
- AlphaWallet/Wallet/ViewControllers/CreateInitialWalletViewController.swift
- AlphaWallet/Wallet/ViewModels/CreateInitialWalletViewModel.swift
> Update the Welcome screen #4505

- AlphaWallet/Accounts/ViewModels/AccountViewModel.swift
- AlphaWallet/Core/Helpers/BlockieGenerator.swift
- AlphaWallet/Tokens/Coordinators/TokensCoordinator.swift
> App Crashes when fetch blockie image #4546

- AlphaWallet/Core/Views/BlockieImageView.swift
- AlphaWallet/Tokens/ViewControllers/TokensViewController.swift
Closes #4506
See 4506 for more details
> Resized BlockieImageView on TokensViewController to 44x44 points instead of 24x24 points

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet/Core/ENS/ENSDelegateImpl.swift
- AlphaWallet/Core/Helpers/BlockieGenerator.swift
- AlphaWallet/Core/TokensAutodetector/TokensAutodetector.swift
- AlphaWallet/Core/Types/TokenProviderType.swift
- AlphaWallet/Market/Coordinators/ImportMagicLinkCoordinator.swift
- AlphaWallet/Settings/ViewControllers/SettingsViewController.swift
- AlphaWallet/TokenScriptClient/Coordinators/EventSourceCoordinatorForActivities.swift
- AlphaWallet/Tokens/Coordinators/GetBlockTimestamp.swift
- AlphaWallet/Tokens/Coordinators/GetContractDecimals.swift
- AlphaWallet/Tokens/Coordinators/GetContractName.swift
- AlphaWallet/Tokens/Coordinators/GetContractSymbol.swift
- AlphaWallet/Tokens/Coordinators/GetDASNameLookup.swift
- AlphaWallet/Tokens/Coordinators/GetErc20Balance.swift
- AlphaWallet/Tokens/Coordinators/GetErc721Balance.swift
- AlphaWallet/Tokens/Coordinators/GetErc721ForTicketsBalance.swift
- AlphaWallet/Tokens/Coordinators/GetErc875Balance.swift
- AlphaWallet/Tokens/Coordinators/GetNativeCryptoCurrencyBalance.swift
- AlphaWallet/Tokens/Coordinators/GetWalletName.swift
- AlphaWallet/Tokens/Coordinators/IsErc1155Contract.swift
- AlphaWallet/Tokens/Coordinators/IsErc721Contract.swift
- AlphaWallet/Tokens/Coordinators/IsErc721ForTicketsContract.swift
- AlphaWallet/Tokens/Coordinators/IsErc875Contract.swift
- AlphaWallet/Tokens/Coordinators/IsInterfaceSupported165.swift
- AlphaWallet/Tokens/Coordinators/TokensCoordinator.swift
- AlphaWalletTests/Factories/FakeGetBalanceCoordinator(.swift
- AlphaWalletTests/Tokens/Coordinators/GetIsERC1155ContractCoordinatorTestCase.swift
> [Refactor] Rename fetch smartcontract data coordinator with provider suffix #4529

- AlphaWallet.xcodeproj/project.pbxproj
> Set version and build numbers are project level instead of at target level

- AlphaWallet/Activities/ActivitiesService.swift
- AlphaWallet/TokenScriptClient/Models/XMLHandler.swift
> Share threadsafe beetwen static instances of PrivateXMLHandler, and XMLHandler #4554

- AlphaWallet/ActiveWalletCoordinator.swift
- AlphaWallet/AppCoordinator.swift
- AlphaWallet/Core/Initializers/CleanupWallets.swift
- AlphaWallet/Core/Initializers/DatabaseMigration.swift
- AlphaWallet/Core/Types/RealmConfiguration.swift
- AlphaWallet/Core/Types/RealmStore.swift
- AlphaWallet/Tokens/Types/TokenObject.swift
> User shared realm for browser #4531

- AlphaWallet/Core/Initializers/DatabaseMigration.swift
> Fix crash when migrate bookmarks #4563

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet/Gas/Models/EtherscanGasPriceEstimator.swift
- AlphaWallet/Transfer/Controllers/GasPriceEstimator.swift
- AlphaWallet/Transfer/Controllers/TransactionConfigurator.swift
- AlphaWallet/Transfer/Types/GasFeeWarning.swift
- AlphaWallet/Transfer/Types/GasLimitWarning.swift
- AlphaWallet/Transfer/Types/GasPriceWarning.swift
> [Refactor] Extract GasEstimation to separate class, move models to separate files for TransactionConfigurator #4559

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet/ActiveWalletCoordinator.swift
- AlphaWallet/AppCoordinator.swift
- AlphaWallet/Core/BuyToken/BuyTokenService.swift
- AlphaWallet/Core/BuyToken/Ramp/Ramp.swift
- AlphaWallet/Core/SwapToken/ArbitrumBridge.swift
- AlphaWallet/Core/SwapToken/HoneySwap/HoneySwap.swift
- AlphaWallet/Core/SwapToken/Oneinch/Oneinch.swift
- AlphaWallet/Core/SwapToken/QuickSwap/QuickSwap.swift
- AlphaWallet/Core/SwapToken/SwapTokenNativeProvider.swift
- AlphaWallet/Core/SwapToken/SwapTokenViaUrlProvider.swift
- AlphaWallet/Core/SwapToken/TokenActionsService.swift
- AlphaWallet/Core/SwapToken/Uniswap/Uniswap.swift
- AlphaWallet/Core/SwapToken/xDaiBridge.swift
- AlphaWallet/Tokens/Coordinators/SingleChainTokenCoordinator.swift
- AlphaWallet/Tokens/Coordinators/TokensCoordinator.swift
- AlphaWallet/Tokens/Types/TokenInstanceAction.swift
- AlphaWallet/Tokens/ViewControllers/TokenViewController.swift
- AlphaWallet/Tokens/ViewModels/TokenViewControllerViewModel.swift
- AlphaWalletTests/Coordinators/TokensCoordinatorTests.swift
> [Refactor] add supporting swap action for native swap #4561

- AlphaWallet/Tokens/Coordinators/GetBlockTimestamp.swift
> Move map of GetBlockTimestampCoordinator to non main queue #4527

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet/ActiveWalletCoordinator.swift
- AlphaWallet/AppCoordinator.swift
- AlphaWallet/Core/Coordinators/Alerts/StorageType.swift
- AlphaWallet/Core/Coordinators/WalletBalance/WalletBalanceService.swift
- AlphaWallet/Core/Initializers/DatabaseMigration.swift
- AlphaWallet/Core/RealmLocalStore.swift
- AlphaWallet/Core/Types/RealmConfiguration.swift
- AlphaWallet/Core/Types/RealmStore.swift
- AlphaWallet/TokenScriptClient/Models/EventsActivityDataStore.swift
- AlphaWallet/TokenScriptClient/Models/NonActivityEventsDataStore.swift
- AlphaWallet/Tokens/Types/TokensDataStore.swift
- AlphaWallet/Transactions/Storage/TransactionsStorage.swift
- AlphaWalletTests/Coordinators/InCoordinatorTests.swift
- AlphaWalletTests/Factories/FakeMultiWalletBalanceService.swift
- AlphaWalletTests/Factories/FakeNftProvider.swift
- AlphaWalletTests/Factories/FakeRealmLocalStore.swift
- AlphaWalletTests/Factories/FakeSingleChainTokenBalanceService.swift
- AlphaWalletTests/Factories/FakeTokensDataStore.swift
- AlphaWalletTests/Factories/FakeTransactionsStorage.swift
- AlphaWalletTests/Factories/WalletSession.swift
- AlphaWalletTests/Settings/Coordinators/SettingsCoordinatorTests.swift
- AlphaWalletTests/TokenScriptClient/FakeEventsDataStore.swift
> Share single realm store between datastores #4568

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet/ActiveWalletCoordinator.swift
- AlphaWallet/AppCoordinator.swift
- AlphaWallet/Core/Helpers/FirebaseReportService.swift
- AlphaWallet/Core/Initializers/ReportUsersWalletAddresses.swift
- AlphaWallet/EtherClient/Wallet.swift
> Add tracking active users wallet address for firebase reports #4566

- AlphaWallet/Core/Views/SelfSizingPanelLayout.swift
> [Refactor] Remove unused code #4575

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet/Features/FeaturesTableViewController.swift
- AlphaWallet/Settings/Types/CustomRpcTableViewSection.swift
- AlphaWallet/Settings/Types/SaveCustomRpcBrowseDataController.swift
- AlphaWallet/Settings/Types/TableViewSection.swift
- AlphaWallet/Settings/ViewControllers/EnabledServersViewController.swift
- AlphaWallet/Settings/ViewControllers/SaveCustomRpcBrowseViewController.swift
- AlphaWallet/Settings/ViewControllers/ServersViewController.swift
- AlphaWallet/Settings/ViewModels/ServerViewModel.swift
- AlphaWallet/Settings/Views/RPCDisplaySelectableTableViewCell.swift
Closes #4402
See #4402 for more details.
> #4402 update screens which show list of chains to include icon and chain

- AlphaWallet/ActiveWalletCoordinator.swift
- AlphaWallet/AppCoordinator.swift
- AlphaWallet/Core/BuyToken/Ramp/Ramp.swift
- AlphaWallet/Core/Coordinators/TokensFilter.swift
- AlphaWallet/Core/SwapToken/ArbitrumBridge.swift
- AlphaWallet/Core/SwapToken/HoneySwap/HoneySwap.swift
- AlphaWallet/Core/SwapToken/Oneinch/Oneinch.swift
- AlphaWallet/Core/SwapToken/QuickSwap/QuickSwap.swift
- AlphaWallet/Core/SwapToken/SwapTokenNativeProvider.swift
- AlphaWallet/Core/SwapToken/TokenActionsService.swift
- AlphaWallet/Core/SwapToken/Uniswap/Uniswap.swift
- AlphaWallet/Core/SwapToken/xDaiBridge.swift
- AlphaWallet/Tokens/Coordinators/SingleChainTokenCoordinator.swift
- AlphaWallet/Tokens/Coordinators/TokensCoordinator.swift
- AlphaWallet/Tokens/ViewControllers/TokenViewController.swift
- AlphaWallet/Tokens/ViewModels/TokenViewControllerViewModel.swift
- AlphaWalletTests/Coordinators/TokensCoordinatorTests.swift
> Make TokenActionsService being able to subscribable for providers updates #4582

- AlphaWallet/Tokens/Helpers/UiTweaks.swift
>  Make noPriceMarker as single whitespace instead to be an empty string, to save label height #4589

- AlphaWallet/TokenScriptClient/Coordinators/EventSourceCoordinator.swift
- AlphaWallet/TokenScriptClient/Coordinators/EventSourceCoordinatorForActivities.swift
- AlphaWallet/Tokens/Helpers/CallSmartContractFunction.swift
> Return directly promise when fetching events EventSourceCoordinatorForActivities #4597

- AlphaWallet/Core/Coordinators/WalletBalance/PrivateBalanceFetcher.swift
> Fix memory leak for Erc1155BalanceFetcher #4599

- AlphaWallet/Core/NFT/OpenSea/OpenSea.swift
> [OpenSea] release latest promise on its completion #4595

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet/Tokens/Coordinators/SingleChainTokenCoordinator.swift
- AlphaWallet/Tokens/ViewControllers/FungibleTokenViewController.swift
- AlphaWallet/Tokens/ViewModels/FungibleTokenViewModel.swift
> [Refactor] Rename TokenViewController with FungibleTokenViewController #4603

- AlphaWallet/Tokens/Coordinators/SingleChainTokenCoordinator.swift
- AlphaWallet/Tokens/Helpers/TokenAdaptor.swift
- AlphaWallet/Tokens/ViewControllers/FungibleTokenViewController.swift
> Make token holder observable (for fungible token) #4590

- AlphaWallet/Activities/ActivitiesService.swift
- AlphaWallet/Core/Coordinators/WalletBalance/WalletBalanceFetcher.swift
- AlphaWallet/Core/Coordinators/WalletBalance/WalletBalanceService.swift
- AlphaWallet/Core/NFT/Enjin/Enjin.swift
- AlphaWallet/Core/NFT/OpenSea/OpenSea.swift
- AlphaWallet/Core/RealmLocalStore.swift
- AlphaWallet/Core/Types/ThreadSafeDictionary.swift
- AlphaWallet/Covalent/TransactionProviders/PendingTransaction/PendingTransactionProvider.swift
- AlphaWallet/Extensions/Date.swift
- AlphaWallet/Extensions/UIView.swift
- AlphaWallet/TokenScriptClient/Models/CallForAssetAttributeCoordinator.swift
- AlphaWallet/TokenScriptClient/Models/XMLHandler.swift
- AlphaWallet/Tokens/Helpers/CallSmartContractFunction.swift
- AlphaWallet/Tokens/Logic/GetBlockTimestamp.swift
- AlphaWallet/UI/TokenObject+UI.swift
- AlphaWalletTests/Factories/FakeRealmLocalStore.swift
- modules/AlphaWalletAddress/AlphaWalletAddress/AlphaWallet.swift
- modules/AlphaWalletAddress/AlphaWalletAddress/AtomicArray.swift
- modules/AlphaWalletAddress/AlphaWalletAddress/AtomicDictionary.swift
> [Refactor] Rename ThreadSafeDictionary with AtomicDictionary, add AtomicArray implementation #4611

- AlphaWallet/Core/BuyToken/Ramp/Ramp.swift
- AlphaWallet/Core/SwapToken/Oneinch/Oneinch.swift
- AlphaWallet/Core/Types/ThreadSafeDictionary.swift
> Fix crash on bad access for Oneinch #4609

- Makefile
Switched from `OS=15.4` to `OS=latest`
> Updated Makefile to always use the latest installed iOS instead of specifying a version.

- AlphaWallet/Activities/ActivitiesService.swift
- AlphaWallet/Covalent/TransactionProviders/PendingTransaction/PendingTransactionProvider.swift
- AlphaWallet/Notifications/TransactionNotificationService.swift
- AlphaWallet/Transactions/Storage/Transaction.swift
- AlphaWallet/Transactions/Storage/TransactionsStorage.swift
- AlphaWallet/Transactions/TransactionsService.swift
- AlphaWalletTests/Factories/Transaction.swift
- AlphaWalletTests/Transactions/Storage/TransactionsStorageTests.swift
> Replace transactions with its value types, (for reducing size of #4621) #4624

- AlphaWallet/Activities/ActivitiesService.swift
- AlphaWallet/TokenScriptClient/Models/EventOrigin.swift
- AlphaWallet/TokenScriptClient/Models/EventsActivityDataStore.swift
- AlphaWallet/TokenScriptClient/Models/NonActivityEventsDataStore.swift
- AlphaWallet/TokenScriptClient/Models/TokenIdOrEvent.swift
- AlphaWallet/Tokens/Helpers/TokenAdaptor.swift
> Replace EventInstance, EventActivityInstance with their value types, (for reducing size of #4621) #4626

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet/Core/Types/ImageOrWebImageUrl.swift
- AlphaWallet/Core/Types/ViewRounding.swift
- AlphaWallet/Core/Views/BlockieImageView.swift
- AlphaWallet/Core/Views/WebImageView.swift
- AlphaWallet/Tokens/Collectibles/ViewControllers/NFTAssetViewController.swift
- AlphaWallet/Tokens/Collectibles/Views/Erc875NonFungibleRowView.swift
- AlphaWallet/Tokens/Collectibles/Views/NFTCollectionInfoPageView.swift
- AlphaWallet/Tokens/Collectibles/Views/NonFungibleRowView.swift
- AlphaWallet/Tokens/Views/OpenSea/OpenSeaNonFungibleTokenViewCell.swift
- AlphaWallet/UI/SvgImageView.swift
- AlphaWallet/UI/TokenImageView.swift
- AlphaWallet/UI/TokenObject+UI.swift
> Make ERC721/ERC1155 token image with rounded corners #4585

- AlphaWallet/Tokens/Collectibles/Views/NonFungibleRowView.swift
> Make token image in NFT's Assets tab have rounded corners #4630

- AlphaWallet/Localization/en.lproj/Localizable.strings
- AlphaWallet/Localization/es.lproj/Localizable.strings
- AlphaWallet/Localization/fi.lproj/Localizable.strings
- AlphaWallet/Localization/ja.lproj/Localizable.strings
- AlphaWallet/Localization/ko.lproj/Localizable.strings
- AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings
- AlphaWallet/Tokens/Collectibles/ViewModels/NFTCollectionInfoPageViewModel.swift
- AlphaWallet/Tokens/Collectibles/Views/NFTCollectionInfoPageView.swift
- AlphaWallet/Tokens/Views/TokenRowView.swift
> add localication for strings, code clean up #4637

- AlphaWallet/Settings/Types/Config.swift
> dasable shouldPretendIsRealWallet #4642

- AlphaWallet/Core/NFT/OpenSea/OpenSea.swift
> OpenSea.Storage get created on each call of fetchAssetImageUrl(for #4646

- AlphaWallet/Localization/en.lproj/Localizable.strings
- AlphaWallet/Localization/es.lproj/Localizable.strings
- AlphaWallet/Localization/fi.lproj/Localizable.strings
- AlphaWallet/Localization/ja.lproj/Localizable.strings
- AlphaWallet/Localization/ko.lproj/Localizable.strings
- AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings
- AlphaWallet/Settings/ViewModels/ServerViewModel.swift
> Replace hard coded “ChainID” with Localizable string “Chain ID” and %i string formatting in ServerImageViewModel.

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet/AppCoordinator.swift
- AlphaWallet/Core/Views/ButtonsBar/VerticalButtonsBar.swift
- AlphaWallet/Settings/Views/EnableServersHeaderView.swift
- AlphaWallet/Wallet/Coordinators/InitialNetworkSelectionCoordinator.swift
- AlphaWallet/Wallet/Coordinators/InitialWalletCreationCoordinator.swift
- AlphaWallet/Wallet/Coordinators/WalletCoordinator.swift
- AlphaWallet/Wallet/Models/InitialNetworkSelectionCollectionModel.swift
- AlphaWallet/Wallet/ViewControllers/InitialNetworkSelectionViewController.swift
- AlphaWallet/Wallet/ViewModels/InitialNetworkSelectionViewModel.swift
- AlphaWallet/Wallet/Views/InitialNetworkSelectionView.swift
- AlphaWalletTests/Wallet/Models/InitialNetworkSelectionCollectionModelTestCase.swift
Closes #4507.
I will squish and merge once approved.
1. Delete the app from your device.
2. Run.
3. Select "Create wallet" (screen 7).
4. Expect InitialNetworkSelectionViewController (screen 1) to show up.
5. Select one or more networks in main net.
6. Press continue button.
7. Expect TokensViewController (screen 6) to show up.
1. Delete the app from your device.
2. Run.
3. Select "I already have a wallet" (screen 7).
4. Select "Import existing wallet" (screen 8).
5. Enter wallet data.
6. Expect InitialNetworkSelectionViewController (screen 1) to show up.
7. Select one or more networks in mainnets.
8. Press continue button.
9. Expect TokensViewController (screen 6) to show up. 
1. Delete the app from your device.
2. Run.
3. Select "I already have a wallet" (screen 7).
4. Select "Track …
> #4507 add select network screen after you create import a new wallet

- AlphaWallet/Activities/ActivitiesService.swift
- AlphaWallet/Market/Coordinators/ImportMagicLinkCoordinator.swift
- AlphaWallet/TokenScriptClient/Models/XMLHandler.swift
- AlphaWallet/Tokens/Collectibles/ViewModels/SelectableNFTAssetContainerViewModel.swift
- AlphaWallet/Tokens/Helpers/TokenAdaptor.swift
- AlphaWallet/Tokens/Types/Token.swift
- AlphaWallet/Tokens/Types/TokenHolder.swift
- AlphaWalletTests/Tokens/Helpers/TokenAdaptorTest.swift
> wrap Token in TokenScript.Token #4645

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet/Tokens/Collectibles/ViewModels/FungibleTokenHeaderViewModel.swift
- AlphaWallet/Tokens/Collectibles/Views/FungibleTokenHeaderView.swift
- AlphaWallet/Tokens/Collectibles/Views/TokenInfoPageView.swift
- AlphaWallet/Tokens/ViewModels/TokenInfoPageViewModel.swift
> [Refactor] Rename NonFungibleTokenHeaderViewModel with FungibleTokenHeaderViewModel (wrong name, of what it actually does) #4670

- AlphaWallet/Foundation/Subscribable.swift
> [Refactor] Remove unused code #4673

- AlphaWallet/Settings/Views/RPCDisplaySelectableTableViewCell.swift
- AlphaWallet/Settings/Views/ServerViewCell.swift
- AlphaWallet/Tokens/Collectibles/Views/TokenInfoPageView.swift
- AlphaWallet/Transfer/Collectibles/ViewControllers/TransferTokenBatchCardsViaWalletAddressViewController.swift
> [Refactor] Replace .separator with .spacer(height as they do the same #4675

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet/Core/Coordinators/WalletBalance/PrivateBalanceFetcher.swift
- AlphaWallet/Core/Coordinators/WalletBalance/WalletBalanceFetcher.swift
- AlphaWallet/Core/Coordinators/WalletBalance/WalletBalanceService.swift
- AlphaWallet/Core/TokensAutodetector/TokensAutodetector.swift
- AlphaWallet/Core/Types/RealmStore.swift
- AlphaWallet/Core/Types/RunLoopThread.swift
- AlphaWallet/TokenScriptClient/Models/EventsActivityDataStore.swift
- AlphaWallet/TokenScriptClient/Models/NonActivityEventsDataStore.swift
- AlphaWallet/Tokens/Types/DelegateContract.swift
- AlphaWallet/Tokens/Types/DeletedContract.swift
- AlphaWallet/Tokens/Types/HiddenContract.swift
- AlphaWallet/Tokens/Types/TokenObject.swift
- AlphaWallet/Tokens/Types/TokensDataStore.swift
- AlphaWallet/Transactions/Storage/TransactionsStorage.swift
- AlphaWallet/Transactions/TokensFromTransactionsFetcher.swift
- AlphaWalletTests/Factories/FakeSingleChainTokenBalanceService.swift
- AlphaWalletTests/Tokens/TokensDataStoreTest.swift
- AlphaWalletTests/Transfer/ViewControllers/SendViewControllerTests.swift
> Use single Realm instances for background, and main threads #4664

- AlphaWallet/Core/Types/RealmConfiguration.swift
> Fix crash when writing data to realm in background #4681

- AlphaWallet/Activities/ActivitiesService.swift
- AlphaWallet/Core/Coordinators/WalletBalance/PrivateBalanceFetcher.swift
- AlphaWallet/Core/Coordinators/WalletBalance/WalletBalanceFetcher.swift
- AlphaWallet/Core/TokensAutodetector/TokensAutodetector.swift
- AlphaWallet/Covalent/TransactionProviders/PendingTransaction/PendingTransactionProvider.swift
- AlphaWallet/Notifications/TransactionNotificationService.swift
- AlphaWallet/TokenScriptClient/Coordinators/EventSourceCoordinator.swift
- AlphaWallet/TokenScriptClient/Coordinators/EventSourceCoordinatorForActivities.swift
- AlphaWallet/TokenScriptClient/Coordinators/FetchAssetDefinitionsCoordinator.swift
- AlphaWallet/TokenScriptClient/Models/EventsActivityDataStore.swift
- AlphaWallet/Tokens/Types/TokenCollection.swift
- AlphaWallet/Tokens/Types/TokensDataStore.swift
- AlphaWallet/Transactions/Coordinators/TransactionCoordinator.swift
- AlphaWallet/Transactions/Storage/TransactionsStorage.swift
- AlphaWallet/Transactions/TokensFromTransactionsFetcher.swift
- AlphaWallet/Transactions/TransactionsService.swift
> [Refactoring] Rename changesetPublishers to changeset #4683

- AlphaWallet/Tokens/Types/TokensDataStore.swift
> Change an order of Token balance update func (current one might not be correct) #4688

- AlphaWallet/Core/NFT/OpenSea/OpenSeaNetworkProvider.swift
- AlphaWallet/Settings/Types/Config.swift
> Add flag to disable OpenSea calls, for debugging #4690

- AlphaWalletTests/Settings/ConfigTests.swift
> Add test case to ensure all flags in `Config.Development` are false #4703

- AlphaWallet/Core/Coordinators/TokensFilter.swift
- AlphaWallet/Core/SwapToken/TokenActionsService.swift
- AlphaWallet/FiatOnRamp/Coordinators/FiatOnRampCoordinator.swift
- AlphaWallet/Tokens/Types/TokenBalance.swift
- AlphaWallet/Tokens/Types/TokenCollection.swift
- AlphaWallet/Tokens/Types/TokensDataStore.swift
- AlphaWallet/Tokens/ViewModels/FungibleTokenViewModel.swift
> Add searching in nfts json by keyword #4658

- AlphaWallet/Activities/ActivitiesService.swift
- AlphaWallet/TokenScriptClient/Coordinators/EventSourceCoordinator.swift
- AlphaWallet/TokenScriptClient/Coordinators/EventSourceCoordinatorForActivities.swift
- AlphaWallet/TokenScriptClient/Models/EventsActivityDataStore.swift
- AlphaWallet/TokenScriptClient/Models/NonActivityEventsDataStore.swift
- AlphaWallet/Tokens/Collectibles/Coordinators/NFTCollectionCoordinator.swift
- AlphaWallet/Tokens/Helpers/TokenAdaptor.swift
- AlphaWallet/Transfer/Coordinators/TokenScriptCoordinator.swift
> [Refactor] Rename functions EventsDataStores #4706

- AlphaWallet/Style/AppStyle.swift
> Increase margins between segmented control buttons

- AlphaWallet/Core/Coordinators/WalletBalance/WalletBalanceFetcher.swift
- AlphaWallet/Core/TokensAutodetector/TokenObjectFetcher.swift
- AlphaWallet/Core/TokensAutodetector/TokensAutodetector.swift
- AlphaWallet/Tokens/Types/TokensDataStore.swift
- AlphaWalletTests/Tokens/Helpers/TokenObjectTest.swift
- AlphaWalletTests/Tokens/TokensDataStoreTest.swift
> [Refactor] Replace DeletedContract, Delegatecontract HiddenContract with AddressAndRPCServer struct #4710

- AlphaWallet/Core/Coordinators/WalletBalance/PrivateBalanceFetcher.swift
- AlphaWallet/Core/Coordinators/WalletBalance/WalletBalanceFetcher.swift
- AlphaWallet/Core/TokensAutodetector/AutoDetectTokensOperation.swift
- AlphaWallet/Core/TokensAutodetector/AutoDetectTransactedTokensOperation.swift
- AlphaWallet/Core/TokensAutodetector/TokenObjectFetcher.swift
- AlphaWallet/Core/TokensAutodetector/TokensAutodetector.swift
- AlphaWallet/Tokens/Coordinators/SingleChainTokenCoordinator.swift
- AlphaWallet/Tokens/Types/TokensDataStore.swift
- AlphaWalletTests/Tokens/Helpers/TokenObjectTest.swift
- AlphaWalletTests/Tokens/TokensDataStoreTest.swift
> [Refactor] Rename TokensDataStore functions names #4713

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet/Core/TokensAutodetector/TokenFetcher.swift
- AlphaWallet/Core/TokensAutodetector/TokensAutodetector.swift
- AlphaWallet/Tokens/Coordinators/SingleChainTokenCoordinator.swift
- AlphaWallet/Tokens/Coordinators/TokensCoordinator.swift
> [Refactor] Rename SingleChainTokenFetcher functions names #4716

- AlphaWallet/WalletConnect/Providers/v2/WalletConnectV2Provider.swift
- AlphaWallet/WalletConnect/Providers/v2/WalletConnectV2Types.swift
Fixes master branch commit d6ffe6b3ec72d561c9b49c0ae5729e7534189349 build issue.
> Removed import WalletConnect from WalletConnectV2Provider and WalletConnectV2Types that was preventing the project from being built.

- AlphaWallet/TokenScriptClient/Models/EventsActivityDataStore.swift
- AlphaWallet/Tokens/Types/TokensDataStore.swift
- AlphaWallet/Transactions/Storage/TransactionsStorage.swift
> Add check for empty operations when perform batch of realm updates #4730

- AlphaWallet/Browser/ViewControllers/BrowserViewController.swift
> Make WalletConnect work in dapp browser #4734

- AlphaWallet/Core/Types/RunLoopThread.swift
- AlphaWallet/Settings/Types/Config.swift
> Add flag for logging in RunLoopThread #4737

- AlphaWallet/Core/Initializers/DatabaseMigration.swift
- AlphaWallet/Tokens/Types/TokenObject.swift
> Fix TokenInfo migration, (prev one, was missing _info object sometimes) #4751

- Podfile
- Podfile.lock
> Upgrate realm to latest version v10.27.0 #4755

- AlphaWallet/Tokens/Types/TokenCollection.swift
- AlphaWallet/Tokens/ViewModels/TokensViewModel.swift
> Move `filterAwaySpuriousTokens` to TokenCollection #4760

- AlphaWallet/Tokens/ViewControllers/TokensViewController.swift
- AlphaWallet/Tokens/ViewModels/TokensViewModel.swift
> [Refactor] Rename `TokenObjectOrRpcServerPair` with `TokenOrRpcServer` #4762

- AlphaWallet/Tokens/ViewModels/TokensViewModel.swift
> [Refactor] Rename function `groupTokenObjectsWithServers` with `groupTokensByServers` #4766

- AlphaWallet/Core/PopularTokens/PopularTokensCollection.swift
- AlphaWallet/Tokens/Coordinators/AddHideTokensCoordinator.swift
- AlphaWallet/Tokens/ViewControllers/AddHideTokensViewController.swift
- AlphaWallet/Tokens/ViewModels/AddHideTokensViewModel.swift
> Move more code to view model for AddHideTokensViewController #4768

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet/Extensions/UIColor.swift
- AlphaWalletTests/Extensions/UIColorExtensionTests.swift
> Corrected UIColor extension to use currentIndex. Test also provided for UIColor hex parsing.

- AlphaWallet/Tokens/Types/TokenObject.swift
- AlphaWallet/Tokens/Types/TokensDataStore.swift
Closes #4776, Closes #4783, Closes #4782
> Fetch TokenInfoObject if _info is null, (actually object should be always there) #4776

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet/Browser/Coordinators/ScanQRCodeCoordinator.swift
- AlphaWallet/Swap/Swap/Types/SwapQuoteState.swift
- AlphaWallet/Swap/Swap/Types/TokenSwapperError.swift
- AlphaWallet/Swap/SwapOptions/ViewControllers/SwapOptionsViewController.swift
- AlphaWallet/Tokens/Types/WalletFilter.swift
> Remove project warnings #4788

- AlphaWallet/Core/Initializers/DatabaseMigration.swift
- AlphaWallet/Tokens/Types/TokenObject.swift
> Warnings about RealmOptional being deprecated #4780

- AlphaWallet/Core/Initializers/DatabaseMigration.swift
- AlphaWallet/Core/Initializers/MigrationInitializerForOneChainPerDatabase.swift
> Define realm database related classes for wallet db #4764

- AlphaWallet/Notifications/TransactionNotificationService.swift
- AlphaWallet/TokenScriptClient/Models/EventsActivityDataStore.swift
- AlphaWallet/TokenScriptClient/Models/NonActivityEventsDataStore.swift
- AlphaWallet/Tokens/Types/TokensDataStore.swift
- AlphaWallet/Transactions/Coordinators/TransactionCoordinator.swift
- AlphaWallet/Transactions/Storage/TransactionsStorage.swift
> Move realm object mapping to background queue (to speedup the app) for changeset #4757

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet/ActiveWalletCoordinator.swift
- AlphaWallet/Core/TokensAutodetector/ImportToken.swift
- AlphaWallet/Core/TokensAutodetector/TokensAutodetector.swift
- AlphaWallet/Tokens/Coordinators/AddHideTokensCoordinator.swift
- AlphaWallet/Tokens/Coordinators/NewTokenCoordinator.swift
- AlphaWallet/Tokens/Coordinators/SingleChainTokenCoordinator.swift
- AlphaWallet/Tokens/Coordinators/TokensCoordinator.swift
- AlphaWallet/Tokens/ViewModels/AddHideTokensViewModel.swift
- AlphaWalletTests/Coordinators/TokensCoordinatorTests.swift
- AlphaWalletTests/Settings/ConfigTests.swift
> Extract more logic from coordinator, move token importing to separate resolver #4770

- AlphaWallet/Tokens/Coordinators/AddHideTokensCoordinator.swift
- AlphaWallet/Tokens/Coordinators/SelectTokenCoordinator.swift
- AlphaWallet/Tokens/Coordinators/TokensCoordinator.swift
- AlphaWallet/Tokens/ViewControllers/AddHideTokensViewController.swift
- AlphaWallet/Tokens/ViewControllers/SelectTokenViewController.swift
- AlphaWallet/Tokens/ViewControllers/TokensViewController.swift
- AlphaWallet/Tokens/ViewModels/AddHideTokensViewModel.swift
- AlphaWallet/Tokens/ViewModels/EthTokenViewCellViewModel.swift
- AlphaWallet/Tokens/ViewModels/FungibleTokenViewCellViewModel.swift
- AlphaWallet/Tokens/ViewModels/NonFungibleTokenViewCellViewModel.swift
- AlphaWallet/Tokens/ViewModels/SelectTokenViewModel.swift
- AlphaWallet/Tokens/Views/EthTokenViewCell.swift
- AlphaWallet/Tokens/Views/FungibleTokenViewCell.swift
- AlphaWallet/Tokens/Views/NonFungibleTokenViewCell.swift
> Move more logic to view models for SelectTokenViewModel, and AddHideTokensViewModel #4774

- AlphaWallet/Style/AppStyle.swift
> Update color of inactive links in Tab Bar #4750

- AlphaWallet/ActiveWalletCoordinator.swift
- AlphaWallet/Core/TokensAutodetector/ImportToken.swift
- AlphaWallet/Tokens/Coordinators/TokensCoordinator.swift
- AlphaWalletTests/Coordinators/TokensCoordinatorTests.swift
> Improve ImportToken #4794

- AlphaWallet/Core/Helpers/BlockieGenerator.swift
> [Refactor] Remove unused function #4799

- AlphaWallet/Core/Initializers/DatabaseMigration.swift
> Fix: Tests fails: AlphaWalletTests.InCoordinatorTests with "Object type 'Bookmark' is not managed by the Realm"

- AlphaWallet/Transfer/ViewModels/SignatureConfirmationConfirmationViewModel.swift
> Dispay domain.name, and domain.verifyingContract if them non empty or non nill #4744

- AlphaWallet/Accounts/Coordinators/AccountsCoordinator.swift
- AlphaWallet/Accounts/ViewControllers/AccountsViewController.swift
- AlphaWallet/Accounts/ViewModels/AccountViewModel.swift
- AlphaWallet/Accounts/ViewModels/AccountsViewModel.swift
- AlphaWallet/Accounts/Views/AccountViewCell.swift
- AlphaWallet/Accounts/Views/AccountViewTableSectionHeader.swift
> ENS name is not displaying in the change wallet page #4726

- AlphaWallet/WalletConnect/Providers/v1/WalletConnectV1Provider.swift
- AlphaWallet/WalletConnect/Providers/v2/WalletConnectV2Provider.swift
- AlphaWallet/WalletConnect/ViewController/WalletConnectSessionsViewController.swift
- AlphaWallet/WalletConnect/ViewModel/WalletConnectSessionsViewModel.swift
> Move wallet connect session updates to main thread #4712

- AlphaWallet/Foundation/Subscribable.swift
- AlphaWallet/TokenScriptClient/Models/AssetAttributeValues.swift
- modules/AlphaWalletAddress/AlphaWalletAddress/AtomicDictionary.swift
> Make AssetAttributeValues, Subscribable threadsafe #4820

- Podfile
- Podfile.lock
> Remove manual ping for wallet connect v1 #4431

- AlphaWallet/Settings/Coordinators/SettingsCoordinator.swift
> Changed code in SettingsCoordinator to remove passed in coordinator rather than the parent coordinator.

- AlphaWallet/ActiveWalletCoordinator.swift
- AlphaWallet/Activities/ActivitiesService.swift
- AlphaWallet/Activities/Coordinators/ActivitiesCoordinator.swift
- AlphaWalletTests/Activitities/FakeActivitiesService.swift
> [Refactor] remove unused code for Activities service #4832

- AlphaWallet/Activities/ActivitiesService.swift
- AlphaWallet/Activities/Coordinators/ActivitiesCoordinator.swift
- AlphaWallet/Tokens/Collectibles/ViewControllers/NFTCollectionViewController.swift
- AlphaWallet/Tokens/ViewControllers/FungibleTokenViewController.swift
- AlphaWalletTests/Activitities/FakeActivitiesService.swift
> [Refactor] Replace passing activities view model with array of activities. #4834

- AlphaWallet/TokenScriptClient/Coordinators/EventSourceCoordinator.swift
- AlphaWallet/TokenScriptClient/Coordinators/EventSourceCoordinatorForActivities.swift
- AlphaWallet/TokenScriptClient/Models/EventsActivityDataStore.swift
- AlphaWallet/TokenScriptClient/Models/NonActivityEventsDataStore.swift
> [Refactor] Rename add(events with addOrUpdate(events:) #4840

- AlphaWallet/Core/RealmLocalStore.swift
- AlphaWallet/Core/Types/RealmStore.swift
- AlphaWalletTests/Factories/FakeRealmLocalStore.swift
> Add wallet naming for realm threads #4844

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet/AppCoordinator.swift
- AlphaWallet/Core/Initializers/ConfigureImageStorage.swift
- AlphaWallet/Core/Views/WebImageView.swift
- AlphaWallet/UI/TokenObject+UI.swift
> Crash when scrolling Wallet tab because of OOM (out of memory) #4856

- AlphaWallet/Core/Types/RealmStore.swift
> Make backgroundThreadRealm as lazy #4859

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet/AppCoordinator.swift
- AlphaWallet/Core/Initializers/CleanupPasscode.swift
> [Refactor] Move CleanupPasscode to initializer #4863

- AlphaWallet/UI/AddressTextField.swift
> Calling incorrent init method for AddressTextField #4870

- AlphaWallet/Core/Coordinators/WalletBalance/PrivateBalanceFetcher.swift
- AlphaWallet/Core/Coordinators/WalletBalance/WalletBalanceFetcher.swift
- AlphaWallet/TokenScriptClient/Coordinators/EventSourceCoordinator.swift
- AlphaWallet/TokenScriptClient/Coordinators/EventSourceCoordinatorForActivities.swift
- AlphaWallet/Tokens/Types/Token.swift
- AlphaWallet/Tokens/Types/TokenBalance.swift
- AlphaWallet/Tokens/Types/TokenCollection.swift
- AlphaWallet/Tokens/Types/TokensDataStore.swift
> Remove duplicates for tokens collection changeset #4861

- AlphaWallet/Browser/Coordinators/DappBrowserCoordinator.swift
- AlphaWallet/Extensions/Error.swift
- AlphaWallet/Swap/Swap/SwapTokensCoordinator.swift
- AlphaWallet/TokenScriptClient/Models/FunctionOrigin.swift
- AlphaWallet/Tokens/Coordinators/ClaimPaidOrderCoordinator.swift
- AlphaWallet/Transactions/Coordinators/ReplaceTransactionCoordinator.swift
- AlphaWallet/Transfer/Collectibles/Coordinators/TransferCollectiblesCoordinator.swift
- AlphaWallet/Transfer/Controllers/TransactionConfigurator.swift
- AlphaWallet/Transfer/Coordinators/SendCoordinator.swift
- AlphaWallet/Transfer/Coordinators/TokenScriptCoordinator.swift
- AlphaWallet/Transfer/Coordinators/TransactionConfirmationCoordinator.swift
- AlphaWallet/Transfer/Coordinators/TransferNFTCoordinator.swift
- AlphaWallet/WalletConnect/Controllers/TransactionConfirmationCoordinatorBridgeToPromise.swift
- AlphaWalletTests/Transfer/Controllers/TransactionConfiguratorTests.swift
- AlphaWalletTests/Transfer/TransactionConfiguratorTransactionsTests.swift
> Remove Force unwrap when building configuration for transaction #4847

- AlphaWallet/Accounts/Coordinators/AccountsCoordinator.swift
- AlphaWallet/Accounts/ViewModels/AccountViewModel.swift
- AlphaWallet/Core/UnstoppableDomains/AddressOrEnsResolution.swift
- AlphaWallet/Core/UnstoppableDomains/DomainResolutionService.swift
- AlphaWallet/Core/Views/AddressOrEnsNameLabel.swift
- AlphaWallet/Settings/ViewControllers/SettingsViewController.swift
- AlphaWallet/Settings/Views/SettingTableViewCell.swift
- AlphaWallet/Tokens/Coordinators/TokensCoordinator.swift
- AlphaWallet/Tokens/Logic/GetWalletName.swift
- AlphaWallet/Transfer/Types/RecipientResolver.swift
- AlphaWallet/Transfer/ViewControllers/RequestViewController.swift
- AlphaWallet/Transfer/ViewControllers/TransactionConfirmationViewController.swift
- AlphaWallet/Wallet/ViewControllers/RenameWalletViewController.swift
- AlphaWalletTests/Core/FakeDomainResolutionService.swift
> [Refactor] Replace promises with publishers for ens resolver #4873

- AlphaWallet/Swap/WalletPupup/WalletPupupViewController.swift
- AlphaWallet/WhatsNew/Coordinators/WhatsNewExperimentCoordinator.swift
- AlphaWallet/WhatsNew/Coordinators/WhatsNewListingCoordinator.swift
- AlphaWallet/WhatsNew/ViewControllers/WhatsNewListingViewController.swift
> Add a bar with rounded corners for `Whats New Listing` popup #4802

- AlphaWallet/Browser/ViewModel/Dapps.swift
This is to add our dApp to browsers
> add PancakeSwap to browser

- AlphaWallet/Settings/ViewControllers/SettingsViewController.swift
- AlphaWallet/Settings/Views/SettingTableViewCell.swift
> Add missing check for indexpath, for settings cell #4886

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet/Accounts/Coordinators/AccountsCoordinator.swift
- AlphaWallet/Accounts/ViewModels/AccountViewModel.swift
- AlphaWallet/Accounts/ViewModels/AccountsViewModel.swift
- AlphaWallet/AppCoordinator.swift
- AlphaWallet/Core/Helpers/WalletStorage.swift
- AlphaWallet/Core/UnstoppableDomains/AddressOrEnsResolution.swift
- AlphaWallet/Core/UnstoppableDomains/DomainResolutionService.swift
- AlphaWallet/Core/Views/AddressOrEnsNameLabel.swift
- AlphaWallet/Extensions/Publishers/Publisher+Utils.swift.swift
- AlphaWallet/Settings/Coordinators/SettingsCoordinator.swift
- AlphaWallet/Settings/Types/Config.swift
- AlphaWallet/Settings/ViewControllers/SettingsViewController.swift
- AlphaWallet/Tokens/Coordinators/TokensCoordinator.swift
- AlphaWallet/Tokens/Logic/GetWalletName.swift
- AlphaWallet/Transfer/Types/RecipientResolver.swift
- AlphaWallet/Transfer/ViewControllers/RequestViewController.swift
- AlphaWallet/Wallet/ViewControllers/RenameWalletViewController.swift
- AlphaWallet/Wallet/ViewModels/RenameWalletViewModel.swift
- AlphaWalletTests/Core/FakeDomainResolutionService.swift
> Move wallet name storage to json file #4733

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet/Tokens/Types/WalletFilter.swift
- AlphaWallet/Tokens/ViewModels/TokensViewModel.swift
- AlphaWalletTests/Tokens/WalletFilterTest.swift
Fixes #4902
Added a testcase that hopefully will catch similar problems in the future.
> Fix: tapping on Assets sub-tab does nothing

- AlphaWallet/Accounts/ViewModels/AccountViewModel.swift
- AlphaWallet/Core/ENS/ENSDelegateImpl.swift
- AlphaWallet/Core/ENS/EnsResolver.swift
- AlphaWallet/Core/ENS/EnsReverseResolver.swift
- AlphaWallet/Core/ENS/GetEnsTextRecord.swift
- AlphaWallet/Core/Helpers/BlockieGenerator.swift
- AlphaWallet/Core/UnstoppableDomains/DomainResolutionService.swift
- AlphaWallet/Core/UnstoppableDomains/UnstoppableDomainsV2Resolver.swift
- AlphaWallet/Extensions/Publishers/Publisher+Utils.swift
- AlphaWallet/Tokens/Coordinators/TokensCoordinator.swift
- AlphaWallet/Transfer/Types/RecipientResolver.swift
- AlphaWalletTests/Ens/EnsResolverTests.swift
- modules/AlphaWalletENS/AlphaWalletENS/ENS.swift
> Update promises with publishers for ens resolving #4894

- AlphaWallet/Tokens/Collectibles/ViewControllers/NFTCollectionViewController.swift
- AlphaWallet/Tokens/ViewControllers/FungibleTokenViewController.swift
> All Activity in Each Asset Disappeared #4901

- AlphaWallet/Tokens/Helpers/CallSmartContractFunction.swift
> Add logging eth_getLogs errors #4909

- AlphaWallet/Core/ViewModels/AcceptProposalViewModel.swift
- AlphaWallet/Core/ViewModels/AcceptWalletConnectSessionViewModel.swift
> Fix expand/collapse networks field when accepting walletconnect proposal #4913

- AlphaWallet/Activities/ActivitiesService.swift
- AlphaWallet/Transactions/Storage/TransactionsStorage.swift
> Pending transaction not appear after posting a transaction #4906

- AlphaWallet/Tokens/Collectibles/ViewControllers/NFTCollectionViewController.swift
- AlphaWallet/Tokens/ViewControllers/FungibleTokenViewController.swift
> Fix: 'verifying...' text appears in navigation bar for TokenScript. It shouldn't

- AlphaWallet/Core/Coordinators/WalletBalance/PrivateBalanceFetcher.swift
- AlphaWallet/Core/NFT/Enjin/Enjin.swift
- AlphaWallet/Core/NFT/NFTProvider.swift
- AlphaWallet/Core/NFT/OpenSea/OpenSea.swift
- AlphaWallet/Core/NFT/OpenSea/OpenSeaNetworkProvider.swift
- modules/AlphaWalletOpenSea/AlphaWalletOpenSea/OpenSea.swift
> Rename types to be more intention revealing

- AlphaWallet/Tokens/Types/Token.swift
- AlphaWallet/Tokens/Types/TokensDataStore.swift
> Make primary key comparison for tokens #4928

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet/Development/DevelopmentForcedError.swift
- AlphaWallet/Settings/Types/Config.swift
- AlphaWallet/Transfer/Coordinators/TransactionConfirmationCoordinator.swift
Useful to print out the transaction (not done yet) and not send it
> Add development flag to disable transaction sending

- AlphaWallet/Core/TokensAutodetector/ImportToken.swift
- AlphaWallet/Tokens/Coordinators/SingleChainTokenCoordinator.swift
- AlphaWallet/Tokens/Coordinators/TokensCoordinator.swift
> [Refactor] Move addUefaTokenIfAny to ImportToken provider, Remove unused dependencies #4953

- AlphaWallet/Settings/Types/RPCServers.swift
- AlphaWallet/Transfer/Controllers/GasPriceEstimator.swift
> Fix: do not add 1gwei to PHI's gas price estimate (because it is already very low: 2000wei as of writing) #4931

- AlphaWallet/Tokens/ViewControllers/TokensViewController.swift
- AlphaWallet/Tokens/Views/ActiveWalletSessionView.swift
> Get rid of layout constraints warning for Wallet tab at launch, when there are WalletConnect sessions. Less noise for debugging

- AlphaWallet/Foundation/EtherNumberFormatter.swift
- AlphaWallet/Transfer/ViewModels/TransactionConfirmation/DappOrWalletConnectTransactionViewModel.swift
- AlphaWallet/Transfer/ViewModels/TransactionConfirmation/SendFungiblesTransactionViewModel.swift
- AlphaWallet/WalletConnect/Types/EIP712TypedData.swift
- AlphaWalletTests/Foundation/EtherNumberFormatterTests.swift
> Update with full number formatter for transaction confirmation view model, Support negative numbers formatting for `EtherNumberFormatter`

- AlphaWallet/Core/Coordinators/TokensFilter.swift
- AlphaWallet/Tokens/Coordinators/AddHideTokensCoordinator.swift
- AlphaWallet/Tokens/Types/Token.swift
- AlphaWallet/Tokens/Types/TokensDataStore.swift
- AlphaWallet/Tokens/ViewControllers/AddHideTokensViewController.swift
- AlphaWallet/Tokens/ViewModels/AddHideTokensViewModel.swift
> Remove manual sorting functionality in "Add / Hide Tokens" screen #4948

- AlphaWallet.xcodeproj/project.pbxproj
- Podfile
- Podfile.lock
> Add CombineExt #4981

- AlphaWallet/Core/PopularTokens/PopularTokensCollection.swift
- AlphaWallet/Settings/Types/Constants.swift
- AlphaWallet/Tokens/ViewModels/PopularTokenViewCellViewModel.swift
- AlphaWallet/UI/TokenObject+UI.swift
> [Refactor] Move token image fetching to protocol #4973

- AlphaWallet/Core/Coordinators/WalletBalance/WalletBalanceService.swift
- AlphaWallet/KeyManagement/EtherKeystore.swift
> [Refactor] Move walletsPublisher to receive/update on main queue #4971

- AlphaWallet/Core/BuyToken/BuyTokenService.swift
- AlphaWallet/Core/BuyToken/Ramp/Ramp.swift
- AlphaWallet/Core/Coordinators/TokensFilter.swift
- AlphaWallet/Core/SwapToken/ArbitrumBridge.swift
- AlphaWallet/Core/SwapToken/HoneySwap/HoneySwap.swift
- AlphaWallet/Core/SwapToken/Oneinch/Oneinch.swift
- AlphaWallet/Core/SwapToken/QuickSwap/QuickSwap.swift
- AlphaWallet/Core/SwapToken/SwapTokenNativeProvider.swift
- AlphaWallet/Core/SwapToken/SwapTokenViaUrlProvider.swift
- AlphaWallet/Core/SwapToken/TokenActionsService.swift
- AlphaWallet/Core/SwapToken/Uniswap/Uniswap.swift
- AlphaWallet/Core/SwapToken/Uniswap/UniswapERC20Token.swift
- AlphaWallet/Core/SwapToken/xDaiBridge.swift
- AlphaWallet/FiatOnRamp/Coordinators/FiatOnRampCoordinator.swift
- AlphaWallet/Tokens/Types/Token.swift
- AlphaWallet/Tokens/ViewModels/FungibleTokenViewModel.swift
> Remove dependency from token for tokens actions, replace with TokenActionsIdentifiable #4979

- AlphaWallet/Core/Coordinators/TokensFilter.swift
- AlphaWallet/Tokens/JSON/TokenGroupIdentifier.swift
- AlphaWalletTests/Factories/FakeTokenGroupIdentifier.swift
- AlphaWalletTests/Tokens/TokenGroupIdentifierTest.swift
> Remove dependency from token for tokens group, replace with TokenGroupIdentifiable #4977

- AlphaWallet/ActiveWalletCoordinator.swift
- AlphaWallet/Core/TokensAutodetector/AutoDetectTokensOperation.swift
- AlphaWallet/Core/TokensAutodetector/AutoDetectTransactedTokensOperation.swift
- AlphaWallet/Core/TokensAutodetector/TokensAutodetector.swift
- AlphaWallet/Share/UrlSchemeCoordinator.swift
- AlphaWallet/Tokens/Coordinators/SingleChainTokenCoordinator.swift
- AlphaWallet/Tokens/Coordinators/TokensCoordinator.swift
- AlphaWallet/Tokens/Types/TokenCollection.swift
- AlphaWallet/Tokens/Types/TokensDataStore.swift
> Remove dependency from tokenDataStore for TokensAutodetector #4983

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet/Core/NFT/OpenSea/Types/OpenSeaNonFungibleTokenHandling.swift
- AlphaWallet/TokenScriptClient/Models/TokenScriptSupportable.swift
- AlphaWallet/TokenScriptClient/Models/XMLHandler.swift
- AlphaWallet/Tokens/Helpers/TokenAdaptor.swift
- AlphaWallet/Tokens/Types/Token.swift
> Conform Token to TokenScriptSupportable protocol #4975

- AlphaWallet/Transfer/ViewModels/ConfirmationHeaderViewModel.swift
- AlphaWallet/Transfer/Views/ConfirmationHeaderView.swift
> Action sheet title background broken

- AlphaWallet/Core/TokensAutodetector/ImportToken.swift
- AlphaWallet/Core/TokensAutodetector/TokensAutodetector.swift
> [Refactor] Adding default tokens #4989

- AlphaWallet/Covalent/TransactionProviders/CovalentToNativeTransactionMapper.swift
- AlphaWallet/Covalent/TransactionProviders/NewlyAddedTransaction/NewlyAddedTransactionProvider.swift
- AlphaWallet/Covalent/TransactionProviders/NewlyAddedTransaction/NewlyAddedTransactionSchedulerProvider.swift
- AlphaWallet/Covalent/TransactionProviders/OldestTransaction/OldestTransactionProvider.swift
- AlphaWallet/Covalent/TransactionProviders/OldestTransaction/OldestTransactionSchedulerProvider.swift
> Add fetching oldest transaction even if fetcher state is `.done`, apply retrying for covalent requests #4935

- AlphaWallet/Browser/ViewModel/Dapps.swift
If bug:
Fixes #
If not a bug:
Closes #
> Add “mail³” to the dapps list

- AlphaWallet/ActiveWalletCoordinator.swift
> Apply 1 sec delay for donateWalletShortcut() #5000

- AlphaWallet/Core/CoinTicker/CoinGecko/CoinGeckoNetworkProvider.swift
- AlphaWallet/Core/CoinTicker/CoinGecko/CoinGeckoTickersFetcher.swift
- AlphaWallet/Tokens/Types/ChartHistory.swift
> Keep order for periods when fetching chart history, fix ticker history decoding #4996

- AlphaWallet/Core/TokensAutodetector/TokenFetcher.swift
> [Refactor] Rename property so it's more intention revealing

- AlphaWallet/Alerts/ViewControllers/EditPriceAlertViewController.swift
- AlphaWallet/Sell/ViewControllers/EnterSellTokensCardPriceQuantityViewController.swift
> Hide token selection view for AmountTextField #5008

- AlphaWalletTests/Core/FakeDomainResolutionService.swift
> [Refactor] Replace fail with empty for FakeDomainResolutionService #5016

- AlphaWallet/Core/CoinTicker/Types/InMemoryTickerIdsFetcher.swift
- AlphaWallet/Covalent/TransactionProviders/CovalentNetworkProvider.swift
- AlphaWallet/Extensions/Publishers/Alamofire+Publishers.swift
- AlphaWallet/Swap/Helpers/TokenSwapperNetworkProvider.swift
- AlphaWallet/Swaps/TokenSwapper.swift
- AlphaWallet/Transactions/Coordinators/AlphaWalletProviderFactory.swift
- AlphaWalletTests/Factories/FakeTokenSwapperNetworkProvider.swift
> [Refactor] Replace DataRequestError with PromiseError #5018

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet/AppCoordinator.swift
- AlphaWallet/Core/CoinTicker/CoinGecko/CoinGeckoNetworkProvider.swift
- AlphaWallet/Core/CoinTicker/CoinGecko/CoinGeckoTickerIdsFetcher.swift
- AlphaWallet/Core/CoinTicker/CoinGecko/CoinGeckoTickersFetcher.swift
- AlphaWallet/Core/CoinTicker/Types/InMemoryTickerIdsFetcher.swift
- AlphaWallet/Core/CoinTicker/Types/TickerIdsFetcher.swift
- AlphaWalletTests/Core/Types/TickerIdsFetcherTests.swift
> Replace unowned refs with weak, add TickerIdsFetcherTests #5006

- AlphaWallet/Core/CoinTicker/CoinGecko/CoinGeckoTickersFetcher.swift
> Remove [CoinGecko] prints, move ticker update back to backround queue #5010

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet/AppCoordinator.swift
- AlphaWallet/Core/CoinTicker/CoinGecko/CoinGeckoTickersFetcher.swift
- AlphaWallet/Core/CoinTicker/CoinTickersStorage.swift
- AlphaWalletTests/Coordinators/ActiveWalletViewTests.swift
- AlphaWalletTests/Coordinators/TokensCoordinatorTests.swift
- AlphaWalletTests/Factories/FakeCoinTickersFetcher.swift
- AlphaWalletTests/Factories/FakeMultiWalletBalanceService.swift
- AlphaWalletTests/Settings/ConfigTests.swift
- modules/AlphaWalletCore/AlphaWalletCore/StorageType.swift
> Prepare CoinTickerFetcher for tests #5012

- AlphaWallet/ActiveWalletCoordinator.swift
- AlphaWallet/AppCoordinator.swift
- AlphaWallet/Core/CoinTicker/CoinGecko/CoinGeckoNetworkProvider.swift
- AlphaWallet/Core/CoinTicker/CoinGecko/CoinGeckoTickersFetcher.swift
- AlphaWallet/Core/CoinTicker/CoinTickersFetcher.swift
- AlphaWallet/Core/CoinTicker/CoinTickersStorage.swift
- AlphaWallet/Core/Coordinators/TokensFilter.swift
- AlphaWallet/Core/Coordinators/WalletBalance/WalletBalanceFetcher.swift
- AlphaWallet/Core/Coordinators/WalletBalance/WalletBalanceService.swift
- AlphaWallet/Core/Types/WalletBalance.swift
- AlphaWallet/Tokens/Coordinators/SingleChainTokenCoordinator.swift
- AlphaWallet/Tokens/Coordinators/TokensCoordinator.swift
- AlphaWallet/Tokens/Types/TokenCollection.swift
- AlphaWallet/Tokens/ViewModels/FungibleTokenViewModel.swift
- AlphaWallet/Tokens/ViewModels/TokenInfoPageViewModel.swift
- AlphaWalletTests/Factories/FakeCoinTickersFetcher.swift
> [Refactor] Rename CoinTickersFetcherType with CoinTickersFetcher #5014

- AlphaWallet/Core/CoinTicker/Types/InMemoryTickerIdsFetcher.swift
> Make reading token entries threadsafe #5026

- AlphaWallet/Tokens/Helpers/CallSmartContractFunction.swift
> Fix: Gnosis RPC node error: Too many ["eth_getLogs"] methods in the batch

- AlphaWallet/Extensions/UIButton.swift
- AlphaWallet/Extensions/UIColor.swift
- AlphaWalletTests/Extensions/UIColorExtensionTests.swift
> Fixed UIButton setBackgroundColor darkMode bug

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet/Core/Coordinators/WalletBalance/PrivateBalanceFetcher.swift
- AlphaWallet/Tokens/Helpers/NonFungibleErc1155JsonBalanceFetcher.swift
- AlphaWallet/Tokens/Helpers/NonFungibleJsonBalanceFetcher.swift
> [Refactor] Move non fungible jsons [erc1155, erc271] fetchers to separate files #5030

- AlphaWallet/Core/CoinTicker/Types/TickerIdsFetcher.swift
- AlphaWallet/Core/Initializers/DatabaseMigration.swift
- AlphaWallet/Tokens/Types/TokensDataStore.swift
- AlphaWalletTests/Factories/FakeRealmLocalStore.swift
- AlphaWalletTests/Tokens/Helpers/TokenObjectTest.swift
- AlphaWalletTests/Transfer/ViewControllers/SendViewControllerTests.swift
Closes #5046, Closes #5048, Closes #5040
> Delete TokenBalance from Realm when remove from list, fix test quite #5046

- AlphaWallet/Accounts/Coordinators/AccountsCoordinator.swift
- AlphaWallet/Accounts/ViewControllers/AccountsViewController.swift
> Display Copied To Clipboard when tap copy button on accounts screen #5056

- AlphaWallet/Core/CoinTicker/CoinGecko/CoinGeckoTickerIdsFetcher.swift
- AlphaWallet/Core/CoinTicker/Types/InMemoryTickerIdsFetcher.swift
- AlphaWallet/Core/UnstoppableDomains/DomainResolutionService.swift
- AlphaWallet/Settings/Types/Config.swift
- AlphaWallet/Swap/SwapOptions/ViewModels/SwapOptionsViewModel.swift
- AlphaWallet/TokenScriptClient/Models/EventsActivityDataStore.swift
- AlphaWallet/TokenScriptClient/Models/NonActivityEventsDataStore.swift
- AlphaWallet/Tokens/Coordinators/TokensCoordinator.swift
- AlphaWallet/Tokens/Types/TokenCollection.swift
- AlphaWallet/Tokens/Types/TokensDataStore.swift
- AlphaWallet/Transactions/Storage/TransactionsStorage.swift
- AlphaWalletTests/Transfer/ViewControllers/SendViewControllerTests.swift
> Move receiving combine events to single queue instead of `.receive(on: DispatchQueue.global())` #5040

- AlphaWallet/Accounts/ViewControllers/AccountsViewController.swift
- AlphaWallet/Accounts/ViewModels/AccountsViewModel.swift
> Allow copy to clipboard by swipe action for selected wallet, move deletion callback to contirmation. #5058

- AlphaWallet/Tokens/Collectibles/ViewControllers/NFTCollectionViewController.swift
- AlphaWallet/Tokens/Collectibles/ViewModels/NFTAssetsPageViewModel.swift
- AlphaWallet/Tokens/Collectibles/Views/NFTAssetsPageView.swift
> Make assets view model observable #5062

- AlphaWallet/Core/Coordinators/WalletBalance/WalletBalanceFetcher.swift
- AlphaWallet/Core/RealmLocalStore.swift
- AlphaWallet/Core/Types/RealmStore.swift
- AlphaWallet/Tokens/Types/Token.swift
- AlphaWalletTests/Factories/FakeEnsRecordsStorage.swift
- AlphaWalletTests/Factories/FakeRealmLocalStore.swift
- AlphaWalletTests/Factories/FakeTokensDataStore.swift
- AlphaWalletTests/Factories/FakeTransactionsStorage.swift
- AlphaWalletTests/Market/OrderSigningTests.swift
- AlphaWalletTests/TokenScriptClient/FakeEventsDataStore.swift
> [Refactoring] remove unused Realm dependencies #5064

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet/Transfer/Coordinators/SendTransaction.swift
- AlphaWallet/Transfer/Coordinators/TransactionConfirmationCoordinator.swift
- AlphaWallet/WalletConnect/Coordinator/WalletConnectCoordinator.swift
> Rename `SendTransactionCoordinator`. Not a coordinator

- AlphaWallet/ActiveWalletCoordinator.swift
> improve shouldPretendIsRealWallet #5069

- AlphaWallet/Covalent/TransactionProviders/CombineTimer.swift
- AlphaWallet/Settings/ViewModels/SettingsViewModel.swift
- AlphaWallet/Swap/Helpers/SwapOptionsConfigurator.swift
- AlphaWallet/Swap/Swap/ViewModels/SwapTokensViewModel.swift
- AlphaWallet/Swaps/TokenSwapper.swift
> [Refactor] Replace map + switchToLatest with flatMapLatest as it does the same #5071

- AlphaWalletShare/Info.plist
> Fix: build number of share extension doesn't match main app #5082

- AlphaWallet/Browser/ViewModel/Dapps.swift
If bug:
Fixes #
If not a bug:
Closes #
> Update Dapps.swift > Add coinwar.app

- AlphaWallet/Configuration.swift
Changed colours from alabaster/venus to white/cod.
> Changed background colors for UITableView and UITableViewCell

- AlphaWallet/Covalent/TransactionProviders/Covalent.swift
- AlphaWallet/Covalent/TransactionProviders/CovalentToNativeTransactionMapper.swift
> Fix: Klaytn NFT token balance wrongly displayed as 0 #5093

- AlphaWallet/Activities/ActivitiesService.swift
> Filter activities to avoid duplicate activity id, to avoid crash #5104

- AlphaWallet/Swap/Swap/SwapTokensCoordinator.swift
- AlphaWallet/Swap/Swap/SwapTokensViewController.swift
> Make swap tokens screen being dismissed by swipe #5108

- AlphaWallet/Transfer/Coordinators/RequestCoordinator.swift
- AlphaWallet/Transfer/ViewControllers/RequestViewController.swift
> Make my qr code screen being dismissed by swipe #5106

- AlphaWallet/Tokens/Collectibles/ViewModels/NFTAssetsPageViewModel.swift
- AlphaWallet/Tokens/Logic/TokenCardTableViewCellFactory.swift
> Tweak displaying assets preview for erc721ForTickets #5114

- AlphaWallet/ActiveWalletCoordinator.swift
- AlphaWallet/Analytics/Models/AnalyticsTypes.swift
- AlphaWallet/AppCoordinator.swift
- AlphaWallet/AppDelegate.swift
- AlphaWallet/Core/Types/DeepLink.swift
- AlphaWallet/Share/UrlSchemeCoordinator.swift
- AlphaWalletTests/Coordinators/ActiveWalletViewTests.swift
- AlphaWalletTests/Market/DeepLinkTests.swift
Helps identify Safari extension usage
> Log deep link analytics

- AlphaWallet/Settings/Types/Constants+Credentials.swift
For Travis since we'll only set these environment variables there.
> Read API keys from environment variables if available

- AlphaWallet/Activities/ActivitiesService.swift
- AlphaWallet/Core/CoinTicker/CoinGecko/CoinGeckoTickerIdsFetcher.swift
- AlphaWallet/Core/CoinTicker/CoinTickersStorage.swift
- AlphaWallet/Core/ReachabilityManager.swift
- AlphaWallet/Core/SwapToken/TokenActionsService.swift
- AlphaWallet/Covalent/TransactionProviders/CombineTimer.swift
- AlphaWallet/Covalent/TransactionProviders/NewlyAddedTransaction/NewlyAddedTransactionSchedulerProvider.swift
- AlphaWallet/Covalent/TransactionProviders/OldestTransaction/OldestTransactionSchedulerProvider.swift
- AlphaWallet/Covalent/TransactionProviders/PendingTransaction/PendingTransactionSchedulerProvider.swift
- AlphaWallet/Extensions/Publishers/Publisher+Utils.swift.swift
- AlphaWallet/Settings/ViewModels/SettingsViewModel.swift
- AlphaWallet/Swaps/TokenSwapper.swift
- AlphaWallet/Tokens/ViewModels/TokenInfoPageViewModel.swift
- AlphaWallet/Transfer/Types/RecipientResolver.swift
- AlphaWallet/Transfer/ViewModels/TransactionConfirmationViewModel.swift
> [Refactor] update code with map to void extension for publishers #5121

- AlphaWallet/Activities/ActivitiesService.swift
- modules/AlphaWalletAddress/AlphaWalletAddress/AtomicDictionary.swift
> Crash on update activity #5119

- AlphaWallet/Tokens/ViewControllers/TokenInstanceActionViewController.swift
- AlphaWallet/Transfer/Collectibles/Coordinators/TransferCollectiblesCoordinator.swift
- AlphaWallet/Transfer/Collectibles/ViewControllers/TransferTokenBatchCardsViaWalletAddressViewController.swift
- AlphaWallet/Transfer/Coordinators/SendCoordinator.swift
- AlphaWallet/Transfer/Coordinators/TokenScriptCoordinator.swift
- AlphaWallet/Transfer/Coordinators/TransferNFTCoordinator.swift
- AlphaWallet/Transfer/ViewControllers/SendViewController.swift
- AlphaWallet/Transfer/ViewControllers/TransferTokensCardViaWalletAddressViewController.swift
> Make transfer token screens being able to close by swipe action #5125

- AlphaWallet/Tokens/Collectibles/Coordinators/NFTCollectionCoordinator.swift
- AlphaWallet/Tokens/Collectibles/ViewControllers/NFTCollectionViewController.swift
- AlphaWallet/Tokens/Coordinators/SingleChainTokenCoordinator.swift
- AlphaWallet/Tokens/ViewControllers/FungibleTokenViewController.swift
> Make token screens being able to close by swipe action #5123

- AlphaWallet/KeyManagement/EtherKeystore.swift
- AlphaWalletTests/Factories/FakeEtherKeystore.swift
- AlphaWalletTests/Market/OrderSigningTests.swift
- AlphaWalletTests/Market/UniversalLinkHandlerTests.swift
> Replace Keystore with FakeEtherKeystore for tests #5131

- AlphaWallet/Accounts/Coordinators/AccountsCoordinator.swift
- AlphaWallet/Accounts/ViewModels/AccountsViewModel.swift
- AlphaWallet/ActiveWalletCoordinator.swift
- AlphaWallet/EtherClient/Wallet.swift
- AlphaWallet/Export/Coordinators/BackupCoordinator.swift
- AlphaWallet/Export/Coordinators/PromptBackupCoordinator.swift
- AlphaWallet/KeyManagement/DefaultsWalletAddressesStore.swift
- AlphaWallet/KeyManagement/EtherKeystore.swift
- AlphaWallet/KeyManagement/JsonWalletAddressesStore.swift
- AlphaWallet/KeyManagement/Keystore.swift
- AlphaWallet/Settings/Coordinators/SettingsCoordinator.swift
- AlphaWallet/Settings/ViewModels/ExportJsonKeystoreFileViewModel.swift
- AlphaWallet/Settings/ViewModels/SettingsViewModel.swift
- AlphaWallet/Wallet/Coordinators/ElevateWalletSecurityCoordinator.swift
- AlphaWallet/Wallet/Coordinators/WalletCoordinator.swift
- AlphaWallet/Wallet/ViewControllers/ElevateWalletSecurityViewController.swift
- AlphaWallet/Wallet/ViewControllers/ImportWalletViewController.swift
- AlphaWalletTests/Coordinators/ActiveWalletViewTests.swift
- AlphaWalletTests/Coordinators/AppCoordinatorTests.swift
- AlphaWalletTests/Coordinators/BackupCoordinatorTests.swift
- AlphaWalletTests/EtherClient/EtherKeystoreTests.swift
- AlphaWalletTests/Factories/FakeEtherKeystore.swift
- AlphaWalletTests/Factories/FakeMultiWalletBalanceService.swift
- AlphaWalletTests/Factories/FakeTransactionsStorage.swift
- AlphaWalletTests/Factories/FakeWalletAddressStore.swift
- AlphaWalletTests/Factories/Wallet.swift
- AlphaWalletTests/Market/OrderSigningTests.swift
- AlphaWalletTests/Redeem/CreateRedeemTests.swift
> [Refactor] Update Wallet model with origin field, remove FakeWallet #5127

- AlphaWallet/Accounts/ViewModels/AccountsViewModel.swift
- AlphaWallet/Accounts/ViewModels/WalletSummaryViewModel.swift
- AlphaWallet/Accounts/Views/WalletSummaryView.swift
- AlphaWallet/Core/Coordinators/WalletBalance/TokenBalanceFetcher.swift
- AlphaWallet/Core/Helpers/BlockieGenerator.swift
- AlphaWallet/Core/Types/WalletSummary.swift
- AlphaWallet/EtherClient/Wallet.swift
- AlphaWallet/Tokens/Coordinators/TokensCoordinator.swift
- AlphaWallet/Tokens/ViewControllers/TokensViewController.swift
- AlphaWallet/Tokens/ViewModels/TokensViewModel.swift
> Make updating tokens screen flatten #5053

- AlphaWallet/Accounts/Coordinators/AccountsCoordinator.swift
- AlphaWallet/Accounts/ViewControllers/AccountsViewController.swift
- AlphaWallet/Accounts/ViewModels/AccountViewModel.swift
- AlphaWallet/Accounts/ViewModels/AccountsViewModel.swift
- AlphaWallet/Accounts/Views/AccountViewCell.swift
> Make updating accounts screen flatten #5060

- AlphaWallet/ActiveWalletCoordinator.swift
- AlphaWallet/Core/Coordinators/WalletBalance/WalletBalanceFetcher.swift
- AlphaWallet/Core/Types/Tokens/TokensProcessingPipeline.swift
- AlphaWallet/Tokens/Collectibles/Coordinators/NFTCollectionCoordinator.swift
- AlphaWallet/Tokens/Collectibles/ViewControllers/NFTCollectionViewController.swift
- AlphaWallet/Tokens/Collectibles/ViewModels/NFTAssetsPageViewModel.swift
- AlphaWallet/Tokens/Collectibles/ViewModels/NFTCollectionInfoPageViewModel.swift
- AlphaWallet/Tokens/Collectibles/ViewModels/NFTCollectionViewModel.swift
- AlphaWallet/Tokens/Collectibles/Views/FungibleTokenHeaderView.swift
- AlphaWallet/Tokens/Collectibles/Views/NFTAssetsPageView.swift
- AlphaWallet/Tokens/Collectibles/Views/NFTCollectionInfoPageView.swift
- AlphaWallet/Tokens/Helpers/TokenInstanceViewConfigurationHelper.swift
- AlphaWallet/Tokens/ViewModels/FungibleTokenViewModel.swift
- AlphaWallet/Tokens/ViewModels/TokensViewModel.swift
> Make updating nonfungible token screen flatten #5079

- AlphaWallet/ActiveWalletCoordinator.swift
- AlphaWallet/AppCoordinator.swift
- AlphaWallet/Core/Coordinators/WalletBalance/WalletBalanceService.swift
- AlphaWallet/Core/Initializers/ReportUsersWalletAddresses.swift
- AlphaWallet/Core/Types/Tokens/TokensProcessingPipeline.swift
> Crash while/right after deleting wallet in list of wallet screen #5076

- AlphaWallet/Accounts/ViewModels/AccountsViewModel.swift
- AlphaWallet/Core/Coordinators/WalletBalance/TokenBalanceFetcher.swift
- AlphaWallet/Core/TokensAutodetector/TokensAutodetector.swift
- AlphaWallet/Core/Types/Session.swift
- AlphaWallet/Core/Types/SessionsProvider.swift
- AlphaWallet/Core/Types/Tokens/AlphaWalletTokensService.swift
- AlphaWallet/Core/Types/Tokens/ClientSideTokenSourceProvider.swift
- AlphaWallet/Core/Types/Tokens/TokensProcessingPipeline.swift
- AlphaWallet/Settings/ViewModels/SettingsViewModel.swift
- AlphaWallet/Tokens/Collectibles/Coordinators/NFTCollectionCoordinator.swift
- AlphaWallet/Tokens/Collectibles/ViewControllers/NFTAssetViewController.swift
- AlphaWallet/Tokens/Collectibles/ViewControllers/NFTCollectionViewController.swift
- AlphaWallet/Tokens/Collectibles/ViewModels/FungibleTokenHeaderViewModel.swift
- AlphaWallet/Tokens/Collectibles/ViewModels/NFTAssetViewModel.swift
- AlphaWallet/Tokens/Collectibles/ViewModels/NFTAssetsPageViewModel.swift
- AlphaWallet/Tokens/Collectibles/ViewModels/NFTCollectionInfoPageViewModel.swift
- AlphaWallet/Tokens/Collectibles/ViewModels/NFTCollectionViewModel.swift
- AlphaWallet/Tokens/Coordinators/SingleChainTokenCoordinator.swift
- AlphaWallet/Tokens/Helpers/TokenAdaptor.swift
- AlphaWallet/Tokens/Helpers/TokenInstanceViewConfigurationHelper.swift
- AlphaWallet/Tokens/ViewModels/FungibleTokenViewModel.swift
- AlphaWallet/Tokens/ViewModels/SelectTokenViewModel.swift
- AlphaWallet/Tokens/ViewModels/TokenInfoPageViewModel.swift
- AlphaWallet/Tokens/ViewModels/TokensViewModel.swift
> Make updating nft asset screen flatten #5091

- AlphaWallet/Tokens/Coordinators/AddHideTokensCoordinator.swift
- AlphaWallet/Tokens/ViewControllers/AddHideTokensViewController.swift
- AlphaWallet/Tokens/ViewModels/AddHideTokensViewModel.swift
> Fix displaying newly added popular tokens #5102

- AlphaWallet/Lock/ViewControllers/LockPasscodeViewController.swift
- AlphaWallet/Wallet/Coordinators/WalletCoordinator.swift
> [Refactor] Replace cancelBarButton with helper function #5141

- AlphaWallet/Alerts/Coordinators/EditPriceAlertCoordinator.swift
- AlphaWallet/Alerts/ViewControllers/EditPriceAlertViewController.swift
> Make EditPriceAlertView being able to close by swipe action #5143

- AlphaWallet/Core/UnstoppableDomains/DomainResolutionService.swift
- AlphaWallet/Core/Views/AddressOrEnsNameLabel.swift
- AlphaWallet/UI/AddressTextField.swift
> Fix ENS resolution slow or broken in Send fungible screen in certain cases

- AlphaWallet/Core/CoinTicker/CoinGecko/CoinGeckoTickerIdsFetcher.swift
- AlphaWallet/Core/CoinTicker/Types/TickerIdFilter.swift
> app crashes on TickerIdFilter.swift line 22 #5139

- AlphaWallet/Core/ENS/ENSDelegateImpl.swift
- AlphaWallet/Core/Ethereum/Erc20.swift
- AlphaWallet/Settings/Types/Constants.swift
- AlphaWallet/Tokens/Helpers/CallSmartContractFunction.swift
- AlphaWallet/Tokens/Logic/Erc1155BalanceFetcher.swift
- AlphaWallet/Tokens/Logic/GetContractDecimals.swift
- AlphaWallet/Tokens/Logic/GetContractName.swift
- AlphaWallet/Tokens/Logic/GetContractSymbol.swift
- AlphaWallet/Tokens/Logic/GetErc20Balance.swift
- AlphaWallet/Tokens/Logic/GetErc721Balance.swift
- AlphaWallet/Tokens/Logic/GetErc721ForTicketsBalance.swift
- AlphaWallet/Tokens/Logic/GetErc875Balance.swift
- AlphaWallet/Tokens/Logic/IsErc875Contract.swift
- AlphaWallet/Tokens/Logic/IsInterfaceSupported165.swift
- AlphaWallet/Tokens/Logic/ScriptUri.swift
- AlphaWallet/Tokens/Models/NonFungibleContract.swift
- modules/AlphaWalletENS/AlphaWalletENS/ENS.swift
> [Refactor] remove unused parameter timeout: Constants.fetchContractDataTimeout #5151

- AlphaWallet/Core/UnstoppableDomains/DomainResolutionService.swift
> Fixes updating ui in background #5155

- AlphaWallet/Browser/ViewModel/Dapps.swift
Looking to add ApeNow to the dapps list!
> Add ApeNow to the iOS dapps list

- AlphaWallet/Browser/Coordinators/DappBrowserCoordinator.swift
- AlphaWallet/Browser/ViewControllers/EditMyDappViewController.swift
> Make EditBookmarkView being able to close by swipe action #5149

- AlphaWallet/Accounts/Coordinators/AccountsCoordinator.swift
- AlphaWallet/Accounts/ViewControllers/AccountsViewController.swift
> Make Accounts view being able to close by swipe action #5147

- AlphaWallet/Core/CoinTicker/Types/InMemoryTickerIdsFetcher.swift
- AlphaWallet/Core/Types/Tokens/AlphaWalletTokensService.swift
- AlphaWallet/Core/Types/Tokens/TokensProcessingPipeline.swift
- AlphaWallet/Settings/Types/Config.swift
- AlphaWallet/Swap/SwapOptions/ViewModels/SwapOptionsViewModel.swift
- AlphaWallet/TokenScriptClient/Models/EventsActivityDataStore.swift
- AlphaWallet/TokenScriptClient/Models/NonActivityEventsDataStore.swift
- AlphaWallet/Tokens/Types/TokensDataStore.swift
- AlphaWallet/Transactions/Storage/TransactionsStorage.swift
> Remove applying Config.backgroundQueue for AlphaWalletRemoteTickerIdsFetcher and SwapOptionsViewModel #5160

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet/WalletConnect/Types/EIP712TypedData.swift
- AlphaWalletTests/Core/Types/EIP712TypedDataTests.swift
> Fix: EIP712 signing when there is a struct that is only contained in an array and not a scalar

- AlphaWallet/Transfer/ViewControllers/ConfigureTransactionViewController.swift
- AlphaWallet/Transfer/ViewModels/ConfigureTransactionViewModel.swift
> [Refactor] Edit transaction configuration view #5170

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet/Accounts/ViewModels/WalletSummaryViewModel.swift
- AlphaWallet/Assets.xcassets/dodge.colorset/Contents.json
- AlphaWallet/Assets.xcassets/shark.colorset/Contents.json
- AlphaWallet/Browser/Views/DappBrowserNavigationBar.swift
- AlphaWallet/Configuration.swift
- AlphaWallet/Extensions/UIButton.swift
- AlphaWallet/Extensions/UIImageAsset+Extension.swift
- AlphaWallet/Style/AppStyle.swift
- AlphaWallet/Tokens/ViewControllers/NewTokenViewController.swift
- AlphaWallet/Tokens/ViewControllers/TokensViewController.swift
- AlphaWallet/Tokens/ViewModels/EthTokenViewCellViewModel.swift
- AlphaWallet/Tokens/ViewModels/FungibleTokenViewCellViewModel.swift
- AlphaWallet/Tokens/ViewModels/NonFungibleTokenViewCellViewModel.swift
- AlphaWallet/Tokens/ViewModels/OpenSea/OpenSeaNonFungibleTokenViewCellViewModel.swift
- AlphaWallet/Tokens/ViewModels/ShowAddHideTokensViewModel.swift
- AlphaWallet/Tokens/ViewModels/TokensViewModel.swift
- AlphaWallet/Tokens/Views/ActiveWalletSessionView.swift
- AlphaWallet/Tokens/Views/TokensViewControllerTableViewSectionHeader.swift
Will delete f03d26ec Set appearance to automatic before merging.
Will squash all commits before merging.
Will pull/rebase from master branch before merging.
> Add dark mode to main wallet tab

- AlphaWallet/Transfer/Views/ConfirmationHeaderView.swift
> App icon in confirmation actionsheet is truncated #5075

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet/Activities/ActivitiesService.swift
- AlphaWallet/Core/Types/Activities/ActivitiesPipeLine.swift
- AlphaWallet/TokenScriptClient/Coordinators/EventSource.swift
- AlphaWallet/TokenScriptClient/Coordinators/EventSourceForActivities.swift
- AlphaWallet/Tokens/Helpers/TokenAdaptor.swift
> [Refactor] Rename event source coordinators #5182

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet/Transfer/Controllers/TransactionConfigurator.swift
- AlphaWallet/Transfer/Types/GetGasLimit.swift
> [Refactoring] Wrap EstimateGasRequest into class, group private vars #5180

- AlphaWallet/Swap/Swap/ViewModels/SwapTokensViewModel.swift
> Fix crash Access realm on incorrect thread, when selection token for swap #5184

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet/Core/Types/Session.swift
- AlphaWallet/Covalent/TransactionProviders/Scheduler.swift
- AlphaWallet/EtherClient/ChainState.swift
- AlphaWallet/EtherClient/ChainStateSchedulerProvider.swift
- AlphaWallet/Settings/Types/Constants.swift
> Update fetching chainState #5195

- Podfile
- Podfile.lock
> Fix ENS wildcard resolution #5199

- AlphaWallet/Browser/ViewControllers/EditMyDappViewController.swift
- AlphaWallet/Core/Views/PasswordTextField.swift
- AlphaWallet/Core/Views/TextField.swift
- AlphaWallet/Extensions/UIView.swift
- AlphaWallet/Settings/ViewControllers/CheckTransactionStateViewController.swift
- AlphaWallet/Settings/ViewControllers/CollectUsersEmailViewController.swift
- AlphaWallet/Style/AppStyle.swift
- AlphaWallet/Swap/Helpers/SwapOptionsConfigurator.swift
- AlphaWallet/Swap/Swap/Types/SwapSlippage.swift
- AlphaWallet/Swap/SwapOptions/ViewControllers/SwapOptionsViewController.swift
- AlphaWallet/Swap/SwapOptions/ViewModels/EditableSlippageViewModel.swift
- AlphaWallet/Swap/SwapOptions/ViewModels/SlippageViewModel.swift
- AlphaWallet/Swap/SwapOptions/Views/EditableSlippageView.swift
- AlphaWallet/Swap/SwapOptions/Views/SlippageView.swift
- AlphaWallet/Tokens/ViewControllers/NewTokenViewController.swift
- AlphaWallet/Transfer/Views/SlidableTextField.swift
- AlphaWallet/Transfer/Views/TextFieldView.swift
- AlphaWallet/Wallet/ViewControllers/ImportWalletViewController.swift
- AlphaWallet/Wallet/ViewControllers/RenameWalletViewController.swift
> Tweak slippage value selection for swap #5201

- AlphaWallet/Settings/Types/Constants+Credentials.swift
- AlphaWallet/UI/NavigationController.swift
- AlphaWallet/WalletConnect/Providers/v1/WalletConnectV1Provider.swift
- AlphaWallet/WalletConnect/Providers/v2/WalletConnectV2Provider.swift
- AlphaWalletTests/Core/Types/RetryPublisherTests.swift
@oa-s would you help verify if replacing the `print()` with `infoLog()` in 8bad6d7219e1cfda18a3d6c660955b81633e19ba is what you want?
> Tweak logs

- AlphaWallet/Core/SwapToken/SwapTokenNativeProvider.swift
> Hide native swap action when it disabled #5210

- AlphaWallet/Info.plist
Reset appearance to Light instead of Automatic.
> Reset Appearance in info.plist to ‘Light’

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet/Activities/ActivitiesService.swift
- AlphaWallet/Activities/Types/ActivitiesFilterStrategy.swift
- AlphaWallet/Activities/ViewModels/ActivitiesViewModel.swift
- AlphaWallet/Analytics/Models/AnalyticsTypes.swift
- AlphaWallet/Core/DecodedFunctionCall.swift
- AlphaWallet/Core/Ethereum/ABI/ABI.swift
- AlphaWallet/Core/Ethereum/ABI/DecodedFunctionCall+Decode.swift
- AlphaWallet/Core/Ethereum/ABI/ERC721.json
- AlphaWallet/EtherClient/TrustClient/Models/OperationType.swift
- AlphaWallet/EtherClient/TrustClient/Models/RawTransaction.swift
- AlphaWallet/Localization/en.lproj/Localizable.strings
- AlphaWallet/Localization/es.lproj/Localizable.strings
- AlphaWallet/Localization/fi.lproj/Localizable.strings
- AlphaWallet/Localization/ja.lproj/Localizable.strings
- AlphaWallet/Localization/ko.lproj/Localizable.strings
- AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings
- AlphaWallet/Swap/Swap/SwapTokensCoordinator.swift
- AlphaWallet/TokenScriptClient/Models/Activity.swift
- AlphaWallet/Transactions/Storage/Transaction.swift
- AlphaWallet/Transactions/TokensFromTransactionsFetcher.swift
- AlphaWallet/Transactions/ViewModels/TransactionRowCellViewModel.swift
- AlphaWallet/Transfer/Coordinators/TransactionConfirmationCoordinator.swift
Closes #5216
Can reproduce with https://streetfighters.fun/ (as of writing) in dapp browser. Tap "Mint" button, but don't sign the transaction. (seems like need Blitmap token in the wallet for the request to show up)
-|-
> Mark up ERC71.setApprovalForAll transactions in confirmation actionsheet #5216

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet/ActiveWalletCoordinator.swift
- AlphaWallet/AppCoordinator.swift
- AlphaWallet/Browser/Coordinators/QRCodeResolutionCoordinator.swift
- AlphaWallet/Browser/Coordinators/ScanQRCodeCoordinator.swift
- AlphaWallet/Core/SwapToken/QuickSwap/QuickSwap.swift
- AlphaWallet/Core/SwapToken/SwapTokenProvider.swift
- AlphaWallet/Extensions/Error.swift
- AlphaWallet/Localization/en.lproj/Localizable.strings
- AlphaWallet/Localization/es.lproj/Localizable.strings
- AlphaWallet/Localization/fi.lproj/Localizable.strings
- AlphaWallet/Localization/ja.lproj/Localizable.strings
- AlphaWallet/Localization/ko.lproj/Localizable.strings
- AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings
- AlphaWallet/Settings/Types/Config.swift
- AlphaWallet/Swap/SelectServiceToSwapCoordinator.swift
- AlphaWallet/Tokens/Coordinators/SingleChainTokenCoordinator.swift
- AlphaWallet/Tokens/Coordinators/TokensCoordinator.swift
- AlphaWallet/Tokens/ViewControllers/FungibleTokenViewController.swift
- AlphaWallet/Transfer/Types/PaymentFlow.swift
> Allow swap service selection #5213

- AlphaWallet/Settings/Coordinators/ServersCoordinator.swift
> Move Polygon up so it's 3rd in the list of chains

- AlphaWallet/AppCoordinator.swift
> Fix: ReportUsersWalletAddresses isn't retained so changes aren't tracked (for debugging purposes)

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet/AppCoordinator.swift
- AlphaWallet/Core/Helpers/FirebaseReportService.swift
- AlphaWallet/Core/Initializers/ReportUsersActiveChains.swift
> Log user active chains

- AlphaWallet/Assets.xcassets/qr_code_icon.imageset/Contents.json
- AlphaWallet/Configuration.swift
- AlphaWallet/Core/Views/TextField.swift
- AlphaWallet/UI/AddressTextField.swift
- AlphaWallet/UI/Button.swift
- AlphaWallet/UI/RoundedBackground.swift
- AlphaWallet/UI/Views/TextView.swift
- AlphaWallet/Wallet/ViewControllers/ImportWalletViewController.swift
> Added dark mode to ImportWalletViewController

- AlphaWallet/Assets.xcassets/oval.imageset/Contents.json
- AlphaWallet/Configuration.swift
- AlphaWallet/Core/Views/SelfSizingPanelLayout.swift
- AlphaWallet/WhatsNew/ViewControllers/WhatsNewListingViewController.swift
- AlphaWallet/WhatsNew/Views/WhatsNewViews.swift
1. Delete the app from the device.
2. Run the app from Xcode.
3. Create a wallet.
4. Click on Blockie in upper left corner of main wallet tab.
5. Create a Watch Wallet.
The dialog will appear.
PR is ready for merging.
> Added dark mode to WhatsNewListingViewController, FloatingPanelController

- AlphaWallet/Core/Views/TextField.swift
> Corrected wrong colour returned from textFieldTextColor function

- AlphaWallet/Common/Views/TextField.swift
- AlphaWallet/Core/SwapToken/NativeSwap/Helpers/ApproveSwapProvider.swift
- AlphaWallet/Core/SwapToken/NativeSwap/Helpers/TokenSwapperNetworkProvider.swift
- AlphaWallet/Core/SwapToken/NativeSwap/SwapQuote.swift
- AlphaWallet/Core/SwapToken/NativeSwap/Types/SwapError.swift
- AlphaWallet/Core/SwapToken/NativeSwap/Types/SwapSlippage.swift
- AlphaWallet/Style/AppStyle.swift
- AlphaWallet/Swap/SwapOptions/ViewModels/EditableSlippageViewModel.swift
- AlphaWallet/Swap/SwapOptions/ViewModels/SlippageViewModel.swift
- AlphaWallet/Swap/SwapOptions/Views/EditableSlippageView.swift
- AlphaWallet/Swap/SwapOptions/Views/SlippageView.swift
> Tweak slippage value for swap #5233

- .swiftlint.yml
- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet/WalletConnect/Types/WalletConnect.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Core/Helpers/ScriptMessageProxy.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Core/Settings/Types/RPCServers.swift
> Remove app warnings #5255

- AlphaWallet/ActiveWalletCoordinator.swift
So it doesn't appear in TestFlights or accidentally in app store builds
> [DEV] dont show swap button in tab bar even when swap feature is enabled unless in debug mode

- AlphaWallet/Common/ViewControllers/ModalViewController.swift
- AlphaWallet/Settings/ViewControllers/CollectUsersEmailViewController.swift
> Added dark mode to CollectUsersEmailViewController

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet/AppDelegate.swift
- Podfile
- Podfile.lock
> Remove AWSSNS, AWSCore dependency #5256

- AlphaWallet/Browser/Coordinators/DappBrowserCoordinator.swift
- AlphaWallet/Common/Views/AddressOrEnsNameLabel.swift
- AlphaWallet/Transfer/Coordinators/SignMessageCoordinator.swift
- AlphaWallet/Transfer/ViewControllers/SendViewController.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Core/EtherClient/Models/GetGasPrice.swift
> Remove unuesd dependencies #5255

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet/ActiveWalletCoordinator.swift
- AlphaWallet/AppCoordinator.swift
- AlphaWallet/AppDelegate.swift
- AlphaWallet/Common/Types/KeychainStorage.swift
- AlphaWallet/Lock/Coordinators/LockCreatePasscodeCoordinator.swift
- AlphaWallet/Lock/ViewControllers/LockCreatePasscodeViewController.swift
- AlphaWallet/Lock/ViewControllers/LockEnterPasscodeViewController.swift
- AlphaWallet/Lock/ViewControllers/LockPasscodeViewController.swift
- AlphaWallet/Lock/ViewModels/LockCreatePasscodeViewModel.swift
- AlphaWallet/Lock/ViewModels/LockEnterPasscodeViewModel.swift
- AlphaWallet/Lock/ViewModels/LockViewModel.swift
- AlphaWallet/Protection/Coordinators/LockEnterPasscodeCoordinator.swift
- AlphaWallet/Protection/Coordinators/ProtectionCoordinator.swift
- AlphaWallet/Settings/Coordinators/SettingsCoordinator.swift
- AlphaWallet/Settings/ViewControllers/SettingsViewController.swift
- AlphaWallet/Settings/ViewModels/SettingsViewModel.swift
- AlphaWalletTests/Coordinators/ActiveWalletViewTests.swift
- AlphaWalletTests/Coordinators/AppCoordinatorTests.swift
- AlphaWalletTests/Coordinators/LockCreatePasscodeCoordinatorTest.swift
- AlphaWalletTests/Coordinators/LockEnterPasscodeCoordinatorTest.swift
- AlphaWalletTests/EtherClient/EtherKeystoreTests.swift
- AlphaWalletTests/Factories/FakeEtherKeystore.swift
- AlphaWalletTests/Factories/FakeLockProtocol.swift
- Podfile.lock
- modules/AlphaWalletFoundation/AlphaWalletFoundation.podspec
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Core/Initializers/CleanupPasscode.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Core/KeyManagement/EtherKeystore.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Core/KeyManagement/LegacyFileBasedKeystore.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Core/Lock/Lock.swift
> Move dependency from KeychainSwift, and SamKaychain to main app, update with protocol definition #5255

- modules/AlphaWalletFoundation/AlphaWalletFoundation/Core/Tokens/Types/EventActivity.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Core/Tokens/Types/EventInstance.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Core/Tokens/Types/EventInstanceValue.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Core/Tokens/Types/Token.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Core/Tokens/Types/TokenBalance.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Core/Tokens/Types/TokenObject.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Core/Tokens/Types/TokensDataStore.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Core/Transactions/Storage/Transaction.swift
> Hide some methods under internal level #5255

- AlphaWallet/Settings/ViewControllers/WellDoneViewController.swift
> Added dark mode to WellDoneViewController

- modules/AlphaWalletFoundation/AlphaWalletFoundation/Core/Settings/Types/RPCServers.swift
> Respect block range limit for eth_getLogs for Candle's RPC node

- AlphaWallet/ActiveWalletCoordinator.swift
- AlphaWallet/Common/Services/DappRequestHandler.swift
> Pass restart reason to caller function #5227

- Podfile.lock
- modules/AlphaWalletFoundation/AlphaWalletFoundation.podspec
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Core/Tokens/PopularTokens/PopularTokensCollection.swift
> Fix: Add / Hide Tokens crash

- modules/AlphaWalletFoundation/AlphaWalletFoundation/Core/Settings/Types/Constants.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Core/Tokens/PopularTokens/known_contract.json
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Core/Tokens/TokensAutodetector/ImportToken.swift
> Add GNO on Gnosis as default token, even if balance is 0 #5239

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet/AppCoordinator.swift
- AlphaWalletTests/Factories/FakeCoinTickersFetcher.swift
- AlphaWalletTests/modules/AlphaWalletFoundation/CoinTicker/TickerIdsFetcher/FileTokenEntriesProviderTests.swift
- AlphaWalletTests/modules/AlphaWalletFoundation/LocalPopularTokensCollectionTests.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/CoinTicker/TickerIdsFetcher/FileTokenEntriesProvider.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/PopularTokens/PopularTokensCollection.swift
Depends on #5299 and similar to it, with a test.
> Fix tokens2 file not read

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWalletTests/modules/AlphaWalletFoundation/LocalPopularTokensCollectionTests.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/PopularTokens/PopularTokensCollection.swift
Fixes #5298
PR also adds a test because it's fragile.
> Fix: crash when tap Add / Hide Tokens

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet/Localization/en.lproj/Localizable.strings
- AlphaWallet/Localization/es.lproj/Localizable.strings
- AlphaWallet/Localization/fi.lproj/Localizable.strings
- AlphaWallet/Localization/ja.lproj/Localizable.strings
- AlphaWallet/Localization/ko.lproj/Localizable.strings
- AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings
- AlphaWalletTests/Core/ViewModels/ChainIdTests.swift
> Fix: chain ID for Palm both mainnet and testnet was displayed as negative number

- Podfile
- Podfile.lock
- modules/AlphaWalletCore/AlphaWalletCore.podspec
- modules/AlphaWalletCore/AlphaWalletCore/Extensions/Publisher+Utils.swift.swift
- modules/AlphaWalletCore/AlphaWalletCore/Storage.swift
- modules/AlphaWalletCore/AlphaWalletCore/StorageType.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation.podspec
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Activities/ActivitiesService.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/BuyToken/BuyTokenService.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/CoinTicker/CoinGecko/CoinGeckoTickerIdsFetcher.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/CoinTicker/CoinTickersStorage.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/EtherClient/ChainStateSchedulerProvider.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Helpers/ReachabilityManager.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/SwapToken/NativeSwap/Helpers/SwapOptionsConfigurator.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/TokenActions/SwapTokenProvider.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/TokenActions/TokenActionsService.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Transactions/Covalent/TransactionProviders/CombineTimer.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Transactions/Covalent/TransactionProviders/NewlyAddedTransaction/NewlyAddedTransactionSchedulerProvider.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Transactions/Covalent/TransactionProviders/OldestTransaction/OldestTransactionSchedulerProvider.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Transactions/Covalent/TransactionProviders/PendingTransaction/PendingTransactionSchedulerProvider.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Transfer/Types/RecipientResolver.swift
- modules/AlphaWalletOpenSea/AlphaWalletOpenSea.podspec
> update dependencies version, replace local extension with CombineExt for publishers #5308

- modules/AlphaWalletFoundation/AlphaWalletFoundation/Features/Features.swift
> Fix bad access to shared features dictionary. #5317

- modules/AlphaWalletFoundation/AlphaWalletFoundation/CoinTicker/Types/TickerIdFilter.swift
> update string comparison for ticker ids with x.compare(y, options: .caseInsensitive) == .orderedSame #5323

- modules/AlphaWalletAddress/AlphaWalletAddress/AtomicDictionary.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Foundation/Subscribable.swift
> Fix crash when getting value call subscribe, when _value is dictionary or array #5320

- modules/AlphaWalletAddress/AlphaWalletAddress/AtomicDictionary.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/TokenScriptClient/Models/AssetDefinitionStore.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/TokenScriptClient/Models/TokenScriptSignatureVerifier.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/TokenScriptClient/Models/XMLHandler.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/Helpers/TokenAdaptor.swift
> Fix crash when creating xmlHandler #5319

- modules/AlphaWalletFoundation/AlphaWalletFoundation/CoinTicker/TickerIdsFetcher/FileTokenEntriesProvider.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/TokenScriptClient/Models/XMLHandler.swift
> hotfix missed case #5333

- modules/AlphaWalletFoundation/AlphaWalletFoundation/Activities/ActivitiesService.swift
> Fix crash #5338

- AlphaWallet/ActiveWalletCoordinator.swift
- AlphaWallet/AppCoordinator.swift
- AlphaWalletTests/Coordinators/ActiveWalletViewTests.swift
- AlphaWalletTests/ViewControllers/PaymentCoordinatorTests.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Activities/ActivitiesPipeLine.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Types/WalletDependencyContainer.swift
> update active wallet dependency, add passing activities pipeline instead of realm instance #5341

- modules/AlphaWalletFoundation/AlphaWalletFoundation/Foundation/Subscribable.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/TokenScriptClient/Models/AssetAttributeMapping.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/TokenScriptClient/Models/AssetAttributeSyntax.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/TokenScriptClient/Models/CallForAssetAttributeCoordinator.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/TokenScriptClient/Models/FunctionOrigin.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/TokenImageFetcher.swift
> [Refactor] update subscribable with send() methods for setting value,e.g PassthroughSubject #5345

- AlphaWallet/ActiveWalletCoordinator.swift
- AlphaWallet/Browser/Coordinators/DappBrowserCoordinator.swift
- AlphaWallet/Browser/ViewControllers/EditMyDappViewController.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Browser/Storage/BookmarksStore.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Browser/Storage/HistoryStore.swift
> Remove realm imports from aw project #5347

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet/ActiveWalletCoordinator.swift
- AlphaWallet/AppDelegate.swift
- AlphaWallet/Common/Helpers/ReportProvider.swift
- AlphaWallet/Common/Services/FirebaseReportService.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Helpers/ReportService.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Initializers/ReportUsersActiveChains.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Initializers/ReportUsersWalletAddresses.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/ClientSideTokenSourceProvider.swift
> Move report provider to aw project. #5349

- AlphaWallet/ActiveWalletCoordinator.swift
- AlphaWallet/Browser/Coordinators/DappBrowserCoordinator.swift
> Fix crash for selected rpc server in dapp browser, (remove force unwrap when accessing session) #5351

- AlphaWalletTests/TokenScriptClient/XMLHandlerTest.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/TokenScriptClient/Models/AssetDefinitionDiskBackingStore.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/TokenScriptClient/Models/AssetDefinitionDiskBackingStoreWithOverrides.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/TokenScriptClient/Models/AssetDefinitionStore.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/TokenScriptClient/Models/XMLHandler.swift
> Move xml handlers cache to asset definition store #5355

- AlphaWallet/AppCoordinator.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/CoinTicker/CoinGecko/CoinGeckoTickersFetcher.swift
> add public convenience init for CoinGeckoTickersFetcher #5357

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet/ActiveWalletCoordinator.swift
- AlphaWallet/Common/Types/Constants.swift
- AlphaWallet/Common/Types/ServiceProvider.swift
- AlphaWallet/Common/Views/AmountTextField.swift
- AlphaWallet/Common/Views/ViewModels/AmountTextField_v2Pair.swift
- AlphaWallet/Common/Views/ViewModels/AmountTextField_v2ViewModel.swift
- AlphaWallet/Transfer/ViewModels/GasSpeedTableViewCellViewModel.swift
- AlphaWallet/Transfer/ViewModels/TransactionConfirmation/ClaimPaidErc875MagicLinkViewModel.swift
- AlphaWallet/Transfer/ViewModels/TransactionConfirmation/DappOrWalletConnectTransactionViewModel.swift
- AlphaWallet/Transfer/ViewModels/TransactionConfirmation/SendFungiblesTransactionViewModel.swift
- AlphaWallet/Transfer/ViewModels/TransactionConfirmation/TokenScriptTransactionViewModel.swift
- AlphaWallet/Transfer/ViewModels/TransactionConfirmationViewModel.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Browser/Storage/HistoryStore.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/CoinTicker/CoinGecko/CoinGeckoNetworkProvider.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Foundation/Formatter.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Helpers/RemoteLogger.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/NFT/Enjin/EnjinUserManagementInterceptor.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Settings/Types/Constants+Credentials.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Settings/Types/Constants.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/TokenScriptClient/Models/AssetDefinitionStore.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/TokenScriptClient/Models/TokenScriptSignatureVerifier.swift
> group defined Constants for sdk and aw project #5375

- modules/AlphaWalletFoundation/AlphaWalletFoundation/BuyToken/Ramp/Ramp.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Settings/Types/Constants.swift
> Fix Ramp not available

- AlphaWallet/BuyCrypto/SelectServiceToBuyCryptoCoordinator.swift
- AlphaWallet/Swap/SelectServiceToSwapCoordinator.swift
- AlphaWallet/Transfer/Collectibles/ViewModels/TransferTokenBatchCardsViaWalletAddressViewControllerViewModel.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/BuyToken/Ramp/Ramp.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Settings/Types/Constants.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Types/AppErrors.swift
> Fix typo in enum case strings

- modules/AlphaWalletFoundation/AlphaWalletFoundation/BuyToken/Ramp/Ramp.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/EtherClient/TrustClient/AlphaWalletService.swift
> Remove AtomicArray from Ramp, make updating assets threadsafe #5379

- AlphaWallet/Tokens/ViewModels/EthTokenViewCellViewModel.swift
- AlphaWallet/Tokens/ViewModels/FungibleTokenViewCellViewModel.swift
> Shouldn't show a "placeholder" view/background for token price when it is not available yet #5328

- AlphaWallet/Accounts/Coordinators/AccountsCoordinator.swift
- AlphaWallet/Accounts/ViewModels/AccountsViewModel.swift
> Show `Rename wallet` screen instead of popup #5401

- AlphaWallet/Transfer/ViewModels/TransactionConfirmationViewModel.swift
> Remove space for on confirmation popup for ERC721 transfer #5405

- AlphaWallet/Extensions/UIBarButtonItem.swift
- AlphaWallet/Settings/Coordinators/EnabledServersCoordinator.swift
- AlphaWallet/Settings/ViewControllers/ServersViewController.swift
- AlphaWallet/WalletConnect/ViewController/WalletConnectSessionsViewController.swift
> Apply swipe to dismiss for wallet connect sessions #5400

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWalletTests/Factories/FakeTokenSwapper.swift
- AlphaWalletTests/modules/AlphaWalletFoundation/Oneinch/OneinchTests.swift
- AlphaWalletTests/modules/AlphaWalletFoundation/Ramp/RampTests.swift
- modules/AlphaWalletCore/AlphaWalletCore/Extensions/RetryIf.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/BuyToken/Ramp/Ramp.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/BuyToken/Ramp/RampAssetsResponse.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/BuyToken/Ramp/RampNetworkProvider.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/SwapToken/Oneinch/Oneinch.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/SwapToken/Oneinch/OneinchAsset.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/SwapToken/Oneinch/OneinchNetworkProvider.swift
> Apply retrying strategy for Ramp and Oneinch #5402

- AlphaWallet/Extensions/RPCServer+Extensions.swift
- AlphaWallet/Settings/Coordinators/ServersCoordinator.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Settings/Types/RPCServers.swift
> Add PHI v2 chain

- modules/AlphaWalletFoundation/AlphaWalletFoundation/ENS/UnstoppableDomains/UnstoppableDomainsV2NetworkProvider.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/ENS/UnstoppableDomains/UnstoppableDomainsV2Resolver.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Settings/Types/Constants.swift
> Update Unstoppable URL endpoint #5414

- AlphaWallet/Common/Types/AppStyle.swift
- AlphaWallet/Common/ViewModels/DropDownViewModel.swift
- AlphaWallet/Common/Views/DropDownView.swift
- AlphaWallet/Common/Views/EmptyView.swift
- AlphaWallet/Extensions/UIViewController.swift
- AlphaWallet/Settings/ViewControllers/ServersViewController.swift
- AlphaWallet/Tokens/ViewControllers/AddHideTokensViewController.swift
- AlphaWallet/Tokens/ViewControllers/TokensViewController.swift
- AlphaWallet/Tokens/ViewModels/AddHideTokenSectionHeaderViewModel.swift
- AlphaWallet/Tokens/ViewModels/AddHideTokensViewModel.swift
- AlphaWallet/Tokens/ViewModels/NonFungibleTokenViewCellViewModel.swift
- AlphaWallet/Tokens/ViewModels/PopularTokenViewCellViewModel.swift
- AlphaWallet/Tokens/ViewModels/WalletTokenViewCellViewModel.swift
- AlphaWallet/Tokens/Views/AddHideTokenSectionHeaderView.swift
- AlphaWallet/Tokens/Views/NonFungibleTokenViewCell.swift
- AlphaWallet/Tokens/Views/TokensViewControllerTableViewSectionHeader.swift
On the main wallet screen, tap the ellipses (…). Tap Add/Hide Tokens.
> Added dark mode to AddHideTokenViewController

- modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/AlphaWalletTokensService.swift
> Refresh token balance sooner for tokens that are newly added/detected rather than to wait for the next refresh cycle

- AlphaWallet/Tokens/Collectibles/ViewControllers/NFTAssetViewController.swift
> Fix more button not working in nft token screen

- modules/AlphaWalletFoundation/AlphaWalletFoundation/EtherClient/Requests/EstimateGasRequest.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Transfer/TransactionConfigurator.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Transfer/Types/GetGasLimit.swift
> Fix: do not cap gas limits to 2M for contract deployments #5441

- AlphaWallet/Alerts/Coordinators/EditPriceAlertCoordinator.swift
- AlphaWallet/Alerts/ViewControllers/EditPriceAlertViewController.swift
- AlphaWallet/Alerts/ViewModels/EditPriceAlertViewModel.swift
- AlphaWallet/Common/Views/ViewModels/AmountTextField_v2ViewModel.swift
> [Refactor] Replace AmountTextField with AmountTextField_v2, update with combine features #5366

- AlphaWallet/Tokens/ViewModels/AddHideTokensViewModel.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/Types/TokenViewModel.swift
> Add or hide tokens after filtering does nothing #5451

- AlphaWallet/Common/Views/DummySearchView.swift
- AlphaWallet/Tokens/ViewControllers/TokensViewController.swift
> Fix table animation glitch after popping from token back to Wallet tab if searching #3729

- AlphaWallet/AppCoordinator.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Initializers/DatabaseMigration.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Types/RealmConfiguration.swift
> move removing realm file on apps launch #5460

- AlphaWalletTests/Factories/FakeTokenSwapperNetworkProvider.swift
> Fix test suite #5473

- modules/AlphaWalletCore/AlphaWalletCore/Extensions/RetryIf.swift
- modules/AlphaWalletCore/AlphaWalletCore/attempt.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/CoinTicker/CoinGecko/CoinGeckoNetworkProvider.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Types/TokenProviderType.swift
> update retry logic for `getTokenType(_: )` function #5472

- AlphaWallet/Settings/Coordinators/ClearDappBrowserCacheCoordinator.swift
- AlphaWallet/Settings/Coordinators/SettingsCoordinator.swift
- AlphaWallet/Settings/ViewControllers/AnalyticsViewController.swift
- AlphaWallet/Settings/ViewControllers/ChooseSendPrivateTransactionsProviderViewController.swift
- AlphaWallet/Settings/ViewControllers/ToolsViewController.swift
- AlphaWallet/Settings/ViewModels/AnalyticsViewModel.swift
- AlphaWallet/Settings/ViewModels/ChooseSendPrivateTransactionsProviderViewModel.swift
- AlphaWallet/Settings/ViewModels/ToolsViewModel.swift
- AlphaWallet/Settings/Views/SwitchView.swift
> apply dark mode to tools and analytics screens #5478

- AlphaWallet/Accounts/ViewControllers/AccountsViewController.swift
- AlphaWallet/Accounts/ViewModels/AccountViewModel.swift
- AlphaWallet/Accounts/ViewModels/AccountsViewModel.swift
- AlphaWallet/AppCoordinator.swift
> Allow user to delete current wallet if it's the last wallet. Make appstore review happy #5483

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWalletTests/Factories/FakeGetEthBalance.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/Logic/GetEthBalance.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Types/TokenProviderType.swift
> remove redundant retrying for get native balance, e.g implemented for ApiKitSession.send(:) #5487

- modules/AlphaWalletFoundation/AlphaWalletFoundation/GasPriceEstimator/GasPriceEstimator.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Transfer/Types/GasPriceConfiguration.swift
> Fix: Gnosis default gas price

- AlphaWallet/Swap/SwapRoutes/ViewModels/SelectableSwapRouteTableViewCellViewModel.swift
- AlphaWallet/Swap/SwapRoutes/Views/SelectableSwapRouteTableViewCell.swift
- AlphaWalletTests/Transfer/Controllers/TransactionConfiguratorTests.swift
> Fix test suite #5507

- AlphaWallet/Tokens/ViewModels/SelectTokenViewModel.swift
> Added dark mode to Swap Option on main wallet tab

- AlphaWallet/Common/Services/KeyboardChecker.swift
- AlphaWallet/Common/Views/ButtonsBar/ButtonsBarBackgroundView.swift
- AlphaWallet/Common/Views/DummySearchView.swift
- AlphaWallet/Tokens/Coordinators/TokensCoordinator.swift
- AlphaWallet/Tokens/ViewControllers/TokensViewController.swift
- AlphaWallet/Tokens/ViewModels/TokensViewModel.swift
> Add Buy ETH button to bottom of Wallet tab #5398

- AlphaWalletTests/modules/AlphaWalletFoundation/LocalPopularTokensCollectionTests.swift
> increase wait time to make LocalPopularTokensCollectionTests test pass #5522

- AlphaWallet/Common/Types/Configuration.swift
- AlphaWallet/Common/Views/AmountTextField.swift
- AlphaWallet/Common/Views/ViewModels/AmountTextFieldPair.swift
- AlphaWallet/Resources/Assets.xcassets/porcelain.colorset/Contents.json
- AlphaWallet/Transfer/ViewControllers/TransactionConfirmationViewController.swift
- AlphaWallet/Transfer/ViewModels/SendViewModel.swift
- AlphaWallet/Transfer/ViewModels/SendViewSectionHeaderViewModel.swift
- AlphaWallet/Transfer/ViewModels/TransactionConfirmationTableHeaderViewModel.swift
- AlphaWallet/Transfer/ViewModels/TransactionConfirmationViewModel.swift
- AlphaWallet/Transfer/Views/TransactionConfirmationHeaderView.swift
- AlphaWallet/Transfer/Views/TransactionConfirmationRowInfoView.swift
Before PR | Light mode | Dark mode
-|-|-
> Add dark mode to TransactionConfirmationViewController

- AlphaWallet/Browser/ViewModel/EditBookmarkViewModel.swift
> Fix: error building on Xcode 13 #5545

- AlphaWallet/Tokens/ViewControllers/NewTokenViewController.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/Logic/ContractDataDetector.swift
> Fix: Can't manually add ERC1155 to Polygon (or any chain)

- AlphaWallet/Browser/Coordinators/DappBrowserCoordinator.swift
- AlphaWallet/Common/Coordinators/WalletApiCoordinator.swift
- AlphaWallet/Tokens/Views/TokenInstanceWebView.swift
- AlphaWallet/Transfer/Coordinators/SignMessageCoordinator.swift
- AlphaWallet/WalletConnect/Coordinator/WalletConnectCoordinator.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Extensions/String.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/KeyManagement/EtherKeystore.swift
Want it to be detected by GitHub for review with this line in `CODEOWNERS`:
```
/modules/AlphaWalletFoundation/AlphaWalletFoundation/KeyManagement/ @hboon
```
(will add @oa-s in a separate PR. Done in #5549)
> [Refactor] Rename function to be more intention-revealing and move critical code so it's always flagged for review

- modules/AlphaWalletFoundation/AlphaWalletFoundation/NFT/Enjin/EnjinNetworkProvider.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/NFT/Enjin/EnjinUserManagementInterceptor.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/NFT/NFTProvider.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/WalletBalance/TokenBalanceFetcher.swift
> Fix bad access crash for apollo #5562

- modules/AlphaWalletFoundation/AlphaWalletFoundation/Extensions/Data.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Extensions/Int.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Extensions/String.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/KeyManagement/EtherKeystore.swift
> remove init with chunk #5547

- AlphaWalletTests/modules/AlphaWalletFoundation/Tokens/Logic/Erc1155TokenIdsFetcherTests.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/Logic/Erc1155TokenIdsFetcher.swift
> Fix number overflow crash while when fetching erc1155 tokens #5550

- AlphaWallet/Extensions/RPCServer+Extensions.swift
- AlphaWallet/Settings/Coordinators/ServersCoordinator.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/CoinTicker/CoinTickersFetcherImpl.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Settings/Types/Constants.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Settings/Types/RPCServers.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/Helpers/CallSmartContractFunction.swift
> Implement new PoS Arbitrum and Optimism Goerli testnets #5466

- AlphaWallet/Transfer/Coordinators/SendCoordinator.swift
- AlphaWallet/Transfer/Coordinators/TransferNFTCoordinator.swift
> Hide bottom bar for send token screen when pushing #5574

- modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/Helpers/JsonFromTokenUri.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/Helpers/NonFungibleErc1155JsonBalanceFetcher.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/Models/NonFungibleContract.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/WalletBalance/TokenBalanceFetcher.swift
> Apply promise caching for JsonFromTokenUri resolver. Release promise when its get resolved. #5584

- AlphaWallet/ActiveWalletCoordinator.swift
- AlphaWallet/Browser/ViewControllers/BookmarksViewController.swift
- AlphaWallet/Browser/Views/DappBrowserNavigationBar.swift
- AlphaWallet/Common/Views/NavigationController.swift
- AlphaWallet/Transfer/Coordinators/PaymentCoordinator.swift
> push send screen on top presented navigation controller #5587

- AlphaWallet/Transfer/ViewControllers/TransactionConfirmationViewController.swift
- AlphaWallet/Transfer/ViewModels/TransactionConfirmationViewModel.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Transfer/Types/RecipientResolver.swift
> Show full Ethereum address in transaction confirmation actionsheet not "0xabcd…cdef" #5576

- AlphaWallet/Transfer/Coordinators/TransactionConfirmationCoordinator.swift
- AlphaWallet/Transfer/ViewControllers/SendTransactionErrorViewController.swift
> Hide bottom bar when no action button for transaction error screen, code refactoring #5499

- modules/AlphaWalletFoundation/AlphaWalletFoundation/Blockies/BlockieGenerator.swift
> Replace BlockieKey with string for blockie icons #5601

- AlphaWallet/Tokens/Views/TestnetTokenInfoView.swift
Switch to Testnet mode. In main wallet tab, tap ETH.
Before PR | Light mode | Dark mode
-|-|-
> Added dark mode to FungibleTokenViewController under Test mode

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWalletTests/modules/AlphaWalletFoundation/Browser/Types/DappCommandTests.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Browser/Types/DappAction.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Browser/Types/DappCommand.swift
> [Browser] Fix: actionsheet doesn't appear to swap or approve tokens #5616

- AlphaWallet/Browser/ViewControllers/BookmarksViewController.swift
- AlphaWallet/Browser/ViewControllers/BrowserHistoryViewController.swift
- AlphaWallet/Browser/ViewControllers/EditBookmarkViewController.swift
- AlphaWallet/Browser/ViewModel/BrowserHistoryCellViewModel.swift
- AlphaWallet/Browser/ViewModel/BrowserHomeViewModel.swift
- AlphaWallet/Browser/ViewModel/DappViewCellViewModel.swift
- AlphaWallet/Browser/ViewModel/DappsHomeHeaderViewModel.swift
- AlphaWallet/Browser/ViewModel/DappsHomeViewControllerHeaderViewViewModel.swift
- AlphaWallet/Browser/ViewModel/MyDappCellViewModel.swift
- AlphaWallet/Browser/Views/DappBrowserNavigationBar.swift
- AlphaWallet/Browser/Views/MyDappCell.swift
> Added dark mode to Browser

- AlphaWallet/AppCoordinator.swift
- AlphaWallet/AppDelegate.swift
- AlphaWalletTests/Coordinators/AppCoordinatorTests.swift
Have to test to verify it still works propertly for tests and app.
> [Refactor] Move all code in AppDelegate to AppCoordinator

- AlphaWallet/Common/Views/SvgImageView.swift
- AlphaWallet/Common/Views/ViewRounding.swift
- AlphaWallet/Common/Views/WebImageView.swift
- AlphaWallet/Tokens/Collectibles/ViewModels/NFTCollectionInfoPageViewModel.swift
> Apply background color for images in dark mode #5608

- modules/AlphaWalletFoundation/AlphaWalletFoundation/Activities/ActivitiesPipeLine.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/TokenScriptClient/EventSource.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/TokenScriptClient/EventSourceForActivities.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/Helpers/CallSmartContractFunction.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/Logic/Erc1155TokenIdsFetcher.swift
> apply inflight promises for getEventLogs #5651

- modules/AlphaWalletFoundation/AlphaWalletFoundation/TokenScriptClient/EventFetcher.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/TokenScriptClient/EventForActivitiesFetcher.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/TokenScriptClient/EventSource.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/TokenScriptClient/EventSourceForActivities.swift
> wrap fetching events into class wrapper #5653

- AlphaWallet/Lock/Coordinators/LockCreatePasscodeCoordinator.swift
- AlphaWallet/Lock/ViewControllers/LockCreatePasscodeViewController.swift
> Set hidesBottmBarWhenPush for create lock view controller #5628

- modules/AlphaWalletFoundation/AlphaWalletFoundation/TokenScriptClient/EventFetcher.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/TokenScriptClient/EventSource.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/TokenScriptClient/EventSourceForActivities.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/Helpers/CallSmartContractFunction.swift
> fix broken build for xcode 13 #5672

- modules/AlphaWalletFoundation/AlphaWalletFoundation/EtherClient/TrustClient/Models/RawTransaction.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Transactions/EtherscanSingleChainTransactionProvider.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Transactions/TokensFromTransactionsFetcher.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Types/Session.swift
> create class wrapper for fetching LocalizedOperation object #5657

- modules/AlphaWalletFoundation/AlphaWalletFoundation/NFT/Enjin/Enjin.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/NFT/Enjin/EnjinNetworkProvider.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/NFT/NFTProvider.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/NFT/OpenSea/OpenSea.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/NFT/OpenSea/OpenSeaNetworkProvider.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/Helpers/JsonFromTokenUri.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/Models/NonFungibleContract.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/TokensAutodetector/TokensAutodetector.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Types/eip155URLDecoder.swift
- modules/AlphaWalletOpenSea/AlphaWalletOpenSea/OpenSea.swift
> Remove passing queue from enjin and opensea providers #5659

- modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/Logic/IsErc721Contract.swift
> Apply inFlightPromises for getIsERC721Contract #5661

- modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/TokensAutodetector/ImportToken.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/TokensAutodetector/TokensAutodetector.swift
> Move fetchErc875OrErc20Token function to importToken #5669

- modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/Logic/IsErc721Contract.swift
> hardcode 0x7Db4de78E6b9A98752B56959611e4cfdA52269D2 as supports `0x80ac58cd` interface #5667

- AlphaWallet/Settings/ViewControllers/ChooseSendPrivateTransactionsProviderViewController.swift
- AlphaWallet/Settings/ViewModels/ChooseSendPrivateTransactionsProviderViewModel.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Settings/Models/SendPrivateTransactionsProvider.swift
> Private ETH Transactions screen allowing multiple selections #5630

- AlphaWallet/Settings/ViewModels/ExportJsonKeystorePasswordViewModel.swift
> Allow all characters for password textfield, (export Json keystore) #5655

- AlphaWallet.xcodeproj/project.pbxproj
- Podfile
- Podfile.lock
> add swiftformat pod, disable formating for now #5638

- AlphaWallet/Settings/Coordinators/CheckTransactionStateCoordinator.swift
- AlphaWallet/Settings/Coordinators/SettingsCoordinator.swift
- AlphaWalletTests/ViewControllers/PaymentCoordinatorTests.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Activities/ActivitiesPipeLine.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/EtherClient/GetTransactionState.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/EtherClient/Requests/BlockByNumberRequest.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/EtherClient/Requests/ChainIdRequest.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/EtherClient/Requests/TransactionReceiptRequest.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Settings/Models/AddCustomChain.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/TokenScriptClient/EventForActivitiesFetcher.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/TokenScriptClient/EventSourceForActivities.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/Logic/GetBlockTimestamp.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Types/WalletDependencyContainer.swift
> replace with using apikit request for eth_getBlockByNumber and eth_getTransactionReceipt instead of web3 #5683

- modules/AlphaWalletFoundation/AlphaWalletFoundation/EtherClient/Models/GetGasPrice.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/EtherClient/Requests/ChainIdRequest.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/EtherClient/Requests/EstimateGasRequest.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/EtherClient/Requests/GasPriceRequest.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Settings/Models/AddCustomChain.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Transfer/Types/GetGasLimit.swift
> return expected value type rather than string representation for JSONRPC Requests #5685

- AlphaWallet/WalletConnect/Coordinator/WalletConnectCoordinator.swift
> Remove unexpected pop when back button selected for sessions screen of WalletConnect #5689

- AlphaWallet/Settings/ViewControllers/SaveCustomRpcBrowseViewController.swift
- AlphaWallet/Settings/Views/SaveCustomRpcOverallView.swift
Tap `Settings > Select Active Networks > Plus`.
Before | After
-|-
> Fixed Dark Mode On AddCustomRPCNetwork Screen

- AlphaWallet/Lock/Coordinators/LockCreatePasscodeCoordinator.swift
- AlphaWallet/Lock/ViewControllers/LockCreatePasscodeViewController.swift
- AlphaWallet/Lock/ViewControllers/LockPasscodeViewController.swift
- AlphaWallet/Lock/ViewModels/LockCreatePasscodeViewModel.swift
- AlphaWallet/Lock/ViewModels/LockViewModel.swift
- AlphaWallet/Settings/Coordinators/SettingsCoordinator.swift
- AlphaWallet/Settings/ViewControllers/SettingsViewController.swift
- AlphaWallet/Settings/ViewModels/SettingsViewModel.swift
- AlphaWallet/WalletConnect/ViewModel/WalletConnectSessionDetailsViewModel.swift
- AlphaWallet/WalletConnect/ViewModel/WalletConnectSessionsViewModel.swift
- AlphaWalletTests/Coordinators/LockCreatePasscodeCoordinatorTest.swift
> Update back navigation for create lock screen #5699

- AlphaWallet/Browser/Coordinators/ScanQRCodeCoordinator.swift
- AlphaWallet/Common/Coordinators/AcceptProposalCoordinator.swift
- AlphaWallet/Common/Views/UIToolbar+Custom.swift
- AlphaWallet/Extensions/UIBarButtonItem.swift
- AlphaWallet/Settings/Coordinators/HelpUsCoordinator.swift
- AlphaWallet/Tokens/Collectibles/Coordinators/NFTAssetSelectionCoordinator.swift
- AlphaWallet/Transactions/ViewControllers/TransactionViewController.swift
- AlphaWallet/Transfer/Coordinators/SignMessageCoordinator.swift
- AlphaWallet/Transfer/Coordinators/TransactionConfirmationCoordinator.swift
> Make use of cancel and buttons with cross symbol more consistent #5701

- AlphaWallet/AddMultipleCustomRpc/AddMultipleCustomRpcView.swift
- AlphaWallet/AddMultipleCustomRpc/AddMultipleCustomRpcViewController.swift
- AlphaWallet/AddMultipleCustomRpc/AddMultipleCustomRpcViewModel.swift
> remove unused `progressIndicatorView` from add custom rpc view #5707

- AlphaWalletTests/Transfer/ViewModels/RequestViewModelTests.swift
> Fix test suite #5716

- AlphaWallet/Transfer/Coordinators/TransactionConfirmationCoordinator.swift
- AlphaWallet/Transfer/ViewControllers/TransactionConfirmationViewController.swift
- AlphaWallet/Transfer/ViewModels/TransactionConfirmationViewModel.swift
> Fix memory leak with TransactionConfirmationViewModel #5717

- AlphaWallet/ActiveWalletCoordinator.swift
- AlphaWallet/Common/Types/Constants.swift
- AlphaWallet/Common/Views/AddressTextField.swift
- AlphaWallet/Common/Views/AmountTextField.swift
- AlphaWallet/Common/Views/SelectCurrencyButton.swift
- AlphaWallet/Common/Views/ViewModels/AmountTextFieldViewModel.swift
- AlphaWallet/Swap/Swap/ViewModels/SwapTokensViewModel.swift
- AlphaWallet/Transfer/Coordinators/PaymentCoordinator.swift
- AlphaWallet/Transfer/Coordinators/SendCoordinator.swift
- AlphaWallet/Transfer/ViewControllers/SendViewController.swift
- AlphaWallet/Transfer/ViewModels/SendViewModel.swift
- AlphaWalletTests/Coordinators/SendCoordinatorTests.swift
- AlphaWalletTests/Transfer/ViewControllers/SendViewControllerTests.swift
- AlphaWalletTests/ViewControllers/PaymentCoordinatorTests.swift
- modules/AlphaWalletCore/AlphaWalletCore/Extensions/Alamofire+Publishers.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Browser/Models/ScanQRCodeResolution.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Redeem/SignatureHelper.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/Eip681UrlResolver.swift
> Refactor Send fungible token screen, replace ContractDataDetector #5581

- AlphaWallet/Localization/es.lproj/Localizable.strings
- AlphaWallet/Localization/fi.lproj/Localizable.strings
- AlphaWallet/Localization/ja.lproj/Localizable.strings
- AlphaWallet/Localization/ko.lproj/Localizable.strings
- AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings
- AlphaWallet/Tokens/ViewModels/TokensViewModel.swift
- AlphaWallet/Transfer/ViewModels/SendViewModel.swift
- AlphaWalletTests/Core/Types/AddressStorageTests.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Settings/Types/RPCServers.swift
- modules/AlphaWalletWeb3/AlphaWalletWeb3/Utils/CcipRead.swift
Closes #5731, Closes #5704, Closes #5703
> Remove build warnings #5731

- AlphaWallet/Tokens/Coordinators/NewTokenCoordinator.swift
- AlphaWallet/Tokens/ViewControllers/NewTokenViewController.swift
- AlphaWallet/Transfer/Coordinators/SendCoordinator.swift
- AlphaWalletTests/Coordinators/TokensCoordinatorTests.swift
- AlphaWalletTests/Core/Helpers/LogLargeNftJsonFilesTests.swift
- AlphaWalletTests/Core/Types/RetryPublisherTests.swift
- AlphaWalletTests/Tokens/Helpers/TokenObjectTest.swift
- AlphaWalletTests/Tokens/TokensDataStoreTest.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/EtherClient/Models/EthCall.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/AlphaWalletTokensService.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/ClientSideTokenSourceProvider.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/Helpers/NonFungibleErc1155JsonBalanceFetcher.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/Logic/ContractDataDetector.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/TokensAutodetector/ImportToken.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/TokensAutodetector/TokensAutodetector.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/TokensProcessingPipeline.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/TokensService.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/Types/ErcToken.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/Types/TokensDataStore.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/WalletBalance/TokenBalanceFetcher.swift
> simplify TokenOrContract #5624

- AlphaWallet/Tokens/Collectibles/ViewModels/FungibleTokenHeaderViewModel.swift
- AlphaWallet/Tokens/Coordinators/SingleChainTokenCoordinator.swift
- AlphaWallet/Tokens/ViewModels/FungibleTokenViewModel.swift
- AlphaWallet/Tokens/ViewModels/TokenInfoPageViewModel.swift
- AlphaWallet/Transactions/Coordinators/ReplaceTransactionCoordinator.swift
- AlphaWallet/Transfer/Coordinators/PaymentCoordinator.swift
- AlphaWallet/Transfer/Coordinators/SendCoordinator.swift
- AlphaWallet/Transfer/ViewModels/ConfigureTransactionViewModel.swift
- AlphaWallet/Transfer/ViewModels/SendViewModel.swift
- AlphaWallet/Transfer/ViewModels/TransactionConfirmation/SendFungiblesTransactionViewModel.swift
- AlphaWallet/Transfer/ViewModels/TransactionConfirmation/SendNftTransactionViewModel.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Activities/Types/ActivitiesFilterStrategy.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/TokenActions/TokenActionsService.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Transfer/TransactionConfigurator.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Transfer/Types/TransactionType.swift
> Remove unused transaction type .erc875TokenOrder #5742

- AlphaWallet/Tokens/Coordinators/ClaimPaidOrderCoordinator.swift
> Refactor encodeOrder(signedOrder with removing callback closure #5743

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet/ActiveWalletCoordinator.swift
- AlphaWallet/AppCoordinator.swift
- AlphaWallet/Common/Views/EmptyView.swift
- AlphaWallet/Localization/en.lproj/Localizable.strings
- AlphaWallet/Localization/es.lproj/Localizable.strings
- AlphaWallet/Localization/fi.lproj/Localizable.strings
- AlphaWallet/Localization/ja.lproj/Localizable.strings
- AlphaWallet/Localization/ko.lproj/Localizable.strings
- AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings
- AlphaWallet/Settings/Coordinators/ConsoleCoordinator.swift
- AlphaWallet/Settings/ViewControllers/ConsoleViewController.swift
- AlphaWallet/Settings/ViewModels/ConsoleViewModel.swift
- AlphaWallet/Tokens/Coordinators/TokensCoordinator.swift
- AlphaWallet/Tokens/ViewModels/TokensViewModel.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/TokenScriptClient/Models/AssetDefinitionStore.swift
> Update console screen, make self reloaded, when tokenScript bad files have changed. Add empty state. #5756

- modules/AlphaWalletFoundation/AlphaWalletFoundation/TokenScriptClient/Models/AssetDefinitionStore.swift
> Fix crash on app launch Thread 1: Simultaneous accesses to 0x11a4e5158, but modification requires exclusive access #5770

- modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/TokensAutodetector/ImportToken.swift
> Remove running at queue warning when importing token #5768

- modules/AlphaWalletFoundation/AlphaWalletFoundation/Helpers/Device.swift
> Added new iPhones and iPads data to Device

- AlphaWallet/Common/Types/Constants.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Settings/Types/Constants+Credentials.swift
@oa-s I thought there was a reason to keep them separate, but I can't remember now. Do you?
> [Refactor] Move credentials/APIs to single file

- AlphaWallet/Tokens/Collectibles/ViewModels/FungibleTokenHeaderViewModel.swift
- AlphaWallet/Tokens/Collectibles/Views/FungibleTokenHeaderView.swift
- AlphaWallet/Tokens/Collectibles/Views/TokenInfoPageView.swift
- AlphaWallet/Tokens/Coordinators/SingleChainTokenCoordinator.swift
- AlphaWallet/Tokens/Coordinators/TokensCoordinator.swift
- AlphaWallet/Tokens/ViewControllers/FungibleTokenViewController.swift
- AlphaWallet/Tokens/ViewModels/FungibleTokenViewModel.swift
- AlphaWallet/Tokens/ViewModels/TokenInfoPageViewModel.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Activities/Types/ActivitiesFilterStrategy.swift
> Remove transaction type from fungible token view controller, not right place for defining transaction type, simplify code #5775

- AlphaWallet/Browser/ViewControllers/BrowserViewController.swift
- AlphaWallet/Sell/ViewModels/EnterSellTokensCardPriceQuantityViewControllerViewModel.swift
- AlphaWallet/Tokens/Views/TokenInstanceWebView.swift
- AlphaWallet/WalletConnect/Types/WalletConnectRequestConverter.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Settings/Types/RPCServers.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/Types/TokensDataStore.swift
> Remove old function `token(forServer` #5772

- AlphaWallet/Transfer/ViewControllers/ConfigureTransactionViewController.swift
> set missing save button for configure transaction screen #5795

- AlphaWallet/Settings/ViewModels/SettingsViewModel.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Analytics/AnalyticsTypes.swift
> send analytics event `Passcode / Face ID enabled/disabled` #5755

- AlphaWallet/Common/Views/TextField.swift
> Set `next` bool bar button for `inputAccessoryButtonType: InputAccess

- AlphaWallet/Common/Types/AppStyle.swift
- AlphaWallet/Common/Types/Configuration.swift
> Added dark mode to refresh control

- AlphaWallet/ActiveWalletCoordinator.swift
> [Analytics] Log if user enabled passcode/Face ID for app at startup (not just when user changes it)

- AlphaWallet/Transfer/ViewControllers/SendViewController.swift
- AlphaWallet/Transfer/ViewModels/SendViewModel.swift
> Move amount text field activating to `viewDidAppear` #5752

- modules/AlphaWalletFoundation/AlphaWalletFoundation/Settings/Types/Constants.swift
> Update AlphaWallet logo image used in Ramp

- AlphaWallet/Common/Views/TextView.swift
> Fix: import wallet with seed phrase screen doesn't enable Import button nor show suggestions as user types

- modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/AlphaWalletTokensService.swift
> Remove spurious tokens for initial state #5828

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet/Settings/Coordinators/SettingsCoordinator.swift
- AlphaWallet/Settings/Coordinators/SupportCoordinator.swift
- AlphaWallet/Settings/ViewControllers/SupportViewController.swift
- AlphaWallet/Settings/ViewModels/SupportViewModel.swift
> Add support coordinator #5831

- AlphaWallet/Lock/ViewControllers/LockPasscodeViewController.swift
> Remove adjusting bottom inset when keyboard appears for LockPasscodeView. #5838

- AlphaWallet/ActiveWalletCoordinator.swift
- AlphaWallet/Swap/SelectServiceToSwapCoordinator.swift
> Add missed logging of selected swap service #5837

- AlphaWallet/Accounts/ViewControllers/AccountsViewController.swift
- AlphaWallet/Accounts/ViewModels/AccountViewModel.swift
- AlphaWallet/Accounts/ViewModels/AccountsViewModel.swift
- AlphaWallet/Accounts/ViewModels/WalletSummaryViewModel.swift
- AlphaWallet/Accounts/Views/AccountViewCell.swift
- AlphaWallet/AppCoordinator.swift
- AlphaWallet/Tokens/ViewModels/TokensViewModel.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/ClientSideTokenSourceProvider.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/TokensProcessingPipeline.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Types/SessionsProvider.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Types/WalletBalance.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Types/WalletDependencyContainer.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Types/WalletSummary.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/WalletBalance/WalletBalanceFetcher.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/WalletBalance/WalletBalanceService.swift
> After switching from mainnet to testnet, list of wallets screen shows fiat balance for every wallet except current wallet #5786

- AlphaWallet/Localization/en.lproj/Localizable.strings
- AlphaWallet/Localization/es.lproj/Localizable.strings
- AlphaWallet/Localization/fi.lproj/Localizable.strings
- AlphaWallet/Localization/ja.lproj/Localizable.strings
- AlphaWallet/Localization/ko.lproj/Localizable.strings
- AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings
- AlphaWallet/Settings/ViewControllers/EnabledServersViewController.swift
- AlphaWallet/Settings/ViewModels/EnabledServersViewModel.swift
> Show current enabled number of networks in the "Enabled Networks" screen #5763

- AlphaWallet/Tokens/Collectibles/Views/TokenHistoryChartView.swift
- AlphaWallet/Tokens/ViewModels/TokenHistoryChartViewModel.swift
- AlphaWallet/Tokens/ViewModels/TokenInfoPageViewModel.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/CoinTicker/BaseCoinTickersFetcher.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/CoinTicker/CoinTickersFetcherImpl.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/Types/ChartHistory.swift
> fix displaying unavailable chart data for selected period #5836

- AlphaWallet/Common/Views/TextView.swift
- AlphaWallet/Wallet/ViewControllers/ImportWalletViewController.swift
> Reset mnemonic text field validation when text changes, on import screen #5824

- modules/AlphaWalletFoundation/AlphaWalletFoundation/TokenScriptClient/Models/XMLHandler.swift
> Replace XmlHandler with struct definition #5840

- AlphaWallet/Localization/fi.lproj/Localizable.strings
> add missing key 'transaction.id' #5865

- AlphaWalletTests/Coordinators/ActiveWalletViewTests.swift
> Fixed ActiveWalletViewTests by adding missing CurrencyService

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet/ActiveWalletCoordinator.swift
- AlphaWallet/AppCoordinator.swift
- AlphaWallet/Common/Views/EmptyView.swift
- AlphaWallet/Settings/Coordinators/SettingsCoordinator.swift
- AlphaWallet/TokenScript/Coordinators/AssetDefinitionStoreCoordinator.swift
- AlphaWallet/TokenScript/ViewControllers/AssetDefinitionsOverridesViewController.swift
- AlphaWallet/TokenScript/ViewModels/AssetDefinitionsOverridesViewCellViewModel.swift
- AlphaWallet/TokenScript/ViewModels/AssetDefinitionsOverridesViewModel.swift
- AlphaWalletTests/Coordinators/ActiveWalletViewTests.swift
- AlphaWalletTests/Coordinators/AppCoordinatorTests.swift
- AlphaWalletTests/Factories/FakeTokenScriptOverridesFileManager.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/TokenScriptClient/TokenScriptOverridesFileManager.swift
> Extract logic from AssetDefinitionStoreCoordinator to separate class #5867

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet/ActiveWalletCoordinator.swift
- AlphaWallet/Browser/Coordinators/DappBrowserCoordinator.swift
- AlphaWallet/Browser/ViewControllers/BookmarksViewController.swift
- AlphaWallet/Browser/ViewControllers/BrowserHistoryViewController.swift
- AlphaWallet/Browser/ViewControllers/BrowserHomeViewController.swift
- AlphaWallet/Browser/ViewModel/BrowserHistoryCellViewModel.swift
- AlphaWallet/Browser/ViewModel/BrowserHomeViewModel.swift
- AlphaWallet/Browser/ViewModel/DappsHomeHeaderViewModel.swift
- AlphaWallet/Browser/ViewModel/HistoriesViewModel.swift
- AlphaWallet/Browser/Views/BookmarksHeaderView.swift
- AlphaWallet/Browser/Views/BrowserHistoryHeaderView.swift
- AlphaWallet/Browser/Views/BrowserHomeHeaderView.swift
- AlphaWallet/Browser/Views/DappsHomeEmptyView.swift
- AlphaWallet/Common/Types/Constants.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Browser/Storage/HistoryStore.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Browser/Types/History.swift
> Move more logic from BrowserHistoryViewController to its view model #5876

- AlphaWallet.xcodeproj/project.pbxproj
> Uncheck "Based on dependency analysis" in the script phase to hide warnings #5870

- modules/AlphaWalletFoundation/AlphaWalletFoundation/TokenScriptClient/Models/AssetDefinitionStore.swift
> Fix: TokenScript not downloaded from IPFS with EIP-5169/scriptURI() when the URL has changed because Infura IPFS gateway always return `304`

- modules/AlphaWalletFoundation/AlphaWalletFoundation/Settings/Types/RPCServers.swift
> Update avalance transaction fetcher with new base URL `https://api.snowtrace.io/api` #5875

- AlphaWallet/Common/Types/Configuration.swift
Closes #5395
Before | After
-|-
> Changed Secondary Button Background Color

- AlphaWallet/Common/Types/Configuration.swift
- AlphaWallet/Common/ViewControllers/ModalViewController.swift
- AlphaWallet/Common/ViewControllers/PromptViewController.swift
- AlphaWallet/Transfer/ViewModels/ConfirmationHeaderViewModel.swift
Closes #5042
Changed background colour for PromptViewController to Venus.
> Changed PromptViewController dark mode background colour to match design

- AlphaWalletTests/Extensions/UIColorExtensionTests.swift
> Fixed UIColorExtensionTests.swift

- AlphaWallet/Transfer/ViewModels/SendViewModel.swift
> Fixed white space violation

- AlphaWalletTests/Foundation/EtherNumberFormatterTests.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Foundation/Formatter.swift
> Fix crash when enter value bigger than Int.max for amount text field #5928

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet/Tokens/ViewControllers/TokenInstanceActionViewController.swift
- AlphaWallet/Tokens/Views/TokenInstanceWebView.swift
- AlphaWallet/Transfer/Coordinators/NoViewCardTokenScriptActionCoordinator.swift
- AlphaWallet/Transfer/Coordinators/TokenScriptCoordinator.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/TokenScriptClient/Models/XMLHandler.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/TokenScriptClient/TokenScript+UI.swift
> Make TokenScript engine support no view cards

- modules/AlphaWalletFoundation/AlphaWalletFoundation/NFT/Enjin/Enjin.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/NFT/Enjin/EnjinNetworkProvider.swift
> Move Apollo callback to main queue to avoid bad access #5931

- AlphaWallet/Resources/tokensToImport.json
> auto import `TIX` (0x89D142Bef8605646881C68dcD48cDAF17FE597dC) token,only if there is a balance #5948

- AlphaWallet/Tokens/TokenInstanceViewConfigurationHelper.swift
i.e. display the attribute `isRedeemed` with the label "Claim Redeemed" but hide the attribute `isRedeemed2`:
```
<ts:attribute name="isRedeemed">
<ts:label>
<ts:string xml:lang="en">Claim Redeemed</ts:string>
</ts:label>
```
```
<ts:attribute name="isRedeemed2">
```
> [TokenScript] Only display token-level attributes which has name/labels in NFT token view

- AlphaWallet/Browser/ViewControllers/BookmarksViewController.swift
- AlphaWallet/Tokens/ViewControllers/TokenInstanceActionViewController.swift
- AlphaWallet/Transfer/Coordinators/TokenScriptCoordinator.swift
- AlphaWalletTests/Coordinators/ActiveWalletViewTests.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/TokenScriptClient/TokenScript+UI.swift
> swiftlint fix warnings

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet.xcworkspace/xcshareddata/swiftpm/Package.resolved
- AlphaWallet/WalletConnect/Providers/v2/WalletConnectV2Provider.swift
- AlphaWallet/WalletConnect/Providers/v2/WalletConnectV2Storage.swift
- AlphaWallet/WalletConnect/Providers/v2/WalletConnectV2Types.swift
- AlphaWallet/WalletConnect/Types/WalletConnect.swift
- AlphaWallet/WalletConnect/Types/WalletConnectRequestConverter.swift
- Podfile
- Podfile.lock
> Update wallet connect sign to 1.0.2 version #5693

- AlphaWallet/Swap/Swap/ViewModels/SwapQuoteDetailsViewModel.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/SwapToken/NativeSwap/Helpers/TokenSwapperNetworkProvider.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/SwapToken/NativeSwap/SwapEstimate.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/SwapToken/NativeSwap/UnsignedSwapTransaction.swift
> fix crashing when decoding swap quote response #5981

- AlphaWallet/AppCoordinator.swift
> Don't prompt user to choose active chains after creating/importing their first wallet #5982

- AlphaWallet/Transfer/ViewModels/SendViewModel.swift
> Take initial value from amount input, when transaction type has no initial amount #5859

- AlphaWallet/Common/Views/ViewModels/AmountTextFieldViewModel.swift
- AlphaWalletTests/Foundation/EtherNumberFormatterTests.swift
- AlphaWalletTests/Transfer/ViewControllers/SendViewControllerTests.swift
- AlphaWalletTests/ViewControllers/PaymentCoordinatorTests.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/CoinTicker/Types/CoinTicker.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Foundation/Formatter.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Types/WalletDependencyContainer.swift
> Fix test suite #6001

- AlphaWallet/Localization/en.lproj/Localizable.strings
- AlphaWallet/Localization/es.lproj/Localizable.strings
- AlphaWallet/Localization/fi.lproj/Localizable.strings
- AlphaWallet/Localization/ja.lproj/Localizable.strings
- AlphaWallet/Localization/ko.lproj/Localizable.strings
> Remove double (usd usd) on backup wallet alert on tokens screen #5997

- modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/Logic/GetBlockTimestamp.swift
Not sure why it's crashing (but the caller is using another queue and this code has its private queue).
```
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------
Incident Identifier: 62BCF975-85D5-4A33-BE88-FC7531203DCE
CrashReporter Key:   192F1E55-BEA3-C6C2-D63B-A7DD0728F6EA
Hardware Model:      MacBookPro18,2
Process:             AlphaWallet [14328]
Path:                /Users/USER/Library/Developer/CoreSimulator/Devices/A595C4ED-EF9C-4077-B906-7E9E0C01B941/data/Containers/Bundle/Application/4EEC93E3-4138-4717-B311-81F9797D520D/AlphaWallet.app/AlphaWallet
Identifier:          com.stormbird.alphawallet
Version:             3.59 (468)
Code Type:           ARM-64 (Native)
Role:                Foreground
Parent Process: …
```
> No longer use a private queue for GetBlockTimestamp. Simpler and possibly avoid crash

- AlphaWallet/Browser/Coordinators/DappBrowserCoordinator.swift
- AlphaWallet/Common/ViewControllers/ModalViewController.swift
- AlphaWallet/Common/Views/NavigationController.swift
- AlphaWallet/Settings/Coordinators/CheckTransactionStateCoordinator.swift
- AlphaWallet/Settings/ViewControllers/ServersViewController.swift
- AlphaWallet/Settings/ViewModels/ServersViewModel.swift
- AlphaWallet/Tokens/Coordinators/NewTokenCoordinator.swift
- AlphaWallet/WalletConnect/Coordinator/WalletConnectSessionCoordinator.swift
> Fix double pop when switching rpc server for wallet connect session, disable unselect all servers #5990

- AlphaWalletTests/Transfer/Types/TransactionTypeFromQrCodeTests.swift
> Remove commented out code #6004

- AlphaWallet/ActiveWalletCoordinator.swift
- AlphaWallet/AppCoordinator.swift
- AlphaWallet/Backup/Coordinators/PromptBackupCoordinator.swift
- AlphaWallet/Backup/ViewModels/PromptBackupWalletAfterExceedingThresholdViewViewModel.swift
- AlphaWallet/Settings/Coordinators/SettingsCoordinator.swift
- AlphaWallet/Settings/ViewModels/SettingsViewModel.swift
- AlphaWalletTests/Coordinators/TokensCoordinatorTests.swift
- AlphaWalletTests/Settings/ConfigTests.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Types/WalletBalance.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Types/WalletDependencyContainer.swift
> Fix: displaying wallets balance in prompted backup view on tokens screen, formatting #5999

- AlphaWallet/Accounts/ViewControllers/AccountsViewController.swift
- AlphaWallet/Alerts/ViewControllers/PriceAlertsViewController.swift
- AlphaWallet/Browser/ViewControllers/BrowserHomeViewController.swift
- AlphaWallet/Settings/ViewControllers/SettingsViewController.swift
- AlphaWallet/Tokens/ViewControllers/TokensViewController.swift
- AlphaWallet/Tokens/ViewModels/TokensViewModel.swift
> Fix memory leaks with datasource [self] capturing #6013

- modules/AlphaWalletFoundation/AlphaWalletFoundation/NFT/OpenSea/Types/NonFungibleFromJson+Extension.swift
> remove global decoder JSONDecoder() for decoding nonfungible from json #6022

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWalletTests/Factories/DataTests.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/EtherClient/Requests/BlockByNumberRequest.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/EtherClient/Requests/DASLookupRequest.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/EtherClient/Requests/TransactionReceiptRequest.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Extensions/Data.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Extensions/Dictionary.swift
> add safe init with json for Data to avoid crash when json is invalid #6020

- modules/AlphaWalletFoundation/AlphaWalletFoundation/TokenScriptClient/Models/AssetDefinitionStore.swift
> Remove AtomicDictionary from AssetDefinitionStore to avoid bad access #6010

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet/Backup/Coordinators/BackupCoordinator.swift
- AlphaWallet/Common/Types/CoordinatorThatEnds.swift
- AlphaWallet/Wallet/Coordinators/BackupSeedPhraseCoordinator.swift
- AlphaWallet/Wallet/Coordinators/ElevateWalletSecurityCoordinator.swift
- AlphaWallet/Wallet/Coordinators/EnterPasswordCoordinator.swift
- AlphaWallet/Wallet/ViewControllers/EnterKeystorePasswordViewController.swift
- AlphaWallet/Wallet/ViewControllers/KeystoreBackupIntroductionViewController.swift
> Fix memory leaks with backup coordinator, remove CoordinatorThatEnds #6027

- AlphaWallet/Transfer/ViewModels/SendViewModel.swift
- AlphaWalletTests/Transfer/ViewControllers/SendViewControllerTests.swift
> Tweak send view model for debuging testScanEip681QrCodeEnglish test #6039

- AlphaWalletTests/Transfer/Types/UnconfirmedTransactionTests.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/CoinTicker/TickerIdsFetcher/AlphaWalletRemoteTickerIdsFetcher.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Ethereum/ABI/DecodedFunctionCall.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Ethereum/Methods/AnyContractMethod.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/JSON/TokenGroupIdentifier.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Transfer/Types/TransactionType.swift
- modules/AlphaWalletWeb3/AlphaWalletWeb3/ABI/ABITypes.swift
- modules/AlphaWalletWeb3/AlphaWalletWeb3/ABIv2/ABIv2Decoding.swift
- modules/AlphaWalletWeb3/AlphaWalletWeb3/Contract/ContractABIv1.swift
- modules/AlphaWalletWeb3/AlphaWalletWeb3/Contract/ContractABIv2.swift
- modules/AlphaWalletWeb3/AlphaWalletWeb3/Contract/ContractProtocol.swift
- modules/AlphaWalletWeb3/AlphaWalletWeb3/Contract/EventFiltering.swift
- modules/AlphaWalletWeb3/AlphaWalletWeb3/Web3/Web3+Contract.swift
- modules/AlphaWalletWeb3/AlphaWalletWeb3/Web3/Web3+EventParser.swift
- modules/AlphaWalletWeb3/AlphaWalletWeb3/Web3/Web3+TransactionIntermediate.swift
> contract abi improvement #6036

- AlphaWallet/WalletConnect/Types/WalletConnectRequestConverter.swift
> fix incorrect transaction type for WalletConnect #6041

- modules/AlphaWalletFoundation/AlphaWalletFoundation/Settings/Types/RPCServers.swift
> Fix: Arbitrum Goerli and Optimism Goerli RPC node mixed up

- AlphaWallet/Transactions/Coordinators/TransactionsCoordinator.swift
> fix share button in TransactionsDetailViewController fails to open share sheet #6053

- AlphaWallet/Tokens/ViewControllers/TokensViewController.swift
- AlphaWallet/Tokens/ViewModels/TokensViewModel.swift
> Change the title of the Wallet tab to show the truncated wallet address if ENS/wallet name is not available #6042

- AlphaWallet/ActiveWalletCoordinator.swift
- AlphaWallet/Tokens/ViewModels/TokensViewModel.swift
- AlphaWalletTests/Settings/ConfigTests.swift
> Fix testsuite #6082

- AlphaWallet/Swap/Swap/ViewModels/SwapQuoteDetailsViewModel.swift
- AlphaWallet/Swap/Swap/ViewModels/SwapStepViewModel.swift
> Fix displaying small amounts when swap #6080

- AlphaWallet/Transfer/ViewModels/TransactionConfirmation/SwapTransactionViewModel.swift
> Fix displaying swap amount on confirmation popup #6076

- AlphaWallet/Transfer/ViewModels/TransactionConfirmation/CancelTransactionViewModel.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Transfer/Types/GasLimitWarning.swift
> Fix displaying gasLimit error when configuring transaction #6074

- AlphaWallet/Swap/Swap/SwapTokensCoordinator.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/EtherClient/Models/GetGasPrice.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/SwapToken/NativeSwap/Helpers/ApproveSwapProvider.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/SwapToken/NativeSwap/Helpers/TokenSwapperNetworkProvider.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/SwapToken/NativeSwap/Types/SwapError.swift
> Fix stucking on loading screen when call approve(), fix displaying small amounts when confirmation swap action. #6055

- AlphaWallet/Settings/ViewControllers/SettingsViewController.swift
> fix showing key lock status in Settings #6105

- AlphaWallet/Swap/Swap/ViewModels/SwapQuoteDetailsViewModel.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/SwapToken/NativeSwap/SwapEstimate.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/SwapToken/NativeSwap/UnsignedSwapTransaction.swift
> Fix encoding missing gasPrice for swap response #6072

- AlphaWallet/ActiveWalletCoordinator.swift
- AlphaWallet/AppCoordinator.swift
- AlphaWallet/Browser/Coordinators/QRCodeResolutionCoordinator.swift
- AlphaWallet/Tokens/ViewControllers/AddHideTokensViewController.swift
- AlphaWallet/Tokens/ViewModels/AddHideTokensViewModel.swift
- AlphaWallet/Transfer/ViewModels/SendViewModel.swift
- AlphaWalletTests/Ens/EnsResolverTests.swift
- AlphaWalletTests/EtherClient/EtherKeystoreTests.swift
- AlphaWalletTests/Foundation/QRCodeValueParserTests.swift
- AlphaWalletTests/Transfer/Types/TransactionTypeFromQrCodeTests.swift
- AlphaWalletTests/Transfer/ViewControllers/SendViewControllerTests.swift
- AlphaWalletTests/ViewControllers/PaymentCoordinatorTests.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Foundation/Eip681Parser.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/Eip681UrlResolver.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/TokensAutodetector/ImportToken.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/TokensAutodetector/TokensAutodetector.swift
Fixes #6097, Closes #6101, Closes #6071
> Fix testsuite #6097

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet/ActiveWalletCoordinator.swift
- AlphaWallet/AppCoordinator.swift
- AlphaWallet/Market/Coordinators/ImportMagicLinkCoordinator.swift
- AlphaWallet/Market/ImportMagicLinkController.swift
- AlphaWallet/Market/ViewControllers/ImportMagicTokenViewController.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/KeyManagement/EtherKeystore.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/UniversalLink/UrlSchemeResolver.swift
> extract functionality from ImportMagicLinkCoordinator #6109

- AlphaWallet/Sell/ViewControllers/EnterSellTokensCardPriceQuantityViewController.swift
> Add done button to amount test field on `EnterSellTokensCardPriceQuantity` screen #6095

- AlphaWallet/Tokens/Collectibles/ViewModels/NonFungibleTraitViewModel.swift
- AlphaWallet/Tokens/TokenInstanceViewConfigurationHelper.swift
- AlphaWallet/Tokens/ViewModels/OpenSea/OpenSeaNonFungibleTokenCardRowViewModel.swift
> Remove whitespaces and new lines in traits view, replace empty strings with "-" #6115

- AlphaWallet/Tokens/ViewModels/NewTokenViewModel.swift
Removed unused fields as per https://discord.com/channels/548357107267928064/923063240060194867/1062899223701499904
> Removed unused fields choiceLabelColor and choiceLabelFont from NewTokenViewModel

- AlphaWallet/AppCoordinator.swift
- AlphaWalletTests/Factories/FakeTokenSwapper.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Analytics/AnalyticsTypes.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/SwapToken/NativeSwap/TokenSwapper.swift
> [Analytics] Log li.fi API errors

- AlphaWallet/Common/Views/ButtonsBar/ButtonsBarBackgroundView.swift
> Remove commented out code #6085

- AlphaWallet/Accounts/ViewModels/AccountsViewModel.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Types/WalletBalance.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/WalletBalance/WalletBalanceFetcher.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/WalletBalance/WalletBalanceService.swift
> Fix long waiting for wallet balance resolution #6033

- AlphaWallet/Common/Types/Error.swift
- AlphaWallet/Localization/en.lproj/Localizable.strings
- AlphaWallet/Localization/es.lproj/Localizable.strings
- AlphaWallet/Localization/fi.lproj/Localizable.strings
- AlphaWallet/Localization/ja.lproj/Localizable.strings
- AlphaWallet/Localization/ko.lproj/Localizable.strings
- AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings
- AlphaWallet/Tokens/Collectibles/Coordinators/NFTCollectionCoordinator.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/EtherClient/KeyStoreError.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/KeyManagement/EtherKeystore.swift
> Fix app crashing when trying to generate a link when private key unavailable #6114

- AlphaWallet/Transfer/Collectibles/Coordinators/TransferCollectiblesCoordinator.swift
- AlphaWallet/Transfer/Coordinators/TransactionConfirmationCoordinator.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Types/DevelopmentForcedError.swift
> display an error when `not enough gas` instead of displaying prompt action sheet #6092

- AlphaWallet/Activities/Views/ActivitiesView.swift
- AlphaWallet/Transactions/Coordinators/TransactionsCoordinator.swift
- AlphaWallet/Transactions/ViewModels/TransactionDetailsViewModel.swift
- AlphaWallet/Transactions/ViewModels/TransactionRowCellViewModel.swift
- AlphaWallet/Transactions/ViewModels/TransactionRowViewModel.swift
- AlphaWallet/Transactions/ViewModels/TransactionViewModel.swift
- AlphaWallet/Transactions/ViewModels/TransactionsViewModel.swift
- AlphaWalletTests/Factories/ChainState.swift
- AlphaWalletTests/Transactions/ViewModels/TransactionViewModelTests.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/EtherClient/ChainState.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/EtherClient/ChainStateSchedulerProvider.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Settings/Types/Constants.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/Logic/Erc1155TokenIdsFetcher.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Types/Session.swift
as part of https://github.com/AlphaWallet/alpha-wallet-ios/pull/5976
> Rename chain state to block number provider

- modules/AlphaWalletFoundation/AlphaWalletFoundation/TokenScriptClient/AssetDefinitionNetworking.swift
> make `fetchXml(request` shared for subscribers

- AlphaWalletTests/Factories/WalletSession.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/EtherClient/Models/GetTransactionState.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/RPC/BlockchainProvider.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/Logic/GetContractInteractions.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Transactions/Covalent/TransactionProviders/CovalentNetworkProvider.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Transactions/Covalent/TransactionProviders/CovalentTransactionProvider.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Transactions/Covalent/TransactionProviders/PendingTransaction/PendingTransactionProvider.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Transactions/Covalent/TransactionProviders/PendingTransaction/PendingTransactionSchedulerProvider.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Transactions/EtherscanSingleChainTransactionProvider.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Transactions/TokensFromTransactionsFetcher.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Transactions/Types/RawTransaction.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Transactions/Types/TransactionItemState.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Types/Session.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Types/SessionsProvider.swift
> create base blockchain provider

- modules/AlphaWalletCore/AlphaWalletCore/Extensions/RetryIf.swift
> Reformated retry function due to SwiftLint warning

- AlphaWallet/Activities/Views/ActivityStateView.swift
- AlphaWallet/Common/Types/AppStyle.swift
- AlphaWallet/Common/Types/Configuration.swift
> [Refactor] Renamed Colors.loadingBackground to Configuration.Color.Semantic.loading.

- AlphaWallet/Common/Types/AppStyle.swift
- AlphaWallet/Common/Types/Configuration.swift
- AlphaWallet/Common/ViewControllers/AcceptProposalViewController.swift
- AlphaWallet/Transfer/ViewControllers/SendTransactionErrorViewController.swift
- AlphaWallet/Transfer/ViewControllers/SignatureConfirmationViewController.swift
- AlphaWallet/Transfer/ViewControllers/TransactionConfirmationViewController.swift
- AlphaWallet/Transfer/Views/ActivityIndicatorControl.swift
> [Refactor] Renamed Colors.loadingIndicatorBorder to Configuration.Colors.Semantic.loadingIndicatorBorder.

- AlphaWallet/AppCoordinator.swift
- AlphaWallet/Market/ImportMagicLinkController.swift
- AlphaWallet/Tokens/ViewControllers/TokenInstanceActionViewController.swift
- AlphaWallet/Tokens/Views/TokenInstanceWebView.swift
- AlphaWalletTests/Coordinators/ActiveWalletViewTests.swift
- AlphaWalletTests/TokenScriptClient/AssetDefinitionStoreTests.swift
- AlphaWalletTests/TokenScriptClient/XMLHandlerTest.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/RPC/BlockchainsProvider.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/TokenScriptClient/Models/AssetAttribute.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/TokenScriptClient/Models/AssetDefinitionStore.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/TokenScriptClient/Models/CallForAssetAttributeProvider.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/TokenScriptClient/Models/XMLHandler.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/TokenScriptClient/TokenScript+UI.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/Helpers/TokenAdaptor.swift
> Remove static assetAttributeProvider from XmlHandler

- AlphaWallet/Transfer/Coordinators/TransactionConfirmationCoordinator.swift
- AlphaWallet/Transfer/ViewControllers/SendTransactionErrorViewController.swift
- AlphaWallet/Transfer/ViewModels/SendTransactionErrorViewModel.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Extensions/Session+PromiseKit.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Transfer/SendTransaction.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Transfer/Types/SendTransactionError.swift
> add conformance to LocalizedError for SendTransactionNotRetryableError, tweak SendTransactionNotRetryableError #6158

- AlphaWalletTests/Coordinators/ActiveWalletViewTests.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Networking/NetworkService.swift
> BaseNetworkService.callbackQueue should probably be .main #6184

- AlphaWallet/Common/Types/AppStyle.swift
- AlphaWallet/Common/Types/Configuration.swift
- AlphaWallet/Common/Views/ButtonsBar/ButtonsBar.swift
> [Refactor] Renamed Colors.disabledActionButton to Configuration.Color.Semantic.disabledActionButton

- AlphaWallet/Browser/Coordinators/ScanQRCodeCoordinator.swift
- AlphaWallet/Common/Types/AppStyle.swift
- AlphaWallet/Common/Types/Configuration.swift
> [Refactor] Renamed Colors.qrCodeRectBorders to Configuration.Color.Semantic.qrCodeRectBorders

- AlphaWallet/Wallet/Coordinators/WalletCoordinator.swift
- AlphaWallet/Wallet/ViewControllers/ImportWalletViewController.swift
> display SuccessOverlayView when creating a new wallet #6210

- modules/AlphaWalletFoundation/AlphaWalletFoundation/Settings/Types/RPCServers.swift
> Update Klaytn Transaction/Transfer API routes #6121

- AlphaWallet/Common/Types/AppStyle.swift
- AlphaWallet/Transfer/Views/ActivityIndicatorControl.swift
> [Refactor] Renamed Colors.green to Configuration.Color.Semantic.pass

- AlphaWallet/Common/Views/ViewModels/AmountTextFieldViewModel.swift
- AlphaWalletTests/Transfer/ViewControllers/SendViewControllerTests.swift
> drop initial 0 value when on send token screen #6216

- AlphaWallet/AppCoordinator.swift
> don't mark a new created wallet as imported to fix prompting to backup #6212

- AlphaWallet/Sell/ViewControllers/EnterSellTokensCardPriceQuantityViewController.swift
- AlphaWallet/Sell/ViewControllers/GenerateSellMagicLinkViewController.swift
- AlphaWallet/Sell/ViewControllers/SetSellTokensCardExpiryDateViewController.swift
- AlphaWallet/Sell/ViewModels/EnterSellTokensCardPriceQuantityViewModel.swift
- AlphaWallet/Sell/ViewModels/GenerateSellMagicLinkViewModel.swift
- AlphaWallet/Sell/ViewModels/SetSellTokensCardExpiryDateViewModel.swift
- AlphaWallet/Tokens/Collectibles/Coordinators/NFTCollectionCoordinator.swift
> Fix displaying total cost when sell token #6098

- AlphaWallet/Common/Views/AmountTextField.swift
- AlphaWallet/Common/Views/SelectCurrencyButton.swift
- AlphaWallet/Transfer/ViewControllers/SendViewController.swift
- AlphaWallet/Transfer/ViewModels/SendViewModel.swift
> Restrict token symbol to half screen width to avoid broken amount text field view #6185

- AlphaWallet/ActiveWalletCoordinator.swift
- AlphaWallet/Swap/Swap/SwapTokensCoordinator.swift
- AlphaWallet/Transfer/Coordinators/PaymentCoordinator.swift
- AlphaWalletTests/ViewControllers/PaymentCoordinatorTests.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/EtherClient/Models/GetErc20Allowance.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/EtherClient/Models/WaitTillTransactionCompleted.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/SwapToken/NativeSwap/Helpers/ApproveSwapProvider.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/SwapToken/NativeSwap/Types/SwapError.swift
> Update handling pending approve() transaction when performing swap #6193

- AlphaWallet/Common/Types/AppStyle.swift
- AlphaWallet/Common/Types/Configuration.swift
> [Refactor] Semantic renaming of variable Colors.dove to Configuration.Color.Semantic.tabBarUnselected.Color.Semantic.tabBarUnselected.

- AlphaWallet/Common/Types/AppStyle.swift
- AlphaWallet/Common/Types/Configuration.swift
- AlphaWallet/Swap/SwapOptions/ViewModels/EditableSlippageViewModel.swift
- AlphaWallet/Tokens/ViewControllers/TokensViewController.swift
- AlphaWallet/Tokens/ViewModels/TokensViewModel.swift
> [Refactor] Configuration.Color.Semantic.searchBar*

- AlphaWallet/Browser/Views/DappBrowserNavigationBar.swift
- AlphaWallet/Common/Types/AppStyle.swift
- AlphaWallet/Common/Types/Configuration.swift
- AlphaWallet/Common/Views/SelfSizingPanelLayout.swift
- AlphaWallet/Extensions/UINavigationController.swift
- AlphaWallet/Extensions/UIViewController.swift
- AlphaWallet/Tokens/ViewControllers/NewTokenViewController.swift
> [Refactor] Configuration.Color.Semantic.navigationBar*

- AlphaWallet/Browser/Views/BrowserErrorView.swift
- AlphaWallet/Common/Types/AppStyle.swift
> [Refactor] Changed Colors.gray to Configuration.Color.Semantic.alternativeText.

- AlphaWalletTests/modules/AlphaWalletCore/URLTests.swift
- AlphaWalletTests/modules/AlphaWalletCore/WebImageUrlTests.swift
- modules/AlphaWalletCore/AlphaWalletCore/URL+Extensions.swift
- modules/AlphaWalletCore/AlphaWalletCore/WebImageURL.swift
> handle receiving ipfs hash without path ipfs// #6271

- modules/AlphaWalletCore/AlphaWalletCore/URL+Extensions.swift
> add replacing ipfs.infura.io with https://alphawallet.infura-ipfs.io #6280

- modules/AlphaWalletCore/AlphaWalletCore/WebImageURL.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/TokenScriptClient/Models/AssetAttributeSyntaxValue.swift
> fix web image urls with whitespaces #6282

- modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/TokensAutodetector/AutoDetectTokensOperation.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/TokensAutodetector/AutoDetectTransactedTokensOperation.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Transactions/EtherscanSingleChainTransactionProvider.swift
> Fix bad access crash for FetchLatestTransactionsOperation, AutoDetectTransactedTokensOperation, FetchLatestTransactionsOperation #6249

- modules/AlphaWalletFoundation/AlphaWalletFoundation/Transactions/EtherscanSingleChainTransactionProvider.swift
> Fix bad access crash for fetchOlderTransactions #6251

- AlphaWalletTests/Factories/FakeSessionsProvider.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/EtherClient/ChainState.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/EtherClient/Models/GetGasPrice.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/Helpers/JsonFromTokenUri.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/Helpers/NonFungibleErc1155JsonBalanceFetcher.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/Logic/Erc1155BalanceFetcher.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/Logic/Erc1155TokenIdsFetcher.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/Models/NonFungibleContract.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/TokensAutodetector/AutoDetectTokensOperation.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/TokensAutodetector/AutoDetectTransactedTokensOperation.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/TokensAutodetector/TokensAutodetector.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Types/SessionsProvider.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/WalletBalance/TokenBalanceFetcher.swift
> Fix memory leaks #6256

- AlphaWallet/Browser/ViewModel/Dapps.swift
If bug:
Fixes #
If not a bug:
Closes #
> Update Dapps.swift with onramper

- AlphaWallet/Accounts/ViewModels/AccountsViewModel.swift
- AlphaWallet/AppCoordinator.swift
- AlphaWalletTests/Coordinators/BackupCoordinatorTests.swift
- AlphaWalletTests/Factories/FakeMultiWalletBalanceService.swift
- AlphaWalletTests/ViewControllers/PaymentCoordinatorTests.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/TokensFilter.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/Types/TokenViewModel.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Types/WalletBalance.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/WalletBalance/WalletBalanceFetcher.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/WalletBalance/WalletBalanceService.swift
> fix crash on accounts screen #6298

- modules/AlphaWalletFoundation/AlphaWalletFoundation/NFT/OpenSea/OpenSea.swift
- modules/AlphaWalletOpenSea/AlphaWalletOpenSea/OpenSea.swift
> add new chains for open sea #6302

- AlphaWallet/Transfer/Views/TransactionConfirmationHeaderView.swift
Removed `fileprivate typealias CFG = Configuration` and replaced `CFG.Color.Semantic.xxx` with `AlphaWallet.Configuration.Color.Semantic.xxx`
> [Refactor] Removed fileprivate typealias CFG = Configuration

- AlphaWallet/WalletConnect/CAIP10AccountProvidable.swift
- AlphaWallet/WalletConnect/Providers/v2/WalletConnectV2Client.swift
- AlphaWallet/WalletConnect/Providers/v2/WalletConnectV2Storage.swift
- Podfile
- Podfile.lock
- modules/AlphaWalletFoundation/AlphaWalletFoundation/EtherClient/Web3.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/KeyManagement/EthereumSigner.swift
- modules/AlphaWalletWeb3/AlphaWalletWeb3/Utils/Web3+Utils.swift
> Update WalletConnect v2 SDK #6183

- AlphaWallet/WalletConnect/Types/WalletConnectServerRequest.swift
> add `eth_signTypedData_v4` as key variation for eth_signTypedData

- AlphaWallet/Common/Types/AppStyle.swift
Remove code that is no longer needed
> [Refactor] Remove code that is no longer needed

- modules/AlphaWalletOpenSea/AlphaWalletOpenSea/OpenSea.swift
> Replace owner param with owner_address for non mainnet chains for open sea. throw an error for not defined chainIds #6360

- AlphaWallet/AlphaWalletHelp/Views/ContactUsBannerView.swift
- AlphaWallet/Backup/ViewModels/PromptBackupWalletAfterExceedingThresholdViewViewModel.swift
- AlphaWallet/Backup/ViewModels/PromptBackupWalletAfterIntervalViewViewModel.swift
- AlphaWallet/Backup/ViewModels/PromptBackupWalletAfterReceivingEtherViewViewModel.swift
- AlphaWallet/Backup/ViewModels/PromptBackupWalletAfterWalletCreationViewViewModel.swift
- AlphaWallet/Browser/ViewModel/BrowserHistoryCellViewModel.swift
- AlphaWallet/Browser/ViewModel/MyDappCellViewModel.swift
- AlphaWallet/Common/Types/AppStyle.swift
- AlphaWallet/Common/Types/Configuration.swift
- AlphaWallet/Common/Views/AddressTextField.swift
- AlphaWallet/Common/Views/Button.swift
- AlphaWallet/Common/Views/ContainerTableViewCell.swift
- AlphaWallet/Common/Views/NumberStepper.swift
- AlphaWallet/Common/Views/TextField.swift
- AlphaWallet/Extensions/RPCServer+Extensions.swift
- AlphaWallet/Tokens/Collectibles/ViewModels/NFTAssetViewModel.swift
- AlphaWallet/Tokens/Collectibles/ViewModels/NonFungibleRowViewModel.swift
- AlphaWallet/Tokens/Collectibles/Views/TokenHistoryChartView.swift
- AlphaWallet/Tokens/ViewModels/OpenSea/OpenSeaNonFungibleTokenCardRowViewModel.swift
- AlphaWallet/Transfer/ViewControllers/ConfigureTransactionViewController.swift
- AlphaWallet/Transfer/Views/ActivityIndicatorControl.swift
- AlphaWallet/Wallet/ViewModels/ImportWalletViewModel.swift
- AlphaWallet/Wallet/ViewModels/SeedPhraseCellViewModel.swift
Changed UIColors into Configuration.Color.Semantic.xxx
> [Refactor] Changed UIColors into Configuration.Color.Semantic.xxx

- AlphaWallet/Tokens/ViewModels/WalletTokenViewCellViewModel.swift
> apply wallet token title formatting on add/hide token page the same as tokens page does #6253

- AlphaWallet/Transfer/ViewControllers/ConfigureTransactionViewController.swift
> fix saving edited tx data value #6393

- AlphaWallet/Transfer/ViewControllers/ConfigureTransactionViewController.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Browser/Factory/WKWebViewConfiguration.swift
> fix sending dapp txs #6394

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet/Activities/ViewControllers/ActivityViewController.swift
- AlphaWallet/Browser/Coordinators/DappBrowserCoordinator.swift
- AlphaWallet/Common/Coordinators/WalletApiCoordinator.swift
- AlphaWallet/Common/Types/Error.swift
- AlphaWallet/Localization/en.lproj/Localizable.strings
- AlphaWallet/Localization/es.lproj/Localizable.strings
- AlphaWallet/Localization/fi.lproj/Localizable.strings
- AlphaWallet/Localization/ja.lproj/Localizable.strings
- AlphaWallet/Localization/ko.lproj/Localizable.strings
- AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings
- AlphaWallet/Transfer/Coordinators/SignMessageCoordinator.swift
- AlphaWallet/WalletConnect/Controllers/SignMessageCoordinatorBridgeToPromise.swift
- AlphaWallet/WalletConnect/Types/WalletConnect.swift
- AlphaWallet/WalletConnect/Types/WalletConnectEip712v3And4Validator.swift
- AlphaWallet/WalletConnect/WalletConnectProvider.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Analytics/AnalyticsTypes.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/EtherClient/EIP712TypedData.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Types/SignMessageValidator.swift
> Check that chain ID in EIP-712 message is the same as the current/enabled chain before showing user the prompt to sign it #6330

- AlphaWallet/Common/Services/MediaContentDownloader.swift
- AlphaWallet/Common/Views/TokenImageView.swift
- AlphaWallet/Common/Views/ViewModels/AVPlayerViewModel.swift
- AlphaWallet/Common/Views/ViewModels/WebImageViewModel.swift
- AlphaWallet/Common/Views/WebImageView.swift
- AlphaWallet/Tokens/Collectibles/ViewModels/NFTAssetViewModel.swift
- AlphaWallet/Tokens/Collectibles/ViewModels/NonFungibleRowViewModel.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/EtherClient/Models/ContractMethodCalls/Erc721TokenUriMethodCall.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/MediaContentDownloader/Base64Decoder.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/NFT/OpenSea/Types/NonFungibleFromJson+Extension.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/Helpers/JsonFromTokenUri.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/Helpers/NonFungibleErc1155JsonBalanceFetcher.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/Models/NonFungibleContract.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/TokenImageFetcher.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/Types/TokenHolder.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/WalletBalance/TokenBalanceFetcher.swift
> handle base64 as response from tokenURI #6284

- AlphaWallet/Settings/Coordinators/EnabledServersCoordinator.swift
- AlphaWallet/Settings/ViewControllers/EnabledServersViewController.swift
- AlphaWallet/Settings/ViewModels/EnabledServersViewModel.swift
- AlphaWallet/Settings/Views/EnableServersHeaderView.swift
- AlphaWallet/WalletConnect/Providers/v2/WalletConnectV2Provider.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Settings/Types/Config.swift
> Remove mutually exclusive mode for mainnet and testnet #6034

- AlphaWallet/Settings/ViewControllers/ChooseSendPrivateTransactionsProviderViewController.swift
- AlphaWallet/Settings/ViewControllers/EnabledServersViewController.swift
> Make Mainnet/testnet headers in Enable Networks sticky #6424

- AlphaWallet/BuyCrypto/SelectServiceToBuyCryptoCoordinator.swift
- AlphaWallet/Swap/SelectServiceToSwapCoordinator.swift
> Fix crash when displaying swap, buy crypto popups #6444

- AlphaWallet/ActiveWalletCoordinator.swift
- AlphaWallet/WalletConnect/Providers/v1/WalletConnectV1Client.swift
- AlphaWallet/WalletConnect/WalletConnectProvider.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Browser/Types/DappCommand.swift
> Fix broken reloading of wallet connect session when switching rpc server #6377

- AlphaWallet/Browser/ViewControllers/BrowserViewController.swift
- Podfile
- Podfile.lock
> Pass dictionary instead of just a string as failure dapp callback #6467

- AlphaWalletTests/Market/DeepLinkTests.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Types/DeepLink.swift
> handle receiving wallet connect url with `awallet` scheme value #6466

- AlphaWallet/Transfer/ViewControllers/ConfigureTransactionViewController.swift
> [Refactoring] Extract function the code to shift focus to next textfield so it's in 1 place #6447

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet/Activities/ViewControllers/ActivityViewController.swift
- AlphaWallet/Activities/Views/DefaultActivityItemViewCell.swift
- AlphaWallet/Common/Views/AVPlayerView.swift
- AlphaWallet/Common/Views/ImageView.swift
- AlphaWallet/Common/Views/SelectCurrencyButton.swift
- AlphaWallet/Common/Views/TokenImageView.swift
- AlphaWallet/Common/Views/ViewModels/WebImageViewModel.swift
- AlphaWallet/Common/Views/ViewRounding.swift
- AlphaWallet/Common/Views/WebImageView.swift
- AlphaWallet/Tokens/Collectibles/Views/Erc875NonFungibleRowView.swift
- AlphaWallet/Tokens/Collectibles/Views/NFTPreviewView.swift
- AlphaWallet/Tokens/Collectibles/Views/NonFungibleRowView.swift
- AlphaWallet/Tokens/TokenCardTableViewCellFactory.swift
- AlphaWallet/Tokens/Views/EthTokenViewCell.swift
- AlphaWallet/Tokens/Views/FungibleTokenViewCell.swift
- AlphaWallet/Tokens/Views/NonFungibleTokenViewCell.swift
- AlphaWallet/Tokens/Views/OpenSea/OpenSeaNonFungibleTokenViewCell.swift
- AlphaWallet/Tokens/Views/PopularTokenViewCell.swift
- AlphaWallet/Tokens/Views/TokenCardWebView.swift
- AlphaWallet/Tokens/Views/WalletTokenViewCell.swift
> make loading indicator with 0 alpha to hide it #6459

- AlphaWalletTests/Activitities/FakeActivitiesService.swift
Added missing function that prevented `make test` from working.
> Added missing function to FakeActivitiesService

- AlphaWallet/Accounts/Coordinators/AccountsCoordinator.swift
- AlphaWallet/Accounts/ViewControllers/AccountsViewController.swift
- AlphaWallet/Browser/Coordinators/DappBrowserCoordinator.swift
- AlphaWallet/Redeem/ViewModels/TokenCardRedemptionViewModel.swift
- AlphaWallet/Tokens/Collectibles/ViewModels/NFTCollectionViewModel.swift
- AlphaWallet/Tokens/Views/TokenInstanceWebView.swift
- AlphaWallet/Transfer/Coordinators/PaymentCoordinator.swift
- AlphaWallet/WalletConnect/WalletConnectProvider.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Backup/PromptBackup.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/BlockscanChat/BlockscanChatService.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/EtherClient/Wallet.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/KeyManagement/EtherKeystore.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/KeyManagement/LegacyFileBasedKeystore.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/Helpers/TokenInstanceActionAdapter.swift
Forgot to add. Expected the PR to be harmless. It doesn't provide any way to add/store or use a hardware wallet.
> Add `WalletType.hardware` enum-case for future use

- AlphaWallet/Redeem/ViewControllers/TokenCardRedemptionViewController.swift
- AlphaWallet/Redeem/ViewModels/TokenCardRedemptionViewModel.swift
- AlphaWallet/Sell/ViewModels/GenerateSellMagicLinkViewModel.swift
- AlphaWallet/Sell/ViewModels/GenerateTransferMagicLinkViewModel.swift
- AlphaWallet/Tokens/Collectibles/Coordinators/NFTCollectionCoordinator.swift
- AlphaWallet/Transfer/Coordinators/SignMessageCoordinator.swift
- AlphaWalletTests/EtherClient/EtherKeystoreTests.swift
- AlphaWalletTests/Market/OrderSigningTests.swift
- AlphaWalletTests/Redeem/CreateRedeemTests.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/KeyManagement/EtherKeystore.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/KeyManagement/Keystore.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Market/OrderHandler.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Redeem/SignatureHelper.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Transfer/SendTransaction.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/UniversalLink/MagicLinkGenerator.swift
Follow up to #6509 and #6510
This should be the last PR that modifies signing to help support upcoming hardware wallet signing supporting
> Modify signing func(s) so they are async. Also include upstream callers as they propogate. Almost a refactoring

- AlphaWallet/Localization/en.lproj/Localizable.strings
- AlphaWallet/Localization/es.lproj/Localizable.strings
- AlphaWallet/Localization/fi.lproj/Localizable.strings
- AlphaWallet/Localization/ja.lproj/Localizable.strings
- AlphaWallet/Localization/ko.lproj/Localizable.strings
- AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings
- AlphaWallet/Transfer/Coordinators/SignMessageCoordinator.swift
> Tweak error message for sign message validation error #6512

- AlphaWallet/WalletConnect/CAIP10AccountProvidable.swift
- AlphaWallet/WalletConnect/Providers/v2/WalletConnectV2Provider.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Types/eip155URLDecoder.swift
fixes receiving wallet connect v2 request for non supported chain, updated with rejecting such request
> replace creating RpcServer with `chainIdOptional` to avoid fallback to mainnet, wallet connect v2

- AlphaWallet/Common/Types/Error.swift
- AlphaWallet/WalletConnect/CAIP10AccountProvidable.swift
- AlphaWallet/WalletConnect/Providers/v1/WalletConnectV1Provider.swift
- AlphaWallet/WalletConnect/Providers/v2/WalletConnectV2Provider.swift
- AlphaWallet/WalletConnect/Providers/v2/WalletConnectV2Types.swift
- AlphaWallet/WalletConnect/Types/WalletConnect.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/ENS/GetEnsTextRecord.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Types/eip155URLDecoder.swift
> [Refactoring] refactor CAIP10AccountProvidable, rename Eip155UrlCoder

- AlphaWallet/Activities/ViewControllers/ActivityViewController.swift
- AlphaWallet/Activities/Views/DefaultActivityItemViewCell.swift
- AlphaWallet/Common/Views/AVPlayerView.swift
- AlphaWallet/Common/Views/RoundedEnsView.swift
- AlphaWallet/Common/Views/SelectCurrencyButton.swift
- AlphaWallet/Common/Views/TokenImageView.swift
- AlphaWallet/Common/Views/ViewRounding.swift
- AlphaWallet/Common/Views/WebImageView.swift
- AlphaWallet/Tokens/Collectibles/Views/FungibleTokenHeaderView.swift
- AlphaWallet/Tokens/Collectibles/Views/NFTPreviewView.swift
- AlphaWallet/Tokens/Views/EthTokenViewCell.swift
- AlphaWallet/Tokens/Views/FungibleTokenViewCell.swift
- AlphaWallet/Tokens/Views/NonFungibleTokenViewCell.swift
- AlphaWallet/Tokens/Views/PopularTokenViewCell.swift
- AlphaWallet/Tokens/Views/TokenCardWebView.swift
- AlphaWallet/Tokens/Views/WalletTokenViewCell.swift
> make token image placeholder as circle #6546

- modules/AlphaWalletFoundation/AlphaWalletFoundation/Settings/Types/RPCServers.swift
> tweak okc transaction details url

- AlphaWalletTests/Coordinators/ActiveWalletViewTests.swift
> Added dummy dataTask function to FakeNetworkService to make it comply with NetworkService Protocol

- AlphaWallet/ActiveWalletCoordinator.swift
- AlphaWallet/Settings/Coordinators/CheckTransactionStateCoordinator.swift
- AlphaWallet/Settings/Coordinators/PingInfuraCoordinator.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/EtherClient/ChainStateSchedulerProvider.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/GasPriceEstimator/GasPriceEstimator.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/GasPriceEstimator/Models/EtherscanGasPriceEstimator.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/RPC/BlockchainProvider.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/TokenScriptClient/EventForActivitiesFetcher.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Transactions/PendingTransaction/PendingTransactionSchedulerProvider.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Transfer/SendTransaction.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Transfer/TransactionConfigurator.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/WalletBalance/TokenBalanceFetcher.swift
updates to move making a rpc calls via async tasks caused additional crashes, revet it back for now
> revert moving to async

- modules/AlphaWalletFoundation/AlphaWalletFoundation/Settings/Types/RPCServers.swift
> Fix: Not fetching ERC721 transaction history and auto-detecting ERC721 tokens on Polygon Mumbai

- modules/AlphaWalletFoundation/AlphaWalletFoundation/RPC/CallSmartContractFunction.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Settings/Types/Constants+Credentials.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Types/RPCServers.swift
> [RPC] Switch RPC node provider for Klaytn Cypress and Baobab

- modules/AlphaWalletFoundation/AlphaWalletFoundation/NFT/Enjin/Enjin.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/NFT/Enjin/EnjinNetworking.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/NFT/Enjin/EnjinUserManagementInterceptor.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/NFT/NFTProvider.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Settings/Types/Constants+Credentials.swift
> Make enjinUserName and enjinUserPassword nil #6603

- AlphaWallet/Tokens/Coordinators/NewTokenCoordinator.swift
- AlphaWallet/Tokens/ViewControllers/NewTokenViewController.swift
- AlphaWallet/Tokens/ViewModels/NewTokenViewModel.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/TokenScriptClient/Models/TokenScriptSupportable.swift
> set valid token balance when importing nonfungible token #4937

- modules/AlphaWalletFoundation/AlphaWalletFoundation/Initializers/MigrationInitializerForOneChainPerDatabase.swift
> remove GasPriceObject from list of objectTypes for MigrationInitializerForOneChainPerDatabase

- modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/Logic/GetContractInteractions.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Transactions/ApiNetworking.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Transactions/Covalent/CovalentApiNetworking.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Transactions/Oklink/OklinkNetworking.swift
> log failure respponse for api provider #6602

- Podfile
- Podfile.lock
Updated KingFisher to version 7.6.2. Added missing imports Xcode 14.3 was complaining about.
> Modifications to project to allow compilation under Xcode 14.3

- AlphaWallet/Resources/tokens.json
Closes #6447
Checked out `Tokens` repo. Followed instructions for steps 1-4. Copied `tokens.json` file into `alpha-wallet-ios` resources folder. All tests passed. App appears to run on simulator under 16.2 without issue.
> Updated Tokens.json file

- AlphaWallet/Accounts/ViewModels/WalletSummaryViewModel.swift
- AlphaWallet/Tokens/Collectibles/ViewModels/FungibleTokenHeaderViewModel.swift
- AlphaWallet/Tokens/ViewModels/EthTokenViewCellViewModel.swift
- AlphaWallet/Tokens/ViewModels/FungibleTokenViewCellViewModel.swift
> remove extra sign from percentageChange24h #6662

- modules/AlphaWalletFoundation/AlphaWalletFoundation/SwapToken/NativeSwap/Helpers/SwapOptionsConfigurator.swift
Closes #6543 
Before | After
-|-
> Sorted session in SwapOptionsConfigurator to show mainnets first and testnets last.

- AlphaWallet/Accounts/ViewModels/WalletSummaryViewModel.swift
- AlphaWallet/Activities/ViewControllers/ActivitiesViewController.swift
- AlphaWallet/Tokens/Collectibles/ViewModels/NFTAssetSelectionViewModel.swift
- AlphaWallet/Tokens/ViewControllers/TokensViewController.swift
- AlphaWallet/Tokens/ViewModels/AddHideTokensViewModel.swift
- AlphaWallet/Tokens/ViewModels/TokensViewModel.swift
- AlphaWallet/Tokens/Views/AddHideTokenSectionHeaderView.swift
- AlphaWallet/Transactions/ViewModels/TransactionsViewModel.swift
- AlphaWallet/WhatsNew/ViewModels/WhatsNewViewModels.swift
- modules/AlphaWalletAddress/AlphaWalletAddress/Extensions/Data+Extensions.swift
- modules/AlphaWalletENS/AlphaWalletENS/ENS.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Activities/ActivitiesService.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Activities/ActivityCollection.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/EtherClient/Models/ContractMethodCalls/AssetAttributeMethodCall.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Networking/NetworkService.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Settings/Models/AddCustomChain.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/SwapToken/QuickSwap/QuickSwap.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/SwapToken/Uniswap/Uniswap.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/TokenScriptClient/EventSource.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/TokenScriptClient/EventSourceForActivities.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/TokenScriptClient/Models/TokenScriptSignatureVerifier.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/Logic/Erc1155TokenIdsFetcher.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/Logic/GetContractInteractions.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/Types/TokensDataStore.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Transactions/ErcTokenDetector.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Transactions/Storage/TransactionsStorage.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Types/DeepLink.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Types/Session.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/WalletBalance/TokenBalanceFetcher.swift
> [Refactor] Changed class to enum for functional{}

- modules/AlphaWalletFoundation/AlphaWalletFoundation/TokenScriptClient/EventSource.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/TokenScriptClient/EventSourceForActivities.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/Logic/Erc1155TokenIdsFetcher.swift
> reduce eth_log calls from event log send event logs for activities #6540

- AlphaWallet/Transfer/ViewModels/EditLegacyGasPriceViewModel.swift
- AlphaWallet/Transfer/ViewModels/EditTransactionViewModel.swift
- AlphaWallet/Transfer/ViewModels/SlidableTextFieldViewModel.swift
- AlphaWallet/Transfer/Views/SlidableTextField.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/Eip681UrlResolver.swift
> Fix losing precision when editing gasprice, gasLimit #6680

- modules/AlphaWalletFoundation/AlphaWalletFoundation/EtherClient/TransactionSigning.swift
Signing is critical functionality. Refactoring it so it's clearer and easier to follow.
> [Refactoring] Move functions that don't operate on state into `functional` enum for signing related functionality

- AlphaWalletTests/Transfer/Controllers/TransactionConfiguratorTests.swift
> Fix: broken test suite #6699

- AlphaWallet/Browser/ViewModel/Dapps.swift
If bug:
Fixes #
If not a bug:
Closes #
Adds Verse DEX to Dapps.swift
> add Verse DEX to Dapps.swift

- .swiftformat
- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWalletTests/Core/HostBasedTokenUriMapperTests.swift
- AlphaWalletTests/Foundation/EtherNumberFormatterTests.swift
- AlphaWalletTests/Tokens/TokensDataStoreTest.swift
- modules/AlphaWalletENS/AlphaWalletENS/ENS.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Types/RPCServers.swift
- resources/SwiftFormatFiles.xcfilelist
Initial SwiftFormat testing.
1. [sortedImports], removed [trailing spaces] (empty lines) ![image](https://user-images.githubusercontent.com/1050309/232385740-fa569c9e-a1de-42bd-a3e4-898774bcef72.png) 
2. [trailing comma] ![image](https://user-images.githubusercontent.com/1050309/232386563-6f00067a-44b4-4401-8e1e-04f44acaaa14.png) 
3. [indent] ![image](https://user-images.githubusercontent.com/1050309/232387248-f5d9a247-7962-41ed-938d-72242ffaac45.png)
> Initial SwiftFormat tests

- modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/Helpers/JsonFromTokenUri.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/Models/NonFungibleContract.swift
> move mapping tokens uri to Json From TokenUri, and make calls synchronized #6678

- modules/AlphaWalletENS/AlphaWalletENS/ENS.swift
Re-formating to fix indentation after SwiftFormat as described in https://github.com/AlphaWallet/alpha-wallet-ios/pull/6686#issuecomment-1512414432
> [Chore] Code formatting

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet.xcworkspace/xcshareddata/swiftpm/Package.resolved
- AlphaWallet/AddMultipleCustomRpc/AddMultipleCustomRpcViewController.swift
- AlphaWallet/Common/ViewModels/AcceptWalletConnectSessionViewModel.swift
- AlphaWallet/Settings/Coordinators/SaveCustomRpcCoordinator.swift
- AlphaWallet/WalletConnect/CAIP10AccountProvidable.swift
- AlphaWallet/WalletConnect/Providers/v2/WalletConnectV2Client.swift
- AlphaWallet/WalletConnect/Providers/v2/WalletConnectV2Provider.swift
- AlphaWallet/WalletConnect/Providers/v2/WalletConnectV2Storage.swift
- AlphaWallet/WalletConnect/Providers/v2/WalletConnectV2Types.swift
- AlphaWallet/WalletConnect/Types/WalletConnect.swift
- AlphaWallet/WalletConnect/WalletConnectProvider.swift
- Podfile
- Podfile.lock
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Browser/Types/DappCommand.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Settings/Models/AddCustomChain.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Settings/Models/AddCustomChainNetworking.swift
> update WalletConnect v2 to 1.5.1 version, to support optionalNamespaces #6572

- AlphaWallet/Browser/Coordinators/QRCodeResolutionCoordinator.swift
- AlphaWallet/Browser/Coordinators/ScanQRCodeCoordinator.swift
- AlphaWallet/Tokens/Coordinators/TokensCoordinator.swift
- AlphaWallet/Wallet/Coordinators/WalletCoordinator.swift
> fix displaing qrcode scanner when importing a new wallet #6618

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet/AppCoordinator.swift
- AlphaWalletTests/Factories/FakeTokenGroupIdentifier.swift
- AlphaWalletTests/Tokens/TokenGroupIdentifierTest.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/JSON/TokenGroupIdentifier.swift
> replace Bundle.main.path() with R.file.tokensJson() for TokenJsonReader #6646

- AlphaWalletFoundation.podspec
- Podfile.lock
> Upgrade `RealmSwift` pod so project archives with Xcode 14.1/14.2/14.3 #6689

- AlphaWallet/Common/Views/SelectCurrencyButton.swift
> adjust token symbol for enter crypto amount view #6577

- .swiftformat
- AlphaWalletTests/Core/HostBasedTokenUriMapperTests.swift
- AlphaWalletTests/Foundation/EtherNumberFormatterTests.swift
- AlphaWalletTests/Tokens/Helpers/TokenAdaptorTest.swift
- AlphaWalletTests/Tokens/TokensDataStoreTest.swift
- modules/AlphaWalletENS/AlphaWalletENS/ENS.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Types/RPCServers.swift
Added the rules mentioned in https://github.com/AlphaWallet/alpha-wallet-ios/issues/6583#issuecomment-1521104075
> Enabled additional rules for SwiftFormat

- AlphaWallet/ActiveWalletCoordinator.swift
- AlphaWallet/Browser/Coordinators/DappBrowserCoordinator.swift
- AlphaWallet/Browser/ViewControllers/BrowserViewController.swift
- AlphaWallet/Browser/ViewModel/BrowserViewModel.swift
- AlphaWallet/Common/Types/AppStyle.swift
- AlphaWallet/Common/Views/NavigationController.swift
> Should not be possible to go dapp browser home screen after opening browser in read-only mode #6613

- AlphaWallet/Common/Views/EmptyView.swift
- AlphaWallet/Tokens/ViewControllers/AddHideTokensViewController.swift
> Fix AddHideToken empty view adjustment #6490

- AlphaWallet/AppDelegate.swift
> fix build warnings #6759

- modules/AlphaWalletFoundation/AlphaWalletFoundation/Initializers/DatabaseMigration.swift
> remove unused method #6761

- modules/AlphaWalletFoundation/AlphaWalletFoundation/EtherClient/BlockchainParams.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/GasPriceEstimator/LegacyGasPriceEstimator.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/GasPriceEstimator/Models/EtherscanGasPriceEstimator.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/RPC/BlockchainProvider.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Transfer/Types/GasPriceConfiguration.swift
> xDai chain should use gas price estimate returned from RPC node with eth_gasPrice #6550

- AlphaWallet/BuyCrypto/BuyCryptoUsingThirdPartyCoordinator.swift
- AlphaWallet/BuyCrypto/SelectServiceToBuyCryptoCoordinator.swift
> move buyCrypto url to open in the app browser with selecting browser tab #5448

- AlphaWallet/ActiveWalletCoordinator.swift
- AlphaWallet/Localization/en.lproj/Localizable.strings
- AlphaWallet/Localization/es.lproj/Localizable.strings
- AlphaWallet/Localization/fi.lproj/Localizable.strings
- AlphaWallet/Localization/ja.lproj/Localizable.strings
- AlphaWallet/Localization/ko.lproj/Localizable.strings
- AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings
- AlphaWallet/Swap/Swap/SwapTokensCoordinator.swift
- AlphaWallet/Transactions/Coordinators/ReplaceTransactionCoordinator.swift
- AlphaWallet/Transfer/Collectibles/Coordinators/TransferCollectiblesCoordinator.swift
- AlphaWallet/Transfer/Coordinators/SendCoordinator.swift
- AlphaWallet/Transfer/Coordinators/TokenScriptCoordinator.swift
- AlphaWallet/Transfer/Coordinators/TransactionInProgressCoordinator.swift
- AlphaWallet/Transfer/Coordinators/TransferNFTCoordinator.swift
- AlphaWallet/Transfer/ViewControllers/ConfigureTransactionViewController.swift
- AlphaWallet/Transfer/ViewModels/ConfigureTransactionViewModel.swift
- AlphaWallet/Transfer/ViewModels/TransactionConfirmation/CancelTransactionViewModel.swift
- AlphaWallet/Transfer/ViewModels/TransactionInProgressViewModel.swift
- AlphaWallet/WalletConnect/Controllers/TransactionInProgressCoordinatorBridgeToPromise.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/GasPriceEstimator/LegacyGasPriceEstimator.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Transfer/Types/GasPriceWarning.swift
> Some references to the word "Ethereum" in our localized strings files should be parameterized #6681

- AlphaWallet/Transfer/ViewModels/ConfigureTransactionViewModel.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Transfer/eip1559/SuggestEip1559.swift
> display gas price warning popup for selected configuration #5533

- AlphaWallet/Common/Views/ButtonsBar/ButtonsBarBackgroundView.swift
- AlphaWallet/Common/Views/ButtonsBar/VerticalButtonsBar.swift
- AlphaWallet/Wallet/ViewControllers/CreateInitialWalletViewController.swift
- AlphaWallet/Wallet/ViewControllers/ImportWalletViewController.swift
- AlphaWallet/Wallet/ViewControllers/SeedPhraseBackupIntroductionViewController.swift
- AlphaWallet/Wallet/ViewControllers/ShowSeedPhraseViewController.swift
- AlphaWallet/Wallet/ViewControllers/VerifySeedPhraseViewController.swift
- AlphaWallet/Wallet/ViewModels/ImportWalletViewModel.swift
> place VerticalButtonsBar in ButtonsBarBackgroundView to make all buttons to be aligned with same height #4500

- AlphaWallet/Browser/Coordinators/QRCodeResolutionCoordinator.swift
- AlphaWallet/Wallet/Coordinators/WalletCoordinator.swift
> add ability to restrict qrcode resolutions #3787

- AlphaWallet/Settings/ViewModels/ConsoleViewModel.swift
> remove duplicate messages on console screen, those caused app crash #6788

- AlphaWallet.xcodeproj/project.pbxproj
> Unchecked show environment variables to reduce noise in build log

- AlphaWalletAddress.podspec
- AlphaWalletCore.podspec
- AlphaWalletENS.podspec
- AlphaWalletFoundation.podspec
- AlphaWalletGoBack.podspec
- AlphaWalletHardwareWallet.podspec
- AlphaWalletLogger.podspec
- AlphaWalletOpenSea.podspec
- AlphaWalletTrackAPICalls.podspec
- AlphaWalletTrustWalletCoreExtensions.podspec
- AlphaWalletWeb3.podspec
- Podfile.lock
- modules/AlphaWalletFoundation/AlphaWalletFoundation/CoinTicker/Types/CoinTicker.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Foundation/Formatter.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/UniversalLink/UniversalLinkService.swift
> Update AlphaWallet pods to swift 5.0

- modules/AlphaWalletFoundation/AlphaWalletFoundation/Transactions/BlockscoutApiNetworking.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Transactions/FallbackApiNetworking.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Transactions/SingleChainTransactionProvider.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Transactions/TransactionProvider/TransactionPaginationFilter.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Transactions/TransactionsService.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Transactions/Types/GetTransactionsRequest.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Types/RPCServers.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Types/SessionsProvider.swift
> Split Etherscan and Blockscout on two independent networkings #6792

- AlphaWalletTests/Factories/WalletSession.swift
- AlphaWalletTests/modules/AlphaWalletFoundation/Types/RPCServerTests.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/GasPriceEstimator/LegacyGasPriceEstimator.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/GasPriceEstimator/Models/EtherscanGasPriceEstimator.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/Logic/EtherscanCompatibleApiNetworking.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Transactions/ApiNetworking.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Transactions/BlockscoutApiNetworking.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Transactions/Covalent/CovalentApiNetworking.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Transactions/FallbackApiNetworking.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Transactions/Oklink/OklinkNetworking.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Transactions/SingleChainTransactionProvider.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Transfer/TransactionConfigurator.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Types/RPCServers.swift
> Move gasoracle api to api networking

- AlphaWallet/Settings/ViewControllers/SaveCustomRpcBrowseViewController.swift
- AlphaWallet/Settings/ViewControllers/SaveCustomRpcManualEntryViewController.swift
- AlphaWallet/Settings/ViewControllers/SaveCustomRpcOverallViewController.swift
- AlphaWallet/Settings/Views/SaveCustomRpcManualEntryView.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Rpc Network/SaveCustomRpcManualEntryViewModel.swift
| Before PR | After PR |
|----|----|
| <img width="300" alt="Screenshot 2023-05-10 at 15 16 07" src="https://github.com/AlphaWallet/alpha-wallet-ios/assets/96283950/e2aebe40-9b05-496b-9f7f-fe404989cdad"> | <img width="300" alt="Screenshot 2023-05-10 at 15 12 10" src="https://github.com/AlphaWallet/alpha-wallet-ios/assets/96283950/608448ef-82bd-4aff-bcca-5810fe7f3025"> |
| <img width="300" alt="Screenshot 2023-05-10 at 15 16 23" src="https://github.com/AlphaWallet/alpha-wallet-ios/assets/96283950/42716d9e-6053-4f24-84b0-bf89835d7918"> | <img width="300" alt="Screenshot 2023-05-10 at 15 12 21" src="https://github.com/AlphaWallet/alpha-wallet-ios/assets/96283950/0ebf4863-d8f8-4c92-a18d-ff7b38929a89"> |
| <img width="300" alt="Screenshot 2023-05-10 at 15 16 01" …
> disable adjusting add network button when keyboard appears, snap it at the views bottom

- .travis.yml
> Update Travis to use iOS 16.2 and Xcode 14.2

- modules/AlphaWalletFoundation/AlphaWalletFoundation/Types/RPCServers.swift
> set nil apiKey for goerli, polygon_testnet

- AlphaWallet/Transactions/Coordinators/ReplaceTransactionCoordinator.swift
Small refactoring. Didn't mean to move code around unnecessarily, but hope to show what could be better.
> [Refactoring] Move function into same-file extension, reads better

- modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/Logic/EtherscanCompatibleApiNetworking.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Transactions/ApiTransporter.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Types/SessionsProvider.swift
> add requests retrying when receive 403 error code for .goerli, .mumbai_testnet

- AlphaWallet/Transactions/Coordinators/ReplaceTransactionCoordinator.swift
> increase priority fee when speeding up or cancelling transaction  #6822

- modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/AlphaWalletTokensService.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/TokensService.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/WalletBalance/WalletBalanceFetcher.swift
- Fire reloading token balance once server enabled or disabled;
- stop reload tokens balance scheduler when app enters in background state.
> improve reloading token balance

- AlphaWallet/Common/Services/FirebaseReportService.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/AlphaWalletTokensService.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/ClientSideTokenSourceProvider.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/Logic/ContractDataDetector.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/TokenRepairService.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/TokensAutodetector/ImportToken.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/TokensService.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/Types/DeletedContract.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/Types/TokensDataStore.swift
> Implement token repair service #5135

- AlphaWallet/Tokens/Collectibles/ViewModels/NFTAssetViewModel.swift
- AlphaWallet/Tokens/NftAssetDisplayHelper.swift
- AlphaWallet/Tokens/Views/TokenInstanceWebView.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Activities/ActivitiesService.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Extensions/Publishers/Promise+Publishers.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Foundation/Subscribable.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/TokenScriptClient/Models/AssetAttributeMapping.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/TokenScriptClient/Models/AssetAttributeSyntax.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/TokenScriptClient/Models/AssetAttributeValues.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/TokenScriptClient/Models/AssetInternalValue.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/TokenScriptClient/Models/CallForAssetAttributeProvider.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/TokenScriptClient/Models/FunctionOrigin.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/TokenScriptClient/TokenScript+UI.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/Helpers/TokenAdaptor.swift
pr fixes attributes resolving memory leaks for token script
> tokenscript attributes memory leak

- modules/AlphaWalletFoundation/AlphaWalletFoundation/Types/RPCServers.swift
> Fix: tapping on native token icon in token screen doesn't open Etherscan/blockchain explorer page correctly #6846

- AlphaWallet/Tokens/Coordinators/TokensCoordinator.swift
- AlphaWallet/Tokens/ViewControllers/AttestationViewController.swift
- modules/AlphaWalletAttestation/AlphaWalletAttestation/Attestation.swift
> [Attestation] Import attestation even if the issuer key is not trusted and show an indicator

- AlphaWallet/Tokens/Coordinators/TokensCoordinator.swift
- AlphaWalletTests/modules/AlphaWalletAttestation/AttestationTest.swift
- modules/AlphaWalletAttestation/AlphaWalletAttestation/EasAttestation.swift
> [Attestation] Support newer message version #6954

- README.md
If bug:
Fixes #
If not a bug:
Closes #
> Fixed typos README.md
