AlphaWallet/alpha-wallet-ios

- AlphaWallet/AssetDefinition/AssetAttribute.swift
- AlphaWallet/AssetDefinition/XMLHandler.swift
- AlphaWallet/Transactions/Coordinators/TicketsCoordinator.swift
Stumbled on this while looking at kitties.
With this PR, from a few random sampling, ticket list takes 20-30% less time to appear.
* Removed some extraneous back-and-forth conversion between token ID's integral and string forms
* Removed some unnecessary code that complicates the logic for XML parsing
> Reduce time taken from tapping ticket token in wallet to ticket list appearing

- AlphaWallet/AssetDefinition/XMLHandler.swift
- AlphaWallet/Tokens/ViewControllers/StaticHTMLViewController.swift
Similar to #567, removing/replacing the `try!`(s) with `try?` where it's reasonable for the app to continue running and not crash.
There are still many uses of `try!` that are kept around, but those are datastore/keystore access. Those are still preserved because there isn't an easy way for the app to continue to run.
> Remove unnecessary try! where it's possible to continue to reduce crashes

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet/Localization/en.lproj/Localizable.strings
- AlphaWallet/Localization/es.lproj/Localizable.strings
- AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings
- AlphaWallet/Tokens/ViewControllers/NewTokenViewController.swift
- AlphaWallet/Transfer/ViewControllers/CanScanQRCode.swift
- AlphaWallet/Transfer/ViewControllers/SendViewController.swift
- AlphaWallet/Transfer/ViewControllers/TransferTicketsViaWalletAddressViewController.swift
- AlphaWallet/Wallet/ViewControllers/ImportWalletViewController.swift
For #569.
This PR, will upon tapping camera icon (various screens, including add a token) and if camera access is already denied previously:
1. Show a dialog with explanation
2. User taps button in dialog to switch to the Settings app where they can just tap a switch to enable access.
3. User launch to app again and re-try what they were doing.
@James-Sangalli iOS, unfortunately, kills the app after camera access is changed, so the user will have to manually launch the app again, navigate to where they were (e.g sending ETH) and repeat their process. Ideally, we should track where they were (what they have entered so far) and try our best to let the user resume. But there are 4 screens where this is needed. So if this is important, create an issue :)
> Prompt user to go to Settings app, with explanation, while trying to scan QR code, if camera access was denied previously.

- AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings
Please help translate this dialog which pops up when a user has already denied access to the camera and then the user tries to scan a QR code. There are 3 pieces:
Title https://github.com/alpha-wallet/alpha-wallet-ios/blob/master/AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings#L278
Multi-line description https://github.com/alpha-wallet/alpha-wallet-ios/blob/master/AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings#L279
"Open Settings" button title https://github.com/alpha-wallet/alpha-wallet-ios/blob/master/AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings#L280
Done
> Fixed Issue #582

- .travis.yml
With this PR, tests should still fail, but at least Travis will give a hint of which test(s) failed.
> Executed 161 tests, with 1 failure (0 unexpected) in 3.722 (4.230) seconds
> Failing tests:
>	InCoordinatorTests.testShowRequstFlow()
> ** TEST FAILED **
> Run tests on Travis directly with `xcodebuild` instead of fastlane

- AlphaWallet/Sell/Views/AmountTextField.swift
- AlphaWallet/Transfer/ViewControllers/SendViewController.swift
- AlphaWallet/Transfer/ViewModels/SendHeaderViewViewModel.swift
- AlphaWallet/Transfer/Views/SendHeaderView.swift
For #642.
This PR fixes these bugs introduced in an earlier commit:
* Should not display equivalent value (and appreciation/change) in ETH
* Should not show ETH button
* Should not show equivalent fiat value
> Fixes broken send ERC 20 UI

- AlphaWallet/Info.plist
> Disable iTunes File Sharing for overriding asset definition

- AlphaWallet/Browser/Factory/WKWebViewConfiguration.swift
For #665
I found 3 instances where it's affected (not sure if there're more):
1. "CONNECT USING TRUST" -> "CONNECT VIA WEB3"
2. "Connect with Trust" + icon. -> "Connect with" (**no wallet name**!) + What looks like the Metamask icon
3. "Please set Trust to use Main Network" -> "Please set web3 to use Main Network".
@James-Sangalli not sure if it's good to merge?
**Update**: Also because this PR clears the `isTrust` flag it *might* break dapps that check for it.
---
It looks like a more "proper" integration involves:
> Using an Ethereum wallet makes it easy to make trades on the go. When we announced #airswapgo we decided to build for mobile out of the box. Try it today using a mobile wallet like Trust Wallet. If you’re an Ethereum wallet developer, we’d love to collaborate. Reach us at …
> Clear web3.currentProvider.isTrust so AirSwap prompts don't mention Trust

- AlphaWallet/Tokens/Coordinators/GetBalanceCoordinator.swift
- AlphaWallet/Tokens/Coordinators/GetDecimalsCoordinator.swift
- AlphaWallet/Tokens/Coordinators/GetERC721BalanceCoordinator.swift
- AlphaWallet/Tokens/Coordinators/GetERC875BalanceCoordinator.swift
- AlphaWallet/Tokens/Coordinators/GetIsERC721ContractCoordinator.swift
- AlphaWallet/Tokens/Coordinators/GetIsERC875ContractCoordinator.swift
- AlphaWallet/Tokens/Coordinators/GetNameCoordinator.swift
- AlphaWallet/Tokens/Coordinators/GetSymbolCoordinator.swift
- Podfile
- Podfile.lock
For #674 
This PR makes use of the Promise for making RPC calls instead of waiting for it, blocking the executing thread. This involves using a patched version of the `web3swift` pod to expose the Promise for making RPC calls.
> Fix: some tests stalling because of web3swift pod

- AlphaWallet/Redeem/Views/TokenListFormatRowView.swift
For #689 This PR fixes a cell reuse problem:
After scrolling in the crypto kitty cards screen, a card which goes offscreen and back again might display another kitty's thumbnail. Especially obvious if the kitty doesn't have a thumbnail yet.
> Fix: Crypto Kitty thumbnail appears in wrong cell upon cell reuse

- AlphaWallet/Tokens/Coordinators/TokensCoordinator.swift
This PR removes the unnecessary delay between fetching details for each contract that is auto- detected at startup. This delay was needed as a hack earlier to keep things running when the web3swift pod didn't expose promises directly, and instead every RPC call was blocking the thread it was running on. Removing the delay since #683 now uses promises correctly.
This speedup is most noticeable when importing a wallet with many tokens, like 0x007 on Ropsten.
> Speedup auto-detect tokens (upon startup) by removing, now, unnecessary delay between fetching details for each contract detected

- AlphaWallet/Browser/ViewControllers/BookmarkViewController.swift
- AlphaWallet/Browser/ViewControllers/HistoryViewController.swift
- AlphaWallet/Browser/Views/BrowserErrorView.swift
- AlphaWallet/Browser/Views/BrowserNavigationBar.swift
- AlphaWallet/Localization/en.lproj/Localizable.strings
- AlphaWallet/Localization/es.lproj/Localizable.strings
- AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings
Missing the benefits of static type checking. Also easier to miss not localised strings. Like in this case.
> Fix: access to localization strings for Dapp browser was not going through R

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet/AppCoordinator.swift
- AlphaWallet/InCoordinator.swift
- AlphaWallet/Localization/en.lproj/Localizable.strings
- AlphaWallet/Localization/es.lproj/Localizable.strings
- AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings
- AlphaWallet/PushNotificationsCoordinator.swift
- AlphaWallet/Settings/Types/Constants.swift
- AlphaWallet/Transactions/Coordinators/TransactionCoordinator.swift
- AlphaWallet/Transactions/Coordinators/TransactionDataCoordinator.swift
- AlphaWalletTests/Coordinators/AppCoordinatorTests.swift
For #718 
With this PR, the app will show a notification when they receive ether while the app is active (i.e. not killed, on switched to another app). If the app is not active when ether is received, the user will be notified when the app is next active again.
I gave up on getting the app to stay running in the background for a few more minutes so it can continue to show a notification if the user receives ether. There's a crash due to writing to the database while it's in the background. Might check back later if it's possible.
> Show local notification to indicate user has received ether. Only while app is active

- AlphaWallet/InCoordinator.swift
- AlphaWallet/Tokens/ViewControllers/TokensCardViewController.swift
- AlphaWallet/Tokens/ViewModels/TokensCardViewModel.swift
- AlphaWallet/Transactions/Coordinators/TokensCardCoordinator.swift
For #738.
Nice, for example, when you watch other people's CryptoKitties.
> Allow watched wallets to tap to view tokens, but with the transfer/redeem/sell buttons disabled

- AlphaWallet/AppDelegate.swift
- AlphaWallet/Info.plist
> Fix: launch screen if app is launched with call/tether bar visible on phones that doesn't have a notch, like iPhone 8 and earlier

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet/Core/ImageCache.swift
- AlphaWallet/PushNotificationsCoordinator.swift
- AlphaWallet/Tokens/Helpers/CryptoKitties/GenerateCryptoKittyPNGFromSVG.swift
- AlphaWallet/Tokens/ViewControllers/TokensCardViewController.swift
- AlphaWallet/Tokens/ViewModels/CryptoKittyCardRowViewModel.swift
- AlphaWallet/Tokens/Views/CryptoKitties/CryptoKittyCardRowView.swift
- Podfile
- Podfile.lock
This PR
* Converts SVG to PNG and cache the PNGs
* No-longer blocks UI while displaying CryptoKitty image #765 
* Fix: crash due to certain CryptoKitty images (might not be exhaustive) #764 
* has a smoother animation when expanding/collapsing CryptoKitty cards
Includes using a fork to the Macaw pod. Needs some followup work to report a bug and submit a PR
> Speed up CryptoKitty cards and fix crash due to certain CryptoKitty images

- AlphaWallet/Tokens/Helpers/TokenAdaptor.swift
- AlphaWallet/Tokens/Types/CryptoKitty.swift
- AlphaWallet/Tokens/Types/TokensDataStore.swift
- AlphaWallet/Tokens/ViewModels/CryptoKittyCardRowViewModel.swift
Read background color for CryptoKitty image from OpenSea API output.
cc @JamesSmartCell. Example API output:
"assets" : [
{
...
"token_id" : "507300",
"background_color" : "ede2f5",
...
}
> Read and use CryptoKitty background color from OpenSea API

- AlphaWallet/Core/ImageCache.swift
- AlphaWallet/Tokens/Helpers/CryptoKitties/GenerateCryptoKittyPNGFromSVG.swift
Some image URLs are png instead of svg. This PR checks for png, as well as jpg and jpeg (just in case).
cc @JamesSmartCell example kitty ID: 107923 owned by 0xb1690C08E213a35Ed9bAb7B318DE14420FB57d8C has https://storage.googleapis.com/opensea-prod.appspot.com/0x06012c8cf97bead5deae237070f9587f8e7a266d/107923.png
> Handle when CryptoKitties images are sometimes not SVG, but PNG

- AlphaWallet/InCoordinator.swift
- AlphaWallet/Settings/Types/Constants.swift
- AlphaWallet/Transfer/Controllers/TransactionConfigurator.swift
for #768
Gas is already being estimated but might fail sometimes when the gas price exceeds the limit of default. Removed the default and used the max for gas limit, also removed the Constants that were duplicate.
> remove gas related Constants and use max for gas limit

- AlphaWallet/EtherClient/TrustClient/TrustClient.swift
- AlphaWallet/Transactions/Coordinators/TransactionDataCoordinator.swift
For #752 
This PR makes fetching transactions less likely to block the entire app:
* Start with only fetching the newest "page" of transactions (and not both old and new transactions) if there are no transactions cached. This could be a new account or a freshly imported account (with potentially many transactions)
* Make sure we don't fetch the newest "page" of transactions multiple times because fetching a large page (10,0000 transactions. Especially common if a newly imported wallet with a long transaction history). This happened when the next scheduled refresh happens before the results from the previous fetch was returned
* Limit the number of transactions checked to send pushes for notifying ether has been received. And only look at transactions in the last 24 hours. Trying to comb …
> Modify fetching transactions to work better with Etherscan API

- AlphaWallet/EtherClient/OpenSea.swift
> Fix: Should not show ERC721 tokens from OpenSea when on testnets

- AlphaWallet/Transactions/Coordinators/TransactionDataCoordinator.swift
For #822 "it should tell the differences between different network, Ropsten, Mainnet etc."
> Indicate in the Ether received notification if testnet

- AlphaWallet/Tokens/Views/OpenSea/OpenSeaNonFungibleTokenCardRowView.swift
This PR adjusts the margins around images and round the corners for OpenSea token cards. Changes are only visible for tokens with images that have backgrounds (like Gods Unchained).
Before:
After:
> Tweak opensea image display

- AlphaWallet/Tokens/ViewModels/OpenSeaNonFungibleTokenCardRowViewModel.swift
- AlphaWallet/Tokens/Views/OpenSea/OpenSeaNonFungibleTokenCardRowView.swift
Some token IDs have a description like:
"Control Atlantean: <strong>deadly</strong>"
> Format HTML markup in OpenSea token ID description

- AlphaWallet/Settings/Coordinators/SettingsCoordinator.swift
When a wallet is created/imported, transactions are downloaded in 2 "directions":
1. The most recent transactions are download first and stored in the database. This is repeated to get new transactions by getting newer transactions than the newest in the database.
2. Then older transactions are fetched by fetching transactions that are older than the oldest in the database. This is repeated until we don't get any more transactions, and we'll set a flag in `UserDefaults` to indicate all old transactions has been fetched for this wallet.
The flag in (2) isn't cleared when a wallet is deleted. So deleting a wallet that has downloaded all transactions and importing it again will not download old transactions.
This PR fixes this by clearing the flag when the wallet is deleted.
> Fix: deleting a wallet should clear the flag that indicates older transactions has been downloaded

- AlphaWallet/Tokens/Coordinators/TokensCoordinator.swift
By not storing contract addresses in a consistent format, we might accidentally add the same token twice in the database.
This PR makes storing of ERC20 tokens addresses in the database in the format defined by EIP55.
> Fix: Storing ERC20 tokens in database should always store address in EIP55

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet/Browser/Coordinators/BrowserCoordinator.swift
- AlphaWallet/Tokens/Views/TokensCardViewControllerTitleHeader.swift
- AlphaWallet/Transfer/Coordinators/SignMessageCoordinator.swift
- AlphaWallet/Transfer/ViewControllers/ConfirmSignMessageViewController.swift
- AlphaWallet/Transfer/ViewModels/ConfirmSignMessageTableViewCellViewModel.swift
- AlphaWallet/Transfer/ViewModels/ConfirmSignMessageViewControllerViewModel.swift
- AlphaWallet/Transfer/Views/ConfirmSignMessageTableViewCell.swift
Related to #760.
This PR makes the prompt to sign message/personal/typed message confirmation nicer and more consistent with the rest of the app.
Just a thought while writing this: Maybe it's good to have another PR after this to display the wallet address for which key we are signing with?
Before:
After:
> Prettify sign message confirmation

- AlphaWallet/Tokens/Views/OpenSea/OpenSeaNonFungibleTokenCardRowView.swift
Fixes #846 
Presumably because the conversion from HTML to NSAttributedString uses WebKit and triggers a threading bug. We skip it entirely when showing the view controller the first time since description isn't displayed at that point.
> Fix: strange visual effect when tapping ERC721 token card in wallet tab

- AlphaWallet/Tokens/ViewModels/OpenSeaNonFungibleTokenCardRowViewModel.swift
- AlphaWallet/Tokens/Views/OpenSea/OpenSeaNonFungibleTokenCardRowView.swift
e.g.
1. Tap ERC721 token card from OpenSea in wallet tab
2. Tokens are shown collapsed the first time
3. Tap on row 0. Row 1 is rended as collapsed a second time
4. Scroll to reveal row 1 completely. Layout of row 1 is broken
> Fix: OpenSea token card layout broken if rendered as collapsed twice in a row

- AlphaWallet/Redeem/ViewControllers/RedeemTokenViewController.swift
- AlphaWallet/Sell/ViewControllers/SellTokensCardViewController.swift
- AlphaWallet/Tokens/ViewControllers/TokensCardViewController.swift
- AlphaWallet/Transactions/ViewControllers/TransactionsViewController.swift
- AlphaWallet/Transfer/ViewControllers/TransferTokensCardViewController.swift
For #870 
PS: Wanted to include a snapshot test. But couldn't any test to run correctly in iOS 12. Sigh.
> Fix: auto-sizing cells has wrong height in iOS 10

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet/AppDelegate.swift
- AlphaWallet/AssetDefinition/AssetAttribute.swift
- AlphaWallet/AssetDefinition/XMLHandler.swift
- AlphaWallet/Core/Initializers/MigrationInitializer.swift
- AlphaWallet/Extensions/String.swift
- AlphaWallet/InCoordinator.swift
- AlphaWallet/Market/Coordinators/UniversalLinkCoordinator.swift
- AlphaWallet/Market/OrderHandler.swift
- AlphaWallet/RPC/Commands/web3swift-pod/CallForAssetAttribute.swift
- AlphaWallet/Tokens/Coordinators/CallForAssetAttributeCoordinator.swift
- AlphaWallet/Tokens/Helpers/TokenAdaptor.swift
- AlphaWallet/Tokens/Types/AssetAttributeFunctionCall.swift
- AlphaWallet/Tokens/Types/TokenBalance.swift
- AlphaWallet/Tokens/Types/TokensDataStore.swift
- AlphaWallet/UI/ViewModels/TokenCardRowViewModel.swift
- AlphaWallet/UI/Views/TokenCardRowView.swift
- AlphaWalletTests/AssetDefinition/XMLHandlerTest.swift
@James-Sangalli: This PR includes the commit in PR #882 in order to support namespaces, so #882 
should be merged first and this PR rebased (or updated) before merging.
@colourful-land you might be interested in: (A), (C) and (D).
This PR adds support for the standard spawnable meetup contract:
1. Calls smart contract functions to retrieve asset attribute values
2. Display most fields in the spawnable meetup contract
To add these quickly, there are a few limitations that should be fixed or improved in the near future:
1. The function-call-based asset attributes are only refreshed when the app is launched or becomes active
2. The token bundles displayed on the current screen don't automatically refresh when the function-call-based asset attributes changes. It does reflect the updated …
> Call contract functions for asset attributes for spawnable meetup contract

- AlphaWallet/AssetDefinition/AssetAttribute.swift
- AlphaWallet/AssetDefinition/XMLHandler.swift
- AlphaWallet/RPC/Commands/web3swift-pod/CallForAssetAttribute.swift
- AlphaWallet/Tokens/Coordinators/CallForAssetAttributeCoordinator.swift
- AlphaWallet/UI/ViewModels/TokenCardRowViewModel.swift
- AlphaWallet/UI/Views/TokenCardRowView.swift
This PR updates XML parsing the handle the asset definitions in https://github.com/AlphaWallet/contracts/pull/86/commits/c6a1ad04ff286b532220866be9eb4035fb99043b
I tested this by downloading the 3 XMLs into the `assetDefinitionsOverrides/` directory and then renaming them to the appropriate contracts.
Might be good to update the contract (I tested against `0x16e58F9a98bc46a572CFb9ce28DDEeaf76AF645a`) based on the spawnable meetup contract XML to have a couple more tokens with various fields encoded in the token ID to see if that works.
Might have to wait till https://github.com/AlphaWallet/contracts/pull/86/commits/c6a1ad04ff286b532220866be9eb4035fb99043b is finalised to merge. cc @colourful-land
> Update XML parsing to handle latest asset definition schema

- AlphaWallet/Market/ViewModels/ImportMagicTokenCardRowViewModel.swift
- AlphaWallet/UI/Views/TokenCardRowView.swift
For #896 
(Note to self: The problem is that while the token card view is shared across many screens in the app, the version in the import screen is slightly different (because it doesn't always have a TokenHolder). So it's easy to change one and forget to change the other. And this has happened to me at least once previously.
Have to come back and figure out how to make this take advantage of strong-typing to catch it.)
> Fix: import screen for spawnable token not displaying attribute values

- Podfile
- Podfile.lock
The author deleted the version (0.0.8) of the pod we are using (really uncommmon and shouldn't be done unless something horrible happened. But every old version was removed..). This situation is bad because we were forced to update the version of the pod we use. It also broke Travis, which couldn't find the pod.
This PR:
1. Forks the repo and use it instead
2. Increases the version from 0.0.8 to 0.0.9 anyway. Had wanted to stick with 0.0.8 with the fork, but can't find the commit (I suppose the pod author must have forced push at some point so pod v0.0.8 and pod v0.0.8 in the repo wasn't exactly the same). We can still use 0.0.8 in the fork, but since both 0.0.8 (in the repo) and 0.0.9 wasn't tested against previously, might as well up version from 0.0.8 -> 0.0.9
With the added …
> Fix broken tests on Travis (and switching to using a fork of TrezorCrypto pod for more control)

- AlphaWallet/Tokens/ViewControllers/TokensCardViewController.swift
Before this PR, tapping on a token asset card to expand it will auto-scroll that card to the top of the list.
With this PR, we only auto scroll to reveal for OpenSea-supported tokens which are usually taller and have a picture. Because:
A. other tokens like ERC875 tickets are usually too short and all text, making it difficult for user to capture where it has scrolled to
B. OpenSea-supported tokens are tall, so after expanding, chances are user need to scroll quite a lot if we don't auto-scroll
> Don't auto scroll token asset cards when expanding non-OpenSea supported tokens

- AlphaWallet/UI/AddressTextField.swift
Especially since we allow entering of ENS names now.
> Don't (offer to) autocorrect or autocapitalize in address textfields.

- AlphaWallet/Transfer/Types/GasLimitConfiguration.swift
- AlphaWalletTests/Transfer/Types/GasLimitConfigurationTests.swift
Sets the limit to the geth limit rather than an arbitrary number.
As for #912, I believe this is actually the dapp not the app, our app gets the gas price from the dapp itself when using the browser. Not sure how @JamesSmartCell does it in android.
> set limit to geth default

- AlphaWallet/Browser/Factory/WKWebViewConfiguration.swift
- Podfile
- Podfile.lock
For https://github.com/AlphaWallet/alpha-wallet-android/pull/451#discussion_r237672053
After this PR is applied, dapps can check `web3.currentProvider.isAlphaWallet` like described in https://github.com/AlphaWallet/AlphaWallet-web3-provider/blob/master/README.md (hopefully to display the name `AlphaWallet` as well as our logo)
> Update web3 provider so that isAlphaWallet flag is set to true

- AlphaWallet/AssetDefinition/XMLHandler.swift
This PR fixes a bug introduced when switching to new XML parser and using XPath — the asset issuer name was not extracted correctly and displayed
> Fix asset issuer name not extracted from asset definition and displayed

- AlphaWallet/Tokens/Views/OpenSea/OpenSeaNonFungibleTokenCardRowView.swift
For #935 
It wraps both when expanded and collapsed, but when collapsed, it is still truncated because the token card's maximum height is set to the image's height.
>  Wrap long token names when displayed as tokens sourced from OpenSea

- AlphaWallet/AppDelegate.swift
- AlphaWallet/InCoordinator.swift
This PR fixes the Realm database file path logged to the console for debugging purposes.
It will also log it correctly again when the user switches wallet/server.
> Print the correct database file path for debugging

- AlphaWallet/Settings/ViewControllers/SettingsViewController.swift
This PR makes it easier for user to see the start and end of the wallet address quickly
> Tweak wallet display in Settings screen so the ellipsis is in middle instead

- AlphaWallet/EtherClient/Wallet.swift
- AlphaWallet/Foundation/QRURLParser.swift
- AlphaWallet/Settings/Types/CustomRPC.swift
- AlphaWallet/Settings/Types/RPCServers.swift
They are auto-synthensized in Swift 4.1
https://github.com/apple/swift-evolution/blob/master/proposals/0185-synthesize-equatable-hashable.md
> Remove unnecessary implementations of Equatable and Hashable

- AlphaWallet/Settings/Types/Config.swift
- AlphaWallet/Tokens/Coordinators/GetENSOwnerCoordinator.swift
- AlphaWallet/UI/AddressTextField.swift
For #911. This PR will 
* Cache the ENS resolution result (in-memory, which will mostly take care of when the ENS name expires)
* Use the resolved result immediately without a delay when they user types, if it has been cached earlier
* Some refactoring
> Cache ENS resolution result

- AlphaWallet/Tokens/ViewControllers/TokensViewController.swift
When there not enough tokens to fill the wallet tab, the search bar appears when the wallet tab is first shown. This PR fixes that.
> Fix: Hide search bar in wallet tabs even if there are only a few tokens

- AlphaWallet/Tokens/ViewControllers/TokensViewController.swift
This PR fixes a bug caused by adding a search bar to the wallet tab: the background color at the top was wrong.
> Fix: background color of table view in wallet tab when pulled down

- dangerfile.js
This PR helps with code health. No functional change.
Checks for something like this (where the `xxxx` represents the spurious spaces added by text editor to otherwise empty lines we are checking for:
```
func oldCode() {
}
xxxx
func newCode() {
}
```
> Add danger rule to check for leading spaces in otherwise empty lines of code

- AlphaWallet/InCoordinator.swift
The send button in this screen:
> Fix: tapping the Send button for ether and token card when on a watch-account doesn't show error message correctly

- AlphaWallet/Transfer/Views/SendHeaderView.swift
> Fix: blockchain name label is clipped in the send/receive screen for Ether

- AlphaWallet/Core/Initializers/MigrationInitializer.swift
- AlphaWallet/EtherClient/TrustClient/Models/OperationType.swift
- AlphaWallet/EtherClient/TrustClient/Models/RawTransaction.swift
- AlphaWallet/Models/PendingTransaction.swift
- AlphaWallet/Tokens/Types/TokensDataStore.swift
- AlphaWallet/Tokens/ViewModels/TokenViewControllerTransactionCellViewModel.swift
- AlphaWallet/Tokens/ViewModels/TokenViewControllerViewModel.swift
- AlphaWallet/Transactions/Coordinators/TransactionCoordinator.swift
- AlphaWallet/Transactions/Coordinators/TransactionDataCoordinator.swift
- AlphaWallet/Transactions/ViewModels/TransactionCellViewModel.swift
- AlphaWallet/Transactions/ViewModels/TransactionViewModel.swift
- AlphaWallet/Transfer/Types/SentTransaction.swift
For #1049.
This involves storing the transaction (transfer) types for transactions in the database. So there is also a slight change to ERC721 transactions to show something like "-1088247" instead of "-1,088,247 CKITTY" to avoid look like we transferred 1 million tokens in the Transactions tab.
Possible future enhancement for tokens we are aware of like CryptoKitties might be to display the image of the token (kitty). Or interpreting ERC875 too (I just did the minimum to get ERC20 to show up, so they are currently still showing as 0 ETH transfers).
|   |   |
| -- | --|
| ![simulator screen shot - iphone x - 2019-01-28 at 17 26 08](https://user-images.githubusercontent.com/56189/51826466-1d5cec00-2322-11e9-9425-8b3df026ba86.png) | ![simulator screen shot - iphone x - 2019-01-28 at 17 26 …
> Display ERC20 transfers (send only) in redesigned send/receive view

- AlphaWallet/Tokens/ViewModels/TokensViewModel.swift
Once this PR is applied, we can type "erc 875", "ERC 875" or "ERC875" in the search bar to filter in the Wallet tab. Works with ERC20, ERC721 and ERC875.
Useful for development and as a hidden feature.
> Filter wallet by token type, by typing "erc 875" in search bar

- AlphaWallet/Redeem/ViewControllers/TokenCardRedemptionViewController.swift
Fixes this: 
(another candidate for snapshot test).
> Fix: Redeem token screen layout broken

- AlphaWallet/Transfer/ViewModels/ChooseTokenCardTransferModeViewControllerViewModel.swift
> Adjust action button titles in choose token transfer mode screen to fit long titles

- dangerfile.js
Checks for this code:
```
Decimal(exactly: aBigUInt)
```
Which compiles without error but crashes at runtime. Couldn't figure a way to make it a compile time error.
If a developer has Danger set up as a git hook in their local repo; when committing code with the line above, danger will throw and error.
> Add Danger check for Decimal(exactly: aBigUInt) which compiles but crashes at runtime

- AlphaWallet/Localization/en.lproj/Localizable.strings
- AlphaWallet/Localization/es.lproj/Localizable.strings
- AlphaWallet/Localization/ja.lproj/Localizable.strings
- AlphaWallet/Localization/ko.lproj/Localizable.strings
- AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings
Confusing to everyone as to why it says "stormbird" should be AlphaWallet or simply say verified
> change text from verified by Stormbird to verified by AlphaWallet

- AlphaWallet/Settings/Types/Constants.swift
- AlphaWallet/Settings/Types/RPCServers.swift
At some point the API endpoints that we use on BlockScout stopped working.
Should fix this #1087?
> Fix: Dai and POA Core API calls failing

- AlphaWallet/Tokens/Types/TokensDataStore.swift
We only support retrieving ETH and xDai native cryptocurrency prices for now. But we were previously displaying the ETH prices in the ETC and Ethereum testnets token cards. This PR fixes it.
> Fix: should not use ETH price for ETC and testnets

- AlphaWallet/Transactions/ViewControllers/TransactionsViewController.swift
Faster, more memory efficient when scrolling.
> Register and dequeue Transactions tab's cells instead of creating brand new ones

- AlphaWallet/EtherClient/TrustClient/Models/RawTransaction.swift
- AlphaWallet/Tokens/Coordinators/TokensCoordinator.swift
- AlphaWallet/Tokens/Helpers/TokenAdaptor.swift
- AlphaWallet/Tokens/Types/TokenObject.swift
- AlphaWallet/Tokens/Types/TokenType.swift
- AlphaWallet/Tokens/Types/TokensDataStore.swift
- AlphaWallet/Tokens/ViewControllers/NewTokenViewController.swift
- AlphaWallet/Tokens/ViewControllers/TokenViewController.swift
- AlphaWallet/Tokens/ViewControllers/TokensCardViewController.swift
- AlphaWallet/Tokens/ViewControllers/TokensViewController.swift
- AlphaWallet/Tokens/ViewModels/TokenViewControllerViewModel.swift
- AlphaWallet/Transactions/Coordinators/TokensCardCoordinator.swift
- AlphaWallet/Transfer/Controllers/TransactionConfigurator.swift
- AlphaWallet/Transfer/Coordinators/SendCoordinator.swift
- AlphaWallet/Transfer/Types/TransferType.swift
- AlphaWallet/Transfer/ViewControllers/SendViewController.swift
- AlphaWallet/Transfer/ViewModels/ConfigureTransactionViewModel.swift
- AlphaWallet/Transfer/ViewModels/ConfirmPaymentDetailsViewModel.swift
- AlphaWallet/Transfer/ViewModels/SendViewModel.swift
- AlphaWallet/UI/BalanceTitleView.swift
Side effect: Removed unnecessary .xDai enum cases
Reproduce before the PR:
1. Switch to xDai chain.
2. Tap Currency filter
Observed:
3. xDai card disappears
Expected:
3. xDai card remains
4. Repeat with Assets filter for the opposite effect.
> Fix: xDai native cryptocurrency card in Wallet tab not appearing/disappearing correct with filters (Currency/Asset)

- AlphaWallet/Tokens/ViewControllers/TokensViewController.swift
This PR fixes this issue:
1. Be under ALL filter in Wallets tab
2. Pan a few times quickly to scroll
3. While it's still scrolling, tap on the COLLECTIBLES tab
> Fix: Crash if switch to Collectibles while scrolling under with any other filter in Wallet tab

- AlphaWallet/Browser/Coordinators/DappBrowserCoordinator.swift
- AlphaWallet/InCoordinator.swift
This is only supported in the Dapp browser tab. Consistent because we don't provide a URL bar in the pop up browsers.
> Don't provide function for user to scan a QR code to load URL in the browsers that pop up

- AlphaWallet/Vendors/Web3Swift/Web3Swift.swift
> Fix: Purchasing tokens with MagicLink shows the activity spinner and doesn't complete the purchase

- AlphaWallet/Browser/Views/NativeCryptoCurrencyBalanceView.swift
Because updating the position of the label was previously done only when the balance is refreshed. If the balance isn't available quickly enough, the label will not be positioned correctly.
> Fix: native crypto currency balance sometimes displayed at the wrong position

- AlphaWallet/Browser/Coordinators/DappBrowserCoordinator.swift
For #1167 
Before this PR, the dapp browser ignores URL like "https://google.com.sg   "
> Fix: entering a URL with leading or trailing space into dapp browser should work

- AlphaWallet/Tokens/Types/TransactionCollection.swift
- AlphaWallet/Transactions/ViewModels/TransactionsViewModel.swift
Before this PR, transactions were grouped correctly into days. But transactions within each day was shown in the reverse order, with oldest on top
> Fix: Order of transactions in tab within each day is displayed in reverse

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet/AppCoordinator.swift
- AlphaWallet/AppDelegate.swift
- AlphaWallet/Core/Coordinators/CustomUrlSchemeCoordinator.swift
- AlphaWallet/Info.plist
- AlphaWallet/Tokens/Coordinators/TokensCoordinator.swift
- AlphaWallet/Tokens/ViewControllers/TokenViewController.swift
- AlphaWallet/Tokens/ViewModels/TokenViewControllerViewModel.swift
- AlphaWallet/Transfer/Controllers/TransactionConfigurator.swift
- AlphaWallet/Transfer/Coordinators/RequestCoordinator.swift
- AlphaWallet/Transfer/Coordinators/SendCoordinator.swift
- AlphaWallet/Transfer/Types/TransferType.swift
- AlphaWallet/Transfer/ViewControllers/SendViewController.swift
- AlphaWallet/Transfer/ViewModels/ConfirmPaymentDetailsViewModel.swift
- AlphaWallet/Transfer/ViewModels/SendViewModel.swift
- AlphaWallet/UI/BalanceTitleView.swift
- AlphaWalletTests/Coordinators/InCoordinatorTests.swift
- AlphaWalletTests/Coordinators/SendCoordinatorTests.swift
- AlphaWalletTests/Factories/UnconfirmedTransaction.swift
- AlphaWalletTests/ViewControllers/PaymentCoordinator.swift
For #1163 
Couple of links I tested with:
ethereum:0xf956F4D787F8CA0F363468859E54eAD5cA1e5184
ethereum:pay-0xf956F4D787F8CA0F363468859E54eAD5cA1e5184?value=1.23e18
ethereum:pay-0xf956F4D787F8CA0F363468859E54eAD5cA1e5184@3?value=1.23e18
ethereum:pay-0x087913a52D327F0CA037D497848ee31Ec146F07e@3/transfer?address=0xf956F4D787F8CA0F363468859E54eAD5cA1e5184&uint256=1.3
The last link is an ERC20 token transfer. It'll be ignored silently by the app if the token is not already in the Realm database.
Everyone's fighting for the only slot:
> Handle EIP681 links. ethereum: especially when scanning QR code which embeds them with Camera.app

- AlphaWallet/Core/Types/ServerDictionary.swift
- AlphaWallet/InCoordinator.swift
- AlphaWallet/Tokens/Types/TokensDataStore.swift
For #1192 
This PR improves data transfer usage by reducing unnecessary Ether price and balance fetching. Just simple de-dup. No fancy exponential backup etc.
> Reduce unnecessary Ether price and Ether balance fetching

- AlphaWallet/Accounts/ViewModels/AccountsViewController.swift
Before this PR, the order of the wallets is unpredictable
> Sort the list of wallets in Settings tab > Wallets

- AlphaWallet/Browser/Coordinators/DappBrowserCoordinator.swift
This PR fixes a bug introduced by #1178. When the verified button in the import MagicLink UI is tapped, the browser doesn't load the MagicLink. ((because it sees a MagicLink and tries again, and failed, to load up the MagicLink UI according to #1178)
> Fix: tapping verified in import MagicLink UI for mainnet token does not load URL in browser correctly

- AlphaWallet/Market/ViewControllers/ImportMagicTokenViewController.swift
Since we support MagicLinks for every chain now:
This PR makes tapping on the verified button in import UI open all MagicLinks in a browser instead of etherscan. We used to only open MagicLinks in the browser for mainnet only, opening etherscan for non-Ethereum-mainnet
> Make tapping on verified button in MagicLink import UI open all MagicLinks instead of etherscan page, not just mainnet MagicLinks

- AlphaWallet/Browser/ViewControllers/MyDappsViewController.swift
- AlphaWallet/EtherClient/TrustClient/AlphaWalletService.swift
- AlphaWallet/InCoordinator.swift
- AlphaWallet/Market/Coordinators/UniversalLinkCoordinator.swift
- AlphaWallet/Market/Coordinators/UniversalLinkInPasteboardCoordinator.swift
- AlphaWallet/PushNotificationsCoordinator.swift
- AlphaWallet/Settings/Types/Config.swift
- AlphaWallet/Settings/ViewControllers/SettingsViewController.swift
- AlphaWallet/Tokens/Coordinators/GetContractInteractions.swift
- AlphaWallet/Tokens/Coordinators/TokensCoordinator.swift
- AlphaWallet/Transactions/Coordinators/SingleChainTransactionDataCoordinator.swift
- AlphaWallet/Transfer/Controllers/TransactionConfigurator.swift
This PR removes a few warnings. Only obviously safe looking changes are made. So there are a few warnings left.
> Fix warnings after Xcode upgrade

- AlphaWallet/Browser/Views/NativeCryptoCurrencyBalanceView.swift
> Fix: should allow taps on crypto balance in dapp browser to passthrough to the content in the dapp browser

- AlphaWallet/Browser/ViewModel/Dapps.swift
Bidali allows you to buy from top brands with crypto. Use your ETH and ERC20 tokens to seamlessly buy from hundreds of brands world wide.
> Adding Bidali dapp

- AlphaWallet/Core/Initializers/MigrationInitializer.swift
- AlphaWallet/EtherClient/TrustClient/Models/RawTransaction.swift
- AlphaWallet/Settings/Types/Constants.swift
- AlphaWallet/Settings/Types/RPCServers.swift
- AlphaWallet/Tokens/Coordinators/GetContractInteractions.swift
- AlphaWallet/Tokens/Coordinators/SingleChainTokenCoordinator.swift
- AlphaWallet/Tokens/Helpers/CallSmartContractFunction.swift
- AlphaWallet/Tokens/ViewModels/TokenViewControllerViewModel.swift
- AlphaWallet/Transactions/Coordinators/SingleChainTransactionDataCoordinator.swift
- AlphaWallet/Transactions/Storage/Transaction.swift
- AlphaWallet/Transactions/Storage/TransactionsStorage.swift
- AlphaWallet/Transfer/Types/SentTransaction.swift
- AlphaWalletTests/Coordinators/ClaimOrderCoordinatorTests.swift
- AlphaWalletTests/Factories/Transaction.swift
This PR:
- Enables an event lookup for erc20 transactions meaning you can get incoming transactions and pick up contracts you haven't transacted with directly (from Etherscan)
- Adds a flag to the Transaction object to prevent getting the block number from one of these event transactions and thus miss some of the older transactions you might have done 
- Adds a function to call for generic events 
Solves #1211 and issues related to it 
@JamesSmartCell This is relevant for Android too.
> Get received transactions

- Podfile.lock
Looks like we missed committing it in a recent commit.
> Make Podfile.lock be in sync with Podfile

- AlphaWallet/AssetDefinition/AssetDefinitionDiskBackingStore.swift
This PR ignore those files so that they don't show up as bad TokenScript files in the top of the Wallet tab and in Settings > Console.
(The desirable general approach when encountering files based on old Schema files should be to let user tap a button to try to download an updated version instead).
> Don't show errors for asset definition files that are based on pre-2019/04 schema

- AlphaWallet/AssetDefinition/Coordinators/FetchAssetDefinitionsCoordinator.swift
Before this PR, when we fetch TokenScript files from the repo for tokens already in the local database, we only include ERC721 and ERC875 tokens.
This PR includes ERC20.
(Running this on a device might have worked before this PR if the token has just been detected and or is just manually added).
> Fix: should also fetch TokenScript files from repo for ERC20 tokens

- AlphaWallet/AppCoordinator.swift
- AlphaWallet/AssetDefinition/AssetDefinitionDiskBackingStore.swift
- AlphaWallet/Tokens/ViewControllers/TokensViewController.swift
Before this PR:
When they are only conflicting TokenScript files but no bad TokenScript files identified, the "Show Errors" button isn't displayed in the Wallet tab despite the conflicting TokenScript files being listed in the Console screen.
This PR fixes it.
> Fix: Wallet tab should still show the 'Show Errors' button when there are conflicting TokenScript files (even if there are no bad TokenScript files)

- AlphaWallet/AssetDefinition/TokenScriptFileIndices.swift
This is more common with files from the repo server.
The same TokenScript file for the entry token is downloaded several times because it applies to several contract address over different networks. Before this PR, the app thinks that these TokenScript files have a conflict. It should not, because the file contents are the same.
> Fix: TokenScript files with the same contents wrongly detected as conflicts

- AlphaWallet/Welcome/ViewControllers/WelcomeViewController.swift
Fix #1216 
Before PR:
After PR (ignore the lack of the nav bar. It's a different screen):
iPhone X | non-iPhone X
-|-
> Fix: Getting Started button height in onboarding screen did not take into account bottom safe area of iPhone X

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet/Tokens/ViewControllers/TokensViewController.swift
- AlphaWallet/Tokens/ViewModels/FungibleTokenViewCellViewModel.swift
- AlphaWallet/Tokens/Views/FungibleTokenViewCell.swift
- AlphaWallet/Tokens/Views/TokenInstanceWebView.swift
Rename TokenViewCell (and view  model) to FungibleTokenViewCell because the existing NFT counterpart is NonFungibleTokenViewCell.
> Refactor: rename files for consistency

- AlphaWallet/Browser/ViewControllers/BrowserViewController.swift
- AlphaWallet/Browser/Views/DappBrowserNavigationBar.swift
- AlphaWallet/Core/Collection+UIView.swift
Fix #1228 
It's actually strange. I'm not sure if this PR is relying on an undocumented behaviour, but it should be safe even if that changes. Here's what's happening.
iOS should fire `UIResponder.keyboardWillShowNotification` when the keyboard is going to be displayed, and `UIResponder.keyboardWillHideNotification` when the keyboard is going to be hidden. For both notifications, this code retrieves the frame of the keyboard:
```
let beginRect = (notification.userInfo?[UIResponder.keyboardFrameBeginUserInfoKey] as? NSValue)?.cgRectValue
let endRect = (notification.userInfo?[UIResponder.keyboardFrameEndUserInfoKey] as? NSValue)?.cgRectValue
```
What's strange is that in the iOS simulator, if the software keyboard is toggled off (so simulating an external keyboard), …
> Fix: while running in the simulator. Dapp browser's URL bar can only become first responder once

- AlphaWallet/AppCoordinator.swift
Blue bar between filters and the Ethereum token card:
> Fix: empty blue bar appears below Wallet tab filters after the first launch for a new app installation

- AlphaWallet/Extensions/Date.swift
- AlphaWallet/Localization/en.lproj/Localizable.strings
- AlphaWallet/Localization/es.lproj/Localizable.strings
- AlphaWallet/Localization/ja.lproj/Localizable.strings
- AlphaWallet/Localization/ko.lproj/Localizable.strings
- AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings
- AlphaWallet/Market/Coordinators/UniversalLinkCoordinator.swift
Instead of the general message "Invalid Link, please try again", we also show more specific error messages when we can:
* "Link has expired"
* "Link has already been redeemed"
> Show more specific error messages when importing MagicLink(s)

- AlphaWallet/TokenScriptClient/Coordinators/AssetDefinitionStoreCoordinator.swift
TokenScript client uses a file called `indices` internally. Add a defensive check against someone AirDropping a file with the same name and corrupting it. Should not be possible in theory because we have configured the app to only accept AirDrops of known file extensions.
> Add defensive check against AirDrop-ing a indices file that replaces the one used by TokenScript client internally

- AlphaWallet/Foundation/QRURLParser.swift
- AlphaWallet/Market/UniversalLinkHandler.swift
- AlphaWallet/TokenScriptClient/Models/UserEntryOrigin.swift
- AlphaWallet/TokenScriptClient/Models/XMLHandler.swift
- AlphaWallet/Tokens/ViewControllers/NewTokenViewController.swift
- AlphaWallet/Transfer/ViewControllers/SendViewController.swift
Examples include:
A) QR code for address which has a trailing newline character
B) User enters an address with a trailing space into a TokenScript rendered view which is captured by a user-entry-origin based attribute with the origin having `as="address"`.
You can generate A) with this:
```
$ echo "0x007bEe82BDd9e866b2bd114780a47f2261C684E3" | qrencode -o ~/Desktop/token-qr.png
```
The correct command to generate without a trailing newline character is:
```
$ echo -n "0x007bEe82BDd9e866b2bd114780a47f2261C684E3" | qrencode -o ~/Desktop/token-qr.png
```
> Accept user input addresses that has leading or trailing whitespaces as valid addresses

- AlphaWallet/Settings/Types/Constants.swift
This PR addresses this: We can't use https://blockscout.com/poa/dai/address/ to display an address even though blockscout.com ultimately redirects there because blockscout.com is only able to show that URL after the address has been searched (with the ?q= URL). So we use the search URL instead.
To observe this in the browser, visit a URL like:
1. https://blockscout.com/poa/dai/address/0xf64bd90bb0bfc05d667ba224be6f1cce817e7be0/transactions
2. If it displays a list of (maybe empty) transactions repeat (1) with a different address until it shows "Page not found".
3. Visit https://blockscout.com/poa/dai/search?q=0xf64bd90bb0bfc05d667ba224be6f1cce817e7be0 (replacing the address with the one in step 1)
4. Repeat (1) again and it should work now
> Replace blockscout.com webpage URLs so that they load more reliably

- AlphaWallet/TokenScriptClient/Models/AssetDefinitionDiskBackingStore.swift
iOS apps is sandboxed. But we still want to prevent TokenScript from accessing files it has permission to read but shouldn't read (It has permission because the client runs as part of the app).
eg.
```
<!ENTITY test SYSTEM "..\\assetDefinitions/indices">
```
> Add check against XML entity injection in TokenScript client

- AlphaWallet/TokenScriptClient/Models/XMLHandler.swift
- AlphaWallet/Tokens/ViewModels/TokenInstanceViewModel.swift
- AlphaWallet/Tokens/ViewModels/TokensCardViewModel.swift
Before this PR, all ERC875 tokens including those with TokenScript files marketing `interface="erc875"` includes a redeem action.
After applying this PR, only FIFA tokens (with the 2 hardcoded contract addresses) will have the redeem action.
> Only show the Redeem action button for FIFA ticket tokens and not for other ERC875 tokens

- AlphaWallet/Browser/Views/DappBrowserNavigationBar.swift
Before this PR, each run of the app prints Auto Layout warnings to the console (at the bottom of this issue).
Reason being when the dapp navigation bar is created by the system, it has a frame of size zero (or at least the width is zero, maybe the height isn't), so Auto Layout can't fulfill both of these constraints:
```
stackView.leadingAnchor.constraint(equalTo: layoutGuide.leadingAnchor, constant: 10),
stackView.trailingAnchor.constraint(equalTo: layoutGuide.trailingAnchor, constant: -10),
```
The Auto Layout warnings:
```
2019-07-01 11:07:52.787892+0800 AlphaWallet[32452:3280887] [LayoutConstraints] Unable to simultaneously satisfy constraints.
Probably at least one of the constraints in the following list is one you don't want. 
Try this: 
(1) look at each constraint and try to …
```
> Fix: remove Auto Layout warnings upon startup

- AlphaWallet/Settings/Types/RPCServers.swift
- AlphaWallet/Tokens/Coordinators/GetContractInteractions.swift
For #1282 
fixes #1220 
Before this PR, when we are fetching transactions via ERC20 interactions and when we auto-detect contracts for Ethereum Classic (and a few other networks), we are (wrongly) fetching them using endpoints for Ethereum mainnet, hence getting those from mainnet instead.
> Fix: Tokens and transactions on Ethereum mainnet are (also) wrongly appearing on Ethereum Classic and a few other networks

- AlphaWallet/Settings/Types/Constants.swift
- AlphaWallet/Settings/Types/RPCServers.swift
After applying this PR, every network we support, other than ETC, the app will load the correct page when we tap to display the Etherscan (like) page.
This PR includes the URL for ETC but I couldn't get the one for ETC to work though: <https://blockscout.com/etc/mainnet/search?q=>. Feel free to fix it if you know why :)
> Fix etherscan-like webpage used to display contract/wallet details for numerous networks including Ethereum Classic

- AlphaWallet/Tokens/Types/TokenCollection.swift
For #1288
This PR fixes a performance bottleneck while sorting tokens. This causes switching to/from the Wallet tab to be very slow. The sorting time can improve from 200ms to 2ms with this PR applied.
> Make performance when switching to/away from Wallet tab to be more acceptable

- AlphaWallet/Transactions/Coordinators/SingleChainTransactionDataCoordinator.swift
This unwrapped a null when I was using the phone. Should be guarded.
> guards against null in address filter

- AlphaWallet/Transactions/Storage/TransactionsStorage.swift
This is causing deleted tokens to return.
> only adds transaction contract addresses on overloaded function

- AlphaWallet/Tokens/ViewControllers/VerifiableStatusViewController.swift
i.e. do nothing when user taps on "Verified by *.aw.app"
> Don't open the domain name for the cert used to sign the current TokenScript file if it's a wildcard

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet/Core/Types/RateLimiter.swift
- AlphaWallet/Tokens/Types/TokenCollection.swift
If N networks are enabled:
Before the PR, a pull down to refresh in the wallet tab or a periodic refresh of token balance/price will trigger N UI refreshes, with each UI refresh pulling from the database N times.
After this PR is applied, completed network requests for token updates will not immediately refresh the UI, instead, it will wait for 2 seconds to see if there's another completed network request for token updates. It will w
Thus, pull down to refresh in the wallet tab or a periodic refresh of token balance/price will trigger as few as 1 UI refresh (if each network call is completed within 2 seconds of the previous call's completion), with each UI refresh still pulling from the database N times. Multiple refreshes (eg. multiple pull down to refresh in succession), might also be …
> Improve wallet tab UI efficiency by rate limiting refreshes

- AlphaWallet/Browser/Coordinators/DappBrowserCoordinator.swift
Fixes #1299.
Disabling the actions is more idiomatic iOS compared to showing an error message that the action is not available.
(On some occasions, error messages for actions that should otherwise be disabled is still useful if we know it's not obvious to the user why the action not available).
> Disable actions under More in Dapp browser, such as Share, Reload, Add to My Dapps, when no valid URL is loaded

- AlphaWallet/TokenScriptClient/Models/TokenScriptSignatureVerifier.swift
i.e. handle:
```
"CN=skstravel.cn,OU=PositiveSSL,OU=Domain Control Validated"
```
in addition to:
```
"CN=skstravel.cn"
```
Reproducible with the FIFA TokenScript file
> Fix: extract CN correctly when there's more than 1 key-value pair in subject

- AlphaWallet/Tokens/ViewControllers/VerifiableStatusViewController.swift
Specifically https://skstravel.cn vs http://skstravel.cn
> Use http instead of https for showing domain name in CN for TokenScript signing certs. Some sites don't serve https

- AlphaWallet/TokenScriptClient/Models/XMLHandler.swift
- AlphaWallet/Tokens/ViewControllers/TokenViewController.swift
- AlphaWallet/Tokens/ViewModels/TokenViewControllerViewModel.swift
- AlphaWalletTests/TokenScriptClient/XMLHandlerTest.swift
> Fix: TokenScript files with invalid signatures are wrongly matched, always to mainnet

- AlphaWalletTests/Settings/ConfigTests.swift
I can reproduce this locally on my laptop, but might not be noticeable on Travis.
Applying this PR will fix the crash when running `TokenScriptSignatureVerifierTest`, where it crashes at an unrelated line of code due to it waiting for the API to complete, exposing the bug fix in this particular test (`ConfigTests`).
> Fix crash if any other test (any test) waits too long to complete

- AlphaWallet/AlphaWalletHelp/Views/ContactUsBannerView.swift
- AlphaWallet/Settings/ViewControllers/SettingsViewController.swift
Inspired by https://github.com/AlphaWallet/TokenScript/issues/217
> Display supported TokenScript schema version in Settings screen and support email template

- AlphaWallet/TokenScriptClient/Models/XMLHandler.swift
For #1313
It will still display that the signature is invalid, along with the usual DEBUG tag in the UI. But the contents of the TokenScript file will be used to render the view and offer actions.
> Allow TokenScript files with invalid signatures to be used, while in debug mode

- AlphaWallet/Tokens/ViewControllers/TokensViewController.swift
Just a stopgap measure in case we need to release based on master branch. Should be alright since it's a well-hidden feature.
I'll work on fixing it in the mean time.
> Disable swipe to delete tokens in Wallet tab to avoid crash (temporarily)

- AlphaWallet/Tokens/Types/TokenCollection.swift
- AlphaWallet/Tokens/Types/TokensDataStore.swift
This is because #1342 introduced a rate limiter that no longer refreshes the Wallet tab immediately.
> Immediately reload Wallet list after deleting tokens, and not be rate limited. So users get immediate feedback that token is deleted

- AlphaWallet/Transactions/Coordinators/SingleChainTransactionDataCoordinator.swift
- AlphaWallet/Transactions/Storage/TransactionsStorage.swift
This is because `TransactionsStorage.tokens(from:)` performs an update/addition to the tokens database with:
```
let operation = transaction.localizedOperations.first,
let contract = operation.contractAddress,
```
updating/adding a token with `contract` as the contract address.
@James-Sangalli  But maybe we need to check both `to` and `operation?.contractAddress` when filtering? Is the former still needed to handle when there's an Ether transfer to the contract?
ie. the PR changes:
```
guard let addressToCheck = AlphaWallet.Address(string: $0.to) else { return false }
return !contractsToAvoid.contains(addressToCheck)
```
to:
```
guard let addressToCheck = $0.operation?.contractAddress else { return false }
return !contractsToAvoid.contains(addressToCheck)
```
Maybe we need to check both …
> Fix: deleted tokens are automatically added back when we detect ERC20 transactions involving them

- AlphaWallet/Browser/Coordinators/DappBrowserCoordinator.swift
- AlphaWallet/InCoordinator.swift
- AlphaWallet/Settings/Coordinators/ServersCoordinator.swift
- AlphaWallet/Tokens/Coordinators/TokensCoordinator.swift
- AlphaWalletTests/Coordinators/TokensCoordinatorTests.swift
Before this PR, even if a network is not enabled, the user can add a token to it or switch to it in the Dapp browser. This isn't consistent in the UI and can also post problems internally as we might (now or in the future) assume in our code that if a network is not enabled, all resources for it is switched off.
Closes #1275
> Only allow users to switch to enabled networks in Dapp browser and when adding a token

- AlphaWallet/Transfer/Coordinators/SignMessageCoordinator.swift
- AlphaWallet/Transfer/ViewControllers/ConfirmPaymentViewController.swift
- AlphaWallet/Transfer/ViewControllers/RequestViewController.swift
* Sign a message/transaction
* Send a payment
* Copy Ethereum address
(only activates for iPhone 7 and later, and not any iPads)
> Add more taptic feedback after user action is successful

- AlphaWallet/Tokens/Views/EthTokenViewCell.swift
- AlphaWallet/Tokens/Views/FungibleTokenViewCell.swift
- AlphaWallet/Tokens/Views/NonFungibleTokenViewCell.swift
Compare the position of the tiny token names before and after the PR:
-|-
> Fix baseline alignment of long token names in Wallet tab when the token name font size automatically shrink to fit

- AlphaWallet/Transfer/Coordinators/SignMessageCoordinator.swift
No functional change.
Before this PR, the function name did more than its name suggested.
> Fix: parts of function body should be in the caller instead for correct semantics

- AlphaWallet/Wallet/ViewControllers/CreateInitialWalletViewController.swift
> Fix: Create/import new wallet screen text placement is wrong for new users

- AlphaWallet/Wallet/ViewControllers/VerifySeedPhraseViewController.swift
Fixes #1394
If we tap 1 or more words in the verify seed phrase screen and then switch to another app or home screen and switch back to AlphaWallet:
-|-
> Fix: clear textbox and hides clear button in verify seed phrase screen after we auto-clear shuffled seed phrase (from app going to background)

- AlphaWallet/UI/SuccessOverlayView.swift
Fixes #1395 
(can be seen after completing a back up)
> Automatically hide the success screen with big green tick after 1 second

- AlphaWallet/UI/ButtonsBar.swift
> Fix baseline alignment of long button names in green action buttons when the font size automatically shrink to fit

- AlphaWallet/Core/Initializers/MigrationInitializer.swift
- AlphaWallet/EtherClient/OpenSea.swift
Fixes #1427 
This PR
* makes the app only accept ERC721 from OpenSea API
* adds a migration to fix the DAI token which is wrongly tagged as ERC721
> Only accept erc721 from OpenSea

- AlphaWallet/Wallet/ViewControllers/VerifySeedPhraseViewController.swift
It's easy to accidentally hit the clear button when trying to tap the seed phrases in the last row on short screens. This is before the PR:
> Fix: Clear button in Verify Seed Phrase screen overlaps with seed phrases on short screens

- AlphaWallet/Tokens/Types/TokensDataStore.swift
This broke on Victor's phone, check if the max value is reached and if it has fail rather than crash (my try-catch block didn't work on this exception for some reason)
This only effects 721 tokens that are not supported by OpenSea
> ensure overflowed integers on 721 balance count doesn't break

- AlphaWallet/Market/UniversalLinkHandler.swift
- AlphaWalletTests/Market/UniversalLinkHandlerTests.swift
Tap http://aw.app or https://aw.app on iOS simulator/device.
> Fix: crash when user taps http(s)://aw.app(/)

- AlphaWallet/Tokens/Coordinators/ClaimOrderCoordinator.swift
- AlphaWallet/Transfer/Controllers/TransactionConfigurator.swift
Should partially help with #1438 but seems to be insufficient.
Encoding failure is definitely a problem (so this PR still can go through by itself if it passes review), but while transferring a FIFA ticket token on 0x007 Ropsten, it fails for some mysterious reason after making it past encoding.
> Fix: addresses are not encoded correctly in certain transactions

- AlphaWallet/EtherClient/OpenSea.swift
- AlphaWallet/InCoordinator.swift
- AlphaWallet/Tokens/Types/TokensDataStore.swift
Fixes #1450
Before this PR, OpenSea API calls (for mainnet and Rinkeby) always takes results from either network (mainnet or Rinkeby, might be random) only. Because tokens on one network aren't present on the other network with the same contract (and hence balance 0) and because we encode the ERC721 token details obtained from OpenSea into the balance, the app thinks that they aren't ERC721 and render them wrongly (as ERC875).
> Fix: OpenSea calls aren't made for the correct servers if both mainnet and Rinkeby are enabled

- AlphaWallet/Browser/Coordinators/DappBrowserCoordinator.swift
> In Dapp browser, fallback to first enabled network when selected network is disabled in the app

- AlphaWallet/Tokens/ViewControllers/TokenInstanceActionViewController.swift
Closes #1454 
Like this:
Before Confirm|After Confirm and successful|
-|-
> Show green tick after action succeeds for user feedback

- AlphaWallet/TokenScriptClient/Models/AssetDefinitionBackingStore.swift
- AlphaWallet/TokenScriptClient/Models/AssetDefinitionDiskBackingStore.swift
- AlphaWallet/TokenScriptClient/Models/AssetDefinitionDiskBackingStoreWithOverrides.swift
- AlphaWallet/TokenScriptClient/Models/AssetDefinitionInMemoryBackingStore.swift
- AlphaWallet/TokenScriptClient/Models/AssetDefinitionStore.swift
- AlphaWallet/TokenScriptClient/Models/TokenScriptFileIndices.swift
- AlphaWallet/TokenScriptClient/Models/XMLHandler.swift
So the cached status is available even if the network is slow or totally offline. Caching uses file contents hash as the key so it should be good until we add the ability to revoke certs (which we can't until we support other kinds of methods of signing).
Addresses part of #1464 
One important flow to test for is:
1. Drop a TokenScript override file in
2. Tap to open the token the TokenScript file is for
3. Wait till signature is verified
4. Switch off network
5. Launch app and open token to check cached signature is available offline
6. Switch on network
7. Change the TokenScript file so that the signature is wrong
8. Verify that the status shows that the signature is invalid
9. Replace with old TokenScript file (which has a correct signature)
10. Verify signature is shown as valid.
In …
> Cache tokenscript sig verification status

- AlphaWallet/Tokens/ViewControllers/TokensViewController.swift
Fixes #1423 
Issue might only be for iOS 13.1 beta (but it has happened for all 4 betas) and iOS 13.1 public release is imminent.
Hackish, but seems safe for other OS versions.
> Fix: navigation bar and status bar color is wrong (black) for Wallet tab when search bar is visible in iOS 13.1

- AlphaWallet/Market/ViewModels/ImportMagicTokenViewControllerViewModel.swift
Fixes #1474 
(Would not have happened if this had a snapshot test)
-|-
> Fix: when displaying token in import MagicLink UI, the section attribute is displayed wrongly

- AlphaWallet/TokenScriptClient/Models/XMLHandler.swift
> Fix: TokenScript client not falling back token name correctly (to 1st element) when target language is not available

- AlphaWallet/Browser/Coordinators/DappBrowserCoordinator.swift
Happens if we disable the server that is dapp browser's current selection
> Fix: crash due to infinite recursion when dapp browser's selected network is not in enabled list

- AlphaWallet/TokenScriptClient/Models/AssetDefinitionDiskBackingStoreWithOverrides.swift
> Fix: override TokenScript file with new schema is ignored if there's an official version with an old schema

- AlphaWallet/Settings/Coordinators/HelpUsCoordinator.swift
- AlphaWallet/Settings/Types/Constants.swift
Very old versions of the app supported iOS 10 which did not have access to `SKStoreReviewController`. No longer a constraint.
> Remove hardcoded app store URL for the app as we can use SKStoreReviewController because of our min deployment target setting

- AlphaWallet/Tokens/Coordinators/SingleChainTokenCoordinator.swift
Before the PR:
1. We know a fungible token (eg. Discover) has a balance of X and the local database stores it as such
2. App is launched again (killed or out of memory previously)
3. App adds default tokens and it shows up as balance = 0 briefly
4. Balance goes to X (or whatever is the current value)
After PR:
1. We know a fungible token (eg. Discover) has a balance of X and the local database stores it as such
2. App is launched again (killed or out of memory previously)
3. App adds default tokens and it shows up as balance = X
4. Balance remains as X or updates to the current value if it's changed.
> Fix: default tokens shows balance of 0 momentarily shortly after startup

- AlphaWallet/UI/Views/AmountTextField.swift
Fixes #1536 
Before this PR:
1. Go to send Ether
2. Enter 1 ETH
3. Tap USD
4. Textbox is cleared
After this PR:
4. Textbox shows 180 (the current value of 1 ETH)
I can rebase after #1535 if there are conflicts.
> Preserve value when switching between crypto native and fiat amounts

- AlphaWallet/Tokens/Types/TokenObject.swift
Fixes #1443, #1540 
Before this PR, this is shown in the wallet tab:
"0x0255 DAI (DAI"
With this PR:
"0x0255 DAI (DAI)".
Interestingly, this is because the DAI contract returns both the name and symbol padded with trailing `\0` characters so they are both 32 characters long.
> Fix: DAI token symbol is shown with a missing trailing parenthesis in the Wallet tab

- AlphaWallet/Tokens/ViewControllers/TokenViewController.swift
- AlphaWallet/Transfer/ViewControllers/SendViewController.swift
Fixes #1472 
Before this PR, for an ERC 20 token with TokenScript file (example DAI):
* Wallet tab displays token name from TokenScript file
* Send screen displays token name returned by the contract
> Display ERC 20 token name from TokenScript file instead of the contract in the send screen (like in the Wallet tab), if the file is available

- AlphaWallet/TokenScriptClient/Coordinators/AssetDefinitionStoreCoordinator.swift
Before this PR, scanning `ethereum:` links might fail because the TokenScript client thinks it's a link to a new TokenScript override file
> Fix: incorrectly treating ethereum: as TokenScript file drops

- AlphaWallet/Market/ViewModels/ImportMagicTokenViewControllerViewModel.swift
We can probably remove this stop-gap code if we don't use it anymore. But anyway a fix while it's still there.
> Fix: Detection of spawnable meetup contract for display

- AlphaWallet/KeyManagement/EtherKeystore.swift
Would have prevented #1565 and help to catch if in the future our seed generation is somehow broken.
With this PR, when importing a seed phrase or generating a new one, we'll double check that the address is what we think it will be and also sign a test message and ecrecover just to be sure.
> Add defensive check when creating and importing wallets with seed

- AlphaWallet/Market/ViewModels/StatusViewControllerViewModel.swift
> Fix: Done button is not visible in transfer NFT notification dialog

- AlphaWallet/Browser/Views/DappBrowserNavigationBar.swift
With this PR, the cancel button becomes visible like this:
> Fix: cancel button is not visible in the dapp browser navigation bar while editing URL

- AlphaWallet/TokenScriptClient/Models/XMLHandler.swift
Symptoms are identical to what Victor reported reported a month or two ago.
This PR disables reading from the cache for token attributes.
This is good for function origin-based attributes since we don't have a way to specify TTL for them yet. But this will worse performance for scrolling in the wallet tab. It should not affect users wouldn't many token IDs (not tokens) with TokenScript tokenID attributes, but we should bring back caching, maybe this time only for token ID-based attributes.
> Fix: TokenScript client sometimes stop displaying attributes in web views. Requires restart to fix

- AlphaWallet/Tokens/Coordinators/GetERC721ForTicketsBalanceCoordinator.swift
If you have a zeroed out array value it will still add to your balance and give you a falsely high number, this PR prevents this for erc721 tickets
> filters zero balance tokens from balances array

- AlphaWallet/Tokens/Coordinators/GetIsERC721ForTicketsContractCoordinator.swift
The first time saying that it's a normal ERC721 token. Causing the token in wallet tab to briefly show the balance as 0 before showing the correct balance
> Fix: Detection for ERC721 for tickets fires completion handler twice

- AlphaWallet/Tokens/ViewControllers/TokenInstanceViewController.swift
> Fix: Tokenscript views flash when tapped in token instance screen (the one with redeem/transfer/sell buttons)

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet/Settings/Types/Constants+Credentials.swift
- AlphaWallet/Settings/Types/RPCServers.swift
- README.md
As a separate step, we can replace this new `Constants+Credentials.swift` file with a local version that is ignored by git.
> Separate out Infura key into a separate file so it is easy to specify a different key (file) locally when building

- AlphaWallet/Tokens/ViewControllers/TokenInstanceViewController.swift
- AlphaWallet/Tokens/Views/BaseTokenCardTableViewCell.swift
- AlphaWallet/Tokens/Views/OpenSea/OpenSeaNonFungibleTokenCardRowView.swift
- AlphaWallet/UI/Views/TokenCardRowView.swift
- AlphaWallet/UI/Views/TokenCardRowViewProtocol.swift
Fixes #1544 
The problem is that the cell height isn't calculated correctly, so the link (button) is outside of its ancestor views so it doesn't get hit-tested.
Unfortunately, it's one of the cases where it's hard (or impossible) to get Auto Layout to work — complicated cell with cell-stackview-multilineLabel. At least I couldn't. Solution is a bit hackish.
> Fix Open on link for ERC721 tokens sourced from OpenSea don't do anything when tapped

- AlphaWallet/AppCoordinator.swift
- AlphaWalletTests/Coordinators/AppCoordinatorTests.swift
Might fix #1589
Before this PR, if NSUSerDefaults is not accessible (then it's an iOS bug) upon startup, the app will think the user has no wallets and ask them to create/import a wallet. It seems random and hard to reproduce. Adds a defensive check to make sure user does not have existing Realm databases for wallets and delays launch if that happens. It can cause #1589, but not sure if it is the only possible cause.
If it does happens, the effects of applying this PR is the app will wait until NSUserDefaults is available or if it doesn't either apply to be hung or iOS/user might kill the app. That way, the user will be able to launch the app again and access their wallets
If there is another cause for #1589, this PR will not make it worse.
> Mitigate user losing access to wallets when app starts up and NSUserDefaults is not accessible

- AlphaWallet/Wallet/ViewControllers/ElevateWalletSecurityViewController.swift
- AlphaWallet/Wallet/ViewModels/ElevateWalletSecurityViewModel.swift
> Fix: text and button overlap on smaller devices in screen prompting to elevate key security

- AlphaWallet/Tokens/ViewControllers/TokenInstanceActionViewController.swift
- AlphaWallet/Tokens/ViewControllers/TokensCardViewController.swift
- AlphaWallet/Tokens/Views/BaseTokenCardTableViewCell.swift
- AlphaWallet/Tokens/Views/TokenInstanceWebView.swift
- AlphaWallet/UI/Views/TokenCardRowView.swift
Closes #1594 with:
* Fix TokenScript view cells height detection
* Remove margins around TokenScript views
Expect to affect only TokenScript-rendered views. The effect on margins:
|Before|After|
-|-
> Fix TokenScript view cells height detection and remove margins

- AlphaWallet/Tokens/ViewControllers/TokenInstanceViewController.swift
- AlphaWallet/Tokens/Views/TokenInstanceWebView.swift
Fixes #1597 
Also fixes the height in the screen. Before this PR, while it's not obvious until the user attempt to scroll it, the scroll view is very tall:
Performance is quite poor when selecting/de-selecting, so probably have to optimise further later
> Fix tokenscript view cells height for heavy tokenscript views

- AlphaWallet/Tokens/Views/TokenInstanceWebView.swift
Before applying this PR, the screen with a list of TokenScript views will crash while scrolling if there are more rows than the screen can fit.
> Fix: crash when scrolling TokenScript views

- AlphaWallet/TokenScriptClient/Models/AssetDefinitionBackingStore.swift
- AlphaWallet/TokenScriptClient/Models/AssetDefinitionDiskBackingStore.swift
- AlphaWallet/TokenScriptClient/Models/AssetDefinitionDiskBackingStoreWithOverrides.swift
- AlphaWallet/TokenScriptClient/Models/AssetDefinitionInMemoryBackingStore.swift
- AlphaWallet/TokenScriptClient/Models/AssetDefinitionStore.swift
- AlphaWallet/Tokens/Coordinators/SingleChainTokenCoordinator.swift
Fixes #1595 
This PR fixes 3 bugs:
1. When a TokenScript file signature is validated, it is cached. This cache also stores if the file has a conflict with another. If A and B has a conflict and then A is updated, the cache still says that A and B has a conflict
2. When a TokenScript file from the repo server covers contracts `0x1` and `0x2`, it is downloaded and stored as the files `0x1.tsml` and `0x2.tsml` with identical content. When `0x1` is deleted by the user and the app checks for updated TokenScript files, only `0x2.tsml` is fetched and written to disk, so there is a conflict between `0x1.tsml` and `0x2.tsml` (the former being outdated)
3. When a TokenScript file from the repo server covers contracts `0x1` and `0x2`, it is downloaded and stored as the files `0x1.tsml` and …
> Fix TokenScript files marked wrongly as having conflicts

- AlphaWallet/Foundation/EtherNumberFormatter.swift
- AlphaWallet/Sell/ViewControllers/EnterSellTokensCardPriceQuantityViewController.swift
- AlphaWallet/UI/Views/AmountTextField.swift
Fixes #1599 
There are a few ways to change the locale or preferred language for the app:
1. Change the locale in Settings.app
2. Change the preferred language in Settings.app
3. Change the preferred language in Settings.app for AlphaWallet only (iOS 13 and newer)
4. Change the language in AlphaWallet Settings tab
When the user sets the in-app locale (method 4) to one that uses a decimal comma (E.g. Spanish), the `.decimalPad` keyboard still (only) shows decimal point. The `.decimalPad` keyboard only switches to the decimal comma correctly with methods 1, 2 and 3.
This PR changes it so that we always consider the decimal point as the one defined by the locale.
> Always support decimal comma as decimal separator in addition to what is specified by locale when entering amounts

- AlphaWallet/Models/TokenUpdate.swift
- AlphaWallet/Settings/Types/Constants.swift
- AlphaWallet/Tokens/Types/TokensDataStore.swift
- AlphaWallet/Transactions/Coordinators/SingleChainTransactionEtherscanDataCoordinator.swift
- AlphaWallet/Transactions/Storage/TransactionsStorage.swift
Especially relevant for ERC721 tickets that are auto-detected.
E.g. Blockscout output: https://blockscout.com/poa/dai/api?module=account&action=tokentx&address=0x08d0d733b65321a1e28bd8b6045e59aa11f6bbe3
Not sure if this affects Android @James-Sangalli @JamesSmartCell
> Fix: Tokens auto-detected from transactions shouldn't always be treated as ERC20 because BlockScout returns ERC721 too

- AlphaWallet/InCoordinator.swift
- AlphaWallet/Models/TokenUpdate.swift
- AlphaWallet/Settings/Types/Constants.swift
- AlphaWallet/Tokens/Coordinators/SingleChainTokenCoordinator.swift
- AlphaWallet/Tokens/Types/TokensDataStore.swift
- AlphaWallet/Transactions/Coordinators/SingleChainTransactionEtherscanDataCoordinator.swift
- AlphaWallet/Transactions/Storage/TransactionsStorage.swift
- AlphaWalletTests/Factories/FakeTransactionsStorage.swift
Dependent on merging #1622 first. Left that PR's commit in so it's easier to merge since they touch the same files.
> Fetch tokenscript file for contracts auto detected from transactions immediately instead of waiting until app is launched again

- Podfile
- Podfile.lock
Fixes #1485
Now runs without crashing with Xcode 11.
Still shouldn't build with Xcode11 for TestFlight/submission because we still need to fix update the view controller presentation styles so they don't look like:
> Fix: App crash with Xcode 11 due to Realm

- AlphaWallet/TokenScriptClient/Models/TokenScriptFileIndices.swift
- AlphaWallet/Tokens/Coordinators/SingleChainTokenCoordinator.swift
- AlphaWallet/Tokens/Types/TokensDataStore.swift
- AlphaWallet/Tokens/Views/TokenInstanceWebView.swift
Closes #1639, #1643 
This PR fixes 2 reasons leading to slower app launch:
* Upon launch, every TokenScript file's content is hashed. The hashing function we used is slow. Even with ~20 TokenScript files, there is noticeable slowdown. Switched to a faster hash function
* A fixed which scan every TokenScript and conditionally process it once for every holding contract they are for is ran at launch. This was for an old database migration and looks like it is no longer necessary.
> Speed up launch

- AlphaWallet/UI/Views/AmountTextField.swift
This PR fixes a display issue which happens when building with an older Xcode and running on a newer iOS versions. Specifically building with Xcode 10.x (which is for iOS 12) and running iOS 13.x. When the symbol in the amount textbox is tapped, the symbol grows a mind of its own and moves to the left of the textbox and the amount entered might be covered.
-|-
> Fix: symbol in amount textfield moves around when tapped. Happens when building with older Xcode and running on new iOS versions

- AlphaWallet/Tokens/ViewControllers/TokenInstanceActionViewController.swift
- AlphaWallet/Tokens/Views/TokenInstanceWebView.swift
Fixes #1646 
TokenScript views continues to be a hairy part of the app. There are 2 different types of screens where the behavior/needs of WKWebview are a bit different in our app:
A. When displaying view-iconified in token card screens and MagicLink creation screen and when importing a MagicLink
B. When displaying an action view
They seem to require slightly different ways to injecting JavaScript into the webviews. (B) also requires reading from user-entry which is done via injecting JavaScript too.
(A) is harder to get rid because we require good performance out of it, whereas (B) seems to be simpler to get right (though broken by a recent PR to optimise for A).
So I imagine we'll just have to remember testing at least these 2 types occasionally.
> Fix: inject token data into action view is broken

- AlphaWallet/TokenScriptClient/Coordinators/FetchAssetDefinitionsCoordinator.swift
- AlphaWallet/TokenScriptClient/Models/AssetDefinitionBackingStore.swift
- AlphaWallet/TokenScriptClient/Models/AssetDefinitionDiskBackingStore.swift
- AlphaWallet/TokenScriptClient/Models/AssetDefinitionDiskBackingStoreWithOverrides.swift
- AlphaWallet/TokenScriptClient/Models/AssetDefinitionInMemoryBackingStore.swift
- AlphaWallet/TokenScriptClient/Models/AssetDefinitionStore.swift
TokenScript files on disk, from official repos that have filenames for tokens that are not in the Realm database don't get refreshed so they will cause conflicts when a copy of the same TokenScript file is updated for another token (which is in the Realm database).
e.g. TokenScript file A is on the repo server which works for holding contracts 0xC1 and 0xC2. For some reason [1], A is written locally as 0xC1.tsml and 0xC2.tsml. Only 0xC1 is in the database. Before this commit, Only 0xC1.tsml will be refreshed. So if A changes, 0xC1.tsml and 0xC2.tsml will be different and cause a conflict.
This PR changes it so that every TokenScript file is refreshed.
> Refresh every TokenScript file on disk that were downloaded from the repo server upon app startup

- AlphaWallet/Tokens/Types/TokensDataStore.swift
This PR adds a defensive check. Instead of force unwrapping the token to update native balance, we perform an early return if the database object is not available (for some unknown reason). At least one crash due to token being nil. Perhaps a Realm bug or in our code, perhaps in between enabling/disabling of chains?
It's harmless to perform an early return here.
> Fix: add defensive check to avoid crash when attempting to update native crypto currency balance

- AlphaWallet/Tokens/ViewControllers/TokensViewController.swift
Fixes #1651 
Before the PR:
1. App is launched
2. ALL tab is selected
3. Tap ASSETS tab and scroll to hide/reveal new rows
4. iOS might decide to load (the first time especially) the collection view at some point even if we don't switch to it, thus getting the wrong count
5. At some point, iOS ask for a cell(s) for those non-existent rows/items
E.g 10 tokens total (ALL), only 3 are collectibles and asked for the 6th cell
This PR adds a defensive check to make sure we only return a non-zero count for collectibles when we are actually at the collectibles tab
> Fix: crash when scrolling assets because collection view is silently loaded by iOS with the wrong/non-existent items

- AlphaWallet/Wallet/ViewControllers/ShowSeedPhraseViewController.swift
- AlphaWallet/Wallet/ViewControllers/VerifySeedPhraseViewController.swift
- AlphaWallet/Wallet/Views/SeedPhraseCollectionView.swift
-|-
Similar for the previous screen which displays the seed phrase
> Make seed phrase display scrollable and avoid blocking the Clear button in Verify seed phrase screen

- AlphaWallet/EtherClient/TrustClient/AlphaWalletService.swift
- AlphaWallet/Settings/Types/Constants+Credentials.swift
- AlphaWallet/Settings/Types/RPCServers.swift
- AlphaWallet/Transactions/Coordinators/TransactionDataCoordinator.swift
Closes #1677 
This PR 
* adds an Etherscan API key
* uses it for access
* use the same approach to manage the key described in #1583 
Since the deadline to use an API key is Feb 15, a build will have to go live before then for transaction history and auto detection of ERC20 tokens from transactions
> Add and use API key for Etherscan

- AlphaWallet/Settings/Types/Constants.swift
- AlphaWallet/Settings/Types/RPCServers.swift
This PR handles the change required by https://medium.com/the-ethereum-name-service/ens-registry-migration-bug-fix-new-features-64379193a5a
Replaces #1682 
* Update all the registrar contracts to be the same
* https://etherscan.io/address/0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e
* https://ropsten.etherscan.io/address/0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e
* https://rinkeby.etherscan.io/address/0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e
* Adds registrar contract for Goerli, which is the same address too
* https://goerli.etherscan.io/address/0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e
> Fix malicious takeover previously owned ens names

- AlphaWallet/InCoordinator.swift
This is the screen shown after confirming the transaction:
-|-
The code was originally written to switch to the Transactions tab, but a bug was causing it to work incorrectly. It's better since the balance and transaction history in the screen before the PR doesn't reflect the pending transaction and the Transactions tab does.
> Fix: Should reveal Transactions tab after sending a token instead of showing the single token screen

- AlphaWallet/Browser/Coordinators/DappBrowserCoordinator.swift
> Fix: some dapps bleed into (under) navigation bar because global navigation bar styles changed when adding support for large titles

- AlphaWallet/Tokens/ViewModels/TokensViewModel.swift
This PR improve performance for searching for tokens in the Wallets tab. It's minor, only ~4-15% speed up with some micro benchmarking.
But it removes several redundant calls to `lowercased()` which will probably keep bugging us to wonder if it will improve performance, so this PR get rids of them.
> Minor speed boost when searching in Wallet tab. More for cleaner code

- AlphaWallet/Transfer/ViewControllers/RequestViewController.swift
> Make Ethereum address in My Wallet screen wrap, retaining font size

- AlphaWallet/AppDelegate.swift
- AlphaWallet/Tokens/ViewModels/SegmentedControlViewModel.swift
* Alerts, actionsheet and cursors
* Copy button in My Wallet Address screen
* Checkboxes in select language and enabled servers screens
Made the tint color magenta to illustrate the problem:
-|-
> Fix: tint color not set correctly in actionsheet etc, including:

- AlphaWallet/Localization/en.lproj/Localizable.strings
- AlphaWallet/Localization/es.lproj/Localizable.strings
- AlphaWallet/Localization/ja.lproj/Localizable.strings
- AlphaWallet/Localization/ko.lproj/Localizable.strings
- AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings
- AlphaWallet/Wallet/ViewControllers/ShowSeedPhraseViewController.swift
It's a stop-gap until #1642 is properly implemented.
> When access to wallet fails, in the error message, mention that should re-import their seed/key if they have restored/migrated to new device

- AlphaWallet/Core/Coordinators/CustomUrlSchemeCoordinator.swift
- AlphaWallet/Foundation/Eip681Parser.swift
- AlphaWallet/Transfer/ViewControllers/SendViewController.swift
- AlphaWalletTests/Foundation/QRCodeValueParserTests.swift
This PR adds support for EIP681 payment links for ERC20 without the recipient `address`, e.g.
ethereum:0x744d70fdbe2ba4cf95131626614a1763df805b9e/transfer?uint256=314e17
> Support EIP681 payment links for EIP681 that has no recipient address

- AlphaWallet/Core/Types/RateLimiter.swift
The `RateLimiter` class is useful because it lets us specify a `block` which can only run 1 time within a certain time limit T. eg. not to refresh by hitting an API endpoint too often without the client code having to deal with this directly.
```
let rateLimiter = RateLimiter(limit: 10) { [weak self] in
doSomethingThatShouldNotHappenTooOften()
}
rateLimiter.run() //as often as we like
```
Before this PR, if "requests" to run this block repeatedly occurred within the window T, T will be reset each time, so `block` finally runs when no requests arrive within the last T window. During busy periods, this can mean `block` never runs.
This PR fixes it so that `block` is run immediately and then the window T starts and during this window, `block` no longer gets fired (as one would expect rate …
> Fix: rate limited code using `RateLimiter` doesn't fire during busy periods

- AlphaWallet/Market/ViewModels/ImportMagicTokenCardRowViewModel.swift
- AlphaWallet/TokenScriptClient/Models/XMLHandler.swift
- AlphaWallet/Tokens/Types/OpenSeaNonFungibleTokenHandling.swift
- AlphaWallet/Tokens/Types/TokenInstanceAction.swift
- AlphaWallet/Tokens/Views/TokenInstanceWebView.swift
- AlphaWallet/Transfer/ViewModels/SendHeaderViewViewModelWithIntroduction.swift
- AlphaWallet/UI/ViewModels/TokenCardRowViewModel.swift
Closes #1777 
Supporting this for `<item-view>` and `<view>`:
```
<ts:item-view xml:lang="en">
<xhtml:style/>
<xhtml:script/>
<xhtml:body/>
```
> [TokenScript schema 2020/03] Extract <style>, <script>, <body> tags from TokenScript views

- AlphaWallet/TokenScriptClient/Models/XMLHandler.swift
- AlphaWalletTests/TokenScriptClient/XMLHandlerTest.swift
> [TokenScript schema 2020/03] Assume no more <attribute-types> wrapper tag for token-level attributes

- AlphaWallet/Browser/ViewControllers/BrowserViewController.swift
Before the PR, adding support for more schemes can easily introduce bugs.
> Refactor custom URL handling in dapp browser so it's easier to make changes to it

- AlphaWallet/Tokens/ViewControllers/TokenViewController.swift
> Fix: signature validation shows up in header for native crypto token screen for TokenScript files that should only another chain

- AlphaWallet/Tokens/ViewControllers/TokensCardViewController.swift
Fixes #1880 
This PR fixes it by caching the cells used by position so we aren't dequeuing the standard UITableView way. This is so the webviews load the correct values, especially when scrolling.
Probably wouldn't scale with many tokens since the number of web views created = number of token instances.
> Fix: cards in token cards screen display information from wrong cards if there are many cards (10-ish), after scrolling

- AlphaWallet/Foundation/StringFormatter.swift
- AlphaWallet/UI/Views/AmountTextField.swift
Fixes #1884 
This PR fixes 2 problems when input is set to fiat:
* Fix: entering fractional value (using comma) for fiat — eg. "3,4"
* Fix: toggling from ETH to fiat, the value is displayed with trailing space — eg. "1,2 " instead of "1,2"
Set locale to Poland to reproduce.
> Fixes: fiat entry shows "Wrong Input" when sending eth/native crypto tokens if locale is set to region which uses comma as decimal separator:

- AlphaWallet/Tokens/ViewModels/TokensViewModel.swift
- AlphaWallet/Wallet/ViewModels/ImportWalletViewModel.swift
Closes #1900
Should have been a computed property because the RHS isn't actually a constant
> Fix: localization for segment controls in Wallet tab do not kick in immediately when user override local in Settings

- AlphaWallet/EtherClient/OpenSea.swift
- AlphaWallet/Extensions/Error.swift
- AlphaWallet/Market/Coordinators/UniversalLinkCoordinator.swift
- AlphaWallet/Settings/Types/ConfigExplorer.swift
- AlphaWallet/Settings/ViewControllers/SupportViewController.swift
- AlphaWallet/Tokens/Models/WalletFilter.swift
- AlphaWallet/Tokens/Views/TextField.swift
- AlphaWallet/Transactions/Coordinators/SingleChainTransactionEtherscanDataCoordinator.swift
- AlphaWallet/Transfer/Types/TransferType.swift
- AlphaWallet/Vendors/TrustCore/ABIValue.swift
> Get rid of or replace unnecessary `default: ` in switches across the code base #1909

- AlphaWallet/Export/Coordinators/BackupCoordinator.swift
> Get rid of unnecessary func arg in `BackupCoordinator.export(for:)` #1910

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet/EtherClient/OpenSea.swift
- AlphaWallet/Tokens/ViewModels/EthTokenViewCellViewModel.swift
- AlphaWallet/Tokens/ViewModels/FungibleTokenViewCellViewModel.swift
- AlphaWallet/Tokens/ViewModels/NonFungibleTokenViewCellViewModel.swift
- AlphaWallet/Tokens/Views/EthTokenViewCell.swift
- AlphaWallet/Tokens/Views/FungibleTokenViewCell.swift
- AlphaWallet/Tokens/Views/NonFungibleTokenViewCell.swift
- AlphaWallet/UI/SelectCurrencyButton.swift
- AlphaWallet/UI/TokenImageView.swift
- AlphaWallet/UI/TokenObject+UI.swift
- AlphaWallet/UI/Views/AmountTextField.swift
The token icons that are displayed in the Wallet tab and Send ERC20/native crypto screens.
Not included in this PR:
* Updated hardcoded native crypto icons in #1665 
* There could be a bug where the symbol in the programmatically generated icon is sometimes wrong. Will try to reproduce it separately.
> Add 3rd party sources for token icons — OpenSea (for ERC721) and a GitHub repo of images

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet/Core/Helpers/withRetry.swift
- AlphaWallet/Tokens/Coordinators/GetDecimalsCoordinator.swift
- AlphaWallet/Tokens/Coordinators/GetERC20BalanceCoordinator.swift
- AlphaWallet/Tokens/Coordinators/GetERC721BalanceCoordinator.swift
- AlphaWallet/Tokens/Coordinators/GetERC721ForTicketsBalanceCoordinator.swift
- AlphaWallet/Tokens/Coordinators/GetERC875BalanceCoordinator.swift
- AlphaWallet/Tokens/Coordinators/GetInterfaceSupported165Coordinator.swift
- AlphaWallet/Tokens/Coordinators/GetIsERC721ContractCoordinator.swift
- AlphaWallet/Tokens/Coordinators/GetIsERC721ForTicketsContractCoordinator.swift
- AlphaWallet/Tokens/Coordinators/GetIsERC875ContractCoordinator.swift
- AlphaWallet/Tokens/Coordinators/GetNameCoordinator.swift
- AlphaWallet/Tokens/Coordinators/GetSymbolCoordinator.swift
- AlphaWallet/Tokens/Helpers/CallSmartContractFunction.swift
- AlphaWallet/Tokens/Types/TokensDataStore.swift
Still with Infura, but changing or adding any other compatible RPC node will get the same benefit
This PR does it by:
* decreasing timeout from default 60s to 4s. Too short, and slower connections might not work with the app; too long a timeout, and it's too long a wait (especially since we introduced retries with this PR) when the server doesn't respond.
* retrying when individual smart contract call fails — we have to make many multiple smart contract calls to detect a token. If one of the calls fails, we retry instead of failing the whole process
The retry function is achieved by introducing a new `withRetry(times:task:)` function.
> Make add custom token more reliable

- AlphaWallet/Settings/Types/ConfigExplorer.swift
- AlphaWallet/Settings/Types/Constants.swift
- AlphaWallet/Settings/Types/RPCServers.swift
@hboon the rationale is as follows:
- Etherscan China works well with western internet (tried on AU connection)
- gf.network needs the transaction history for their token
Etherscan China's API is identical and only available on mainnet as of today. 
@JamesSmartCell FYI
> use etherscan china api on mainnet

- AlphaWallet.xcodeproj/project.pbxproj
Should get triggered only when we choose Product > Archive in Xcode and the app ID matches ours (so forks are ignored)
> Add a build time check that we are using the correct credentials for production builds

- AlphaWallet/Core/Collection+UIView.swift
- AlphaWallet/Tokens/Types/TokenObject.swift
Just happened to not make a difference in functionality, and it's (currently) only used in test code. Code was wrong, nevertheless.
> Fix: setter should use newValue, not the attribute name (which is the old value)

- AlphaWallet/Transfer/ViewControllers/SendViewController.swift
- AlphaWallet/Transfer/ViewModels/SendViewModel.swift
> Showing the send screen the first time for a token which has no exchange rate/price should not show the down arrow #1949

- AlphaWallet/EtherClient/CoinMarket/Types/CoinTicker.swift
> Fix: Show token 24 hour price change instead of 24 hour market cap change

- AlphaWallet/Core/Formatters/CurrencyFormatter.swift
So we can do things like:
```
NumberFormatter.percent.string(from: 0.4) //40%
NumberFormatter.shortCrypto.string(from: 0.123499) //0.1234
```
Similar to how `.currency` and `.usd` is used now.
`.percent` and `.shortCrypto` aren't actually used yet, but they were used in the `train-leaves` branch. `.shortCrypto` is going to be used in a a future refactor.
That refactor is roughly:
* we can rename `CurrencyFormatter.swift` to `NumberFormatter.swift` (keeping the contents)
* rename `EtherNumberFormatter` to `CryptoValueConvertor`
* change the underlying logic of `CryptoValueConvertor.swift` to use `NumberFormatter.swift` so formatting logic and specs (2 decimals, etc) are kept in 1 place.
> Add number formatters for percentages and crypto (that has already taken into account decimals)

- AlphaWallet/Tokens/Views/TokenInstanceWebView.swift
Any of this:
A. Tap on a token with TokenScript file with item-views. eg. ENS
B. Tap on a token with action-only TokenScript and tap on an action button e.g. xDai
> Fix: crash when opening TokenScript views

- AlphaWallet/EtherClient/Requests/EstimateGasRequest.swift
- AlphaWallet/Transfer/Controllers/TransactionConfigurator.swift
- AlphaWallet/Transfer/Types/GasLimitConfiguration.swift
- AlphaWallet/Transfer/Types/TransactionConfiguration.swift
Fixes #2046 
The problem was 3 things:
1. The data was not yet included in the configurator and therefore couldn't estimate properly
2. the value param was encoded incorrectly, running BigInt.description.hexEncoded produced 0x30 on a 0 value
3. The value param is used incorrectly, for erc20 transfers the value is the amount of tokens being sent instead of the attached native currency amount, doing so can and will produce an error because erc20 transfers that include a value are often reverted in the contract.
Created https://github.com/AlphaWallet/alpha-wallet-ios/issues/2101 as the code base is not good here.
> set gas limit from node rather than hardcoding for token transactions

- AlphaWallet/Tokens/Helpers/CallSmartContractFunction.swift
Fixes #1652
This was because too many calls are made. Since the Ethereum block time is > 10s as of now, the (simple) solution is to cache the values for a few seconds (3).
This is only reproducible on a device, not in the simulator
This took a long time to fix. Lots of debugging code written and very slow tweak-verify-build cycle because I was sent down the rabbit hole at https://github.com/AlphaWallet/web3swift/pull/1 (which is hard to test because I had to rebuild the project after each tweak in the pod) mistaking that it was the cause.
<p align=center style='font-size: 100%'>··•··</p>
To reproduce the problem, trigger 1000s of smart contract calls fairly quickly.
> Fix: TokenScript attribute fetching (actually most smart contract function calls) not working anymore, so TokenScript views display NaN #1652

- AlphaWallet/Tokens/Helpers/CallSmartContractFunction.swift
- AlphaWallet/Tokens/Types/TokensDataStore.swift
- AlphaWallet/Tokens/ViewControllers/TokensViewController.swift
- AlphaWallet/Transactions/ViewControllers/TransactionsViewController.swift
- Podfile
- Podfile.lock
Fixes #1652
Follow up attempt to #2115 to fix #1652
The cause is still as identified previously:
> To reproduce the problem, trigger 1000s of smart contract calls fairly quickly.
It's still happening because:
A. Going to the Wallet tab triggers a refresh. This pulls the balance of every token in the Realm database
B. Going to the Transaction tab triggers a refresh. This pulls the balance of every token in the Realm database
C. Pull down to refresh in either tab has the same result as (A) and (B)
This is heavy for wallets with many tokens.
A highly probable way to verify that #1652 is fixed is to perform this sequence:
1. Tab on a token which has a TokenScript file, and tap a TokenScript action to show it's view
2. Verify if the attributes are loaded and displayed
3. Back to Wallet tab
4. …
> Fix again: TokenScript attribute fetching (actually most smart contra…ct function calls) not working anymore, so TokenScript views display NaN

- AlphaWallet/Tokens/ViewControllers/TokensCardViewController.swift
> Fix: Navigation bar is too tall (like with large title enabled) for NFT token views

- Podfile
- Podfile.lock
- README.md
Closes #1831 
Closes #1872 
Closes #2135 
Will update Travis config (which is set to Xcode 11.3) separately just in case there's trouble with it: #2144 seems to work for updating Travis config
> Support building with Xcode 11.7

- AlphaWallet/Settings/Types/Config.swift
- AlphaWallet/Settings/Types/RPCServers.swift
- AlphaWallet/Tokens/Coordinators/GetContractInteractions.swift
- AlphaWallet/Tokens/Coordinators/SingleChainTokenCoordinator.swift
- AlphaWallet/Transactions/Coordinators/SingleChainTransactionEtherscanDataCoordinator.swift
A. `GetContractInteractions.getContractList()` is called once per launch (called again if the user switches wallet) for ERC20 transactions and once for non-ERC20s [1]
B. `GetContractInteractions.getErc20Interactions()` is called at regular intervals
Before this PR, they both attempt to fetch data without specifying the `startBlock`.
This PR stores the last seen block from the results of each of these calls and only looks at newer blocks.
(B) in particular is really heavy and blocks the UI for *a few seconds* when running a decent-sized wallet
[1] The call for ERC20s transactions is actually a duplicate of (B), but this PR doesn't fix/refactor this.
> Speed up app by not fetching all blocks when fetching transactions for token detection

- AlphaWallet/Activities/Coordinators/ActivitiesCoordinator.swift
- AlphaWallet/TokenScriptClient/Models/EventsActivityDataStore.swift
- AlphaWallet/TokenScriptClient/Models/XMLHandler.swift
- AlphaWallet/Transactions/Coordinators/TokensCardCoordinator.swift
Especially from app launch till Activities tab is available.
Primarily by only ever, loading a subset of activities. 1000 for now, as well as transactions in the same period.
> Improve activities performance

- AlphaWallet/InCoordinator.swift
- AlphaWallet/TokenScriptClient/Models/AssetAttributesCache.swift
- AlphaWallet/TokenScriptClient/Models/AssetDefinitionStore.swift
- AlphaWallet/Tokens/Coordinators/SingleChainTokenCoordinator.swift
- AlphaWallet/Transactions/Coordinators/TokensCardCoordinator.swift
Before the PR, when an `PrivateXMLHandler` (1:1 with reading a TokenScript file) is created, we verify the signature and once upon getting the verification result, we inform all the listeners (subscribers in the code) watching for TokenScript file changes to refresh. This means that soon after app launch, we verify the signature of every TokenScript file we have on-disk and trigger a refresh of every token which has those TokenScript file. Most screens don't care about the signature verification result.
This is unnecessary, so with this PR, we track 2 sets of subscribers — 1 for watching for TokenScript file changes, another for signature verification changes/results.
> Speed up refreshes by not treat signature invalidation as the TokenScript file being modified/updated

- AlphaWallet/AppDelegate.swift
- AlphaWallet/Settings/Types/Constants.swift
This PR is for this functionality:
1. Tap and hold app icon in home screen
2. Choose Scan QR Code
Before this PR, this only work if the app is in the background, inactive. Doing it after a reboot or if the app is killed, only launches the app, but doesn't show the QR scanner.
This was missing in the implementation of #2153
> Fix home screen quick action qr scanner not work with cold launch

- AlphaWallet/Activities/ViewControllers/ActivitiesViewController.swift
Show activity view (like how the base ERC20 describes it for ERC20 tokens send/receive) for native crypto send/receives transactions when they are tapped in the Activity tab.
Prior to this, while these native crypto send/receive transactions are displayed similarly to ERC20 send/receive activities in the Activities tab, they show the transaction details screen when tapped.
And with #2165, tapping the top right button in the Activity View will show the transaction screen
-|-
> Show activity view for native crypto send/receives transactions when they are tapped in the Activity tab.

- AlphaWallet/Browser/Coordinators/DappBrowserCoordinator.swift
- AlphaWallet/Browser/Coordinators/QRCodeResolutionCoordinator.swift
- AlphaWallet/Browser/Coordinators/ScanQRCodeCoordinator.swift
- AlphaWallet/Tokens/Coordinators/AddHideTokensCoordinator.swift
- AlphaWallet/Tokens/Coordinators/NewTokenCoordinator.swift
- AlphaWallet/Wallet/Coordinators/WalletCoordinator.swift
Fixes #2164 
Other than the universal scanner, all the other QR code scanner camera screen can't be closed. This PR fixes this.
> Fix: QR code scanners in the app are broken, besides the universal scanner. The scanner screen don't close

- AlphaWallet/Accounts/Coordinators/AccountsCoordinator.swift
Before the PR, long tap on a watch wallet in "Change Wallet" screen does nothing.
This PR adds an option to copy address when a watched wallet is long tapped.
> Support copy watched wallet's address in list of wallets screen

- AlphaWallet/InCoordinator.swift
Before this PR, even when Activities is enabled, it's still trying to switch to the Transactions tab (which isn't shown)
> Fix: not switching to Activities tab correctly after sending a transaction

- AlphaWallet/InCoordinator.swift
Merge after #2185
Seems like the code to display it has been around for a long time, but was broken for equally long..
> Fix sent notification popup not appearing

- AlphaWallet/Transactions/Coordinators/SingleChainTransactionEtherscanDataCoordinator.swift
Reproduce:
1. Switch to Ropsten
2. Send ETH to self
3. Wait
4. 2 notifications appear for the sent transactions, for ETH received
Looked at the results returned from Etherscan for Ropsten. The same transaction is duplicated there.
> Fix: showing duplicate ETH received notifications for Ropsten

- AlphaWallet/Accounts/Coordinators/AccountsCoordinator.swift
- AlphaWallet/Settings/Coordinators/SettingsCoordinator.swift
> Fix: pushing Advanced Settings screen and List of wallets screen did not hide the tab bar

- AlphaWallet/KeyManagement/EtherKeystore.swift
Before this PR:
1. Watch a wallet W
2. Give it a name N
3. Delete W
4. Watch or import W
Observed
---
W is called N
Expected
---
W is not called N
> Fix: deleting a watched wallet doesn't clean up wallet name storage correctly

- AlphaWallet/Activities/ViewControllers/ActivitiesViewController.swift
> Fix: timestamp not appearing in Activity tab for native crypto transfers

- AlphaWallet/Activities/ViewModels/DefaultActivityCellViewModel.swift
Thus some token value will be shown as 0, eg. USDT which is decimals=6.
-|-
> Fix: default ERC20 send/receive activities always assumed (wrongly) that token decimals = 18

- AlphaWallet/Transfer/Controllers/TransactionConfigurator.swift
- AlphaWallet/Transfer/Coordinators/TransferNFTCoordinator.swift
- AlphaWallet/Transfer/Types/TransactionConfiguration.swift
- AlphaWallet/Transfer/ViewControllers/ConfigureTransactionViewController.swift
- AlphaWallet/Transfer/ViewControllers/ConfirmPaymentViewController.swift
- AlphaWallet/Transfer/ViewControllers/SendViewController.swift
- AlphaWalletTests/Transfer/Controllers/TransactionConfiguratorTests.swift
Closes #2101 
* Estimate gas price and gas limit for all type of transactions
* Estimation of gas price and gas limit for send transactions is now only done in 1 place (not done for TokenScript transactions as well as import ERC875 transactions yet)
* Make sure that when the gas price and limit estimates are retrieved, it is only applied if the user hasn't set their own
* Only provide gas limit estimate if it hasn't already been specified in the transaction (currently only dapp-initiated transactions optionally set this)
> Refactor transaction gas price limit estimating

- AlphaWallet/InCoordinator.swift
- AlphaWallet/Market/Coordinators/UniversalLinkInPasteboardCoordinator.swift
- AlphaWallet/TokenScriptClient/Models/AssetDefinitionStore.swift
This is avoid the scary iOS 14 warning: 'AlphaWallet pasted from <app>' like in the screenshot unnecessarily.
This means only urls copied as a link will be auto detected as MagicLink.
More specifically:
A. if someone selects and uses the cursors on iOS to copy a URL from a passage of text, it will no longer be detected as a MagicLink
B. taps and hold a link on iOS and choose Copy, it will be detected as a MagicLink
C. ctrl-clicks on macOS a link and choose Copy Link and has Universal Clipboard enabled, it will be detected as a MagicLink
This means that if the user copies a URL which is not a MagicLink with (B) or (C), the scary message will still appear.
> Only read specifically for URL(s) in the pasteboard when app is launch/resumed

- AlphaWallet/UI/Form/SliderTextFieldRow.swift
This screen, showing text automatically selected when tapped, so user can just type over it
> Automatically select all text in textfield in gas configuration screen when the textfield is tapped for better usability

- AlphaWallet/Tokens/Types/TokensDataStore.swift
- AlphaWallet/Tokens/ViewControllers/TokensViewController.swift
- AlphaWallet/Transactions/ViewControllers/TransactionsViewController.swift
Fixes #2205 
This was due to an aggressive fix for TokenScript values appearing as NaN previously. This is no longer needed (at least not as aggressively) since we batch RPC calls now.
Reproduce before PR:
1. Look at balance of a token in Wallet tab
2. Send token to someone
3. Wait for transaction to be confirmed
4. Observe balance of token in Wallet tab
Expected
---
5a. Balance updated after a while
Observed
---
5b. Balance seems to be stuck (it's just way too slow), until app is restarted.
> Fix: token balance refreshing in wallet tab is way too slow

- AlphaWallet/Accounts/Coordinators/AccountsCoordinator.swift
- AlphaWallet/Accounts/ViewModels/AccountsViewController.swift
- AlphaWallet/Activities/Coordinators/ActivitiesCoordinator.swift
- AlphaWallet/Activities/ViewControllers/ActivitiesViewController.swift
- AlphaWallet/Activities/ViewControllers/ActivityViewController.swift
- AlphaWallet/Activities/Views/ActivityViewCell.swift
- AlphaWallet/AppCoordinator.swift
- AlphaWallet/InCoordinator.swift
- AlphaWallet/KeyManagement/EtherKeystore.swift
- AlphaWallet/KeyManagement/Keystore.swift
- AlphaWallet/Market/Coordinators/UniversalLinkCoordinator.swift
- AlphaWallet/Tokens/Coordinators/SingleChainTokenCoordinator.swift
- AlphaWallet/Tokens/ViewControllers/TokenInstanceActionViewController.swift
- AlphaWallet/Tokens/Views/TokenInstanceWebView.swift
- AlphaWallet/Transactions/Coordinators/SingleChainTransactionEtherscanDataCoordinator.swift
- AlphaWallet/Transactions/Coordinators/TokensCardCoordinator.swift
- AlphaWallet/UI/Views/TokenCardRowView.swift
- AlphaWallet/Wallet/Coordinators/WalletCoordinator.swift
- AlphaWalletTests/Coordinators/InCoordinatorTests.swift
- AlphaWalletTests/EtherClient/EtherKeystoreTests.swift
- AlphaWalletTests/Factories/FakeKeystore.swift
No functional change.
If the current wallet is nil, something is very wrong and we should crash early rather than populate call sites with guard/`if let` which does nothing meaningful when the current wallet is nil.
Part of effort to reduce meaningless optionals in the code base.
> Refactor: remove most `Wallet?` references for current wallet to get rid of optionals

- AlphaWallet/Activities/Coordinators/ActivitiesCoordinator.swift
- AlphaWallet/Activities/ViewModels/ActivitiesViewModel.swift
- AlphaWallet/Transactions/Coordinators/TransactionDataCoordinator.swift
- AlphaWallet/Transactions/Storage/Transaction.swift
- AlphaWallet/Transactions/ViewControllers/TransactionsViewController.swift
- AlphaWallet/Transfer/Types/SentTransaction.swift
The UI isn't the best (still using the old-style transaction cell), but at least the information displayed is much more useful and correct than before the PR.
> Show pending erc20 transactions as such rather than as 0 eth sends

- AlphaWallet/InCoordinator.swift
- AlphaWallet/Settings/Types/Constants.swift
- AlphaWallet/Settings/Types/RPCServers.swift
> Tap to open Etherscan now opens token page if Ethereum mainnet which provides a richer page than if opened as a contract

- AlphaWallet/Activities/Coordinators/ActivitiesCoordinator.swift
- AlphaWallet/Activities/ViewControllers/ActivitiesViewController.swift
> Make pending ERC20/721 sends in Activity tab be displayed using the new Activity cells rather than old-style transactions

- AlphaWallet/Accounts/Views/AccountViewCell.swift
> Wallet address is truncated in iPhone 5s in the Change/add wallet cell in Settings tab #2259

- AlphaWallet/Activities/ViewControllers/ActivityViewController.swift
- AlphaWallet/Activities/ViewModels/DefaultActivityCellViewModel.swift
- AlphaWallet/Activities/ViewModels/DefaultActivityViewModel.swift
- AlphaWallet/Activities/Views/DefaultActivityItemViewCell.swift
- AlphaWallet/Activities/Views/DefaultActivityView.swift
- AlphaWallet/Localization/en.lproj/Localizable.strings
- AlphaWallet/Localization/es.lproj/Localizable.strings
- AlphaWallet/Localization/ja.lproj/Localizable.strings
- AlphaWallet/Localization/ko.lproj/Localizable.strings
- AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings
- AlphaWallet/Transactions/ViewModels/ActivityViewModel.swift
Closes #2255 
Before PR: failed state | After PR: failed state
-|-
Also after PR for pending state:
> Make text font/weight in Activity tab cells be different to indicate different states

- AlphaWallet/Share/ShareContentAction.swift
Fixes #2289
Before PR:
After PR:
> Open URL in AlphaWallet using share extension doesn't convert % escapes #2289

- AlphaWallet/Transfer/Types/ConfigureTransaction.swift
Closes #2099.
Still a limit because it's quite scary if we remove it completely.
> Raise gas fee max to 3 ETH

- AlphaWallet/Activities/ViewModels/DefaultActivityCellViewModel.swift
- AlphaWallet/Localization/en.lproj/Localizable.strings
- AlphaWallet/Localization/es.lproj/Localizable.strings
- AlphaWallet/Localization/ja.lproj/Localizable.strings
- AlphaWallet/Localization/ko.lproj/Localizable.strings
- AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings
Doesn't look like there's a standard number being used for incredibly large amounts, so this PR just picks an arbitrarily large number.
-|-
> In Activity tab, show "All <symbol>" instead of an very long string of numbers that garbles the display for ERC20 approvals for very large amounts

- AlphaWallet/Transfer/ViewModels/TransactionConfirmationViewModel.swift
> Fix: if enter "" for eth when sending ETH, should show "0 ETH" instead of " ETH"

- AlphaWallet/Transfer/Types/CurrencyRate+Fee.swift
>     Fix: Gas fee estimate in fiat should be displayed when editing custom gas for transaction on mainnet

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet/EtherClient/TrustClient/AlphaWalletService.swift
- AlphaWallet/Gas/Models/GasEstimates.swift
- AlphaWallet/Gas/Models/GasNowGasPriceEstimator.swift
- AlphaWallet/Gas/Models/GasNowPriceEstimates.swift
- AlphaWallet/Localization/en.lproj/Localizable.strings
- AlphaWallet/Localization/es.lproj/Localizable.strings
- AlphaWallet/Localization/ja.lproj/Localizable.strings
- AlphaWallet/Localization/ko.lproj/Localizable.strings
- AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings
- AlphaWallet/Settings/Types/Constants.swift
- AlphaWallet/Transfer/Controllers/TransactionConfigurator.swift
- AlphaWallet/Transfer/Coordinators/TransactionConfirmationCoordinator.swift
- AlphaWallet/Transfer/Types/TransactionConfiguration.swift
- AlphaWallet/Transfer/Types/TransactionConfigurations.swift
- AlphaWallet/Transfer/ViewControllers/ConfigureTransactionViewController.swift
- AlphaWallet/Transfer/ViewModels/ConfigureTransactionViewModel.swift
- AlphaWallet/Transfer/ViewModels/EditedTransactionConfiguration.swift
- AlphaWallet/Transfer/ViewModels/GasSpeedTableViewCellViewModel.swift
- AlphaWallet/Transfer/ViewModels/TransactionConfirmationViewModel.swift
- AlphaWallet/Transfer/Views/GasSpeedTableViewCell.swift
- AlphaWalletTests/Transfer/Controllers/TransactionConfiguratorTests.swift
Closes #2242
* Fetch and show gas estimates from https://www.gasnow.org/api/v3/gas/price
* Show informational footer about gas fee in configure gas/nonce screen
-|-
> Provide rapid/fast/slow (in addition to average and custom) options in actionsheet for transaction confirmation

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet/Browser/Coordinators/QRCodeResolutionCoordinator.swift
- AlphaWallet/Browser/Types/DappAction.swift
- AlphaWallet/Browser/ViewControllers/BrowserViewController.swift
- AlphaWallet/Core/Coordinators/CustomUrlSchemeCoordinator.swift
- AlphaWallet/TokenScriptClient/Models/FunctionOrigin.swift
- AlphaWallet/Tokens/Coordinators/ClaimPaidOrderCoordinator.swift
- AlphaWallet/Tokens/Coordinators/SingleChainTokenCoordinator.swift
- AlphaWallet/Tokens/Coordinators/TokensCoordinator.swift
- AlphaWallet/Tokens/ViewControllers/TokenInstanceViewController.swift
- AlphaWallet/Tokens/ViewControllers/TokenViewController.swift
- AlphaWallet/Tokens/ViewControllers/TokensCardViewController.swift
- AlphaWallet/Tokens/ViewModels/TokenViewControllerViewModel.swift
- AlphaWallet/Tokens/Views/TokenInstanceWebView.swift
- AlphaWallet/Transactions/Coordinators/TokensCardCoordinator.swift
- AlphaWallet/Transfer/Controllers/TransactionConfigurator.swift
- AlphaWallet/Transfer/Coordinators/PaymentCoordinator.swift
- AlphaWallet/Transfer/Coordinators/SendCoordinator.swift
- AlphaWallet/Transfer/Coordinators/TransferNFTCoordinator.swift
- AlphaWallet/Transfer/Types/PaymentFlow.swift
- AlphaWallet/Transfer/Types/TransactionType.swift
- AlphaWallet/Transfer/Types/UnconfirmedTransaction.swift
- AlphaWallet/Transfer/ViewControllers/SendViewController.swift
- AlphaWallet/Transfer/ViewControllers/TransactionConfirmationViewController.swift
- AlphaWallet/Transfer/ViewModels/ConfigureTransactionViewModel.swift
- AlphaWallet/Transfer/ViewModels/SendHeaderViewViewModel.swift
- AlphaWallet/Transfer/ViewModels/SendViewModel.swift
- AlphaWallet/Transfer/ViewModels/TransactionConfirmationViewModel.swift
- AlphaWalletTests/Coordinators/SendCoordinatorTests.swift
- AlphaWalletTests/Factories/UnconfirmedTransaction.swift
Normally wouldn't unnecessarily rename, but the name is just wrong.
> Rename TransferType -> TransactionType. Name was misleading for a long time

- AlphaWallet/Localization/en.lproj/Localizable.strings
- AlphaWallet/Localization/es.lproj/Localizable.strings
- AlphaWallet/Localization/ja.lproj/Localizable.strings
- AlphaWallet/Localization/ko.lproj/Localizable.strings
- AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings
- AlphaWallet/Transfer/ViewModels/TransactionConfirmationViewModel.swift
- AlphaWallet/Transfer/Views/TransactionConfirmationHeaderView.swift
Make the label "Speed (gas)" the same for all transaction types, and fix word wrap
Before PR (TokenScript transactions)|Before PR (others)|After PR (all transactions)
-|-|-
> Tweak gas label in actionsheet for transaction confirmation

- AlphaWallet/Localization/en.lproj/Localizable.strings
- AlphaWallet/Localization/es.lproj/Localizable.strings
- AlphaWallet/Localization/ja.lproj/Localizable.strings
- AlphaWallet/Localization/ko.lproj/Localizable.strings
- AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings
- AlphaWallet/TokenScriptClient/Models/FunctionOrigin.swift
- AlphaWallet/Tokens/Coordinators/SingleChainTokenCoordinator.swift
- AlphaWallet/Transactions/Coordinators/TokensCardCoordinator.swift
- AlphaWallet/Transfer/Coordinators/TransactionConfirmationCoordinator.swift
- AlphaWallet/Transfer/ViewControllers/TransactionConfirmationViewController.swift
- AlphaWallet/Transfer/ViewModels/TransactionConfirmationViewModel.swift
"Enable" Before PR:
"Enable" After PR|"Enable" After PR (expanded)
-|-
Wrap WETH After PR|Wrap WETH After PR (expanded)
-|-
Unwrap WETH after PR|Unwrap WETH after PR (expanded)
-|-
> Show function names, args, and transaction value in actionsheet for TokenScript transactions

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet/Browser/Coordinators/ScanQRCodeCoordinator.swift
- AlphaWallet/Wallet/Coordinators/WalletCoordinator.swift
Fixes #2352. This is based on the `3.11` (365) tag, which was submitted to the appstore (there's a number of commits to master since the submission)
Also disables the "Show My QR Code" button which is related to the crash. It shouldn't be displayed when importing a wallet during onboarding.
-|-
TODOs after merge into `3.11-appstore`:
> Hotfix: Crash if tap camera button while importing a wallet while onboarding #2352

- AlphaWallet/Transfer/ViewControllers/ConfigureTransactionViewController.swift
- AlphaWallet/Transfer/ViewModels/ConfigureTransactionViewModel.swift
Fixes #2359 
If testing, note that Ethereum mainnet and others (especially testnets), have different number of gas options, so different index for the Custom cell which is being updated.
> Refresh custom gas values in actionsheet txn while editing

- AlphaWallet/Transfer/ViewControllers/TransactionConfirmationViewController.swift
Can't discern from the diff, but some ruby code to print out the ascii values:
```ruby
before = 'сontainerView'
p before.each_byte.to_a
after = 'containerView'
p "     " +  after.each_byte.to_a.to_s
```
Output:
```
[209, 129, 111, 110, 116, 97, 105, 110, 101, 114, 86, 105, 101, 119]
"     [99, 111, 110, 116, 97, 105, 110, 101, 114, 86, 105, 101, 119]"
```
> Fix: non-ascii character in variable name

- AlphaWallet/Transfer/Controllers/TransactionConfigurator.swift
- AlphaWallet/Transfer/ViewControllers/ConfigureTransactionViewController.swift
- AlphaWallet/Transfer/ViewModels/ConfigureTransactionViewModel.swift
Before the PR, the red border around the textboxes and error messages only appear when the Save button is tapped.
After the PR, they (dis)appear as the user is typing.
> Make gas limit and gas fee exceed threshold error messages appear immediately rather than wait until user taps Save button

- AlphaWallet/Transfer/ViewModels/EditedTransactionConfiguration.swift
Fixes #2385 
Little chance of it happening, but still.
> Fix: custom gas price appears as 1 in edit custom gas screen if we set it to >= 1000 and saved it

- AlphaWallet/Browser/Coordinators/DappBrowserCoordinator.swift
- AlphaWallet/Browser/Coordinators/QRCodeResolutionCoordinator.swift
- AlphaWallet/Browser/Coordinators/ScanQRCodeCoordinator.swift
- AlphaWallet/Localization/en.lproj/Localizable.strings
- AlphaWallet/Localization/es.lproj/Localizable.strings
- AlphaWallet/Localization/ja.lproj/Localizable.strings
- AlphaWallet/Localization/ko.lproj/Localizable.strings
- AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings
- AlphaWallet/Settings/Types/Config.swift
- AlphaWallet/Tokens/Coordinators/NewTokenCoordinator.swift
- AlphaWallet/Tokens/Coordinators/TokensCoordinator.swift
- AlphaWallet/Transactions/Coordinators/TokensCardCoordinator.swift
- AlphaWallet/Transfer/Coordinators/PaymentCoordinator.swift
- AlphaWallet/Transfer/Coordinators/RequestCoordinator.swift
- AlphaWallet/Transfer/Coordinators/SendCoordinator.swift
- AlphaWallet/Transfer/ViewModels/RequestViewModel.swift
- AlphaWallet/Wallet/Coordinators/WalletCoordinator.swift
- AlphaWallet/WalletConnect/Coordinator/WalletConnectCoordinator.swift
- AlphaWallet/WalletConnect/WalletConnectServer.swift
- AlphaWalletTests/Coordinators/RequestCoordinatorTests.swift
- AlphaWalletTests/Transfer/ViewModels/RequestViewModelTests.swift
Current chain (ID) should only be used by dapp and WalletConnect as the other parts of the app support multichain.
> Refactor to fix unnecessary/wrong access to "current chain id"

- AlphaWallet/Transfer/Coordinators/SendTransactionCoordinator.swift
Not sure if it's needed, but existing code (for sending transactions) does it, so better to be safe.
> Make sure to prefix raw transactions sending initiated by WalletConnect with 0x

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet/InCoordinator.swift
- AlphaWallet/Localization/en.lproj/Localizable.strings
- AlphaWallet/Localization/es.lproj/Localizable.strings
- AlphaWallet/Localization/ja.lproj/Localizable.strings
- AlphaWallet/Localization/ko.lproj/Localizable.strings
- AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings
- AlphaWallet/Settings/Types/RPCServers.swift
- AlphaWallet/Tokens/Coordinators/TokensCoordinator.swift
- AlphaWallet/Tokens/ViewControllers/TokensViewController.swift
- AlphaWallet/WalletConnect/Controllers/SignMessageCoordinatorBridgeToPromise.swift
- AlphaWallet/WalletConnect/Controllers/TransactionConfirmationCoordinatorBridgeToPromise.swift
- AlphaWallet/WalletConnect/Controllers/WalletConnectSessionsViewController.swift
- AlphaWallet/WalletConnect/Coordinator/WalletConnectCoordinator.swift
- AlphaWallet/WalletConnect/Coordinator/WalletConnectSessionCoordinator.swift
- AlphaWallet/WalletConnect/View/WalletConnectRowView.swift
- AlphaWallet/WalletConnect/View/WalletConnectSessionCell.swift
- AlphaWallet/WalletConnect/ViewController/WalletConnectSessionDetailsViewController.swift
- AlphaWallet/WalletConnect/ViewModel/WalletConnectSessionCellViewModel.swift
- AlphaWallet/WalletConnect/WalletConnect+UserDefaults.swift
- AlphaWallet/WalletConnect/WalletConnectServer.swift
- AlphaWalletTests/Settings/ConfigTests.swift
Closes #2398, closes #2396
Before this PR, WalletConnect sessions connect to the chain selected in the browser tab.
After this PR is applied, the user will be asked to choose the (enabled) chain to connect to when opening a WalletConnect session:
and when there are more than 1 active session, a list of sessions is shown:
> Add multi-session support to WalletConnect

- AlphaWallet/Browser/Types/DappAction.swift
- AlphaWallet/TokenScriptClient/Models/FunctionOrigin.swift
- AlphaWallet/Tokens/Coordinators/ClaimPaidOrderCoordinator.swift
- AlphaWallet/Transfer/Controllers/TransactionConfigurator.swift
- AlphaWallet/Transfer/Coordinators/TransferNFTCoordinator.swift
- AlphaWallet/Transfer/Types/UnconfirmedTransaction.swift
- AlphaWallet/Transfer/ViewControllers/SendViewController.swift
- AlphaWallet/WalletConnect/Types/UnconfirmedTransaction+Extensions.swift
- AlphaWalletTests/Factories/UnconfirmedTransaction.swift
> Fix: ERC20 token transactions are sent wrong to the recipient address. Should send to contract instead

- AlphaWallet/WalletConnect/Coordinator/WalletConnectSessionCoordinator.swift
- AlphaWallet/WalletConnect/ViewController/WalletConnectSessionDetailsViewController.swift
> Remove the Signed Transactions cell from the WalletConnect session screen, which does nothing when tapped anyway

- AlphaWallet/InCoordinator.swift
- AlphaWallet/WalletConnect/Coordinator/WalletConnectCoordinator.swift
- AlphaWalletTests/Settings/ConfigTests.swift
> Fix: make gas and Ether `value` in fiat appear in actionsheet for confirming transactions initiated by WalletConnect

- AlphaWallet/AppCoordinator.swift
- AlphaWallet/InCoordinator.swift
- AlphaWallet/Market/Coordinators/UniversalLinkCoordinator.swift
i.e. when user access a dapp on their iOS device, they get to see AlphaWallet in the list to use WalletConnect against in this screen:
This is described in https://docs.walletconnect.org/mobile-linking
The actual flow isn't testable directly yet, as we'll have to submit a PR to WalletConnect's repo to register our universal link. This can happen only after this PR is merged and the app is submitted + approved. It still might take a while to appear in dapps that support WalletConnect as I'm not sure whether the list of wallet apps/universal links is dynamically fetched by the WalletConnect dapp-side SDK..
One way to test now is to go to a dapp, choose WalletConnect to generate the the QR code, scan it to get the URL and form such a URL manually: …
> Add mobile linking support for WalletConnect

- AlphaWallet/Browser/Coordinators/DappBrowserCoordinator.swift
- AlphaWallet/Browser/Types/DappAction.swift
- AlphaWallet/Browser/Types/DappCommand.swift
- AlphaWallet/Core/Types/AlphaWalletAddress.swift
- AlphaWallet/KeyManagement/EtherKeystore.swift
- AlphaWallet/Tokens/Views/TokenInstanceWebView.swift
- AlphaWallet/Transfer/Coordinators/SignMessageCoordinator.swift
- AlphaWallet/Transfer/ViewModels/ConfirmSignMessageViewControllerViewModel.swift
- AlphaWallet/Vendors/TrustCore/ABIEncoder.swift
- AlphaWallet/Vendors/TrustCore/ABIValue.swift
- AlphaWallet/WalletConnect/Coordinator/WalletConnectCoordinator.swift
- AlphaWallet/WalletConnect/Types/EIP712TypedData.swift
- AlphaWallet/WalletConnect/Types/WalletConnectActionType.swift
- AlphaWallet/WalletConnect/Types/WalletConnectServerRequest.swift
- AlphaWallet/WalletConnect/WalletConnectServer.swift
Note that this was tested against https://danfinlay.github.io/js-eth-personal-sign-examples/ in the dapp browser rather than with WalletConnect.
The bulk of the change is in `EIP712TypedData.swift`.
This PR doesn't work in the dapp browser though because there are a few missing things:
* The version of `HookedWalletSubprovider` included and used by the web3 provider doesn't support EIP712v3
* `web3.currentProvider.sendAsync({ method: 'net_version', ... })` doesn't work in our dapp browser
The above were temporarily fixed during development for testing. Will follow up with separate PR(s) if we can fix them properly and enable EIP712v3 for the dapp browser.
> Fix EIP712 v3 support for WalletConnect

- AlphaWallet/Localization/en.lproj/Localizable.strings
- AlphaWallet/Localization/es.lproj/Localizable.strings
- AlphaWallet/Localization/ja.lproj/Localizable.strings
- AlphaWallet/Localization/ko.lproj/Localizable.strings
- AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings
- AlphaWallet/WalletConnect/Coordinator/WalletConnectCoordinator.swift
- AlphaWallet/WalletConnect/WalletConnectServer.swift
- Podfile
- Podfile.lock
If `chainId` is provided in the incoming request:
-|-
> Use the chainId in the WalletConnect connection request, if provided and don't ask the user to choose chain

- AlphaWallet/WalletConnect/Controllers/WalletConnectSessionsViewController.swift
- AlphaWallet/WalletConnect/Coordinator/WalletConnectCoordinator.swift
- AlphaWallet/WalletConnect/ViewController/WalletConnectSessionDetailsViewController.swift
- AlphaWallet/WalletConnect/ViewModel/WalletConnectSessionCellViewModel.swift
- AlphaWallet/WalletConnect/ViewModel/WalletConnectSessionDetailsViewModel.swift
> Display the chain which each WalletConnect session is connected for

- AlphaWallet/Extensions/Session+PromiseKit.swift
- AlphaWallet/Localization/en.lproj/Localizable.strings
- AlphaWallet/Localization/es.lproj/Localizable.strings
- AlphaWallet/Localization/ja.lproj/Localizable.strings
- AlphaWallet/Localization/ko.lproj/Localizable.strings
- AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings
Closes #2441.
Easiest way to reproduce is to send 0 eth on a testnet without funds.
> Display more user-friendly message when there's not enough funds for sending a transaction instead of: "APIKit.Session-TaskError error 2"

- AlphaWallet/Browser/Coordinators/DappBrowserCoordinator.swift
- AlphaWallet/Browser/Types/DappAction.swift
- AlphaWallet/Browser/Types/DappCommand.swift
- AlphaWallet/Tokens/Views/TokenInstanceWebView.swift
- AlphaWallet/Transfer/Coordinators/SignMessageCoordinator.swift
- AlphaWallet/Transfer/ViewControllers/ConfirmSignMessageViewController.swift
- AlphaWallet/Transfer/ViewModels/ConfirmSignMessageViewControllerViewModel.swift
- AlphaWallet/WalletConnect/Coordinator/WalletConnectCoordinator.swift
- AlphaWallet/WalletConnect/Types/EIP712TypedData.swift
* Pretty print the EIP712v3 or v4 message to be signed
* Also display the `domain` information
The second commit is just a rename for the enum-case and var name.
Barring bugs or tweaks to the UI, this should close everything EIP712 for a while.
-|-
> Pretty print the Eip712v3 or v4 message to be signed

- AlphaWallet/Transfer/Coordinators/TransactionConfirmationCoordinator.swift
- AlphaWallet/Transfer/ViewControllers/TransactionConfirmationViewController.swift
Fixes #2430
Will likely follow up with a separate PR that disables the "Confirm" button briefly when the price changes.
> Fix: refresh actionsheet (for transaction confirmation) as soon as gas estimates are back instead of waiting for the next gas price refresh.

- AlphaWallet/Transfer/Coordinators/TransactionConfirmationCoordinator.swift
- AlphaWallet/Transfer/ViewControllers/TransactionConfirmationViewController.swift
> Disable actionsheet's (for transaction confirmation) Confirm button briefly when the gas fee displayed changes so the user has the chance to review

- AlphaWallet/WalletConnect/Types/EIP712TypedData.swift
Fixes #2480 fixes #2462
Reproducible with https://example.walletconnect.org
> Fix: signing of EIP712 message which includes bytes

- AlphaWallet/Browser/Coordinators/DappBrowserCoordinator.swift
- AlphaWallet/Browser/Types/DAppError.swift
- AlphaWallet/Browser/ViewControllers/BrowserViewController.swift
Closes #2516.
This fixes the problem where the dapp makes an `eth_call` which fails and blocks on it and get stuck if the `eth_call` fails.
Pseudo code for dapp:
```
let tokenName = await contract.getName() //uses eth_call underneath
//do something else. Never reach here since we don't return an error, the promise above don't reject
```
> Fix: dapp web3 provider needs to invoke Dapp's callbacks for `eth_call` when an error has occurred

- AlphaWallet/Market/Coordinators/UniversalLinkCoordinator.swift
Related to #2498
This is the WalletConnect mobile link referred to:
When the user taps on the AlphaWallet icon which is a link to a universal link with a WalletConnect link embedded in it,
Before PR: the link is not parsed correctly (I think either an old version or the one given in the docs doesn't URL encode the WalletConnect link)
After PR: the link is now parsed correctly
> Fix: parse WalletConnect links picked up from mobile linking

- AlphaWallet/AppCoordinator.swift
- AlphaWallet/Browser/Coordinators/DappBrowserCoordinator.swift
- AlphaWallet/Browser/ViewControllers/BrowserViewController.swift
- AlphaWallet/InCoordinator.swift
- AlphaWallet/Market/Coordinators/UniversalLinkCoordinator.swift
Related to #2498 and #2528
Make sure that when WalletConnect and mobile link button is used in the dapp browser, we connect to WalletConnect properly instead of opening the universal link  in the dapp browser
> Fix: handle WalletConnect links when the mobile link is launched in dapp browser

- AlphaWallet/EtherClient/ChainState.swift
- AlphaWallet/Extensions/Session+PromiseKit.swift
> Fix: Disable error about malformed JSON if it appears to be caused by Binance testnet timing out (as there's nothing we can do about it)

- Podfile
- Podfile.lock
> Fix: xDai chain access (actually all chainId >= 16) broken in dapp browser

- AlphaWallet/Protection/Coordinators/ProtectionCoordinator.swift
Fixes #2137 
Not sure if it's reproducible easily. I spotted this on my phone and debugged against it. A possible reason might be this message:
> Unbalanced calls to begin/end appearance transitions for <AlphaWallet.SplashViewController: 0x10b40b7e0>.
We might improve the way the splash screen is displayed, but in this case just not attempting to show it at launch still seems to work correctly.
> Fix: hang at splash screen at launch

- AlphaWallet/Extensions/Session+PromiseKit.swift
Users sees: "insufficient funds for gas * price + value"
Should see: "Not enough funds to send this transaction".
Introduced in #2449, but broken for some chains because of case sensitivity matching (they don't all show the exact same message, eg. xDai: "Insufficient funds. The account you tried to send transaction from does not have enough funds. Required 1000021000000000000 and got: 0.", Goerli: "insufficient funds for gas * price + value"
> Fix: error message shown when user doesn't have enough funds for sending a transaction (send amount + gas) is not user friendly

- AlphaWallet/Transfer/Coordinators/SendTransactionCoordinator.swift
> Use promise instead of callback for sending raw transaction from WalletConnect so it's more consistent and easier to log errors

- AlphaWallet/TokenScriptClient/Models/FunctionOrigin.swift
They aren't implemented. While harmless to call, they introduce error messages to our logs which could be puzzling
> PromiseKit:cauterized-error: execution reverted
> Remove unnecessary call to name and symbol for ENS token

- AlphaWallet/Transfer/Coordinators/SignMessageCoordinator.swift
Fixes #2617 
https://web3js.readthedocs.io/en/v1.2.7/web3-eth-accounts.html#sign
This breaks compatibility with https://xcontract.herokuapp.com/sign. Will have to observe if there'll be reports of this breaking other dapps.
> Switching `eth_sign` to sign personal as web3.js v1 (unlike v0.20.x) and probably other modern libraries expect so

- AlphaWallet/Transfer/ViewModels/TransactionConfirmationViewModel.swift
> Fix: amount of ERC20 to send in actionsheet for transaction confirmation is displayed incorrectly

- AlphaWallet/Browser/ViewModel/Dapps.swift
If bug:
Fixes #
If not a bug:
Closes #
Added [SCV.finance](https://scv.finance), a tool to manage DeFi portfolio on multiple chains.
> Add SCV.Finance as an dApp

- AlphaWallet/AppCoordinator.swift
- AlphaWallet/Core/Features.swift
- AlphaWallet/Settings/ViewControllers/AdvancedSettingsViewController.swift
- AlphaWallet/Settings/ViewControllers/SupportViewController.swift
- AlphaWallet/Settings/ViewModels/AdvancedSettingsViewModel.swift
- AlphaWallet/Tokens/ViewControllers/TokensViewController.swift
Followup #2666
Closes #2655, fixes #2596
Decimal separators doesn't seem to get overridden as expected in newer iOS versions.
> Hide in-app language setting

- AlphaWallet/Core/Features.swift
- AlphaWallet/TokenScriptClient/Models/XMLHandler.swift
Temporarily until the web API is working again
> Load TokenScript file even if signature verification fails (because signature verification web API isn't working properly)

- AlphaWallet/Accounts/Coordinators/AccountsCoordinator.swift
- AlphaWallet/Accounts/ViewControllers/AccountsViewController.swift
- AlphaWallet/Core/Views/AddressOrEnsNameLabel.swift
- AlphaWallet/InCoordinator.swift
- AlphaWallet/Settings/Coordinators/ServersCoordinator.swift
- AlphaWallet/Settings/Types/Config.swift
- AlphaWallet/Settings/Types/RPCServers.swift
- AlphaWallet/Tokens/Coordinators/GetWalletNameCoordinator.swift
- AlphaWallet/Tokens/Coordinators/TokensCoordinator.swift
- AlphaWallet/Tokens/ViewControllers/TokenInstanceViewController.swift
- AlphaWallet/Tokens/ViewControllers/TokensCardViewController.swift
- AlphaWallet/Tokens/ViewModels/TokensViewModel.swift
- AlphaWallet/Transfer/Types/RecipientResolver.swift
- AlphaWallet/Transfer/ViewControllers/RequestViewController.swift
- AlphaWallet/UI/AddressTextField.swift
After #2689 is merged.
This PR gets rid of most cases where `.main` is referenced directly. After this PR is merged, any direct reference to `.main` that is not in `switch-case` should be watched with caution.
> Refactor make clear when rpcserver main is accessed explicitly

- AlphaWallet/Settings/ViewControllers/EnabledServersViewController.swift
Before this PR, the code was trying to disable the left navigation item (because some time ago, this screen was presented modally instead of pushed onto a navigation controller), which did nothing any way.
> Clarify that we don't disable the back button in the network selector even when no network is selected

- AlphaWallet/Core/SwapToken/Oneinch/ERC20Token.swift
- AlphaWallet/Core/SwapToken/Oneinch/Oneinch.swift
- AlphaWallet/EtherClient/TrustClient/AlphaWalletService.swift
Fixes: #2711 
The version 1.1 of the web API we were using seems no longer work and the latest is v3.0. The response has changed from
```
{
"0x2688213fedd489762a281a67ae4f2295d8e17ecc" : {
"logoURI" : "https://tokens.1inch.exchange/0x2688213fedd489762a281a67ae4f2295d8e17ecc.png",
"address" : "0x2688213fedd489762a281a67ae4f2295d8e17ecc",
"name" : "FUD.finance",
"decimals" : 18,
"symbol" : "FUD"
},
```
to:
```
{
"tokens" : {
"0x2688213fedd489762a281a67ae4f2295d8e17ecc" : {
"logoURI" : "https://tokens.1inch.exchange/0x2688213fedd489762a281a67ae4f2295d8e17ecc.png",
"address" : "0x2688213fedd489762a281a67ae4f2295d8e17ecc",
"name" : "FUD.finance",
"decimals" : 18,
"symbol" : "FUD"
},
```
> Fix: Oneinch (swap) service broken because web API is no longer valid

- AlphaWallet/Core/SwapToken/SwapTokenService.swift
The "magic" search keyword in the wallet tab "swap" was returning wrong set of results because the condition was inverted, i.e. `isEmpty` instead of `!isEmpty`.
> Fix: special search keyword in wallet 'swap' returned wrong results

- AlphaWallet/Core/DecodedFunctionCall.swift
- AlphaWallet/Core/Ethereum/ABI/DecodedFunctionCall+Decode.swift
- AlphaWallet/EtherClient/TrustClient/Models/RawTransaction.swift
- AlphaWallet/Transactions/Storage/Transaction.swift
* Also fix naming "sender" -> "spender" for ERC20 approvals
> Fix: detecting of transactions for ERC20 approvals broken when downloading transaction history

- AlphaWallet/Core/Ethereum/ABI/DecodedFunctionCall+Decode.swift
Otherwise might be easy to extract the wrong argument. eg. in the future we'll have which has 2 addresses:
```
function transferFrom(address _from, address _to, uint256 _value) public returns (bool success)
```
> Make extracting arguments from Transaction function calls be more explicit and safer

- AlphaWallet/Tokens/Coordinators/GetContractInteractions.swift
> Fix: ERC20 receive transactions are displayed wrongly with an additional (erroneous) receive ETH with the same amount

- AlphaWallet/Browser/ViewModel/Dapps.swift
Closes #2779 
[Not a dApp] 
Kyber Migration Portal: https://kyber.org/migrate
Category: "Token Migration" 
Background: KIP6: a Kyber Token Upgrade
For KNC holders managing their own tokens on self-custodial wallets such as Alphawallet, they can connect to the Kyber Migration Portal to Alphawallet and convert to the new KNC token on their own.
Old KNC token contract: 0xdd974d5c2e2928dea5f71b9825b8b646686bd200
New KNC token contract: 0xdeFA4e8a7bcBA345F687a2f1456F5Edd9CE97202
Migration ratio: 1:1 (1 old KNC will be migrated to 1 new ERC-20 KNC token)
Timeline:
Migration began Tuesday 20 April 9pm SGT.
Migration process has no hard deadline and is open-ended (as of writing).
No rush to convert to the new KNC tokens.
More info:
https://blog.kyber.network/knc-token-migration-guide-fda08bfe62c2 …
> Add Kyber Migration Portal  to convert legacy KNC into ERC20 KNC tokens

- AlphaWallet/Activities/Coordinators/ActivitiesCoordinator.swift
When `TokenBalance.balance` is "{}"
> Fix: crash when we write and then read OpenSea data which is empty for a token

- AlphaWallet/Core/Types/ServerDictionary.swift
- AlphaWallet/InCoordinator.swift
Fixes #2798 
Reproduce before PR:
1. Enable ETH and xDai
2. Disable xDai
3. Might crash within a few seconds.
Repeat 1-3 a few times to crash.
> Fix: crash sometimes right after switch networks if price is refreshed just before the TokensStorage is destroyed

- AlphaWallet/Browser/ViewModel/Dapps.swift
Added Matic Faucet dApp after testing 3 Matic faucets: 
Tested 3 sites on Alphawallet browser: 
Works - https://faucet.matic.network/ ---> Matic Faucet for Testnet Tokens on Mumbai, Goerli, and DA Testnet (successful txns, ADDED ENTRY) 
Issues - https://wallet.matic.network/faucet/ ---> Matic Faucet for Ropsten Testnet Tokens (requires tweet, did not authenticate) 
Issues - https://matic.supply/ ---> Matic Faucet for 0.001 MATIC Tokens on Polygon Network (connected to Alphawallet, click receive, but threw error "undefined"
*PR Entry has been made to keep Android and iOS dApp list in sync, but understand this will not be shipped to index of dapps anymore until Apple changes mind (iOS app store review policy).
> Add Matic Faucet for Testnet Tokens to dApp list

- AlphaWallet/Browser/ViewModel/Dapps.swift
Add Utility dApps to list: 
https://ethgasstation.info - Consumer oriented metrics for Eth Gas Market
https://www.gasnow.org/ - Eth Gas Price forecast system
Submitting in iOS to keep track of dapp list. Also in Android: https://github.com/AlphaWallet/alpha-wallet-android/pull/1876
> Add Gas Fee Estimator utility to dApps list

- AlphaWallet/InCoordinator.swift
- AlphaWallet/Settings/Types/Constants.swift
- AlphaWallet/Settings/Types/RPCServers.swift
- AlphaWallet/Tokens/Coordinators/GetContractInteractions.swift
Started out as refactoring to clean up after #2819 and #2829, but found bugs related in transaction fetching and token detection for several chains.
* Fixed token autodetection for several chains
* ARTIS sigma1
* ARTIS tau1
* Sokol
* Callisto
* Binance and testnet
* Heco and testnet
* Mumbai testnet
* Refactoring of how and where Etherscan API and web URLs are specified
> Fixed token autodetection for several chains + refactoring

- AlphaWallet/Core/BuyToken/Ramp/Ramp.swift
- AlphaWallet/Core/CoinTicker/CoinTickersFetcher.swift
- AlphaWallet/Core/DomainResolver.swift
- AlphaWallet/Core/SwapToken/HoneySwap/HoneySwap.swift
- AlphaWallet/Core/SwapToken/Oneinch/Oneinch.swift
- AlphaWallet/Core/SwapToken/Uniswap/UniswapERC20Token.swift
- AlphaWallet/EtherClient/OpenSea.swift
- AlphaWallet/EtherClient/TrustClient/AlphaWalletService.swift
- AlphaWallet/InCoordinator.swift
- AlphaWallet/Localization/en.lproj/Localizable.strings
- AlphaWallet/Market/Coordinators/UniversalLinkCoordinator.swift
- AlphaWallet/Settings/Coordinators/ServersCoordinator.swift
- AlphaWallet/Settings/Types/ConfigExplorer.swift
- AlphaWallet/Settings/Types/Constants.swift
- AlphaWallet/Settings/Types/RPCServers.swift
- AlphaWallet/Tokens/Coordinators/GetContractInteractions.swift
- AlphaWallet/Tokens/Coordinators/SingleChainTokenCoordinator.swift
- AlphaWallet/Tokens/Types/TokenCollection.swift
- AlphaWallet/Tokens/ViewModels/TokenViewControllerViewModel.swift
- AlphaWallet/Transactions/Coordinators/SingleChainTransactionEtherscanDataCoordinator.swift
- AlphaWallet/Transfer/Controllers/TransactionConfigurator.swift
- AlphaWallet/Transfer/Coordinators/SendTransactionCoordinator.swift
Only after #2841 is merged, because it includes commits from that PR.
Comments in the code which explains the rationale:
> We just filter out those that we don't think are supported by the API. One problem this helps to alleviate is in the API output, certain tickers have a non-empty platform yet the platform list might not be complete, eg. Ether on Ethereum mainnet:
> {
>    "symbol" : "eth",
>    "id" : "ethereum",
>    "name" : "Ethereum",
>    "platforms" : {
>       "huobi-token" : "0x64ff637fb478863b7468bc97d30a5bf3a428a1fd",
>       "binance-smart-chain" : "0x2170ed0880ac9a755fd29b2688956bd959f933f8"
>    }
> },
> This means we can only match solely by symbol, ignoring platform matches. But this means it's easy to match the wrong ticker (by symbol only). Hence, we at least remove …
> Remove price ticker matching completely for unsupported chains to reduce erroneous matching

- AlphaWallet/Core/CoinTicker/CoinTickersFetcher.swift
Specifically:
This "360APP" token (symbol=DAPP) [1] has at least 2 false positives when they are different tokens. They no longer match if we check the names too.
[1] https://etherscan.io/token/0x5D0fa08AEb173AdE44B0Cf7F31d506D8E04f0ac8
> Improve price matching false positives

- AlphaWallet/Browser/Types/DappCommand.swift
Fixes #2839 
Example payload (note the encodeAbi = false):
```
{
"object" : {
"to" : "0x5d0fa08aeb173ade44b0cf7f31d506d8e04f0ac8",
"nonce" : "0x76",
"chainType" : "ETH",
"gas" : "0xb51c",
"gasPrice" : "0x2b06f0380",
"data" : "0x095ea7b300000000000000000000000040ec5b33f54e0e8a33a975908c5ba1c14e5bbbdfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff",
"encodeAbi" : false,
"chainId" : 1,
"from" : "0xbbce83173d5c1d122ae64856b4af0d5ae07fa362",
"value" : "0x0"
},
"name" : "signTransaction",
"id" : 8888
}
```
> Fix: when a dapp asks to sign a transaction and has a bool in the payload, actionsheet doesn't appear

- AlphaWallet/Tokens/Types/TokensDataStore.swift
There can be many "execution reverted" errors (especially obvious if looking with Charles proxy). Many of these are caused by checking the token type for ERC875, with the function hash `0x4f452b9a`.
This PR adds a comment, including the hash so this can be more easily discovered as well as a TODO to how to improve it.
> Add comment for clarify about frequent "execution reverted" RPC node errors

- AlphaWallet/EtherClient/TrustClient/AlphaWalletService.swift
- AlphaWallet/Settings/Types/RPCServers.swift
Make it clearer where the API key is used.
This still has the limitation that we are sometimes sending the Etherscan API key to sites that are based on Etherscan (not Blockscout), but is actually not Etherscan, eg. https://ftmscan.com for `.fantom`. This should be harmless, so leave it for now.
> Refactor to make sending Etherscan API key clearer

- AlphaWallet/Activities/Views/GroupActivityViewCell.swift
Closes #2850 
Temporarily solution until we implement the real thing (want to have a build we can ship first).
-|-
Final form (not in this PR):
> Tweak height of 'Contract Execution' cell in Activity tab

- AlphaWallet/Settings/Types/RPCServers.swift
Because `action=tokennfttx` is supported:
> curl 'https://api.bscscan.com/api?module=account&action=tokennfttx&address=0x007bEe82BDd9e866b2bd114780a47f2261C684E3'
> {"status":"0","message":"No transactions found","result":[]}
Doesn't say: "Unknown action"
> Fix: Binance explorer APIs wrongly taken as Blockscout. Should be Etherscan

- AlphaWallet/Settings/Types/RPCServers.swift
> Standardize to use `startblock=` in Etherscan APIs as `startBlock=` only works with xxx.etherscan.io, but not BlockScout

- AlphaWallet/Tokens/ViewModels/NonFungibleTokenViewCellViewModel.swift
> Show '1 <symbol>` instead of `1 Tickers` in Wallet tab for NFTs

- AlphaWallet/Settings/Types/RPCServers.swift
Old ones are deprecated. Inline with Android's https://github.com/AlphaWallet/alpha-wallet-android/pull/1896
> Update Polygon explorer endpoints

- AlphaWallet/Tokens/Types/NonFungibleFromTokenUri.swift
- AlphaWallet/Tokens/Types/TokensDataStore.swift
This was already read from the OpenSea API results. But if the ERC721 token isn't found in OpenSea, we would fallback to the `tokenURI` for the token metadata.
This PR makes it so that we look for the token's permalink in that metadata when we read `tokenURI`directly.
> Read token instance permalink from ERC721 token for those source directly from smart contract + JSON metadata (i.e not from OpenSea)

- AlphaWallet/Browser/Factory/WKWebViewConfiguration.swift
Before PR:
```
(new Web3(window.web3.currentProvider)).version.getNetwork(function(e, chainId) { console.log(chainId) })
```
> 128
After PR:
```
(new Web3(window.web3.currentProvider)).version.getNetwork(function(e, chainId) { console.log(chainId) })
```
> 0x80
After the PR, it will be consistent with this:
```
await ethereum.request({method: 'eth_chainId'})
```
> "0x80"
and adhere to how JSON RPC hex value is encoded according to https://eth.wiki/json-rpc/API
> Make chain ID returned by `web3.version.getNetwork()` be hex encoded

- AlphaWallet/Settings/Coordinators/SettingsCoordinator.swift
Would you look in the diff for the read-only property that's removed by this PR? Seems the property is unnecessary.
> Refactor: rename var to remove leading _

- AlphaWallet/Tokens/Types/TokensDataStore.swift
- AlphaWallet/Transactions/Storage/TransactionsStorage.swift
This is for tokens source directly from blockchain explorer APIs, not from OpenSea.
Fixes: #2917 
ie. given a token with transactions in this sequence:
1. Receive tokenId 11 //balance 1, ok
2. Receive tokenId 23 //balance 2, ok
3. Sent tokenId 11 //balance 1, ok
4. Sent tokenId 23 //balance still 1, wrong, should be 0.
> Fix: ERC721 token balance which has become 0 aren't zeroed-out correctly

- AlphaWallet/Tokens/Types/TokensDataStore.swift
- AlphaWallet/Transactions/Storage/TransactionsStorage.swift
Code isn't used in production, but we can write something like this for examining transactions during debugging:
```
let server: RPCServer = .rinkeby
guard let datastore = tokenDataStores.first(where: { $0.server == server }) else { return }
datastore.writeJsonForTransactions(toUrl: URL(string: "file:///Users/hboon/Desktop/transactions.json")!)
```
Output looks something like this:
```
[
{
"operations" : [],
"transactionHash" : "0x1bdef25def9066bf2c24250405ef0790d880cc98eb527d2ee0378e892161fb80"
},
{
"operations" : [
{
"contract" : "0x9693a618E4FC4912986b2e5342A82BaC47CF4d52",
"from" : "0xc6de318431867f9a46ea8d5a5dd383093c797cd6",
"to" : "0xbbce83173d5c1d122ae64856b4af0d5ae07fa362",
"tokenId" : "22700797609544887914633724561329530711386729212148302025067786624739445834752"
}
], …
```
> Add debugging code that lets us dump transaction data to a JSON file

- Podfile
- Podfile.lock
Fixes #2758 
Involves this PR: https://github.com/AlphaWallet/AlphaWallet-web3-provider/pull/19
> Set `ethereum.chainId` in dapp browser. Some dapps (e.g https://omni.xdaichain.com/bridge) expect it

- AlphaWallet/EtherClient/OpenSea.swift
- AlphaWallet/Settings/Types/Constants+Credentials.swift
- AlphaWallet/Settings/Types/Constants.swift
And so we can swap those keys for production builds.
> Refactor, move remaining API keys in `Constants.swift` to `Constants+Credentials.swift`

- AlphaWallet.xcworkspace/xcshareddata/xcschemes/AlphaWallet.xcscheme
- AlphaWallet.xcworkspace/xcshareddata/xcschemes/AlphaWalletTests.xcscheme
This PR adds a pre-build script to get rid of this error which causes tests not to run at all:
> ❌  error: Build input file cannot be found: '/Users/travis/build/AlphaWallet/alpha-wallet-ios/AlphaWallet/R.generated.swift' (in target 'AlphaWallet' from project 'AlphaWallet')
> Fix: Travis not running tests at all because R.generated.swift is not present in clean builds

- AlphaWallet/Tokens/Coordinators/GetContractInteractions.swift
- AlphaWallet/Tokens/Coordinators/SingleChainTokenCoordinator.swift
- AlphaWallet/Transactions/Coordinators/SingleChainTransactionEtherscanDataCoordinator.swift
Also switching the affected code from completion blocks to PromiseKit. I think it makes clearer that [GetContractInteractions.swift](https://github.com/AlphaWallet/alpha-wallet-ios/compare/refactor-extract-out-functional-code-promisekit?expand=1#diff-5c0f118276d9837f1d1a72bd3dd3fbe44f946b696c33fd351431f677d7c71caf) doesn't mutate state, since the interface functions only call functional code (without having to change the callers to call the static functions directly. I'm hoping the functional interfaces are never/seldom exposed.)
Some parts like [this](https://github.com/AlphaWallet/alpha-wallet-ios/compare/refactor-extract-out-functional-code-promisekit?expand=1#diff-4902c50a135f139a6c1960fb7a536bfcba64af0a20777c986ea276b64a459e95R100) in `SingleChainTransactionEtherscanDataCoordinator` …
> Refactor: move code that doesn't mutate state

- AlphaWallet/Market/Coordinators/UniversalLinkCoordinator.swift
- AlphaWallet/Tokens/Coordinators/NewTokenCoordinator.swift
- AlphaWallet/Tokens/Coordinators/SingleChainTokenCoordinator.swift
- AlphaWallet/Tokens/Helpers/TokenAdaptor.swift
- AlphaWallet/Tokens/Types/TokenObject.swift
- AlphaWallet/Tokens/ViewControllers/NewTokenViewController.swift
- AlphaWalletTests/Tokens/Helpers/TokenObjectTest.swift
Part of #2972
ERC875 considered `0` as a nulled out token instance, be it burnt or transferred. But `0` is a valid ERC721 token ID. e.g. https://bscscan.com/tx/0xf6f3ddbb6719d8e47a47cf8ec66853682c02f03626cc4c4f5ece9338a8f20aee
> Fix: detection of (non-zero) balance for NFTs, specifically ERC721

- AlphaWallet/Settings/Types/Constants+Credentials.swift
- AlphaWallet/Settings/Types/RPCServers.swift
Part of #2972
Also makes sure to not include the Etherscan Api for etherscan-like sites. They might error out if we included invalid keys.
> Add API key for binance smart chain

- AlphaWallet/EtherClient/OpenSea.swift
Before the PR, we passed `limit=200`. The API endpoint used to apply the max (`50`) it can take. It now error outs
After the PR, we send `limit=50` instead.
> Fix: OpenSea API doesn't allow limits that are too big to be passed to it anymore

- AlphaWallet/Core/CoinTicker/CoinTickersFetcher.swift
Note that we cache the matched price data for 1 hour. So the effects of the PR is not visible immediately if the cache is warm.
> Fix: Polygon native token not showing price

- AlphaWallet/Localization/en.lproj/Localizable.strings
- AlphaWallet/Localization/es.lproj/Localizable.strings
- AlphaWallet/Localization/ja.lproj/Localizable.strings
- AlphaWallet/Localization/ko.lproj/Localizable.strings
- AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings
- AlphaWallet/Wallet/ViewControllers/SeedPhraseBackupIntroductionViewController.swift
Fixes https://github.com/AlphaWallet/alpha-wallet-ios/issues/2985
[x] kill the thin, top, gray line
[x] break down the text into
[x] Increase the picture size
[x] Make the text break accordingly
[ ] Move the bottom button a bit more to the top -> Remain out of scope because of dependency on other views.
> 2985 improve backup screen

- AlphaWallet/Settings/Types/RPCServers.swift
- AlphaWallet/Tokens/Types/TokensDataStore.swift
> Fix: remove duplicate ETH token for Optimistic mainnet and testnet — remove the native token when the ERC20 equivalent is in the database

- AlphaWallet/Tokens/Coordinators/AddHideTokensCoordinator.swift
Fixes #3045 
Problem is the popular token list needs to be filtered for enabled chains.
> Fix: "Add token failure" error when tap to add popular tokens in Add/Hide token screen

- AlphaWallet/Browser/Coordinators/DappBrowserCoordinator.swift
Closes #3088 
Because of previous change to the navigation stack which is still in-flight animation
> Fix: dapp browser is not reloading the previous URL after switching networks in-app (i.e not triggered by the dapp)

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet/AppDelegate.swift
- AlphaWallet/Core/Coordinators/WalletBalance/PrivateBalanceFetcher.swift
- AlphaWallet/Core/Ethereum/ABI/ERC1155.json
- AlphaWallet/EtherClient/OpenSea.swift
- AlphaWallet/Tokens/Coordinators/TokensCoordinator.swift
- AlphaWallet/Tokens/Logic/Erc1155BalanceFetcher.swift
- AlphaWallet/Tokens/Logic/Erc1155TokenIdsFetcher.swift
- AlphaWallet/Tokens/Types/NonFungibleFromJson.swift
- AlphaWallet/Tokens/Types/NonFungibleFromTokenUri.swift
- AlphaWallet/Tokens/Types/OpenSeaNonFungible.swift
- AlphaWallet/Tokens/Types/TokensDataStore.swift
- AlphaWallet/Tokens/ViewControllers/Collectibles/ViewControllers/TokensCardCollectionViewController.swift
- AlphaWallet/Tokens/ViewControllers/Collectibles/Views/TokenAssetTableViewCell.swift
This PR changes the internal flow for ERC1155 detection and balance so it's clearer and easier to maintain like this:
Fetching ERC1155 tokens in 2 steps:
A. Fetch known contracts and tokenIds owned (now or previously) for each, writing them to JSON. tokenIds are never removed (so we can easily discover their balance is 0 in the next step)
B. Fetch balance for each tokenId owned (now or previously. For the latter value would be 0)
> Modify internal flow for ERC1155 detection and balance refresh to be clearer and more maintainable

- AlphaWallet/Settings/Types/Config.swift
One of the cases we'll need to remote log and figure out the cause. But for now, just set the selected chains to be the default when that happens
> Workaround crash if app launches with no chain selected (no idea why that can happen)

- AlphaWallet/Transfer/Controllers/TransactionConfigurator.swift
> Make sure that when user chooses to transfer all funds, ERC1155 token IDs are preserved (not sure if this will ever matter)

- AlphaWallet/Settings/Models/AddCustomChain.swift
Reproduce:
1. https://chainlist.org in browser tab
2. Look for "Arbitrum One" and add it
Crashes because first RPC URL is `https://mainnet.infura.io/v3/${INFURA_API_KEY}` and because we don't substitute the Infura key [1], is not a valid URL.
[1] We can't support Infura keys because if we don't already support this chain in the app, then it must not have been enabled for our Infura account so it wouldn't work anyway.
> Fix: crash if RPC URL in EIP3085 is not a valid URL

- AlphaWallet/Localization/en.lproj/Localizable.strings
- AlphaWallet/Localization/es.lproj/Localizable.strings
- AlphaWallet/Localization/ja.lproj/Localizable.strings
- AlphaWallet/Localization/ko.lproj/Localizable.strings
- AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings
> Tweak copy for private transactions to remove mention of "Ethermine" least users (or Apple!) think this is about mining on the device

- AlphaWallet/Browser/ViewControllers/BrowserViewController.swift
Had originally wanted to open 1inch in a standalone browser instead and only modify the user-agent there, but the flow needs to change too much because the standalone browser doesn't enable switching of chains.
> Tweak user-agent in dapp browser for 1inch so the smart app banner doesn't show up

- AlphaWallet/Core/Helpers/RemoteLogger.swift
Should be helpful:
Before PR:
```
test 1
```
After PR:
```
test 1 from: application(_:didFinishLaunchingWithOptions:)
```
> Include caller func names in debug logs

- AlphaWallet/Core/Types/ERC20BalanceViewModel.swift
- AlphaWallet/Tokens/ViewControllers/TokenViewController.swift
Fix: fiat value displayed for ERC20 tokens in single token view is wrong
Polygon WETH is using Matic's fiat value:
-|-
> Fix: fiat value displayed for ERC20 tokens in single token view is wrong

- AlphaWallet/Core/CoinTicker/CoinTickersFetcher.swift
Includes commit from #3424.
Only 1 of the tokens will show the price.
E.g WETH on mainnet and Polygon are based on CoinGecko's "weth", only one of them (random pick) will show the price
-|-
> Fix price for ERC20 tokens matching same CoinGecko ID not appearing correctly

- AlphaWallet/KeyManagement/EtherKeystore.swift
Fixes #3455 
Tests still don't work #3456
@vladyslav-iosdev since key management is a delicate part of the app, can you help to verify that this doesn't affect actual devices? It's not so bad if it just breaks running on simulators.
> Fix: app broken on iOS 15 simulator

- AlphaWallet/Settings/Models/SendPrivateTransactionsProvider.swift
Potential bug because removing the `case .main` would have compiled with no errors and `server  == .main` would have went down the wrong code path.
```
switch server {
case .main:
case .somethingElse, .main:
}
```
> Fix: remove duplicate switch-case. No functional change, but could have been a bug

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet/Tokens/ViewModels/EthTokenViewCellViewModel.swift
- AlphaWallet/Tokens/ViewModels/FungibleTokenViewCellViewModel.swift
- AlphaWallet/Tokens/ViewModels/UiTweaks.swift
- AlphaWallet/Tokens/Views/FungibleTokenViewCell.swift
- AlphaWallet/Transfer/ViewModels/SendHeaderViewViewModel.swift
Introduced `UiTweaks.swift` (for now since there's nothing to generalize) with a variable to replace the "-" with "" (empty string). So we can revert this or tweak it further more easily.
Before|Before
-|-
After|After
> Remove most "-" displayed in Wallet tab when price is not available to reduce clutter

- .travis.yml
- AlphaWalletTests/Coordinators/LockEnterPasscodeCoordinatorTest.swift
Closes #3456
The error were apparently caused by `LockEnterPasscodeCoordinator` not calling the `.stop()` function before terminating the test.
> Updated Travis.yml and corrected code to allow tests to pass

- .swiftlint.yml
Closes #3459.
I am not able to test this other than by compiling the project under the AlphaWalletShare and AlphaWalletSafariExtension schemes. When I run Project > Test under the AlphaWallet scheme, I get `Cannot test target “AlphaWalletUITests” on “iPhone 12”: UITargetAppPath should be provided`. I am able to compile and run the AlphaWallet target on the simulator. 
In Xcode:
1) Select AlphaWalletShare scheme.
2) Build the extension.
**Expects**
3) Successful build.
In Xcode:
1) Select AlphaWalletSafariExtension scheme.
2) Build the extension.
**Expects**
3) Successful build.
In Xcode:
1) Select the AlphaWallet scheme.
2) Run the app.
**Expects**
3) Successful build.
4) App runs on simulator/iPhone.
The SwiftLint command is invoked via `${SRCROOT}/Pods/SwiftLint/swiftlint` instead of …
> Added Run SwiftLint phase to AlphaWalletShare / AlphaWalletSafariExtensions

- AlphaWallet/Settings/ViewControllers/SaveCustomRpcViewController.swift
- AlphaWallet/Settings/Views/SaveCustomRpcView.swift
Closes #3475
On the main screen, tap the "Settings" tab option followed by the "Select Active Networks" option.
delete "Expanse Network" if it exists.
1. Tap the add button in the upper right corner.
2. **Expects** Add Custom RPC screen to appear with Network name field as first responder and an alphabetical keyboard at the bottom. The enter key should read "next". There should be a "<" and ">" button on top of the keyboard.
3. Enter "expanse network" and tap the ">" button.
4. **Expects** RPC URL field to be first responder. A url keyboard should appear.  The enter key should read "next". There should be  "<", ">", "https://" buttons on top of the keyboard.
5. Enter "node.expanse.tech" and tap the "https://" button.
6. **Expects** RPC URL field to display "https://node.expanse.tech".
7. …
> Fixed and improved Keyboard behaviour in SaveCustomRpc series.

- AlphaWallet/Settings/Types/Config.swift
- AlphaWallet/Tokens/Coordinators/TokensCoordinator.swift
To use it:
1. Set `Config.shouldReadClipboardForWalletConnectUrl` to `true` (do not commit)
2. Copy a WalletConnect URL to clipboard
3. Tap Camera button in Wallet tab and it'll try to connect
Probably should set up to read launch arguments and UserDefaults for such flags as a followup
> Add debug flag to read clipboard for WalletConnect URL and use it when camera button in Wallet tab is tapped

- AlphaWallet/Transactions/Coordinators/SingleChainTransactionEtherscanDataCoordinator.swift
Don't say it's because of deserialization.
Before PR:
> main() server: custom(AlphaWallet.CustomRPC(chainID: 2, nativeCryptoTokenName: Optional("Unnamed"), chainName: "a", symbol: Optional("EXP"), rpcEndpoint: "https://node.expanse.tech", explorerEndpoint: Optional("https://expanse.tech"), etherscanCompatibleType: AlphaWallet.RPCServer.EtherscanCompatibleType.unknown, isTestnet: true)) address: 0x97446491E282EC33CEB6f114D88aaFA40FdEc4e6 objectMapping(Swift.DecodingError.dataCorrupted(Swift.DecodingError.Context(codingPath: [], debugDescription: "The given data was not valid JSON.", underlyingError: Optional(Error Domain=NSCocoaErrorDomain Code=3840 "JSON text did not start with array or object and option to allow fragments not set." UserInfo={NSDebugDescription=JSON text did not start …
> Improve error logged when accessing blockchain explorer API if it's 404. Make it clearer

- .gitignore
- Makefile
- README.md
Closes #3486
I rewrote the Makefile. In a new installation, use `make bootstrap` to set up the gems and pods. 
`make`, `make target` - Lists all the useful targets in the makefile.
`make clean` - Remove all files in the `Pods` and `vendor/bundle` directories.
`make install_gems` - Install all the gems listed in the Gemfile into the `vendor/bundle` directory.
`make install_pods` - Install all the pods listed in the Podfile into the `Pods` directory. This command uses the cocoapod binary installed via `make install_gems` otherwise we will get a version conflict in the `Podfile.lock` file.
`make install_all` - Perform `make install_gems` followed by `make install_pods`.
`make bootstrap` - Same as make install_all.
1. In the command line, change to the root directory of the project.
2. Type …
> New build instructions and makefile

- AlphaWallet/Settings/ViewControllers/SaveCustomRpcViewController.swift
- AlphaWallet/Settings/Views/SaveCustomRpcView.swift
- AlphaWallet/Tokens/Views/TextField.swift
Closes #3453
If a textfield in the edit custom rpc screen becomes first responder and is hidden, it will be scrolled into view.
Requires a custom rpc to be added. Refer to "enter network data" section of this [pull request](https://github.com/AlphaWallet/alpha-wallet-ios/pull/3465) for instructions on how to add one.
1. When on the main screen of app, tap the settings tab bar icon.
2. Tap select active networks option on the Settings screen.
3. Slide the custom rpc (normally Expanse Network) to the left to expose the edit button.
4. Tap the edit button and the edit custom rpc network screen should appear.
5. Tap on the Symbol text field. A keyboard will appear at the bottom of the screen and hide the Block Explorer URL text field.
6. Tap the next button on the keyboard.
7. The Block …
> Make visible textfields, hidden by keyboard, when becoming first responder

- AlphaWallet/Settings/Coordinators/SaveCustomRpcCoordinator.swift
- AlphaWallet/Settings/Models/AddCustomChain.swift
- AlphaWallet/Settings/ViewControllers/SaveCustomRpcViewController.swift
Fixes: #3482
1. Delete the "expanse network" if it exists.
2. On the main screen, tap "settings", then "select active networks".
1. Tap the + button in the upper right corner.
2. **Expects** to see "Add Custom RPC Network" screen.
3. Type "Expanse network" into the Network Name text field.
4. Type "https://node.expanse.tect" into the RPC URL text field.
5. Type "2" into the Chain ID text field.
6. Type "EXP" into the Symbol text field.
7. Type "https://expanse.tech" into the Block Explorer URL text field.
8. Tap the "Save network" button.
9. **Expects** RPC URL text field to be highlighted in red with "RPC URL is invalid" under the text field.
> Added code to indicate rpc url error

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet/Analytics/Models/AnalyticsTypes.swift
- AlphaWallet/Browser/Coordinators/DappBrowserCoordinator.swift
- AlphaWallet/FiatOnRamp/Coordinators/FiatOnRampCoordinator.swift
- AlphaWallet/InCoordinator.swift
- AlphaWallet/Tokens/Coordinators/ClaimPaidOrderCoordinator.swift
- AlphaWallet/Tokens/Coordinators/SingleChainTokenCoordinator.swift
- AlphaWallet/Tokens/Coordinators/TokensCoordinator.swift
- AlphaWallet/Tokens/ViewControllers/Collectibles/Coordinators/TokensCardCollectionCoordinator.swift
- AlphaWallet/Tokens/ViewControllers/TokenViewController.swift
- AlphaWallet/Transactions/Coordinators/ReplaceTransactionCoordinator.swift
- AlphaWallet/Transactions/Coordinators/TokensCardCoordinator.swift
- AlphaWallet/Transfer/Coordinators/PaymentCoordinator.swift
- AlphaWallet/Transfer/Coordinators/SendCoordinator.swift
- AlphaWallet/Transfer/Coordinators/TransactionConfirmationCoordinator.swift
- AlphaWallet/Transfer/Coordinators/TransferNFTCoordinator.swift
- AlphaWallet/WalletConnect/Controllers/TransactionConfirmationCoordinatorBridgeToPromise.swift
- AlphaWallet/WalletConnect/Coordinator/WalletConnectCoordinator.swift
This refactor is to enable us to call up Fiat On-Ramp (current the ramp.network webpage) in other places. In the future we might replace it with a native UI.
~@vladyslav-iosdev would you help to implement the part marked with `//hhh1`?~
~No idea how to do it for transaction sending initiated with WalletConnect~
> Refactor: Extract code to access Fiat On-ramp

- AlphaWallet/WhatsNew/ViewControllers/WhatsNewListingViewController.swift
Fixes #3493
The ModalViewController required it's own dismissal function instead of the standard one.
> Fixed ModalViewController dismissal animation missing from WhatsNewListingViewController.

- AlphaWallet/EtherClient/Requests/EstimateGasRequest.swift
- AlphaWallet/Transfer/Controllers/TransactionConfigurator.swift
- AlphaWallet/Transfer/Types/GasLimitConfiguration.swift
Before the PR, because contract deployment transactions do not include a `to` address, `eth_estimateGas` calls aren't made for estimating the gas limit. PR enables it.
In addition, the hardcoded gas limit maximum of 1M is too low for contract deployment. This PR changes it to 2M. Ideally we should enforce 2 limits, a lower (1M) limit for non-deployments; leave it as a TODO.
> Support contract deployment gas limit estimation

- AlphaWallet/Wallet/Coordinators/WalletCoordinator.swift
- AlphaWallet/WhatsNew/Coordinators/WhatsNewExperimentCoordinator.swift
i.e. fix #3502 so it doesn't clash with the following:
> Do not show What's New after wallet creation as it crashes with the back up prompt

- AlphaWallet/Accounts/Views/WalletSummaryTableViewCell.swift
> Removed redundant chevron from WalletSummaryTableViewCell

- AlphaWallet/Style/AppStyle.swift
- AlphaWallet/Tokens/ViewModels/SegmentedControlViewModel.swift
Closes #3524
I'm not sure how to verify this. What I did was make the colours Yellow instead of Mercury and the changes showed up on the simulator. Now that I've changed them all to Mercury I can't tell the difference between any of the lines. @colourfreak 
Screen 1
Screen 2
Screen 3
> Changed the default uitableview colour separators, uinavigation bar shadow image, uitabbar shadow image to colour mercury

- AlphaWallet/Tokens/Views/OpenSea/OpenSeaNonFungibleTokenViewCell.swift
> The "<N> <Symbol>" subtitle under collection in Wallet tab Collectible sub-tab is clipped off at the bottom #3599

- AlphaWallet/KeyManagement/EtherKeystore.swift
- AlphaWallet/UI/Form/HDWallet+Extension.swift
- AlphaWalletTests/Core/Types/HDWalletTest.swift
- Podfile
- Podfile.lock
Offer support for implementing #3447.
No functional change introduced but:
* Updated TrustWalletCore
* Backend can handle (store, read, sign with) wallets created with 24-word seed phrases
* Can import 24-word seed phrases, but the UI doesn't enable this yet
* Added tests for wallets using 12-word and 24-word seed phrases
@oa-s this is a delicated part of the system; would you help to test this?
At least this:
* Test signing with existing wallets that were imported prior to this PR, that are 12-word seed phrases
* Create new wallet (12-words)
* Import private key-based wallet
* Import 12-words seed phrase
* Test signing
> Add backend support for 24-word seed phrases. Not enabled in UI

- AlphaWallet/Transfer/Coordinators/SendTransactionCoordinator.swift
> When computing nonce while private transactions are enabled, check against the private JSON-RPC endpoint instead #3574

- AlphaWallet/UI/TokenImageView.swift
Compare the ENS token icon:
-|-
> Fix: Token icons should be rounded

- AlphaWallet/Style/AppStyle.swift
- AlphaWallet/Tokens/Coordinators/TokensCoordinator.swift
- AlphaWallet/UI/TokenImageView.swift
- AlphaWallet/UI/TokenObject+UI.swift
- AlphaWallet/UI/Views/AmountTextField.swift
Closes #3542
Contains commit in #3626. With this PR, the chain icon overlay on the token icons are generated in the app. A fork of the token icons without the preprocessed overlay icons in https://github.com/AlphaWallet/iconassets/tree/with-chain-overlay-removed are used. The native tokens on each chain do not show the chain overlay.
Once both iOS and Android app implements this PR and have rolled out sufficiently, we can update `iconassets` repo's `master` branch with `with-chain-overlay-removed` and switch both apps back to accessing `master`.
> Overlay chain icons in-app instead of using preprocessed token icons with the overlay

- AlphaWallet/KeyManagement/EtherKeystore.swift
Didn't rename vars or function names. Since we can't do it completely (the keychain keys can't be changed without risk), better not do it halfway.
> Fix class comments to mention entropy rather than seed

- AlphaWallet/Tokens/ViewControllers/TokensViewController.swift
Fixes: #3537
Closes: #3547
**Testing**
1. Delete the AlphaWallet app.
2. Install a new copy of AlphaWallet.
3. Run AlphaWallet and create a wallet.
**Expects**
4. User to be on the Wallet screen.
**Testing**
5. Tap on the ellipses (…) in the upper trailing edge corner.
6. Tap Add/Hide tokens.
7. Add any 3 popular tokens.
8. Tap the back arrow in the upper leading edge corner.
**Expects**
9. User to be on the Wallet screen. The added tokens are listed in the Wallet screen.
**Testing**
10. Swipe to delete one of the 3 added tokens. Tap the X to delete the token.
**Expects**
11. Token to be deleted.
**Testing**
12. Swipe on Ethereum/xDai/Polygon Mainnet.
**Expects**
13. Nothing to happen.
> Added canDelete check to prevent TokensViewController from deleting native tokens

- .github/CODEOWNERS
Useful when we remove the first line and thus default reviewers for most files:
> * @hboon @oa-s
> Update CODEOWNERS file to specify delicate parts of system

- AlphaWallet/Tokens/ViewControllers/TokensViewController.swift
- AlphaWallet/Tokens/ViewModels/TokensViewModel.swift
Fixes #3537.
You need some items to display on the Wallet main screen. Add some if you have none.
1. Swipe left on a token displayed in the Wallet main screen.
2. **Expects** delete icon "X" appears.
3. Tap on "X".
4. **Expects** deleted token disappears from Wallet main screen.
The token rows displayed on the view controller consists of an array of `TokenObjectOrRpcServerPair` objects. `TokenObject` is used to represent a token while `RpcServerPair` is used to represent the header. We need to consider a minimum of 3 rows (previous to the swiped row, the swiped row, next to the swiped row) in order to determine the outcome. If a row does not exist, it is treated as Not removable. If the row is a `RpcServerPair`, the row is treated as Not removable. If the row is a `TokenObject`, it is …
> Fixed code on Wallet main screen that crashed when token row was swiped to delete

- AlphaWallet/Style/AppStyle.swift
- AlphaWallet/Tokens/Views/EthTokenViewCell.swift
Closes #3766
I cannot get the line height to be 34 as it throws the entire horizontal alignment off (unless I redo the layout of the EthTokenViewCell).
> Changed font attributes for token value in EthTokenViewCell #3766

- AlphaWallet/Settings/ViewControllers/SaveCustomRpcManualEntryViewController.swift
- AlphaWallet/Settings/Views/SaveCustomRpcManualEntryView.swift
Closes #3752 
Settings > Select Active Network > + 
Try and cut and paste floating point numbers or non-integer strings to the ChainIDTextField.
> Prevent "." from being entered in ChainIDTextField of SaveCustomRpcManualEntryViewController

- README.md
Based on https://github.com/AlphaWallet/alpha-wallet-ios/issues/2135#issuecomment-1021194840
Xcode used to warn you if you open the `xcodeproj` file when there's a matching `xcworkspace` file. Apparently doesn't do that anymore in Xcode 13.
> Update README to be explicit about not opening the xcodeproj file

- AlphaWallet/Tokens/Collectibles/ViewControllers/Erc1155TokenInstanceViewController.swift
Closes #3813 
See this [comment](https://github.com/AlphaWallet/alpha-wallet-ios/issues/3813#issuecomment-1022790761).
> Added NavigationBarTopSeparatorLine code in Erc1155TokenInstanceViewController to remove the gray line #3813

- AlphaWallet/InCoordinator.swift
- AlphaWallet/Tokens/Coordinators/TokensCoordinator.swift
Closes #3825 
1. On Wallet screen, tap QR code scanner in upper right corner.
2. Scan Wallet QR code.
3. Tap Watch Wallet when pop up appears.
4. **Expects** Scanned Wallet to be the displayed wallet in the Wallet screen.
> Modified InCoordinator and TokensCoordinator to switch wallets when a QR code is scanned and placed on the watch wallets list in the Wallet screen.

- AlphaWallet/Localization/en.lproj/Localizable.strings
- AlphaWallet/Localization/es.lproj/Localizable.strings
- AlphaWallet/Localization/ja.lproj/Localizable.strings
- AlphaWallet/Localization/ko.lproj/Localizable.strings
- AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings
- AlphaWallet/Settings/Types/ServiceProvider.swift
Closes #3807 
@oa-s @hboon 
Does anyone know how to trigger `HelpContentsViewController` and `HelpViewController` are in the app? I can't find them to test. The one spot I know where to test is below:
Settings > Support > Email
> Modifed code so that an error message is displayed if MFMailComposeViewController.canSendMail() returns false

- AlphaWallet.xcodeproj/project.pbxproj
Closes #3921
Warnings like:
> The `AlphaWallet [Debug]` target overrides the `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` build setting defined in `Pods/Target Support Files/Pods-AlphaWallet/Pods-AlphaWallet.debug.xcconfig'. This can lead to problems with the CocoaPods installation`
> Remove warning after running `pod install`

- AlphaWallet/Tokens/Views/TokenInstanceWebView.swift
- AlphaWallet/WalletConnect/Controllers/SignMessageCoordinatorBridgeToPromise.swift
> Pass coordinator instance in `TokenInstanceWebView` to keep it alive and avoid early dellocation #3902

- AlphaWallet/Browser/Coordinators/DappBrowserCoordinator.swift
- AlphaWallet/Redeem/ViewControllers/TokenCardRedemptionViewController.swift
- AlphaWallet/Settings/Types/Config.swift
- AlphaWallet/Tokens/Collectibles/Coordinators/TokensCardCollectionCoordinator.swift
- AlphaWallet/Tokens/Collectibles/ViewControllers/TokensCardCollectionViewController.swift
- AlphaWallet/Tokens/ViewControllers/TokenInstanceViewController.swift
- AlphaWallet/Tokens/ViewControllers/TokenViewController.swift
- AlphaWallet/Tokens/ViewControllers/TokensCardViewController.swift
- AlphaWallet/Tokens/Views/TokenInstanceWebView.swift
- AlphaWallet/Transactions/Coordinators/TokensCardCoordinator.swift
- AlphaWallet/Transfer/Coordinators/PaymentCoordinator.swift
- AlphaWallet/WalletConnect/Coordinator/WalletConnectCoordinator.swift
Useful especially when we want to force the send buttons, signing actionsheets to appear for watched wallets
> Add development flag `Config.development.shouldPretendIsRealWallet` so we can force watch wallets to proceed to sign (and fail), etc

- AlphaWallet/Transactions/Storage/TransactionsStorage.swift
Closes #3995
`NSPredicate(format:)` isn't type safe. Is there a better way? Does Realm provide some type-safe magic to form the predicate from the `Transaction` perhaps?
@oa-s would you help check the other `NSPredicate(format:)` calls for these? :)
> Fix: crash after posting transaction

- AlphaWallet/Browser/Types/Favicon.swift
> Improve favicon resolution in dapp browser (history, favorites) so it is more likely to pick up if a site has a favicon #4009

- AlphaWallet/Core/Features.swift
- AlphaWallet/Tokens/ViewControllers/TokenViewController.swift
- AlphaWallet/Tokens/ViewControllers/TokensCardViewController.swift
- AlphaWallet/Tokens/ViewControllers/VerifiableStatusViewController.swift
> Hide TokenScript signature verifier result because it's always invalid now

- modules/AlphaWalletAddress/AlphaWalletAddress/AlphaWallet.swift
But maybe due to the font used, it looks unchanged. But changing it otherwise it sticks out in the codebase all the time.
Referring to this:
> Replace the "..." used when truncating addresses in the middle with the real thing: "…"

- AlphaWallet/Browser/ViewModel/Dapps.swift
DAS has branded as .bit. And the new website is https://did.id
> Update DAS DApp info

- AlphaWallet/Core/DecodedFunctionCall.swift
- AlphaWallet/Core/SwapToken/HoneySwap/HoneySwapERC20Token.swift
- AlphaWallet/Core/SwapToken/Oneinch/ERC20Token.swift
- AlphaWallet/Tokens/Coordinators/ClaimPaidOrderCoordinator.swift
- AlphaWallet/Transfer/Controllers/TransactionConfigurator.swift
- AlphaWalletTests/Coordinators/SendCoordinatorTests.swift
- AlphaWalletTests/EtherClient/EtherKeystoreTests.swift
- AlphaWalletTests/EtherClient/TransactionSigningTests.swift
- AlphaWalletTests/Factories/FakeKeystore.swift
- AlphaWalletTests/Factories/Wallet.swift
Includes using `AlphaWallet.Address` instead of `TrustKeystore.Address` for encoding function calls because it has been supported for a long time
> Remove unnecessary `import Trustkeystore`

- AlphaWallet/Core/Ethereum/ABI/DecodedFunctionCall+Decode.swift
- AlphaWalletTests/Core/Ethereum/ABI/DecodedFunctionCall+DecodeTests.swift
eg. decoding an ERC20 `approve()` function might not work.
Added a unit test, but unfortunately the tests doesn't reliably show the original code will fail. But it helps proves the new version works.
> Fix: transaction ABI function parsing. Previous code is dependent on order of enumerating a dictionary key-value pairs of function arguments

- AlphaWallet/Core/OpenSea/OpenSeaNetworkProvider.swift
Closes #4163
We seem to have lost the debug log for `429`s. This PR restores it too.
> Improve OpenSea API call error logging

- AlphaWallet/Transfer/ViewControllers/SendViewController.swift
- AlphaWallet/UI/Views/AmountTextField.swift
> Added function to update AmountTextField’s InputAccessoryView based on button type. SendViewController modified to use the "next" InputAccessoryView.

- AlphaWallet/Core/Helpers/RemoteLogger.swift
replace DDASLLogger with DDOSLogger in logger because of DDASLLogger deprecation in iOS 10
> RemoteLogger.swift:97:20: 'DDASLLogger' was deprecated in iOS 10.0: Use DDOSLogger instead #4199

- AlphaWallet/Core/Helpers/BlockieGenerator.swift
- AlphaWallet/Core/UnstoppableDomains/AddressOrEnsResolution.swift
- AlphaWallet/Core/UnstoppableDomains/DomainResolutionService.swift
- AlphaWallet/Core/UnstoppableDomains/UnstoppableDomainsV2Resolver.swift
- AlphaWallet/Tokens/Coordinators/ENSReverseLookupCoordinator.swift
- AlphaWallet/Tokens/Coordinators/GetENSOwnerCoordinator.swift
- AlphaWallet/Tokens/Coordinators/GetENSTextRecordsCoordinator.swift
- AlphaWalletTests/Tokens/Coordinators/GetENSOwnerCoordinatorTests.swift
- modules/AlphaWalletENS/AlphaWalletENS/Extensions/Address+Extensions.swift
Less computation and easier to debug
Depends on and includes: #4272
> Cache ENS forward and reverse resolution by name and address respectively, instead of their hashes

- Makefile
make `build_and_run_booted`
Useful for quick testing of PR — especially after cloning the repo separately — without launching Xcode/AppCode and waiting for project to refresh.
> Add Makefile target to build and run app in booted simulator

- AlphaWallet/WalletConnect/Types/WalletConnectActionType.swift
> Remove warning in WalletConnectActionType.swift about String interpolation #4250

- Makefile
I added this to the makefile so that when building via the command line, we won't have to automatically resolve the Package dependency. The dependency should be resolved and updated when you add a new dependency (via Xcode or the command line). Once it's checked in to the git repository, we shouldn't resolve the dependencies again.
https://developer.apple.com/documentation/swift_packages/building_swift_packages_or_apps_that_use_them_in_continuous_integration_workflows
```
Use the Expected Version of a Package Dependency
To ensure the CI workflow’s reliability, make sure it uses the appropriate version of package dependencies. Xcode stores the exact version of each package dependency in a file called Package.resolved. The file automatically updates when package requirements in your Xcode …
```
> Added -disableAutomaticPackageResolution to test14, test15, build_and_run_booted targets

- Makefile
Clean now cleans the Xcode project as well. Before this it only removed the Podfile and Gem directories that bundle installed.
> Make clean clean the test targets

- Makefile
- docs/data-source-chains.md
- scripts/compress_chains
Closes #4168
The chains.json file is downloaded from https://chainid.network/chains.json.
This file is then compressed using NSData.CompressionAlgorithm.lzma.
It is then renamed as chains.zip and must be added to the Rpc Network group of the project.
A Makefile target has been added to automate this process. At the command line, type in:
```
make update_chains_file
```
and you should see the following response:
```console
Deleting chains file in scripts folder.
Downloading chains file.
################################################################################################################# 100.0%
Compressing.
Moving compressed file into project.
Update completed.
```
> Added documentation and a target to Makefile to download, compress, and add the chains.zip file to the AlphaWallet project.

- AlphaWallet.xcodeproj/project.pbxproj
Changed minimumVersion of Firebase from 8.0.0 to 8.10.0 as stated in `SwiftPackageManager.md`.
> Updated minimumVersion of Firebase to 8.10.0

- AlphaWalletTests/Tokens/Coordinators/GetIsERC1155ContractCoordinatorTestCase.swift
Changed time out for GetIsERC1155ContractCoordinatorTestCase from 10 minutes to 20 seconds. Fixed up some style issues with PromiseKit calls.
> Changed timeout in GetIsERC1155ContractCoordinatorTestCase to 20 seconds instead of 10 minutes, fixed up some style issues.

- AlphaWalletTests/Tokens/Coordinators/GetENSOwnerCoordinatorTests.swift
When GetENSOwnerCoordinatorTests is run, some of the existing tests waits 20 seconds if there is a network  or response error. This rewrite removes the 20 second wait to time out. The following are the tests:
1. testResolution
2. testResolutionThatHasDifferentOwnerAndResolver
3. testEnsIp10WildcardAndEip3668CcipRead
> Modified GetENSOwnerCoordinatorTests so that if there is a network or response error, we don’t wait 20 seconds for the expectation to time out.

- AlphaWallet/Core/Coordinators/WalletBalance/PrivateBalanceFetcher.swift
- AlphaWallet/Core/NFT/Enjin/EnjinNetworkProvider.swift
- AlphaWallet/Core/NFT/OpenSea/OpenSeaNetworkProvider.swift
- AlphaWallet/Core/TokensAutodetector/TokensAutodetector.swift
- AlphaWallet/Core/Types/TokenProviderType.swift
- AlphaWallet/TokenScriptClient/Coordinators/EventSourceCoordinator.swift
- AlphaWallet/TokenScriptClient/Coordinators/EventSourceCoordinatorForActivities.swift
- AlphaWallet/Transactions/Coordinators/AlphaWalletProviderFactory.swift
- Podfile.lock
- modules/AlphaWalletCore/AlphaWalletCore.podspec
- modules/AlphaWalletCore/AlphaWalletCore/Extensions/PromiseKit+Extensions.swift
- modules/AlphaWalletCore/AlphaWalletCore/attempt.swift
Towards #4472 as these code are used across modules/apps. 
Probably have to be careful with moving stuff into `AlphaWalletCore` like this. This PR for example adds `PromiseKit` as a dependency to `AlphaWalletCore` which had zero third party dependencies. But did it anyway to avoid add yet another new pod (for now, since I'm building one for OpenSea).
> Move utility functions to AlphaWalletCore pod

- modules/AlphaWalletOpenSea/AlphaWalletOpenSea/OpenSea.swift
> Fix: OpenSea CallCounter crash because it's not threadsafe and accessing it from multiple threads

- AlphaWallet/Settings/Views/SaveCustomRpcManualEntryView.swift
- AlphaWallet/WhatsNew/Coordinators/WhatsNewExperimentCoordinator.swift
- AlphaWallet/WhatsNew/Coordinators/WhatsNewListingCoordinator.swift
- AlphaWallet/WhatsNew/ViewControllers/WhatsNewListingViewController.swift
Code renamed to remove Protocol from DelegateProtocols and CoordinatorProtocols.
> Renamed protocols in SaveCustomRpcManualEntryView and WhatsNewListingViewController-Coordinator from DelegateProtocols to Delegate etc

- Podfile
- Podfile.lock
> Tweak pod url to fix memory leak for [EthereumABI.pod] #4635

- Podfile
- Podfile.lock
Fix pod install for Github non-SSH key developers.
> Changed url from git@github.com:AlphaWallet/EthereumABI.git to https://github.com.AlphaWallet/EthereumABI.git in Podfile.

- AlphaWalletTests/Transfer/ViewControllers/SendViewControllerTests.swift
There is a compile bug in the `SendViewControllerTests`. This pull request fixes it.
> Corrected enabledTokens function call parameters in SendViewControllerTests.

- AlphaWallet/Tokens/ViewModels/TokensViewModel.swift
(Disregard margin differences in screenshot below:)
-|-
> Re-order groups in Wallet tab

- AlphaWallet/AddMultipleCustomRpc/AddMultipleCustomRpcView.swift
- AlphaWallet/Features/FeaturesTableViewController.swift
- AlphaWallet/Settings/ViewModels/ServerViewModel.swift
- AlphaWallet/Style/AppStyle.swift
- AlphaWallet/WhatsNew/Views/WhatsNewViews.swift
> [Refactor] Access fonts via Fonts.regular(size:) etc instead of explicitly referring to the font family/name

- AlphaWallet/Tokens/Coordinators/TokensCoordinator.swift
Fixes #4791
Not the best fix, but comment in code explains why:
```
//TODO maybe should make `importToken` fail gracefully when requested for a server that isn't active instead, but it'd involve introducing optionals to other call-sites which seem to make things more complicated and worse
guard sessions.hasKey(server) else { return }
```
> Fix: crash when mainnet is not enabled #4791

- AlphaWallet/TokenScriptClient/Models/AssetAttributesCache.swift
Fixes #4810
`AssetAttributesCacheData` no longer implements `Codable`. It's harmless since we haven't implemented persistance to disk.
I look at switching to `AtomicDictionary ` as a short-term solution though. Refer to: https://github.com/AlphaWallet/alpha-wallet-ios/issues/4810#issuecomment-1148208721
> Fix crash because dictionary property in `AssetAttributesCache` is accessed in both main and non-main threads concurrently #4810

- modules/AlphaWalletOpenSea/AlphaWalletOpenSea/OpenSea.swift
Closes #4812 
Interestingly, a key that has expired might still return `429` (rate limited) sometimes.
> [Log] Capture in debug log that OpenSea API key has expired #4812

- AlphaWallet/Extensions/UITableView.swift
```
/alpha-wallet-ios/AlphaWallet/Extensions/UITableView.swift:26:33: conformance of 'UICollectionViewCell' to protocol 'WithReusableIdentifier' was already stated in the type's module 'UIKit'
extension UICollectionViewCell: WithReusableIdentifier {
```
Pull request to silence the above warning.
> Remove WithReusableIdentifier from UICollectionViewCell as conformance is set somewhere else.

- AlphaWallet/Settings/Types/RPCServers.swift
Fixes #4875
According to https://developers.gnosischain.com/for-developers/developer-resources/update-rpc-url
Test data
---
Wallet with wQOIN: https://blockscout.com/xdai/mainnet/address/0x4873678E53484e7Bbf1242a5fD6D608FDF24D48F/transactions
wQOIN: https://blockscout.com/xdai/mainnet/token/0x5A6086794668d7D94f2CA2616DB3C6BB0528d3a2
> Fix: Gnosis RPC URL is outdated and doesn't work anymore #4875

- AlphaWallet/Core/Types/RealmStore.swift
- AlphaWallet/Core/Types/RunLoopThread.swift
> Syncronize access to `func performSync(_ block: @escaping (Realm) -> Void) {`, to make sure there is no two or more call at same time #4883

- AlphaWallet/Accounts/Views/WalletSummaryView.swift
> Get rid of layout constraints warning for Wallet tab at launch. Less noise for debugging #4891

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet/Assets.xcassets/cod.colorset/Contents.json
- AlphaWallet/Configuration.swift
- AlphaWallet/Core/Views/ButtonsBar/ButtonsBar.swift
- AlphaWallet/Extensions/UIButton.swift
- AlphaWallet/Extensions/UIColor.swift
- AlphaWallet/Wallet/ViewControllers/CreateInitialWalletViewController.swift
- AlphaWallet/Wallet/ViewModels/CreateInitialWalletViewModel.swift
- AlphaWalletTests/Extensions/UIColorExtensionTests.swift
Delete current app to remove wallet data. Check to see if this code style is acceptable. Once approved, I will fix the info.plist flag to change `appearance` to `light` before merging. Also are the colours right? I went by the style guide. Also Dusty is defined as RGB 153, 153, 153 in the colour guide but the style guide had 151, 151, 151. I followed the colour guide.
@hboon @colourfreak
> Added dark mode to initial wallet creation screen

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet/KeyManagement/EtherKeystore.swift
- AlphaWalletTests/EtherClient/KeysTests.swift
- modules/AlphaWalletAddress/AlphaWalletAddress/AlphaWalletAddress.swift
Fixes: #4921
Reproduce by importing this as key: `fffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364141`
> Fix: Should show an error instead of crash when importing an invalid "raw" private key #4921

- AlphaWallet/Core/Helpers/WalletApiService.swift
> Fix: Deep-link Wallet API's output URL for signpersonalmessage's signature value should have the key "signature" instead of "message" #4938

- AlphaWallet/Analytics/Models/AnalyticsTypes.swift
- AlphaWallet/Browser/Coordinators/DappBrowserCoordinator.swift
- AlphaWallet/Core/Ethereum/EthereumTransaction.swift
- AlphaWallet/Covalent/TransactionProviders/PendingTransaction/PendingTransactionFetcher.swift
- AlphaWallet/EtherClient/ChainState.swift
- AlphaWallet/EtherClient/Models/GetNextNonce.swift
- AlphaWallet/Extensions/Publishers/Session+Publishers.swift
- AlphaWallet/Extensions/Session+PromiseKit.swift
- AlphaWallet/Settings/Coordinators/PingInfuraCoordinator.swift
- AlphaWallet/Settings/Models/AddCustomChain.swift
- AlphaWallet/Tokens/Logic/GetDASNameLookup.swift
- AlphaWallet/Tokens/Logic/GetNativeCryptoCurrencyBalance.swift
- AlphaWallet/Transactions/EtherscanSingleChainTransactionProvider.swift
- AlphaWallet/Transfer/Controllers/GasPriceEstimator.swift
- AlphaWallet/Transfer/Controllers/TransactionConfigurator.swift
- AlphaWallet/Transfer/Coordinators/SendTransactionCoordinator.swift
- AlphaWallet/Transfer/Types/SendTransactionError.swift
- AlphaWalletTests/Core/Types/SessionTests.swift
2 commits:
- Pass around RPCServer more so it can be used for logging in a future commit
- Attach domain name of RPC node and chain ID when logging RPC node rate limited errors to analytics
Helps identify problematic RPC nodes where we get rate limited and affect users
> Attach domain name and chain ID to RPC node rate limited error analytics logging

- AlphaWallet/ActiveWalletCoordinator.swift
- AlphaWallet/Core/TokensAutodetector/AutoDetectTransactedTokensOperation.swift
- AlphaWallet/Core/TokensAutodetector/ImportToken.swift
- AlphaWallet/Core/TokensAutodetector/TokenFetcher.swift
- AlphaWallet/TokenScriptClient/Models/TokenScriptSignatureVerifier.swift
- AlphaWallet/Tokens/Logic/ContractDataDetector.swift
- AlphaWallet/Tokens/Logic/Erc1155TokenIdsFetcher.swift
Part of #4952
Eventually there should be no `.cauterize()` calls to PromiseKit and all the errors should be caught and printed out:
* programmatic errors are fixed
* rate limited calls are logged
* those we can't handle are hardcoded to be ignored
> Trap and print some PromiseKit cauterized errors

- fastlane/Fastfile
- fastlane/README.md
> Rename fastlane lane to `upload` to avoid name collison: "Name of the lane 'testflight' is already taken by the action named 'testflight' #4964

- AlphaWallet/EtherClient/EtherServiceRequest.swift
- AlphaWallet/EtherClient/Models/GetNextNonce.swift
- AlphaWallet/Market/Coordinators/ImportMagicLinkCoordinator.swift
- AlphaWallet/Settings/Types/Constants+Credentials.swift
- AlphaWallet/Settings/Types/RPCServers.swift
- AlphaWallet/Tokens/Helpers/CallSmartContractFunction.swift
- AlphaWallet/Tokens/Logic/GetDASNameLookup.swift
- AlphaWallet/Transfer/Coordinators/SendTransactionCoordinator.swift
- Podfile
- Podfile.lock
Closes #5050
```
if API basic auth credentials provided in credentials file
Use it with Klaytn API Service (KAS)
else
use public/free node
end
```
---
Actually not sure what is the rate limit with KAS, but the public node that we used is from a shared pool with every user/app, so let's go with KAS and if necessary we can get a better plan later
> Use Klaytn production RPC node for Cypress mainnet and Baobab testnet

- AlphaWallet/Settings/ViewControllers/EnabledServersViewController.swift
When not at the bottom:
-|-
Unchanged, at the bottom:
> Make enable network screen fill bottom safe area

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet/ActiveWalletCoordinator.swift
- AlphaWallet/Market/Coordinators/ImportMagicLinkCoordinator.swift
- AlphaWallet/TokenScriptClient/Coordinators/FetchTokenScriptFiles.swift
- AlphaWallet/TokenScriptClient/Models/AssetDefinitionBackingStore.swift
- AlphaWallet/TokenScriptClient/Models/AssetDefinitionDiskBackingStore.swift
- AlphaWallet/TokenScriptClient/Models/AssetDefinitionDiskBackingStoreWithOverrides.swift
- AlphaWallet/TokenScriptClient/Models/AssetDefinitionStore.swift
- AlphaWallet/Tokens/Logic/ContractDataDetector.swift
- AlphaWallet/Tokens/Logic/ScriptUri.swift
- AlphaWallet/Tokens/Types/AddressAndRPCServer.swift
- AlphaWallet/Transactions/TokensFromTransactionsFetcher.swift
- AlphaWallet/Transactions/TransactionsService.swift
- AlphaWalletTests/TokenScriptClient/AssetDefinitionStoreTests.swift
Closes #5110
Can verify it with:
token: 0xd915c8ad3241f459a45adcbbf8af42caa561a154
wallet: 0xbbce83173d5c1D122AE64856b4Af0D5AE07Fa362 (balance = 1)
The TokenScript actions Unlock and Lock (maybe a bit more) should be available
> Support `scriptURI()` smart contract call to retrieve URI for TokenScript files

- Podfile
- Podfile.lock
Closes #5164
Not sure if it actually fixes #5164, but it definitely makes it clearer that those `.typeMismatch` errors are 429s when rate limited by the RPC nodes.
> Capture rate limited errors (`429`s) for batched RPC/JSON requests #5164

- AlphaWallet/Tokens/ViewModels/FungibleTokenViewCellViewModel.swift
> Fix: ERC20 token's titles in wrong font in Wallet tab

- AlphaWallet/Transfer/ViewModels/TransactionConfirmationViewModel.swift
> Fix: Speed up/cancel transaction's confirmation actionsheet does not display the network correctly #5186

- .gitignore
- AlphaWallet.xcworkspace/xcshareddata/xcschemes/AlphaWallet.xcscheme
- AlphaWallet/Settings/Types/Constants+Credentials.swift
With this PR, we can create a file `.credentials` at the root of the project directory and when running in debug mode on the simulator, keys will be read from the file.
```
INFURAKEY=xyz
OPENSEAKEY=abc
```
Going to try this out to see if it's better than replacing the ones in `Constants+Credentials.swift`. Using `.credentials` has some advantages over changing `Constants+Credentials.swift` locally since it's much harder to accidentally check the file in
> Support overriding (some) API keys in `.credentials` file at root of project for development purpose

- AlphaWallet/Configuration.swift
- AlphaWallet/UI/WhereIsWalletAddressFoundOverlayView.swift
Run `xcrun simctl uninstall booted com.stormbird.alphawallet` on the command line in the `alpha-wallet-ios` directory before running the app.
Will delete commit for setting appearance to automatic before merging.
> Add dark mode to WhereIsWalletAddressFoundOverlayView

- AlphaWallet/ActiveWalletCoordinator.swift
- AlphaWallet/BlockscanChat/BlockscanChatService.swift
- AlphaWallet/Browser/Types/DappAction.swift
- AlphaWallet/Browser/ViewControllers/BrowserViewController.swift
- AlphaWallet/Core/Helpers/FirebaseReportService.swift
- AlphaWallet/Core/TokensAutodetector/AutoDetectTransactedTokensOperation.swift
- AlphaWallet/Core/UnstoppableDomains/UnstoppableDomainsV2Resolver.swift
- AlphaWallet/EtherClient/Requests/GetTransactionRequest.swift
- AlphaWallet/Settings/Types/Constants+Credentials.swift
- AlphaWallet/TokenScriptClient/Coordinators/AssetDefinitionStoreCoordinator.swift
- AlphaWallet/TokenScriptClient/Models/AssetDefinitionStore.swift
- AlphaWallet/TokenScriptClient/Models/TokenScriptSignatureVerifier.swift
- AlphaWallet/Tokens/Helpers/CachedERC1155ContractDictionary.swift
- AlphaWallet/Tokens/Helpers/CallSmartContractFunction.swift
- AlphaWallet/Tokens/Helpers/NonFungibleJsonBalanceFetcher.swift
- AlphaWallet/Tokens/Logic/GetDASNameLookup.swift
- AlphaWallet/Transactions/EtherscanSingleChainTransactionProvider.swift
- AlphaWallet/Transactions/Storage/TransactionsStorage.swift
- AlphaWallet/UI/SvgImageView.swift
- AlphaWallet/WalletConnect/Providers/v1/WalletConnectV1Provider.swift
- AlphaWallet/WalletConnect/Providers/v2/WalletConnectV2Provider.swift
- AlphaWallet/WalletConnect/Types/WalletConnectRequestConverter.swift
- AlphaWalletTests/Redeem/CreateRedeemTests.swift
Tweaked our logging so:
* verboseLog() — like debug, but not want to show it by default (since we configure our loggers to `.debug`) because it's too verbose/noisy. This includes logging in `deinit{}` and things that happen too frequently, yet not useful (eg. skipping TokenScript signature verification)
* debugLog() — like info, but more for debugging purposes. This is our default logging level for console, so must not be so excessive that the console is unreadable
* infoLog() — should be the most common. Refreshes, etc. This is our default logging level for log files (currently unused, but we'll let user attach them to support emails in the future)
* warnLog() - unexpected errors that are unhandled, mostly. So we can look out for these and fix/handle them
* errorLog() — not used
cc …
> Tweak log and logging levels

- AlphaWallet/Core/DecodedFunctionCall.swift
- AlphaWalletTests/Core/Types/FunctionCallArgumentTests.swift
> Fix: Bool args in confirmation actionsheet should show up as "true" or "false", not "1"

- AlphaWallet/AppCoordinator.swift
- AlphaWallet/AppDelegate.swift
```
window = UIWindow(frame: UIScreen.main.bounds)
//Necessary to make UIAlertController have the correct tint colors, despite already doing: `UIWindow.appearance().tintColor = Colors.appTint`
window?.tintColor = Colors.appTint
```
Modified code to remove this.
> Modified AppCoordinator and AppDelegate to handle UIAlertController not having the correct tint colours.

- AlphaWallet/Core/CoinTicker/CoinTickersStorage.swift
- AlphaWallet/Core/CoinTicker/Types/TokenMappedToTicker.swift
- AlphaWallet/Core/Types/NativecryptoBalanceViewModel.swift
Fixes #5237
It was using GNO token's price
Before PR (way more than $1/token)|After PR (~$1/token)
-|-
This PR includes a fix for users with the old price so the first time the user runs this it will go through this states:
old price|no price|correct price
-|-|-
(Ignore the swap button in screenshots, forgot to switch it off)
> Fix: Gnosis' native token xDai shows wrong fiat rate

- modules/AlphaWalletFoundation/AlphaWalletFoundation/Core/Features/Features.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Core/Settings/Types/Constants.swift
Since it doesn't seem to work correctly at the moment — might not be due to our integration.
> Hide and disable Coinbase Pay behind a feature flag

- AlphaWallet/AppCoordinator.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Core/CoinTicker/Types/TickerIdFilter.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Core/Features/Features.swift
Includes some logging so we can come back and revisit it by setting `Features.isLoggingEnabledForTickerMatches`
> Stop matching ticker id by ignoring platform

- AlphaWallet/AppCoordinator.swift
- AlphaWallet/Localization/en.lproj/Localizable.strings
- AlphaWallet/Localization/es.lproj/Localizable.strings
- AlphaWallet/Localization/fi.lproj/Localizable.strings
- AlphaWallet/Localization/ja.lproj/Localizable.strings
- AlphaWallet/Localization/ko.lproj/Localizable.strings
- AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Core/Analytics/Models/AnalyticsTypes.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Core/SwapToken/Carthage/Carthage.swift
1-liner summary: Allows the user to swap Candle (CNDL) by opening the Carthage DEX link. 
I've tested choosing to swap CNDL to open the Carthage DEX.
> Support Carthage DEX for swapping Candle

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet/Tokens/TokenScriptOverrides+Extensions.swift
- AlphaWallet/Tokens/ViewModels/EthTokenViewCellViewModel.swift
- AlphaWallet/Tokens/ViewModels/FungibleTokenViewCellViewModel.swift
- AlphaWallet/Tokens/ViewModels/NonFungibleTokenViewCellViewModel.swift
-|-
The underlying code is fragile; the PR doesn't change this, so this is a short-term fix.
> Fix: Cryptokitties token title wrong in wallet tab

- Podfile
- Podfile.lock
Fixes build error:
```
alpha-wallet-ios/Pods/Charts/Source/Charts/Data/Implementations/Standard/ChartDataSet.swift:530:1: Type 'ChartDataSet' does not conform to protocol 'RangeReplaceableCollection'
alpha-wallet-ios/Pods/Charts/Source/Charts/Data/Implementations/Standard/ChartDataSet.swift:530:1: Unavailable instance method 'replaceSubrange(_:with:)' was used to satisfy a requirement of protocol 'RangeReplaceableCollection'
```
Still builds with Xcode 13.3.1
We'll switch to Xcode 14 soon, when it's available, but only when we update `.xcode-version`.
But not sure if chart data is showing up correctly. #5325
> [DEV] Support building with Xcode 14 RC

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet/Common/Types/Error.swift
- AlphaWallet/Transfer/Collectibles/ViewModels/TransferTokenBatchCardsViaWalletAddressViewControllerViewModel.swift
- AlphaWalletTests/Common/Types/ErrorTests.swift
Fixes: #5330. Includes a test. Hard to catch it otherwise.
@oa-s This seems like it's related to us adding localized strings in the app, outside of AlphaWalletFoundation and it not loading correctly. Do you think there are other cases like this?
-|-
> Fix: Wrong error message when it should be "You already added this address to wallets" when importing a wallet again

- modules/AlphaWalletFoundation/AlphaWalletFoundation/Types/RealmStore.swift
> make queueForRealmStore as class property #5343

- AlphaWalletTests/TokenScriptClient/XMLHandlerTest.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/TokenScriptClient/Models/AssetAttribute.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/TokenScriptClient/Models/CallForAssetAttributeProvider.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/TokenScriptClient/Models/FunctionOrigin.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/TokenScriptClient/Models/Origin.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/TokenScriptClient/Models/XMLHandler.swift
> Rename `CallForAssetAttributeCoordinator` with `CallForAssetAttributeProvider`, #5353

- AlphaWalletFoundation.podspec
> Update foundation with manually defining dependency version for 'SwiftProtobuf', '1.20.1' #5362

- AlphaWalletFoundation.podspec
- Podfile.lock
> Update foundation with manually defining dependency version for 'SwiftProtobuf', '~>1.18.0' #5362

- AlphaWallet/Common/Types/Error.swift
Finishing the work after #5332. This should clean up all the error sub-types. It's a little fragile having to list the error sub-types in a switch case, so we'll have to find a better way in the long run
Before PR|After PR (and recently)
-|-
> Fix: wrong/overly-generic error messages displayed

- AlphaWallet/Browser/Views/DappBrowserNavigationBar.swift
- AlphaWallet/Common/Views/ButtonsBar/ButtonsBarBackgroundView.swift
- AlphaWallet/Transfer/ViewModels/RequestViewModel.swift
On the main wallet menu, tap the `...` button on the upper right corner, then tap `buy crypto` or `rename wallet`.
> Added dark mode to DappBrowserNavigationBar and ButtonsBarBackgroundView

- AlphaWallet/Common/Services/LocalNotificationService.swift
- AlphaWallet/Market/Coordinators/ImportMagicLinkCoordinator.swift
- AlphaWallet/Tokens/ViewModels/FungibleTokenViewModel.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/GasPriceEstimator/GasPriceEstimator.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/GasPriceEstimator/Models/EtherscanGasPriceEstimator.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/NFT/Enjin/Enjin.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/NFT/OpenSea/OpenSea.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Notifications/TransactionNotificationService.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Settings/Models/SendPrivateTransactionsProvider.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Settings/Types/RPCServerWithEnhancedSupport.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Settings/Types/RPCServers.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/SwapToken/Carthage/Carthage.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/SwapToken/HoneySwap/HoneySwap.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/SwapToken/Oneinch/Oneinch.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/SwapToken/QuickSwap/QuickSwap.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/SwapToken/Uniswap/UniswapERC20Token.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/TokensAutodetector/TokensAutodetector.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Transactions/Covalent/TransactionProviders/NewlyAddedTransaction/NewlyAddedTransactionSchedulerProvider.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Transfer/TransactionConfigurator.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Transfer/Types/GasLimitConfiguration.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Transfer/Types/GasPriceConfiguration.swift
Contains 2 commits:
* 1st commit contains the changes for this PR
* 2nd commit is to show how many files and changes are needed to add a basic chain (4 files, but still many lines of changes) — will be removed before merging
With this PR, when we need to add a new chain that doesn't have more fancy features and exceptions, it should only touch 4 files instead of 20 (!) files. I've also noticed that since we moved lots of code out into pods, including `AlphaWalletFoundation`, when we add a new case to `RPCServer` and build, it no longer shows all the places which needs to be changed (i.e. with errors) like it used to. We have to change and build, repeat a few times to sweep through all the files, making it even slower.
@oa-s not sure if this approach is good. Thoughts?
Edit: have to change …
> Add `RPCServerWithEnhancedSupport` to dramatically reduce number of files and changes required to add most new chains

- AlphaWallet/Localization/en.lproj/Localizable.strings
- AlphaWallet/Localization/es.lproj/Localizable.strings
- AlphaWallet/Localization/fi.lproj/Localizable.strings
- AlphaWallet/Localization/ja.lproj/Localizable.strings
- AlphaWallet/Localization/ko.lproj/Localizable.strings
- AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings
Closes #5415
I had checked for limit validation on the name and there was no validation so that we could remove the unused remark.
> remove unused remark from locale files - fix issue #5415

- AlphaWallet/Transfer/Coordinators/TransactionConfirmationCoordinator.swift
- AlphaWallet/Transfer/ViewControllers/SendTransactionErrorViewController.swift
- AlphaWallet/Transfer/ViewModels/SendTransactionErrorViewModel.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Extensions/Session+PromiseKit.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Transfer/SendTransaction.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Transfer/Types/SendTransactionError.swift
-|-
The handling of this particular message (in the "after" screenshot) will be improve separately. This PR is just to improve handling when the error is unknown.
> Handle unknown errors in actionsheet confirmation better by displaying them so support/developer can hear from user about it and improve it

- modules/AlphaWalletFoundation/AlphaWalletFoundation/GasPriceEstimator/GasPriceEstimator.swift
> Fix: we should use dapp provided gas price even if it's lower than expected

- AlphaWallet/Activities/ViewModels/ActivitiesViewModel.swift
- AlphaWallet/Activities/ViewModels/ActivityCellViewModel.swift
- AlphaWallet/Activities/ViewModels/DefaultActivityCellViewModel.swift
- AlphaWallet/Activities/ViewModels/GroupActivityCellViewModel.swift
- AlphaWallet/Activities/Views/ActivitiesView.swift
- AlphaWallet/Common/Types/Configuration.swift
- AlphaWallet/Resources/Assets.xcassets/bali.colorset/Contents.json
- AlphaWallet/Resources/Assets.xcassets/cheese.colorset/Contents.json
- AlphaWallet/Resources/Assets.xcassets/ocean.colorset/Contents.json
- AlphaWallet/Resources/Assets.xcassets/porcelain.colorset/Contents.json
- AlphaWallet/Tokens/Collectibles/ViewModels/FungibleTokenHeaderViewModel.swift
- AlphaWallet/Tokens/Collectibles/ViewModels/TokenAttributeViewModel.swift
- AlphaWallet/Tokens/Collectibles/Views/TokenHistoryChartView.swift
- AlphaWallet/Tokens/Collectibles/Views/TokenHistoryPeriodSelectorView.swift
- AlphaWallet/Tokens/Collectibles/Views/TokenInfoHeaderView.swift
- AlphaWallet/Tokens/Collectibles/Views/TokenInfoPageView.swift
- AlphaWallet/Transactions/ViewModels/TransactionRowCellViewModel.swift
Main wallet tab > Ethereum 
From created Wallet
Before PR | Light mode | Dark mode
-|-|-
From watched Wallet
Before PR | Light mode | Dark mode
-|-|-
From created Wallet
Before PR | Light mode | Dark mode
-|-|-
Push button animation below:
> Added dark mode to FungibleTokenViewController

- Makefile
Removed --repo-update option in cocoa pods install command.
> Removed —repo-update option in pod install command which causes errors when switching between Xcode 13.x and 14.x.

- AlphaWallet/Activities/ViewControllers/ActivityViewController.swift
- AlphaWallet/Activities/ViewModels/ActivityViewModel.swift
- AlphaWallet/Activities/ViewModels/DefaultActivityViewModel.swift
In main wallet tab, tap `ETH (Goerli) > Activity tab > Any display activity row`.
Before PR | Light mode | Dark mode
-|-|-
> Added dark mode to ActivityViewController

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet/AppCoordinator.swift
- AlphaWallet/AppDelegate.swift
- AlphaWalletTrackAPICalls.podspec
- Podfile
- Podfile.lock
- modules/AlphaWalletTrackAPICalls/.gitignore
- modules/AlphaWalletTrackAPICalls/AlphaWalletTrackAPICalls/AlphaWalletTrackAPICalls.h
- modules/AlphaWalletTrackAPICalls/AlphaWalletTrackAPICalls/Logger.swift
- modules/AlphaWalletTrackAPICalls/AlphaWalletTrackAPICalls/TrackApiCalls.swift
- modules/AlphaWalletTrackAPICalls/LICENSE
Closes #5589
Prints something like this every 10 seconds, only when running in simulator:
```
[TrackApiCalls] (sub)domains accessed: 16 Calls for each (sub)domain: [(key: "repo.tokenscript.org", value: 46), (key: "mainnet.infura.io", value: 45), (key: "rpc.ankr.com", value: 28), (key: "polygon-mainnet.infura.io", value: 23), (key: "api-cn.etherscan.com", value: 11), (key: "api.opensea.io", value: 10), (key: "api.polygonscan.com", value: 5), (key: "api.coingecko.com", value: 5), (key: "cloud.enjin.io", value: 5), (key: "blockscout.com", value: 4), (key: "li.quest", value: 2), (key: "api-instant.ramp.network", value: 1), (key: "firebaselogging-pa.googleapis.com", value: 1), (key: "raw.githubusercontent.com", value: 1), (key: "price.phi.network", value: 1), (key: "api.1inch.exchange", value: …
```
> Track number of API calls made while running in simulator

- modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/Helpers/JsonFromTokenUri.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/WalletBalance/TokenBalanceFetcher.swift
Closes #5595
Fixes #5596
@oa-s type inference in Xcode 13 is a bit weaker
> Fix: error building on Xcode 13 #5595 #5596

- modules/AlphaWalletFoundation/AlphaWalletFoundation/Helpers/Device.swift
Comment explains it:
> //Original check was: `versionCode == "i386" || versionCode == "x86_64" || versionCode == "arm64"`. But we want this to have no false-negatives since wrongly identifying as simulator can cause certain functionality to be unlocked for production/appstore users
> Reduce chance of false-negatively identifying app as running in simulator

- AlphaWallet/Wallet/ViewControllers/ImportWalletViewController.swift
- AlphaWallet/Wallet/ViewModels/ImportWalletViewModel.swift
In main wallet tab screen, tap the upper left corner icon. Then tap the plus symbol on the upper right corner. Select Import. Tap on the SEED PHRASE text view.
Before fix | After fix
-|-
> Fixed Dark Mode for Background In ImportWalletViewController

- AlphaWallet/Tokens/Collectibles/ViewModels/NFTAssetViewModel.swift
Main wallet tab, tap collectible tab, tap collectible with at least 1 token, tap any row.
1|2|3
-|-|-
Top before commit | Top after commit
-|-
Bottom before commit | Bottom after commit
> Added dark mode to NFTAssetViewController

- AlphaWallet/Tokens/ViewControllers/NewTokenViewController.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/EtherClient/TrustClient/Models/RawTransaction.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/Logic/ContractDataDetector.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/Logic/GetContractDecimals.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/Types/TokensDataStore.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Types/TokenProviderType.swift
A little undecided on this. Correctness vs simplicity. Let's try it anyway
> Make `decimals` be stored as `Int` instead of `UInt8`. Latter (to match actual source data in ERC20) seems unnecessary

- .travis.yml
If caching is enabled, adding a file to an existing module doesn't modify `Podfile.lock` and breaks the build on Travis
> [DEV] Remove Cocoapods caching with Travis because we are using development pods for our inhouse modules

- AlphaWallet/Extensions/UINavigationController.swift
Tap activity on tab bar at bottom of screen.
-|-
> Added dark mode to navigationController of Activity tab

- AlphaWallet/Common/Types/Configuration.swift
- AlphaWallet/Transactions/ViewModels/TransactionDetailsViewModel.swift
- AlphaWallet/Transactions/Views/TransactionAppearance.swift
Tap the activity tab, tap an entry listed, tap the icon in the upper right corner.
0 | 1 | 2
-|-|-
.png)
-|-
> Added dark mode to Transaction view

- AlphaWallet/Wallet/ViewModels/SeedPhraseBackupIntroductionViewModel.swift
- AlphaWallet/Wallet/ViewModels/SeedPhraseCollectionViewModel.swift
- AlphaWallet/Wallet/ViewModels/ShowSeedPhraseViewModel.swift
- AlphaWallet/Wallet/ViewModels/VerifySeedPhraseViewModel.swift
Tap Settings > Back up this wallet
Before | After
-|-
> Added dark mode to back up this wallet screen

- AlphaWallet/Wallet/ViewControllers/ShowSeedPhraseIntroductionViewController.swift
- AlphaWallet/Wallet/ViewModels/ShowSeedPhraseIntroductionViewModel.swift
Tap `Settings > Show seed phrase`
-|-
> Added dark mode to show seed phrase screen

- AlphaWallet/Lock/ViewControllers/LockPasscodeViewController.swift
- AlphaWallet/Lock/Views/LockView.swift
- AlphaWallet/Lock/Views/PasscodeCharacterView.swift
Tap `Settings > Passcode/FaceId`
Before | After
-|-
> Added dark mode to passcode / faceid screen

- AlphaWallet/Settings/ViewControllers/SupportViewController.swift
Tap `Settings > Support`
Before | After
-|-
> Added dark mode to support screen

- AlphaWallet/Activities/ViewControllers/ActivitiesViewController.swift
> Activity tab search bar does not update view for empty search results until tabs are switched. #5609

- AlphaWallet/Settings/Views/RPCDisplaySelectableTableViewCell.swift
Tap `Settings > Select Active Networks`, then toggle the `Testnet` switch to on. Tap the `enable testate` button on the pop up dialog.
Before | After
-|-
> Fixed dark mode in select active networks test net screen

- AlphaWallet/Localization/en.lproj/Localizable.strings
- AlphaWallet/Localization/es.lproj/Localizable.strings
- AlphaWallet/Localization/fi.lproj/Localizable.strings
- AlphaWallet/Localization/ja.lproj/Localizable.strings
- AlphaWallet/Localization/ko.lproj/Localizable.strings
- AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings
- AlphaWallet/TokenScript/ViewControllers/AssetDefinitionsOverridesViewController.swift
Closes: #5629
Tap `Settings > Advanced > TokenScript Overrides`.
Before | After (Light mode) | After (Dark mode)
-|-|-
> Added dark mode to Tokenscript Overrides screen

- AlphaWallet/Transfer/ViewModels/TransactionInProgressViewModel.swift
Send some test Eth to another wallet.
Before | After (Light mode) | After (Dark mode)
-|-|-
> Added dark mode to Transaction In Progress screen

- AlphaWallet/Transfer/ViewControllers/RequestViewController.swift
Fixes #5723
On the main wallet screen tap ... > Show My Wallet Address on the upper right corner.
iPhone 14 Pro
Before | After
-|-
> Fixed position of text and QRCode in My Wallet Address screen

- AlphaWallet/Common/Types/Configuration.swift
- AlphaWallet/Resources/Assets.xcassets/luckyPoint.colorset/Contents.json
Fixes #5614
Light mode | Dark mode
-|-
The colour is named luckyPoint based on a Google search for #323250. https://www.htmlcsscolor.com/hex/323250
> Fixed table view cell color in dark mode when sending currency in activity tab

- AlphaWallet/Common/Types/AppStyle.swift
From the wallet main screen, tap the upper left corner, tap the `+` sign, tap `Import Wallet`, tap `Keystore JSON`, tap `Import from iCloud/Dropbox/Google Drive`, tap `iCloud/Dropbox/Google Drive`.
Before | After
-|-
> Fixed UISearchBar dark mode background color in the iOS Document Browser.

- AlphaWallet/Common/Types/Configuration.swift
- AlphaWallet/Common/Views/ViewModels/RoundedEnsViewModel.swift
Fixes #5725
I changed the background of the button from R:237, G:237, B:237 to mike (233, 233, 233) in light mode (nearest fit in the style guide) and mine (47, 47, 47) in dark mode.
Before | After
-|-
> Fixed dark mode of background of Round button display wallet address

- modules/AlphaWalletFoundation/AlphaWalletFoundation/Helpers/Device.swift
In Device.swift, some Versions were named phoneXXX and some named iPhoneXXX. Renamed them all to phoneXXX to be consistent.
> Renamed Device.Version iPhone to phone in order to be consistent.

- AlphaWallet/ActiveWalletCoordinator.swift
Refer to tab bar in screenshots:
-|-
> Fix: empty tab bar button appears in the middle on devices because Swap is now enabled

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet/Tokens/Collectibles/Views/TokenHistoryChartView.swift
- AlphaWallet/Tokens/ViewModels/TokenHistoryChartViewModel.swift
- Podfile
- Podfile.lock
We don't need the fork now since it only adds a commit from upstream so it with Xcode 14 RC.
Also needed the updated pod for #5513 which makes Travis builds with Xcode 14 because Travis uses x86_64 and don't support Apple Silicon.
> Switch `Charts` pod back to upstream so it can build with Travis (x86_64)

- AlphaWallet/Transfer/ViewModels/SendViewModel.swift
> Fix: ERC20 tokens sent wrongly to token contract (instead of intended address)

- modules/AlphaWalletFoundation/AlphaWalletFoundation/Analytics/AnalyticsTypes.swift
@oa-s seems should be removed as `AnalyticsUserProperty` is for logging to user "profile"?
> [Refactor] Remove spurious inheritance

- AlphaWalletTests/EtherClient/EtherKeystoreTests.swift
@oa-s `KeystoreKey(password: passphrase, key: privateKey)` seems to have become slower? So strange.
> [Tests] Fix broken tests

- AlphaWallet.xcodeproj/project.pbxproj
> [!] `<PBXSourcesBuildPhase UUID=`2912CCF11F6A830700C6CBE3`>` attempted to initialize an object with an unknown UUID. `87DD0C40279977E700460260` for attribute: `files`. This can be the result of a merge and the unknown UUID is being discarded.
> Fix warning with `bundle pod install`

- AlphaWalletTests/Transactions/Storage/TransactionsStorageTests.swift
> Amended storage.delete in TransactionsStorageTests to accept new syntax.

- AlphaWallet/AddMultipleCustomRpc/AddMultipleCustomRpcView.swift
- AlphaWallet/Common/Types/Configuration.swift
Tap `Settings > Select Active Networks > + on top right corner`. Select two or more networks. Tap `Add Network` button.
-|-
> Added dark mode to add network dialog on Add Custom RPC network screen

- modules/AlphaWalletFoundation/AlphaWalletFoundation/TokenScriptClient/Models/AssetDefinitionStore.swift
> [TokenScript] Fix infinite recursion when we drop in a TokenScript file for a contract which has a official TokenScript file in the central repo

- modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/Helpers/CallSmartContractFunction.swift
> Fix: TokenScript attributes calling the same function but with different return types specified will return wrong results

- AlphaWallet/Tokens/Collectibles/ViewModels/NFTAssetViewModel.swift
- AlphaWallet/Tokens/Collectibles/ViewModels/NFTCollectionInfoPageViewModel.swift
- AlphaWallet/Tokens/Collectibles/ViewModels/NFTCollectionViewModel.swift
- AlphaWallet/Tokens/TokenInstanceViewConfigurationHelper.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/TokenScriptClient/Models/AssetAttributeToUserinterfaceConvertor.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/TokenScriptClient/Models/XMLHandler.swift
- modules/AlphaWalletOpenSea/AlphaWalletOpenSea/OpenSeaNonFungibleTrait.swift
Closes #5862
Includes #5918
TokenScript-level attributes look like this (like how OpenSea traits does) — the "IsRedeemed" and "IsRedeemedBool" attributes from `wget https://alphawallet.infura-ipfs.io/ipfs/QmcxMgfV4dsZpr5S6w2GXKXPA6LLErxxGY7WPY5JwEK957`
> Inject tokenscript attributes in token view

- AlphaWallet/Common/Types/Configuration.swift
- AlphaWallet/Lock/Views/PasscodeCharacterView.swift
Fixes #4577
From main wallet screen:
1. Set screen in light mode
2. Tap Settings
3. Tap Passcode/FaceID
4. Tap 3 digits
5. Switch to dark mode (glitch occurs here)
6. Tap 2 digits
When the glitch occurs, the PasscodeCharacterView is displaying all empty until another key is tapped. Then it presents the correct display.
Before | After
-|-
> Corrected glitch in PasscodeCharacterView when switching between light and dark modes.

- AlphaWallet/TokenScript/ViewControllers/AssetDefinitionsOverridesViewController.swift
> Replace delete cell function with `trailingSwipeActionsConfigurationForRowAt` for asset definitions overrides screen #5923

- AlphaWallet/Browser/Coordinators/ScanQRCodeCoordinator.swift
> Fix: Scanning a QR code containing an address with a trailing linebreak does nothing

- .swiftformat
- AlphaWallet.xcodeproj/project.pbxproj
Also include rules (but commented out) that should be enabled gradually.
Also fixes invocation of SwiftFormat in build phase so:
* It only runs for `Debug` builds
* It uses the CocoaPod instead of testing for a system wide `swiftformat` binary
> [SwiftFormat] Enable SwiftFormat, but with minimal set of rules that doesn't modify existing code

- AlphaWallet/Browser/Coordinators/DappBrowserCoordinator.swift
The DappBrowser passes in the account field but it is currently unused. This is because we rely on the unconfirmed transaction from address to be the appropriate account we need to sign with.
Tests: builds
> remove unused account parameter for DappBrowserCoordinator

- AlphaWallet/Tokens/ViewControllers/TokensViewController.swift
- AlphaWallet/Tokens/ViewModels/TokensViewModel.swift
Before PR when near the bottom|After PR
-|-
This remains unchanged when scrolled to the bottom:
> Make Buy Crypto button's button bar in wallet tab have a transparent background color so list of tokens scroll behind it

- modules/AlphaWalletFoundation/AlphaWalletFoundation/Settings/Types/RPCServers.swift
By empirically running against something like these and watching for error messages and time to respond:
```
curl -H 'accept: application/json' -H 'content-type: application/json' -H 'user-agent: AlphaWallet/395 CFNetwork/1237 Darwin/20.5.0' -H 'accept-language: en-us' --data-binary '[
{"method":"eth_blockNumber","id":1,"params":[],"jsonrpc":"2.0"},
{"method":"eth_blockNumber","id":2,"params":[],"jsonrpc":"2.0"},
{"method":"eth_blockNumber","id":999999999,"params":[],"jsonrpc":"2.0"}]'
--compressed '<RPC node URL>'
```
> Increase RPC batch limits to improve app performance

- AlphaWallet/Browser/Views/BrowserErrorView.swift
- AlphaWallet/Common/Types/AppStyle.swift
- AlphaWallet/Common/Types/Configuration.swift
- AlphaWallet/Common/Views/Button.swift
1. From main wallet screen, tap browser button.
2. Enter 127.0.0.1 in address bar of browser.
3. The background has been changed to adapt to dark mode.
Before | Light After | Dark After
-|-|-
`.solid`, `.squared`, `.border` are not used as far as I can determine.
```swift
var borderColor: UIColor {
switch self {
case .solid, .squared, .border: return Configuration.Color.Semantic.defaultButtonBorder
case .borderless, .system, .special: return .clear
case .green: return ButtonsBarViewModel.primaryButton.buttonBorderColor
}
}
```
> Removed all direct references and definition of `Colors.alabaster`

- Makefile
Fixes #6104
No change required in Swift code as the file is referenced as `R.file.chainsZip` which is taken care of by R.swift.
> Updated Makefile to move the compressed chains file into the AlphaWallet/Resources directory

- AlphaWallet/Common/Types/AppStyle.swift
- AlphaWallet/Common/Types/Configuration.swift
- AlphaWallet/Common/Views/ButtonsBar/ButtonsBar.swift
- AlphaWallet/Sell/ViewModels/GenerateSellMagicLinkViewModel.swift
- AlphaWallet/Sell/ViewModels/GenerateTransferMagicLinkViewModel.swift
- AlphaWallet/Tokens/ViewModels/OpenSea/OpenSeaNonFungibleTokenCardRowViewModel.swift
- AlphaWallet/Tokens/ViewModels/TokenHistoryChartViewModel.swift
After #6100 
1. From main wallet screen, look at Buy Crypto Button.
Light | Dark After
-|-
> Removed all direct references and definition of `Colors.appActionButtonShadow`.

- AlphaWallet/Settings/ViewModels/LocaleViewModel.swift
- AlphaWallet/Tokens/ViewControllers/TokenInstanceActionViewController.swift
- AlphaWallet/Wallet/ViewControllers/ElevateWalletSecurityViewController.swift
- AlphaWallet/Wallet/ViewControllers/SeedPhraseBackupIntroductionViewController.swift
- AlphaWallet/Wallet/ViewControllers/ShowSeedPhraseViewController.swift
- AlphaWallet/Wallet/ViewControllers/VerifySeedPhraseViewController.swift
- AlphaWallet/Wallet/ViewModels/ElevateWalletSecurityViewModel.swift
There is nothing in this wallet.
1. Tap settings
2. Tap Advanced
3. Tap Features
4. Enable "Is language switcher enabled"
5. Tap back arrow
6. Tap Change Language
Light mode (before/after) | Dark mode
-|-
This view is totally obscured by an instance of RoundedBackground so it's colour doesn't matter.
[Link to instructions](https://github.com/AlphaWallet/alpha-wallet-ios/pull/5956#issuecomment-1373173201)
On a device, not simulator:
1. Settings tab
2. Back up this Wallet
3. Tap Back up my Wallet
4. OK, I wrote this down
5. Tap to enter seed phrase
6. Tap Verify Seed Phrase
7. Tap Lock Seed Phrase
Light mode (before/after) | Dark mode before | Dark mode after image
-|-|-
1. Tap settings
2. Tap back up this wallet
Light mode (before/after) | Dark mode image
-|-
1. Tap settings
2. Tap show …
> Removed all direct references and definition of `Colors.appBackground`

- AlphaWallet/Common/Types/AppStyle.swift
- AlphaWallet/Common/Types/Configuration.swift
- AlphaWallet/Common/Views/AmountTextField.swift
- AlphaWallet/Tokens/ViewControllers/VerifiableStatusViewController.swift
Semantic renaming of variable. No change in actual colour.
> Semantic renaming of variable `Colors.appGreenContrastBackground` to `Configuration.Color.Semantic.textFieldContrastText`. No change in actual colour.

- modules/AlphaWalletFoundation/AlphaWalletFoundation/EtherClient/RLP.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/EtherClient/Requests/GetTransactionRequest.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Foundation/QRCodeValueParser.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Rpc Network/AvailableRpcNetwork.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/TokenScriptClient/Models/AssetAttributeSyntax.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/TokenScriptClient/Models/AssetAttributeValueUsableAsFunctionArguments.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Types/PendingTransaction.swift
- modules/AlphaWalletWeb3/AlphaWalletWeb3/Extensions/String+Extension.swift
- modules/AlphaWalletWeb3/AlphaWalletWeb3/Utils/Web3+Utils.swift
Separate commits because they are atomic. Can merge as it is without squashing.
> Make functions return type reflect actual return types

- modules/AlphaWalletWeb3/AlphaWalletWeb3/Transaction/EthereumTransaction.swift
- modules/AlphaWalletWeb3/AlphaWalletWeb3/Web3/Web3+Contract.swift
- modules/AlphaWalletWeb3/AlphaWalletWeb3/Web3/Web3+Options.swift
- modules/AlphaWalletWeb3/AlphaWalletWeb3/Web3/Web3+TransactionIntermediate.swift
@oa-s help check if the intention is for `merge(_:,with:)` to return an non-optional default if both the args are `nil`?
> Make function return type be non-optional to reflect actual return type

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWallet/AppCoordinator.swift
- AlphaWallet/Browser/Coordinators/ScanQRCodeCoordinator.swift
- AlphaWallet/Donations/CameraDonation.swift
- AlphaWallet/Info.plist
- AlphaWallet/Localization/en.lproj/Localizable.strings
- AlphaWallet/Localization/es.lproj/Localizable.strings
- AlphaWallet/Localization/fi.lproj/Localizable.strings
- AlphaWallet/Localization/ja.lproj/Localizable.strings
- AlphaWallet/Localization/ko.lproj/Localizable.strings
- AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Analytics/AnalyticsTypes.swift
Donates the Siri shortcut when the user starts the in-app camera (unlike the shortcut for displaying the wallet QR code which is is donated when the wallet is loaded/switched to).
Tapping the shortcut launches the in-app camera/QR code scanner.
The donated shortcut appears in search results and in the Siri suggestions widget. Looks like this in the search results:
> Donate shortcut for camera

- AlphaWallet/Common/Types/AppStyle.swift
- AlphaWallet/Common/Types/Configuration.swift
This commit is temporary. A later commit will remove Configuration.Colors.Semantic.secondary.
> Changed Configuration.Colors.Semantic.secondary to refer to the actual color instead of Colors.appGrayLabel

- AlphaWallet/Accounts/ViewModels/AccountsViewModel.swift
- AlphaWallet/Alerts/ViewControllers/PriceAlertsViewController.swift
- AlphaWallet/Browser/ViewControllers/BookmarksViewController.swift
- AlphaWallet/Browser/ViewControllers/BrowserHistoryViewController.swift
- AlphaWallet/Browser/Views/DappViewCell.swift
- AlphaWallet/Common/Types/AppStyle.swift
- AlphaWallet/Common/Types/Configuration.swift
- AlphaWallet/Common/Views/TextField.swift
- AlphaWallet/Common/Views/WhereIsWalletAddressFoundOverlayView.swift
- AlphaWallet/Market/ViewModels/ImportMagicTokenViewControllerViewModel.swift
- AlphaWallet/Sell/ViewControllers/SetSellTokensCardExpiryDateViewController.swift
- AlphaWallet/Sell/ViewModels/GenerateSellMagicLinkViewModel.swift
- AlphaWallet/Sell/ViewModels/GenerateTransferMagicLinkViewModel.swift
- AlphaWallet/Settings/ViewControllers/EnabledServersViewController.swift
- AlphaWallet/TokenScript/ViewControllers/AssetDefinitionsOverridesViewController.swift
- AlphaWallet/Tokens/ViewControllers/AddHideTokensViewController.swift
- AlphaWallet/Tokens/ViewControllers/VerifiableStatusViewController.swift
- AlphaWallet/Tokens/ViewModels/FungibleTokenDetailsViewModel.swift
- AlphaWallet/Tokens/ViewModels/TokenHistoryChartViewModel.swift
- AlphaWallet/Tokens/ViewModels/TokensViewModel.swift
- AlphaWallet/Transactions/ViewModels/TransactionRowViewModel.swift
- AlphaWallet/Transactions/ViewModels/TransactionViewModel.swift
- AlphaWallet/Transfer/ViewControllers/ConfigureTransactionViewController.swift
- AlphaWallet/Transfer/ViewControllers/SetTransferTokensCardExpiryDateViewController.swift
- AlphaWallet/Wallet/ViewModels/ElevateWalletSecurityViewModel.swift
- AlphaWallet/Wallet/ViewModels/ShowSeedPhraseViewModel.swift
- AlphaWallet/Wallet/ViewModels/VerifySeedPhraseViewModel.swift
- AlphaWallet/WalletConnect/ViewController/WalletConnectSessionsViewController.swift
- AlphaWallet/WalletConnect/ViewModel/WalletConnectSessionDetailsViewModel.swift
The only two types of actual change here is from `Configuration.Color.Semantic.fail` and `Configuration.Color.Semantic.depreciation` to `UIColor(hex: "ff3b30")`. The rest of the changes are just renaming `Colors.appRed` to their equivilant semantic counter part.
| Name | Value |
-|-
Colors.appRed | R.color.danger
Configuration.Color.Semantic.dangerBackground | R.color.danger
Configuration.Color.Semantic.deleteButtonTitle | R.color.danger
Configuration.Color.Semantic.textFieldError | R.color.danger
Configuration.Color.Semantic.defaultNote | R.color.danger
Configuration.Color.Semantic.defaultErrorText | R.color.danger
Configuration.Color.Semantic.fail | UIColor(hex: "ff3b30")
Configuration.Color.Semantic.depreciation | UIColor(hex: "ff3b30")
Turns out R.color.danger is also ff3b30. So there …
> [Refactor] Semantic renaming of variable Colors.appRed to various Configuration.Color.Semantic values. No change in actual colour.

- AlphaWallet/Common/Types/AppStyle.swift
- AlphaWallet/Transactions/Views/TransactionTableViewCell.swift
Changed Colors.appSubtitle (UIColor(red: 117, green: 117, blue: 117)) to Configuration.Colors.Semantic.defaultSubtitleText (Light mode: UIColor(red: 113, green: 113, blue: 113), Dark mode: UIColor(red: 153, green: 153, blue: 153)) or (Light mode: Dove, Dark mode: Dusty).
I changed the colors to the closest matching color in the style guide. RGB: 117/117/117 did not exist. Closest match was Dove (113/113/113). 
Light (Before) | Light (After) | Dark (After)
-|-|-
> [Refactor] Changed Colors.appSubtitle to Configuration.Colors.Semantic.defaultSubtitleText

- modules/AlphaWalletFoundation/AlphaWalletFoundation/Types/WalletBalance.swift
> move to default comparison implementation for structs for `WalletBalance` #6247

- AlphaWallet/Common/Types/AppStyle.swift
- AlphaWallet/Common/Types/Configuration.swift
- AlphaWallet/Common/Views/TextField.swift
- AlphaWallet/Common/Views/ViewModels/TokenCardRowViewModelProtocol.swift
- AlphaWallet/Lock/Views/PasscodeCharacterView.swift
- AlphaWallet/Market/ViewModels/ImportMagicTokenViewControllerViewModel.swift
Light mode | Dark mode
-|-
Light mode | Dark mode
-|-
Light mode | Dark mode
-|-
> [Refactor] Removed Colors.navigationTitleColor

- AlphaWallet/Common/Types/AppStyle.swift
- AlphaWallet/Tokens/Collectibles/Views/TokenHistoryChartView.swift
- AlphaWallet/WalletConnect/View/TransactionConfirmationRPCServerInfoView.swift
Light mode | Dark mode
-|-
This view was forced to appear by setting the `isHidden` field to false. I could not get it to show without intervention.
Light mode | Dark mode
-|-
> [Refactor] Changed Colors.darkGray to Configuration.Color.Semantic.alternativeText.

- AlphaWallet/Common/Types/AppStyle.swift
- AlphaWallet/Common/Views/SelectAssetAmountView.swift
- AlphaWallet/Tokens/ViewControllers/TokensViewController.swift
- AlphaWallet/Tokens/ViewModels/FungibleTokenDetailsViewModel.swift
Color was changed from 313849 to black (light mode) and white (dark mode).
Original | Light | Dark
-|-|-
Original | Light | Dark
-|-|-
Original | Light | Dark
-|-|-
> [Refactor] Changed Colors.black to Configuration.Color.Semantic.defaultForegroundText

- AlphaWallet/Transfer/ViewModels/SignatureConfirmationConfirmationViewModel.swift
> When we sign a short message that is still long enough to be truncated, the "Show" button doesn't appear #6221

- AlphaWallet/AlphaWalletHelp/Views/ContactUsBannerView.swift
- AlphaWallet/Common/Types/AppStyle.swift
- AlphaWallet/Common/Types/Configuration.swift
- AlphaWallet/Common/Views/StateViewModel.swift
- AlphaWallet/Tokens/Collectibles/ViewControllers/NFTAssetSelectionViewController.swift
Light | Dark
-|-
Default Colours overridden by https://github.com/AlphaWallet/alpha-wallet-ios/blob/eeea2673c9c44a9e8024f2b15d9f05285ca55bfc/AlphaWallet/Common/Views/LoadingView.swift#L66-L73
Light | Dark
-|-
> [Refactor] Changed Colors.appText to Configuration.Color.Semantic.defaultIcon and Configuration.Color.Semantic.defaultForegroundText

- AlphaWallet/Accounts/ViewModels/AccountsViewModel.swift
- AlphaWallet/Activities/Views/ActivityStateView.swift
- AlphaWallet/Browser/ViewControllers/BrowserViewController.swift
- AlphaWallet/Browser/ViewModel/BrowserHistoryCellViewModel.swift
- AlphaWallet/Browser/ViewModel/MyDappCellViewModel.swift
- AlphaWallet/Common/Types/AppStyle.swift
- AlphaWallet/Common/Types/Configuration.swift
- AlphaWallet/Common/Views/Button.swift
- AlphaWallet/Common/Views/ButtonsBar/ButtonsBar.swift
- AlphaWallet/Settings/Views/LocaleViewCell.swift
- AlphaWallet/Swap/Swap/Views/SwapQuoteDetailsView.swift
- AlphaWallet/Swap/SwapOptions/Views/SwapOptionsHeaderView.swift
- AlphaWallet/Swap/SwapRoutes/ViewModels/SelectableSwapRouteTableViewCellViewModel.swift
- AlphaWallet/Tokens/Collectibles/ViewModels/NonFungibleTraitViewModel.swift
- AlphaWallet/Tokens/Collectibles/ViewModels/SingleNFTAssetSelectionViewModel.swift
- AlphaWallet/Tokens/ViewModels/ShowAddHideTokensViewModel.swift
- AlphaWallet/Transfer/ViewControllers/SendTransactionErrorViewController.swift
- AlphaWallet/Transfer/Views/TransactionConfirmationHeaderView.swift
Light | Dark 
-|-
Light | Dark 
-|-
Light | Dark 
-|-
Light | Dark 
-|-
Light | Dark
-|-
Light | Dark
-|-
Light | Dark
-|-
Light | Dark
-|-
Light | Dark
-|-
Light | Dark
-|-
Light | Dark
-|-
Light | Dark
-|-
Light | Dark
-|-
Light | Dark
-|-
Light | Dark
-|-
Light | Dark
-|-
> [Refactor] Changed Colors.appTint to Configuration.Color.Semantic.appTint

- AlphaWallet/Backup/ViewModels/PromptBackupWalletViewViewModel.swift
- AlphaWallet/Common/Types/AppStyle.swift
- AlphaWallet/Common/Types/Configuration.swift
- AlphaWallet/Common/Views/Button.swift
- AlphaWallet/Common/Views/ButtonsBar/ButtonsBar.swift
- AlphaWallet/Transfer/Views/TransitionButton.swift
The text.
Light | Dark
-|-
The button background.
Light | Dark
-|-
The text.
Light | Dark
-|-
The background of the confirm button during transition (when the button shrinks).
Light | Dark
-|-
> [Refactor] Changed Colors.appWhite to Configuration.Color.Semantic.defaultInverseText and Configuration.Color.Semantic.defaultButtonBackground

- AlphaWallet/WalletConnect/Providers/v2/WalletConnectV2Client.swift
Because:
```
public struct EthereumSignature {
public let v: UInt8
public let r: [UInt8]
public let s: [UInt8]
public init(v: UInt8, r: [UInt8], s: [UInt8]) {
self.v = v
self.r = r
self.s = s
}
//...
public var serialized: Data {
return Data(r + s + [UInt8(v + 27)])
}
```
> Fix: remove spurious +27 to v since it's done in WalletConnectSwiftV2.EthereumSignature.serialized

- AlphaWallet/Activities/Views/ActivityStateView.swift
- AlphaWallet/Browser/ViewControllers/BrowserViewController.swift
- AlphaWallet/Common/Types/Configuration.swift
- AlphaWallet/Common/Views/LoadingIndicatorView.swift
- AlphaWallet/Common/Views/LoadingView.swift
- AlphaWallet/Common/Views/ScrollableSegmentedControl/ScrollableSegmentedControlCell.swift
- AlphaWallet/Tokens/ViewModels/OpenSea/OpenSeaNonFungibleTokenCardRowViewModel.swift
- AlphaWallet/Tokens/ViewModels/TokensViewModel.swift
- AlphaWallet/Tokens/Views/AddHideTokensView.swift
Direct replacement of .white.
Direct replacement of .white.
Added new definitions
Direct replacement of .white.
Replaced .white with .defaultViewBackground
Removed .white as textColor is always overridden by ScrollableSegmentedControlCellConfiguration
Modified code to show label with string "MYTARGET".
Light | Dark
-|-
Replaced .white with .defaultViewBackground
The red circle with the number. Modified code to display label.
Light | Dark
-|-
> [Refactor] Changed UIColor.white to various Configuration.Color.Semantic versions

- modules/AlphaWalletFoundation/AlphaWalletFoundation/KeyManagement/EtherKeystore.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/KeyManagement/Keystore.swift
More refactoring around signing to code to support hardware signing. In this PR, we remove a duplicate function and call the remaining one. They both operate on `Data`. Just the one that is removed is non-optional.
> [Refactoring] Remove duplicate function and only call the remaining one

- AlphaWallet/Accounts/Views/AccountViewTableSectionHeader.swift
> Removed background color from AccountViewTableSectionHeader label (default is clear)

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWalletTests/Core/HostBasedTokenUriMapperTests.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/Helpers/JsonFromTokenUri.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/Models/NonFungibleContract.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Types/TokenUriMapSupportable.swift
support token uri rewriting, some of returned token uris return uri with token id with zeros siffix to reach 64 characters, and api don't suport it such uris
such as `https://api.mintkudos.xyz/metadata/3ba0000000000000000000000000000000000000000000000000000000000000` it needs to be converted to 
`https://api.mintkudos.xyz/metadata/954`
> support token uri rewriting

- AlphaWallet/Common/Views/AddressTextField.swift
- AlphaWallet/Swap/Swap/ViewModels/SwapQuoteDetailsViewModel.swift
- AlphaWallet/Transfer/ViewModels/TransactionConfirmation/CancelTransactionViewModel.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Settings/Models/AddCustomChain.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Settings/Types/SendInputErrors.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/TokenScriptClient/Models/XMLHandler.swift
Closes #6541
I ran `grep -nriI "LocalizedError" . | grep -i ".swift" | grep -i "module" | sort > ~/Desktop/LocalizedErrors.txt` on the root directory of the repo to find all the instances where `LocalizedError ` occurred in swift files in the module directory. This gave me a list of 19 instances.
```text
./modules/AlphaWalletENS/AlphaWalletENS/ENSError.swift:9:struct ENSError: LocalizedError {
./modules/AlphaWalletFoundation/AlphaWalletFoundation/EtherClient/CastError.swift:5:public struct CastError<ExpectedType>: LocalizedError {
./modules/AlphaWalletFoundation/AlphaWalletFoundation/Ethereum/ABI/ABIError.swift:9:public enum ABIError: LocalizedError {
./modules/AlphaWalletFoundation/AlphaWalletFoundation/KeyManagement/EtherKeystore.swift:11:public enum EtherKeystoreError: LocalizedError { …
```
> Fixed error type implementation for errors that are defined in modules which provide errorDescription in the application. 

- modules/AlphaWalletFoundation/AlphaWalletFoundation/Settings/Types/RPCServers.swift
Sepolia is a testnet:
https://ethereum.org/en/developers/docs/networks/#ethereum-testnets
If bug:
Fixes #6575 
If not a bug:
Closes #
1-liner summary: Mark Sepolia as testnet, not mainnet
> Mark Sepolia as testnet, not mainnet (close #6575)

- AlphaWallet/Localization/en.lproj/Localizable.strings
> Setting passcode in Settings should say "passcode", not "password" #6639

- modules/AlphaWalletFoundation/AlphaWalletFoundation/EtherClient/RLP.swift
Fixes: #6655
@oa-s would you help to add a test case? Maybe just need to pass some hardcoded to `EIP155Signer.rlpEncoded(transaction:, with:)` and verify output? No signing involved.
> [Sign] Fix: signing pre-EIP-1559 transactions always fails with `SignerError.rplEncodeFailure` #6655

- AlphaWallet.xcodeproj/project.pbxproj
- AlphaWalletTests/Misc/ScheduledToDoTest.swift
When date is past, we get this output:
```text
ScheduleSpamTokenIconRemovalFromIconAssetsTest
✖ testDueDate, XCTAssertTrue failed - TODO:- Spam Token Icon Removal task: https://github.com/AlphaWallet/iconassets/issues/30
```
> Added `testReminderToRemoveSpamTokenIconFilesFromIconAssetsRepo` to schedule removal of spam token icon from iconassets repository

- AlphaWalletTests/Core/PublisherToAsyncTests.swift
Removed PublisherToAsyncTests.testCancellation
[Link to comment](https://github.com/AlphaWallet/alpha-wallet-ios/issues/6673#issuecomment-1510733990)
> Removed incomplete PublisherToAsyncTests.testCancellation

- AlphaWalletTests/Tokens/TokenGroupIdentifierTest.swift
Changed the input to read an actual non-json file.
> Fixed testReadingExistingNonJsonFile by reading an actual non-json file

- .travis.yml
Closes #6798
In the terminal go to the root directory of the project.
1. type `set -o pipefail && xcodebuild -workspace AlphaWallet.xcworkspace -scheme AlphaWalletTests -destination "platform=iOS Simulator,OS=16.4,name=iPhone 14 Pro" clean | ./Pods/xcbeautify/xcbeautify`
2. type `set -o pipefail && xcodebuild -workspace AlphaWallet.xcworkspace -scheme AlphaWalletTests -destination "platform=iOS Simulator,OS=16.4,name=iPhone 14 Pro" build-for-testing | ./Pods/xcbeautify/xcbeautify`
To see the project build succeed.
1. type `set -o pipefail && xcodebuild -workspace AlphaWallet.xcworkspace -scheme AlphaWalletTests -destination "platform=iOS Simulator,OS=16.4,name=iPhone 14 Pro" clean | ./Pods/xcbeautify/xcbeautify`
2. Go to a test and type in a syntax error
3. type `set -o pipefail && …
> Update Travis to only build the main target (AlphaWallet) and the test target (AlphaWalletTests)

- modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/Logic/EtherscanCompatibleApiNetworking.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/UniqueNonEmptyContracts.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Transactions/BlockscoutApiNetworking.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Types/RPCServers.swift
validate token transfer transaction, add filtering for only expected transaction types
e.g Blockscout api might return eip20 an eip721 token transfer transactions in same response
> Validate token transfer transactions

- modules/AlphaWalletFoundation/AlphaWalletFoundation/Extensions/Session+PromiseKit.swift
> Fix displaying "The data couldn't be read because it isn't in the correct format." decoding error #6821

- modules/AlphaWalletFoundation/AlphaWalletFoundation/Analytics/AnalyticsTypes.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/Logic/EtherscanCompatibleApiNetworking.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Transactions/BlockscoutApiNetworking.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Transactions/Covalent/CovalentApiNetworking.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Transactions/Oklink/OklinkNetworking.swift
- modules/AlphaWalletFoundation/AlphaWalletFoundation/Types/SessionsProvider.swift
Also trap and log Etherscan rate limiting errors, which are still returned as `200`
> [Analytics] Log blockchain explorer API errors
