AlphaWallet/InCoordinator.swift
AlphaWallet/Sell/Views/AmountTextField.swift
AlphaWallet/Transfer/Coordinators/PaymentCoordinator.swift
AlphaWallet/Transfer/Coordinators/SendCoordinator.swift
AlphaWallet/Transfer/ViewControllers/SendViewController.swift
AlphaWallet/Transfer/ViewModels/SendHeaderViewViewModel.swift
AlphaWallet/Transfer/ViewModels/SendViewModel.swift
AlphaWallet/Transfer/Views/SendHeaderView.swift
AlphaWalletTests/Coordinators/SendCoordinatorTests.swift
AlphaWalletTests/ViewControllers/PaymentCoordinator.swift

Use the shared AmountTextField class in SendViewController, replacing a bunch of duplicated code

---

AlphaWallet/AssetDefinition/AssetAttribute.swift
AlphaWallet/AssetDefinition/XMLHandler.swift
AlphaWallet/Settings/Types/Constants.swift
AlphaWallet/Tokens/Types/Ticket.swift
AlphaWallet/Tokens/Types/TokenHolder.swift
AlphaWalletTests/Market/ViewControllers/ImportTicketViewControllerTests.swift
AlphaWalletTests/Tokens/Helpers/TicketAdaptorTest.swift
AlphaWalletTests/Transfer/ViewControllers/TransferTicketsQuantitySelectionViewControllerTests.swift

Move hardcoded attribute names closer to ui layer

---

AlphaWallet/Redeem/ViewControllers/RedeemTicketsViewController.swift
AlphaWallet/Sell/ViewControllers/SellTicketsViewController.swift
AlphaWallet/Tokens/ViewControllers/TicketsViewController.swift
AlphaWallet/Tokens/Views/BaseTicketTableViewCell.swift

Needed for #574 (and also for other cases in the future) where rows have varying heights.

Make tickets row cells in ticket/redeem/transfer/sell lists self-sizing

---

AlphaWallet/InCoordinator.swift
AlphaWalletTests/Coordinators/InCoordinatorTests.swift

Ok. The key to reproducing this on a development machine is to delete the app in the simulator first.

Fix broken test(s) on Travis

---

AlphaWallet/Tokens/Types/TokenObject.swift
AlphaWalletTests/Tokens/Helpers/TokenObjectTest.swift

compare with null ticket as biguint does not work for comparing to zero

---

AlphaWallet.xcodeproj/project.pbxproj
AlphaWallet/Tokens/Helpers/TokenAdaptor.swift
AlphaWallet/Tokens/ViewControllers/TicketsViewController.swift
AlphaWallet/Transactions/Coordinators/TicketsCoordinator.swift
AlphaWallet/Transfer/Coordinators/TransferNFTCoordinator.swift
AlphaWallet/Transfer/Types/TransferType.swift

Fix transfer logic erc721

---

AlphaWallet/Tokens/ViewControllers/TokensCardViewController.swift

One of the renames wasn't picked up.

Fix: bad merge

---

AlphaWallet/Transfer/Coordinators/TransferNFTCoordinator.swift

Fix: wrong text shown in token transfer UI

---

AlphaWallet/Info.plist
Podfile
Podfile.lock

Seems to work with all functions in web3js, will keep as WIP until full testing and/or we find a way to fix the original

with nervos as web3js provider for dapp browser

---

.swiftlint.yml
AlphaWallet.xcodeproj/project.pbxproj
AlphaWallet/Core/Initializers/MigrationInitializer.swift
AlphaWallet/Tokens/Coordinators/TokensCoordinator.swift
AlphaWallet/Tokens/Types/DelegateContract.swift
AlphaWallet/Tokens/Types/TokensDataStore.swift

Filter delegate contracts when autodetecting tokens

---

AlphaWallet/Tokens/Coordinators/TokensCoordinator.swift

For #646 
This PR should be considered a temporary fix as it adds this very ugly code to avoid firing too many requests consecutively, to keep the app from hanging:
```
let millionthOfSecondsToSleep: UInt32 = 300000
usleep(millionthOfSecondsToSleep)
```
This will go away when we fork web3swift to make it use Promises without blocking.

Fix: app hangs if many tokens are auto-detected and we fetch their name, symbols etc

---

AlphaWallet/Redeem/ViewModels/TokenListFormatRowViewModel.swift
AlphaWallet/Settings/Types/Constants.swift

Fix: app crash when displaying CryptoKitty with a cooldown that is longer than expected

---

AlphaWallet/Core/Initializers/MigrationInitializer.swift
AlphaWallet/Settings/Types/Constants.swift
AlphaWallet/Tokens/Types/TokensDataStore.swift

migrates realm correctly to prevent ether being marked as erc20

---

AlphaWallet/InCoordinator.swift
AlphaWallet/Transfer/Coordinators/PaymentCoordinator.swift
AlphaWallet/Transfer/Coordinators/SendCoordinator.swift
AlphaWallet/Transfer/ViewControllers/SendViewController.swift

For #640.
It's using the "Unverified" icon + title.

Add open etherscan button for erc20 token cards

---

AlphaWallet/Tokens/ViewControllers/VerifiableStatusViewController.swift

Hide redeem info button for ERC875 tokens if not FIFA tickets

---

AlphaWallet/Market/Coordinators/UniversalLinkCoordinator.swift
AlphaWallet/Settings/Types/Constants.swift

Check against payment server if free contract is supported for contract while importing

---

AlphaWallet/AppDelegate.swift
AlphaWallet/AssetDefinition/XMLHandler.swift
AlphaWallet/InCoordinator.swift
AlphaWallet/Market/Coordinators/UniversalLinkCoordinator.swift
AlphaWallet/Market/ViewControllers/ImportMagicTokenViewController.swift
AlphaWallet/Market/ViewModels/ImportMagicTokenViewControllerViewModel.swift
AlphaWallet/Redeem/ViewControllers/RedeemTokenCardQuantitySelectionViewController.swift
AlphaWallet/Redeem/ViewModels/TokenCardRowViewModel.swift
AlphaWallet/Redeem/Views/TokenCardRowView.swift
AlphaWallet/Sell/ViewControllers/EnterSellTokensCardPriceQuantityViewController.swift
AlphaWallet/Tokens/Helpers/TokenAdaptor.swift
AlphaWallet/Tokens/Types/TokenHolder.swift
AlphaWallet/Tokens/Types/TokenObject.swift
AlphaWallet/Transfer/ViewControllers/TransferTokensCardQuantitySelectionViewController.swift
AlphaWalletTests/AssetDefinition/XMLHandlerTest.swift
AlphaWalletTests/Market/ViewControllers/ImportTokenViewControllerTests.swift
AlphaWalletTests/Sell/ViewControllers/EnterSellTokensCardPriceQuantityViewControllerTests.swift
AlphaWalletTests/Transfer/ViewControllers/TransferTokensCardQuantitySelectionViewControllerTests.swift

Show only title and quantity in ERC 875 token card if there's no asset definition

---

AlphaWallet/Accounts/ViewModels/AccountsViewController.swift

For #681 
Also fixes bug when there is only 1 wallet, it should not be delete-able

Speed up list of wallets screen

---

AlphaWallet/EtherClient/CoinMarket/Types/CoinTicker.swift
AlphaWallet/EtherClient/TrustClient/Models/ArrayResponse.swift
AlphaWallet/EtherClient/TrustClient/Models/RawTransaction.swift
AlphaWallet/EtherClient/TrustClient/TrustClient.swift
AlphaWallet/InCoordinator.swift
AlphaWallet/Info.plist
AlphaWallet/Settings/Types/Config.swift
AlphaWallet/Settings/Types/Constants.swift
AlphaWallet/Tokens/Types/TokensDataStore.swift
AlphaWallet/Tokens/ViewModels/TokensViewModel.swift
AlphaWallet/Transactions/Coordinators/TransactionDataCoordinator.swift
AlphaWallet/Transfer/ViewModels/SendViewModel.swift

Replace api calls

---

AlphaWallet/Transactions/ViewControllers/TransactionsViewController.swift
AlphaWallet/Transactions/Views/TransactionViewCell.swift

Tweak transactions list layout

---

AlphaWallet/Localization/en.lproj/Localizable.strings
AlphaWallet/Localization/es.lproj/Localizable.strings
AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings

More consistent with the rest of the app.

Improve ether received notification text

---

AlphaWallet/Settings/Types/Constants.swift
AlphaWallet/Tokens/Types/TokensDataStore.swift

added key for opensea

---

AlphaWallet/Info.plist

set LSSupportsOpeningDocumentsInPlace to true

---

AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings

update the L238

---

AlphaWallet/Transfer/ViewControllers/SendViewController.swift

Show the verified button, opening etherscan, for ether card

---

AlphaWalletTests/Coordinators/ClaimOrderCoordinatorTests.swift
AlphaWalletTests/Market/OrderSigningTests.swift

Fix: test suite leaves 2 new wallets around after each run

---

AlphaWallet/EtherClient/Keystore.swift
AlphaWallet/Transfer/Coordinators/SignMessageCoordinator.swift

for #792 
Needs further testing as it does not seem consistent

Fix signing message

---

AlphaWallet/AppDelegate.swift

Fix SNS rego

---

AlphaWallet/Browser/Coordinators/BrowserCoordinator.swift

check if message is in hex

---

AlphaWallet/Transfer/Coordinators/SignMessageCoordinator.swift

checks message is convertable to utf8

---

AlphaWallet/InCoordinator.swift
AlphaWallet/RPC/Commands/web3swift-pod/GetERC721BalanceEncode.swift
AlphaWallet/Settings/Types/Constants.swift
AlphaWallet/Tokens/Coordinators/GetERC721BalanceCoordinator.swift
AlphaWallet/Tokens/Coordinators/GetIsERC721ContractCoordinator.swift
AlphaWallet/Tokens/Types/TokensDataStore.swift

This PR will:
* Detect correctly that a non-CryptoKitties ERC721 token is actually ERC721
* Fetch balance of ERC721 tokens correctly (when autodetecting or adding a custom token)

Fix: ERC721 token detection and fetch balance

---

AlphaWallet/EtherClient/OpenSea.swift

Don't block the main thread when processing results from OpenSea API, related to #752

Process OpenSea API results in the background

---

AlphaWallet.xcodeproj/project.pbxproj
AlphaWallet/EtherClient/OpenSea.swift
AlphaWallet/Extensions/UIView.swift
AlphaWallet/Localization/en.lproj/Localizable.strings
AlphaWallet/Localization/es.lproj/Localizable.strings
AlphaWallet/Localization/ja.lproj/Localizable.strings
AlphaWallet/Localization/ko.lproj/Localizable.strings
AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings
AlphaWallet/Tokens/Helpers/CryptoKitties/ConvertSVGToPNG.swift
AlphaWallet/Tokens/Helpers/TokenAdaptor.swift
AlphaWallet/Tokens/Models/WalletFilter.swift
AlphaWallet/Tokens/Types/OpenSeaNonFungible.swift
AlphaWallet/Tokens/ViewControllers/TokensViewController.swift
AlphaWallet/Tokens/ViewModels/OpenSea/OpenSeaNonFungibleTokenViewCellViewModel.swift
AlphaWallet/Tokens/ViewModels/TokensViewModel.swift
AlphaWallet/Tokens/Views/OpenSea/OpenSeaNonFungibleTokenCardRowView.swift
AlphaWallet/Tokens/Views/OpenSea/OpenSeaNonFungibleTokenViewCell.swift
AlphaWallet/Tokens/Views/WalletFilterView.swift

For #817.
Good wallets to test with:
0xbeE5348d07466997E566A4D7551a7C95470a0b05
0x0008d343091EF8BD3EFA730F6aAE5A26a285C7a2
0x7E1DCf785f0353BF657c38Ab7865C1f184EFE208
0x07b99b5a4093be2c4465d55fcaad50a3cb61447a
0xEF07a57c4CF84eEd6739Cf3FFd5EDF40237431da

Add collectibles tab in wallet

---

AlphaWallet/Info.plist
AlphaWallet/Market/UniversalLinkHandler.swift
AlphaWallet/RPC/Commands/web3wift-web3js/ClaimERC875Order.swift
AlphaWallet/Transactions/Coordinators/TransactionDataCoordinator.swift

changes from uint256 to bytes32 for r s values

---

AlphaWallet/AppCoordinator.swift
AlphaWallet/InCoordinator.swift

This PR marks private properties and func in `AppCoordinator` and `InCoordinator` as private.

Make private properties/func in AppCoordinator, InCoordinator private

---

AlphaWallet/Tokens/Types/TokensDataStore.swift

This PR marks private properties and func in TokensDataStore  as private.

Make private properties/func in TokensDataStore private

---

AlphaWallet/Extensions/String.swift
AlphaWallet/InCoordinator.swift
AlphaWallet/RPC/Commands/web3wift-web3js/ClaimERC875Order.swift
AlphaWallet/RPC/Commands/web3wift-web3js/ContractERC875Transfer.swift
AlphaWallet/Settings/Types/Constants.swift
AlphaWallet/Tokens/Coordinators/ClaimOrderCoordinator.swift
AlphaWallet/Transfer/Controllers/TransactionConfigurator.swift
AlphaWalletTests/Coordinators/ClaimOrderCoordinatorTests.swift

up to date abi with updated 875 spec

---

AlphaWallet/InCoordinator.swift
AlphaWallet/Market/Coordinators/UniversalLinkCoordinator.swift
AlphaWallet/Tokens/Types/TokensDataStore.swift
AlphaWalletTests/Factories/FakeTokensDataStore.swift

This PR does some clean up, removing unused web3swift properties across several classes

Remove unused web3(swift) property

---

AlphaWallet/AppCoordinator.swift
AlphaWallet/AssetDefinition/AssetDefinitionDiskBackingStore.swift
AlphaWallet/AssetDefinition/Coordinators/AssetDefinitionStoreCoordinator.swift
AlphaWallet/EtherClient/OpenSea.swift
AlphaWallet/Market/Coordinators/UniversalLinkCoordinator.swift
AlphaWallet/Tokens/Coordinators/TokensCoordinator.swift
AlphaWallet/Tokens/Types/TokensDataStore.swift
AlphaWallet/Tokens/ViewControllers/TokensViewController.swift
AlphaWallet/Tokens/ViewModels/OpenSea/OpenSeaNonFungibleTokenDisplayHelper.swift
AlphaWallet/Transfer/ViewControllers/RequestViewController.swift
AlphaWallet/Transfer/ViewControllers/SendViewController.swift
AlphaWallet/Transfer/ViewModels/ConfirmSignMessageViewControllerViewModel.swift

Get rid of build warnings that has accumulated since previous cleanups

Remove build warnings

---

AlphaWallet/Sell/Views/AmountTextField.swift

Fix: next button in send ether screen for address field should move focus to amount textfield

---

AlphaWallet/Transactions/Coordinators/TransactionDataCoordinator.swift

Fix crash on testnet when etherscan not support fetch transactions

---

AlphaWallet.xcodeproj/project.pbxproj
AlphaWallet/Tokens/ViewControllers/PeekOpenSeaNonFungibleTokenViewController.swift
AlphaWallet/Tokens/ViewControllers/TokensCardViewController.swift
AlphaWallet/Tokens/ViewModels/OpenSeaNonFungibleTokenCardRowViewModel.swift
AlphaWallet/Tokens/Views/OpenSea/OpenSeaNonFungibleTokenCardRowView.swift

1. Tap ERC721 token on wallet tab
2. Tap and press hard on a token ID that has an image like CryptoKitties.
More iOS-y

Token id peek pop

---

AlphaWallet/RPC/Commands/web3wift-web3js/ClaimERC875Order.swift
AlphaWallet/Settings/Types/Constants.swift

Related to: https://github.com/AlphaWallet/ERC875-token-factory/issues/9

wrong contract put in legacy addresses

---

AlphaWallet/AssetDefinition/AssetAttribute.swift
AlphaWallet/AssetDefinition/XMLHandler.swift

For #880.
This is a poor man's handling of XML namespaces: the current iOS parser library we use has no knowledge about namespaces, so depending on what we use for XML validation, we might need and probably should switch to a different parser later.
Can test this PR by tapping on a token and then AirDrop (or use Finder if simulator) to override the XML. Add, remove, change the XML namespace prefix in the entire XML and the screen should refresh automatically.
Update: this PR has not switched the repo server to `repo.attestation.id` yet because it doesn't seem to be up. But it supports both the old and new repo's XMLs.

Support namespaces in asset definitions

---

AlphaWallet/Browser/Coordinators/BrowserCoordinator.swift
AlphaWallet/Settings/Types/Constants.swift

Change dapp browser homepage to http://aw.app

---

AlphaWallet/Localization/en.lproj/privacyPolicy.html
AlphaWallet/Localization/en.lproj/termsOfService.html
AlphaWallet/Localization/zh-Hans.lproj/privacyPolicy.html
AlphaWallet/Localization/zh-Hans.lproj/termsOfService.html
AlphaWallet/Settings/Types/Constants.swift
README.md

Update urls to alphawallet.com

---

AlphaWallet/Settings/Types/Constants.swift

For #880, part of https://github.com/AlphaWallet/alpha-wallet-ios/pull/884#issuecomment-437281781

Update repo URL

---

AlphaWallet.xcodeproj/project.pbxproj
AlphaWallet/RPC/Commands/web3swift-pod/GetENSNameEncode.swift
AlphaWallet/RPC/Commands/web3swift-pod/GetERC875Balance.swift
AlphaWallet/Settings/Types/Constants.swift
AlphaWallet/Tokens/Coordinators/GetENSOwnerCoordinator.swift
AlphaWallet/Tokens/Coordinators/GetIsERC875ContractCoordinator.swift
AlphaWallet/Transfer/ViewControllers/SendViewController.swift
AlphaWallet/UI/AddressTextField.swift

For #810 
Allows you to write/paste any valid ENS name into the box and it will be translated into the corresponding address

ENS compatibility

---

AlphaWallet/Tokens/ViewControllers/NewTokenViewController.swift
AlphaWallet/Tokens/ViewControllers/TokensViewController.swift
AlphaWallet/Transfer/ViewControllers/SendViewController.swift
AlphaWallet/Transfer/ViewControllers/TransferTokensCardViaWalletAddressViewController.swift
AlphaWallet/UI/AddressTextField.swift
AlphaWallet/UI/Views/AmountTextField.swift
AlphaWallet/Wallet/ViewControllers/ImportWalletViewController.swift

Should perhaps also show the label when the user leaves the text box and switches to amount? A better idea?

With ens label

---

AlphaWallet.xcodeproj/project.pbxproj
AlphaWallet/Browser/Factory/WKWebViewConfiguration.swift
Podfile
Podfile.lock

For #877 
@hboon can make a seperate PR for upgrading versions, especially for #901

With new provider module

---

AlphaWallet/Localization/en.lproj/Localizable.strings
AlphaWallet/Localization/es.lproj/Localizable.strings
AlphaWallet/Localization/ja.lproj/Localizable.strings
AlphaWallet/Localization/ko.lproj/Localizable.strings
AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings
AlphaWallet/UI/AddressTextField.swift

For #907 
@hboon the translation service will cover localisation into every language

adds ens label to localisation

---

AlphaWallet/Localization/zh-Hans.lproj/sellInfo.html

Translted the sellinfo.html into Chinese

Translted the sellinfo.html into Chinese

---

AlphaWallet/AssetDefinition/AssetAttribute.swift
AlphaWallet/AssetDefinition/XMLHandler.swift
AlphaWallet/InCoordinator.swift
AlphaWallet/Tokens/Coordinators/CallForAssetAttributeCoordinator.swift

This PR cleans up some of the code written to make smart contract calls to retrieve asset attribute values.

Refactor handle asset attributes based on function calls

---

AlphaWallet.xcodeproj/project.pbxproj
AlphaWallet/Browser/Views/BookmarkViewCell.xib
AlphaWallet/EtherClient/TrustClient/AlphaWalletService.swift
AlphaWallet/Tokens/Types/TokensDataStore.swift
AlphaWallet/Transactions/Coordinators/AlphaWalletProviderFactory.swift
AlphaWallet/Transactions/Coordinators/TransactionDataCoordinator.swift
AlphaWallet/Wallet/Views/WordCollectionViewCell.xib

Rename a few more instances to AlphaWallet

---

AlphaWallet.xcodeproj/project.pbxproj
AlphaWallet/InCoordinator.swift
AlphaWallet/Transactions/Coordinators/TrustProvider.swift
AlphaWallet/Transfer/Controllers/TransactionConfigurator.swift
AlphaWallet/Transfer/Types/GasLimitConfiguration.swift
AlphaWallet/Transfer/Types/GasPriceConfiguration.swift
AlphaWallet/Transfer/ViewControllers/ConfigureTransactionViewController.swift
AlphaWalletTests/Transfer/Controllers/TransactionConfiguratorTests.swift
AlphaWalletTests/Transfer/Types/GasPriceConfigurationTests.swift

For #928 
This PR also makes the distinction more clear with more verbose variable names and a note at the top of each struct.

Fix gas amounts

---

AlphaWallet.xcodeproj/project.pbxproj
AlphaWallet/Localization/en.lproj/Localizable.strings
AlphaWallet/Localization/es.lproj/Localizable.strings
AlphaWallet/Localization/ja.lproj/Localizable.strings
AlphaWallet/Localization/ko.lproj/Localizable.strings
AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings
AlphaWallet/Settings/ViewControllers/SettingsViewController.swift
AlphaWallet/Settings/Views/SettingsHeaderView.swift

Group Settings screen items into labelled sections

---

AlphaWallet/EtherClient/OpenSea.swift

Fetch smaller pages from OpenSea. Seems to be choking with big pages

---

AlphaWallet/RPC/Commands/web3wift-web3js/ContractERC721Transfer.swift
AlphaWallet/Settings/Types/Constants.swift
AlphaWallet/Transfer/Controllers/TransactionConfigurator.swift

@hboon seems that 721 does not specify a transfer function... 
for #945

default to safeTransferFrom unless contract is legacy 

---

AlphaWallet/Extensions/UIImage.swift
AlphaWallet/Style/AppStyle.swift
AlphaWallet/Tokens/Models/WalletFilter.swift
AlphaWallet/Tokens/ViewControllers/TokensViewController.swift
AlphaWallet/Tokens/ViewModels/TokensViewModel.swift
AlphaWallet/Tokens/Views/WalletFilterView.swift

Add search bar to Wallet tab to filter tokens

---

AlphaWallet/Settings/Types/Constants.swift
AlphaWallet/Tokens/Coordinators/TokensCoordinator.swift

For #961
This PR automatically adds the token to the wallet tab if the token has a non-zero balance.

Auto-detect partner tokens

---

AlphaWallet.xcodeproj/project.pbxproj
AlphaWallet/Tokens/Coordinators/CallForAssetAttributeCoordinator.swift
AlphaWallet/Tokens/Coordinators/GetBalanceCoordinator.swift
AlphaWallet/Tokens/Coordinators/GetDecimalsCoordinator.swift
AlphaWallet/Tokens/Coordinators/GetENSOwnerCoordinator.swift
AlphaWallet/Tokens/Coordinators/GetERC721BalanceCoordinator.swift
AlphaWallet/Tokens/Coordinators/GetERC875BalanceCoordinator.swift
AlphaWallet/Tokens/Coordinators/GetIsERC875ContractCoordinator.swift
AlphaWallet/Tokens/Coordinators/GetNameCoordinator.swift
AlphaWallet/Tokens/Coordinators/GetSymbolCoordinator.swift
AlphaWallet/Tokens/Helpers/CallSmartContractFunction.swift

This PR extracts calling of smart contract functions into a global Swift function.

Refactor calling of smart contract functions, removing duplicate code

---

AlphaWallet/Core/ViewModels/InCoordinatorViewModel.swift
AlphaWallet/InCoordinator.swift
AlphaWallet/Settings/Types/Config.swift

This PR breaks down the ~120 lines function which creates and shows the tab bar into shorter, more self-contained functions

Refactor function in Incoordinator which create tabs and tab bar

---

AlphaWallet/Settings/Types/Constants.swift
AlphaWallet/Settings/Types/RPCServers.swift

For #973 .
Auto detecting contracts also works on Kovan now.

Fix kovan etherscan url

---

AlphaWallet/Browser/Types/DappAction.swift

Patch to work when dapps call signTransaction() with additional gasLimit dictionary

---

AlphaWallet.xcodeproj/project.pbxproj
AlphaWallet/Tokens/ViewControllers/TokenViewController.swift
AlphaWallet/Tokens/ViewModels/TokenViewControllerViewModel.swift
AlphaWallet/UI/ContainerViewWithShadow.swift

Add shadows to floating send/receive buttons

---

AlphaWallet/Localization/en.lproj/Localizable.strings
AlphaWallet/Localization/es.lproj/Localizable.strings
AlphaWallet/Localization/ja.lproj/Localizable.strings
AlphaWallet/Localization/ko.lproj/Localizable.strings
AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings

Update add bookmark menu item to say "Add to My Dapps" instead

---

AlphaWallet/Browser/Views/DappViewCell.swift

Fix: delete button for dapp in Dapp home screen is clipped while shaking

---

AlphaWallet/Browser/ViewControllers/DappsHomeViewController.swift

Confirm before deleting a dapp in Dapp home screen

---

AlphaWallet/InCoordinator.swift
AlphaWallet/Transactions/Coordinators/TransactionCoordinator.swift
AlphaWallet/Transactions/ViewControllers/TransactionsViewController.swift

Fix: crypto currency price not fetched correctly after switching network or wallet

---

AlphaWallet/Accounts/Coordinators/AccountsCoordinator.swift
AlphaWallet/Accounts/ViewModels/AccountViewModel.swift
AlphaWallet/Accounts/ViewModels/AccountsViewController.swift
AlphaWallet/AppCoordinator.swift
AlphaWallet/Localization/en.lproj/Localizable.strings
AlphaWallet/Localization/es.lproj/Localizable.strings
AlphaWallet/Localization/ja.lproj/Localizable.strings
AlphaWallet/Localization/ko.lproj/Localizable.strings
AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings
AlphaWallet/Market/Coordinators/UniversalLinkCoordinator.swift
AlphaWallet/Market/ViewModels/ImportMagicTokenViewControllerViewModel.swift
AlphaWallet/PushNotificationsCoordinator.swift
AlphaWallet/Sell/ViewModels/EnterSellTokensCardPriceQuantityViewControllerViewModel.swift
AlphaWallet/Sell/ViewModels/GenerateSellMagicLinkViewControllerViewModel.swift
AlphaWallet/Sell/ViewModels/SetSellTokensCardExpiryDateViewControllerViewModel.swift
AlphaWallet/Settings/Types/RPCServers.swift
AlphaWallet/Tokens/ViewControllers/TokensCardViewController.swift
AlphaWallet/Tokens/ViewControllers/TokensViewController.swift
AlphaWallet/Tokens/ViewModels/TokenViewCellViewModel.swift
AlphaWallet/Tokens/ViewModels/TokensCardViewControllerHeaderViewModel.swift
AlphaWallet/Transactions/Coordinators/TokensCardCoordinator.swift
AlphaWallet/Transactions/Coordinators/TransactionDataCoordinator.swift
AlphaWalletTests/Market/ViewControllers/ImportTokenViewControllerTests.swift
AlphaWalletTests/Sell/ViewControllers/EnterSellTokensCardPriceQuantityViewControllerTests.swift

Replace more references of eth/ETH with xDai when on xDai

---

AlphaWallet/Browser/Coordinators/DappBrowserCoordinator.swift
AlphaWallet/Browser/Storage/BookmarksStore.swift
AlphaWallet/Browser/Types/Bookmark.swift
AlphaWallet/Browser/ViewControllers/MyDappsViewController.swift
AlphaWallet/Core/Initializers/MigrationInitializer.swift

Be able to re-order dapps in My Dapps screen (not in Dapps home screen)

---

AlphaWallet/Market/ViewModels/ImportMagicTokenViewControllerViewModel.swift
AlphaWallet/Redeem/ViewModels/RedeemTokenCardQuantitySelectionViewModel.swift
AlphaWallet/Redeem/ViewModels/RedeemTokenCardViewModel.swift
AlphaWallet/Sell/ViewModels/EnterSellTokensCardPriceQuantityViewControllerViewModel.swift
AlphaWallet/Sell/ViewModels/SellTokensCardViewModel.swift
AlphaWallet/Sell/ViewModels/SetSellTokensCardExpiryDateViewControllerViewModel.swift
AlphaWallet/Style/AppStyle.swift
AlphaWallet/Tokens/ViewModels/NewTokenViewModel.swift
AlphaWallet/Tokens/ViewModels/TokenViewControllerViewModel.swift
AlphaWallet/Tokens/ViewModels/TokensCardViewModel.swift
AlphaWallet/Transfer/ViewModels/ChooseTokenCardTransferModeViewControllerViewModel.swift
AlphaWallet/Transfer/ViewModels/SendViewModel.swift
AlphaWallet/Transfer/ViewModels/SetTransferTokensCardExpiryDateViewControllerViewModel.swift
AlphaWallet/Transfer/ViewModels/TransferTokensCardQuantitySelectionViewModel.swift
AlphaWallet/Transfer/ViewModels/TransferTokensCardViaWalletAddressViewControllerViewModel.swift
AlphaWallet/Transfer/ViewModels/TransferTokensCardViewModel.swift
AlphaWallet/Wallet/ViewModels/ImportWalletViewModel.swift

Tweak green action buttons background color and remove shadows

---

AlphaWallet/Tokens/ViewControllers/TokensCardViewController.swift

Fix: green action buttons are not hidden correctly

---

AlphaWallet/Settings/Types/Config.swift

This is the same node that has been confirmed to work with MyEtherWallet see [here](https://github.com/MyEtherWallet/MyEtherWallet/blob/57690d95b88053fda8f507f2c72083d2ab5883ad/src/networks/nodes/etc-gastracker.js#L5).
Fixes issues connecting to ETC Dapps (Issue [960](https://github.com/AlphaWallet/alpha-wallet-ios/issues/960))

Add working ETC Node

---

AlphaWallet/Market/ViewModels/ImportMagicTokenCardRowViewModel.swift
AlphaWallet/Market/ViewModels/ImportMagicTokenViewControllerViewModel.swift
AlphaWallet/Tokens/Helpers/TokenAdaptor.swift
AlphaWallet/Tokens/Types/Token.swift
AlphaWallet/Tokens/Types/TokenHolder.swift
AlphaWallet/UI/ViewModels/TokenCardRowViewModel.swift
AlphaWallet/UI/ViewModels/TokenCardRowViewModelProtocol.swift
AlphaWallet/UI/Views/TokenCardRowView.swift

Change token list fields layout for spawnable contract

---

AlphaWallet/AssetDefinition/AssetAttribute.swift
AlphaWallet/Market/ViewModels/ImportMagicTokenViewControllerViewModel.swift
AlphaWallet/UI/ViewModels/TokenCardRowViewModel.swift

Fix: import UI display of fields for spawnable contract so it looks the same as Wallet tab's token list view

---

AlphaWallet/Redeem/ViewModels/RedeemTokenCardViewModel.swift
AlphaWallet/Sell/ViewModels/SellTokensCardViewModel.swift
AlphaWallet/Transfer/ViewModels/TransferTokensCardViewModel.swift

Auto-select token if there's only 1 bundle when redeeming, selling or transferring

---

AlphaWallet/Localization/en.lproj/Localizable.strings
AlphaWallet/Localization/es.lproj/Localizable.strings
AlphaWallet/Localization/ja.lproj/Localizable.strings
AlphaWallet/Localization/ko.lproj/Localizable.strings
AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings
AlphaWallet/Market/Coordinators/UniversalLinkCoordinator.swift

add string for not enough xdai, replacing eth string

---

AlphaWallet/Tokens/ViewControllers/TokenViewController.swift

use contract address instead of user address for erc contracts

---

AlphaWallet/Transfer/Controllers/TransactionConfigurator.swift
AlphaWallet/Transfer/Types/GasPriceConfiguration.swift

for #1051
@hboon perhaps we could add a restriction to prevent the user from changing the gas price

ensure 1 gwei is set for all xdai transactions

---

AlphaWallet/Settings/Types/Constants.swift

Auto-detect more partner xDai tokens for ETHDever

---

AlphaWallet/Browser/ViewModel/Dapps.swift

Add nexo.io to Discover

---

AlphaWallet/Browser/Coordinators/DappBrowserCoordinator.swift
AlphaWallet/Localization/en.lproj/Localizable.strings
AlphaWallet/Localization/es.lproj/Localizable.strings
AlphaWallet/Localization/ja.lproj/Localizable.strings
AlphaWallet/Localization/ko.lproj/Localizable.strings
AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings
AlphaWallet/UI/NavigationController.swift

Restore scan QR code for URL functionality in Dapp browser

---

AlphaWallet/Market/Coordinators/UniversalLinkCoordinator.swift
AlphaWallet/Market/MarketQueueHandler.swift
AlphaWallet/Market/UniversalLinkHandler.swift
AlphaWallet/Settings/Types/Constants.swift
AlphaWallet/Tokens/Coordinators/TokensCoordinator.swift

add route and handling for currency links

---

AlphaWallet/Localization/en.lproj/Localizable.strings
AlphaWallet/Localization/es.lproj/Localizable.strings
AlphaWallet/Localization/ja.lproj/Localizable.strings
AlphaWallet/Localization/ko.lproj/Localizable.strings
AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings
AlphaWallet/Market/Coordinators/UniversalLinkCoordinator.swift

For #1091
@hboon slightly hacky but requires a kind of TBML implementation to get it right exactly with the UI

display amount of currency you can import

---

AlphaWallet/Browser/Coordinators/ScanQRCodeCoordinator.swift
AlphaWallet/Localization/en.lproj/Localizable.strings
AlphaWallet/Localization/es.lproj/Localizable.strings
AlphaWallet/Localization/ja.lproj/Localizable.strings
AlphaWallet/Localization/ko.lproj/Localizable.strings
AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings
AlphaWallet/Tokens/ViewControllers/NewTokenViewController.swift
AlphaWallet/Transfer/ViewControllers/SendViewController.swift
AlphaWallet/Transfer/ViewControllers/TransferTokensCardViaWalletAddressViewController.swift
AlphaWallet/Wallet/ViewControllers/ImportWalletViewController.swift
Podfile
Podfile.lock

Replace QR code scanner's switch front/back camera button with photo picker button so we can pick photos with QR codes in them

---

AlphaWallet/Localization/en.lproj/Localizable.strings
AlphaWallet/Localization/es.lproj/Localizable.strings
AlphaWallet/Localization/ja.lproj/Localizable.strings
AlphaWallet/Localization/ko.lproj/Localizable.strings
AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings
AlphaWallet/Market/Coordinators/UniversalLinkCoordinator.swift
AlphaWallet/Settings/Types/RPCServers.swift

require paymaster for certain currency links 

---

AlphaWallet/Market/Coordinators/UniversalLinkCoordinator.swift
AlphaWallet/Settings/Types/Config.swift

replace with blockscout on poa sokol and etc

---

AlphaWallet/AlphaWallet.entitlements
AlphaWallet/AppCoordinator.swift
AlphaWallet/Localization/en.lproj/Localizable.strings
AlphaWallet/Localization/es.lproj/Localizable.strings
AlphaWallet/Localization/ja.lproj/Localizable.strings
AlphaWallet/Localization/ko.lproj/Localizable.strings
AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings
AlphaWallet/Market/Coordinators/UniversalLinkCoordinator.swift
AlphaWallet/Market/Coordinators/UniversalLinkInPasteboardCoordinator.swift
AlphaWallet/Market/UniversalLinkHandler.swift
AlphaWallet/Settings/Types/Config.swift
AlphaWallet/Settings/Types/Constants.swift
AlphaWallet/Settings/Types/RPCServers.swift
AlphaWalletTests/Market/UniversalLinkHandlerTests.swift

For #1050
@hboon can merge once we have the server up and running with different subdomains

filter and handle magic links by DNS specified network

---

AlphaWallet/Foundation/QRURLParser.swift
AlphaWallet/Transfer/ViewControllers/SendViewController.swift

For #1113 
Note: Ignores the chainID for now
Edit: chain ids are checked

support eip681 qr codes

---

AlphaWallet/Settings/Types/Config.swift

Sync with https://github.com/AlphaWallet/alpha-wallet-android/pull/614

Fix: update RPC node used for Ethereum Classic

---

AlphaWallet/Market/Coordinators/UniversalLinkCoordinator.swift
AlphaWallet/Market/ViewModels/ImportMagicTokenViewControllerViewModel.swift
AlphaWallet/Models/EthereumUnit.swift

Fix: native currency value is displayed incorrectly in MagicLink import UI

---

AlphaWallet/Market/Coordinators/UniversalLinkCoordinator.swift

correct label on xdai import page

---

AlphaWallet/Settings/Types/Constants.swift

Update link to community forums

---

AlphaWallet/Market/Coordinators/UniversalLinkCoordinator.swift
AlphaWallet/Market/UniversalLinkHandler.swift
AlphaWallet/Settings/Types/Constants.swift

checks if the currency link is claimed and refactor

---

AlphaWallet/Foundation/QRURLParser.swift
AlphaWalletTests/Foundation/QRURLParserTests.swift

Fix: extraction of chain ID from EIP681 payment links

---

AlphaWallet/Browser/ViewModel/Dapps.swift

Add Zerion to Discover Dapps

---

AlphaWallet/EtherClient/EtherServiceRequest.swift
AlphaWallet/Settings/Types/Config.swift
AlphaWallet/Vendors/Web3Swift/Web3Swift.swift
AlphaWallet/Vendors/Web3Swift/html/index.html

WIP until error fixed or we move node provider 
For #731

with new api route for infura

---

AlphaWallet/EtherClient/OpenSea.swift
AlphaWallet/Settings/Types/Constants.swift

add support for ropsten and rinkeby opensea api calls

---

AlphaWallet/Tokens/Coordinators/TokensCoordinator.swift
AlphaWalletTests/Coordinators/ClaimOrderCoordinatorTests.swift
AlphaWalletTests/Settings/ConfigTests.swift

check token type before getting the balance for partner contracts

---

AlphaWallet/Browser/Views/NativeCryptoCurrencyBalanceView.swift

Tweak how native crypto currency balance is displayed in dapp browser

---

AlphaWallet/AppCoordinator.swift
AlphaWallet/Browser/Coordinators/DappBrowserCoordinator.swift
AlphaWallet/InCoordinator.swift

If user enters MagicLink into dapp browser, auto launch import screen

---

AlphaWallet/InCoordinator.swift

Was ignoring which networks were enabled/disabled

Make Transactions tab only display transactions from enabled networks

---

AlphaWallet/Browser/ViewModel/Dapps.swift

Add entry to Discover Dapps

---

AlphaWallet/Browser/ViewModel/Dapps.swift

remove swap from url

---

AlphaWallet/EtherClient/OpenSea.swift
AlphaWallet/Settings/Coordinators/ServersCoordinator.swift
AlphaWallet/Settings/Types/ConfigExplorer.swift
AlphaWallet/Settings/Types/Constants.swift
AlphaWallet/Settings/Types/RPCServers.swift
AlphaWallet/Tokens/Coordinators/SingleChainTokenCoordinator.swift
AlphaWallet/Tokens/Types/TokenCollection.swift
AlphaWallet/Tokens/Types/TokensDataStore.swift
AlphaWallet/Transactions/Coordinators/SingleChainTransactionDataCoordinator.swift
AlphaWallet/UI/Views/AmountTextField.swift

with new goerli testnet and infura spec

---

AlphaWallet/Settings/Types/Constants.swift

with new url for paymaster

---

AlphaWallet/Transfer/Coordinators/SendCoordinator.swift

Fix: don't default to 0 ether in Send screen. Bad UX and unnecessary

---

AlphaWallet/Browser/Factory/WKWebViewConfiguration.swift

This may have been causing issues on multiple dapp sites.

sets the ethereum window object

---

AlphaWallet/Browser/Factory/WKWebViewConfiguration.swift

Should solve issues like #987 but doesn't seem to.

Add enable function to dapp browser

---

Podfile

has new pod for alphawallet provider

---

AlphaWallet/Browser/ViewModel/Dapps.swift

Sync with https://github.com/AlphaWallet/alpha-wallet-android/pull/705/

Add Humanity to Dapp listing

---

AlphaWallet/Browser/ViewModel/Dapps.swift

Sync with https://github.com/AlphaWallet/alpha-wallet-android/pull/704

Fix: typo in dapp listing

---

AlphaWallet.xcodeproj/project.pbxproj
AlphaWallet/Localization/en.lproj/Localizable.strings
AlphaWallet/Localization/es.lproj/Localizable.strings
AlphaWallet/Localization/ja.lproj/Localizable.strings
AlphaWallet/Localization/ko.lproj/Localizable.strings
AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings
AlphaWallet/Settings/Coordinators/ClearDappBrowserCacheCoordinator.swift
AlphaWallet/Settings/Coordinators/SettingsCoordinator.swift
AlphaWallet/Settings/Types/SettingsAction.swift
AlphaWallet/Settings/ViewControllers/SettingsViewController.swift
AlphaWallet/Tokens/Views/WKWebViewExtension.swift

Add clear dapp browser cache action to Settings tab

---

AlphaWallet/Core/Types/AlphaWalletAddress.swift
AlphaWalletTests/Market/UniversalLinkHandlerTests.swift

Fix parsing of universal link which is broken by #1245 
This PR includes fixing an existing test case to catch it.

Fix: parsing of universal link broken

---

AlphaWallet/Tokens/ViewControllers/TokenInstanceViewController.swift
AlphaWallet/Tokens/ViewControllers/TokensCardViewController.swift

Resolves #1067 
like this (duplicates in the screenshots are for development):

Make action buttons in Token instance view controller float over the token cards

---

AlphaWallet/Browser/ViewModel/Dapps.swift

correct airswap URL

---

AlphaWallet/Accounts/ViewModels/AccountsViewController.swift
AlphaWallet/Settings/ViewControllers/EnabledServersViewController.swift
AlphaWallet/Settings/ViewControllers/LocalesViewController.swift
AlphaWallet/Settings/ViewControllers/ServersViewController.swift
AlphaWallet/Tokens/ViewControllers/TokenInstanceViewController.swift
AlphaWallet/Tokens/ViewControllers/TokensCardViewController.swift

No functional change. Remove unnecessary code.

Remove unnecessary code that says tableview has a section of 1. It's the default

---

AlphaWallet/Core/Formatters/CurrencyFormatter.swift

For #1268
In future we should convert the prices into the localised currency

display price in USD only, do not localise the label 

---

AlphaWallet/Tokens/Coordinators/GetContractInteractions.swift

Noticed this while working on #1283 and comparing `getErc20Interactions()` and `getContractList()`.
This PR makes `getErc20Interactions()` process the JSON result in a background queue like `getContractList()`. Before this PR, `getErc20Interactions()` might cause a slowdown in the UI depending on how many transactions the web API returns as well as how many networks are enabled in the app. (this call is made once per enabled network).
@James-Sangalli this might be 1 of the cause for slowdown in Victor's phone, but I don't think it's the only one. Can you try it again after merging?

Don't block UI while fetching ERC20 transactions

---

AlphaWallet/Transfer/Controllers/TransactionConfigurator.swift

Fix: ERC20 transfer transaction is not formed correctly

---

AlphaWallet/Transactions/Coordinators/SingleChainTransactionDataCoordinator.swift
AlphaWallet/Transactions/Storage/TransactionsStorage.swift

don't re add contracts from erc20Interactions if they are not supposed to

---

AlphaWallet/Settings/Types/Constants.swift

Fixes #996 
@hboon they support the old transfer function, saw it in the decompiler

add hyperdragons to legacy 721 list for transferring

---

AlphaWallet/Browser/Factory/WKWebViewConfiguration.swift

adds space because it is sometimes chopped by sites

---

AlphaWallet/Settings/Coordinators/SettingsCoordinator.swift
AlphaWallet/Settings/ViewControllers/EnabledServersViewController.swift

Fix: Don't allow users to disable all networks

---

README.md

Sync with https://github.com/AlphaWallet/alpha-wallet-android/pull/773

Tweak grammar and link URLs

---

AlphaWallet/Tokens/ViewModels/TokensViewModel.swift

Speed up search in Wallets screen (so it's usable)

---

AlphaWallet/Settings/ViewControllers/EnabledServersViewController.swift

Fix: strange scrolling effect after scrolling and tapping on any item in Enable Servers screen

---

AlphaWallet/TokenScriptClient/Models/XMLHandler.swift

[Refactor] Rename to be more intention revealing

---

AlphaWallet/Browser/ViewControllers/BrowserHistoryViewController.swift
AlphaWallet/Browser/ViewModel/HistoriesViewModel.swift
AlphaWallet/Tokens/ViewControllers/TokensViewController.swift
AlphaWallet/Tokens/ViewModels/TokensViewModel.swift
AlphaWallet/Welcome/ViewControllers/OnboardingCollectionViewController.swift

Remove unnecessary code that says tableview/collection has a section count of 1. It's the default

---

AlphaWallet/Core/Core.swift
AlphaWallet/InCoordinator.swift
AlphaWallet/Tokens/Coordinators/SingleChainTokenCoordinator.swift

[Refactor] Extract function which checks if we are running automated tests

---

AlphaWallet/Tokens/ViewControllers/TokensViewController.swift
AlphaWallet/Tokens/ViewModels/TokensViewModel.swift

Restore swipe to delete tokens in Wallet tab, fixing crash when deleting

---

AlphaWallet/Browser/Factory/WKWebViewConfiguration.swift
AlphaWallet/Browser/ViewControllers/BrowserViewController.swift
AlphaWallet/Browser/ViewControllers/DiscoverDappsViewController.swift
AlphaWallet/Browser/ViewControllers/MyDappsViewController.swift
AlphaWallet/Export/Coordinators/BackupCoordinator.swift
AlphaWallet/Export/Coordinators/PromptBackupCoordinator.swift
AlphaWallet/KeyManagement/EtherKeystore.swift
AlphaWallet/KeyManagement/LegacyFileBasedKeystore.swift
AlphaWallet/KeyManagement/SecureEnclave.swift
AlphaWallet/Market/Coordinators/UniversalLinkCoordinator.swift
AlphaWallet/Market/MarketQueueHandler.swift
AlphaWallet/Market/ViewModels/ImportMagicTokenViewControllerViewModel.swift
AlphaWallet/Settings/Coordinators/ClearDappBrowserCacheCoordinator.swift
AlphaWallet/Settings/ViewControllers/SettingsViewController.swift
AlphaWallet/TokenScriptClient/Coordinators/AssetDefinitionStoreCoordinator.swift
AlphaWallet/TokenScriptClient/Models/FunctionOrigin.swift
AlphaWallet/TokenScriptClient/Models/TokenScriptSignatureVerifier.swift
AlphaWallet/TokenScriptClient/Models/XMLHandler.swift
AlphaWallet/Tokens/Coordinators/GetENSOwnerCoordinator.swift
AlphaWallet/Tokens/ViewControllers/TokenViewController.swift
AlphaWallet/Tokens/ViewControllers/VerifiableStatusViewController.swift
AlphaWallet/Wallet/Coordinators/BackupSeedPhraseCoordinator.swift
AlphaWallet/Wallet/Coordinators/EnterPasswordCoordinator.swift
AlphaWallet/Wallet/Coordinators/WalletCoordinator.swift
AlphaWallet/Wallet/ViewControllers/VerifySeedPhraseViewController.swift
AlphaWalletTests/Coordinators/ClaimOrderCoordinatorTests.swift
AlphaWalletTests/EtherClient/EtherKeystoreTests.swift
AlphaWalletTests/Settings/Coordinators/SettingsCoordinatorTests.swift

Not expecting functional changes.

Fix compilation warnings

---

AlphaWallet/Settings/Types/Constants.swift

Fix outdated feedback URL

---

AlphaWallet/Market/UniversalLinkHandler.swift

Fix: crash when MagicLink is truncated

---

AlphaWallet/Tokens/ViewControllers/TokenViewController.swift

Fix: Native crypto and ERC20 token screen with send/receive button doesn't scroll correctly in shorter screens

---

AlphaWallet/EtherClient/TransactionSigning.swift
AlphaWallet/KeyManagement/EtherKeystore.swift
AlphaWallet/KeyManagement/EthereumSigner.swift
AlphaWallet/Market/UniversalLinkHandler.swift

Closes #1369 
Simple change. But have to be careful during review @James-Sangalli

Extract recid/v + 27

---

AlphaWallet/Transfer/ViewControllers/ConfirmSignMessageViewController.swift

Fixes #1142 
Before PR | After PR 1 | After PR 2
-|-|-
This is useful for testing typed messages: https://danfinlay.github.io/js-eth-personal-sign-examples/
Should probably have another PR for fixing signing compatibility against the URL above. But have to be careful to keep compatible with Android version.

Fix: make confirm prompt for signing, handle long messages

---

AlphaWallet/Browser/Coordinators/DappBrowserCoordinator.swift

Before the PR (look for "0 ETH"):

Hide current networks native balance in dapp browser when prompt to sign screen is shown

---

AlphaWallet/Browser/Coordinators/DappBrowserCoordinator.swift

Fixes broken git merge in #1381

Fix: Hide current networks native balance in dapp browser when switching networking screen is shown

---

AlphaWallet/Settings/ViewControllers/SettingsViewController.swift

Show current wallet address under My Wallet Address, and not Change Wallet to reduce confusion for user trying to find their Ethereum address

---

AlphaWallet/Style/AppStyle.swift
AlphaWallet/UI/ButtonsBar.swift

Improve disabled action buttons background color

---

AlphaWallet/Localization/en.lproj/Localizable.strings
AlphaWallet/Localization/es.lproj/Localizable.strings
AlphaWallet/Localization/ja.lproj/Localizable.strings
AlphaWallet/Localization/ko.lproj/Localizable.strings
AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings
AlphaWallet/UI/WhereIsWalletAddressFoundOverlayView.swift

After creating a new wallet, make pop up remind user to back up their wallet instead of informing them where to find their wallet address

---

AlphaWallet/Settings/ViewControllers/SettingsViewController.swift

In Settings screen, scroll the back up alert together with the table rather than be a sticky header

---

AlphaWallet/Localization/en.lproj/Localizable.strings
AlphaWallet/Localization/es.lproj/Localizable.strings
AlphaWallet/Localization/ja.lproj/Localizable.strings
AlphaWallet/Localization/ko.lproj/Localizable.strings
AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings
AlphaWallet/Wallet/ViewControllers/ShowSeedPhraseViewController.swift
AlphaWallet/Wallet/ViewModels/ShowSeedPhraseViewModel.swift

Tweak text and button title in show seed phrase screen

---

AlphaWallet/Tokens/Coordinators/SingleChainTokenCoordinator.swift

Fixes https://github.com/AlphaWallet/TokenScript/issues/223
@JamesSmartCell might be relevant for you too.

prevent caching of action cards

---

AlphaWallet/Wallet/ViewModels/SeedPhraseCollectionViewModel.swift

Show sequence number for seed phrase during back up

---

AlphaWallet/InCoordinator.swift
AlphaWallet/Tokens/Types/TokenCollection.swift
AlphaWallet/Tokens/Types/TokensDataStore.swift
AlphaWallet/Tokens/ViewControllers/TokensViewController.swift
AlphaWallet/Tokens/ViewModels/TokensViewModel.swift
AlphaWalletTests/Coordinators/TokensCoordinatorTests.swift
AlphaWalletTests/Settings/ConfigTests.swift

Just like we can now with "ERC 20", "ERC 721" and "ERC 875" before this PR

Add `tokenscript` as a special search keyword in the Wallet tab search bar to filter for tokens with TokenScript file

---

AlphaWallet/Transfer/ViewControllers/RequestViewController.swift

Fix: QRCode chopped off in receive screen in short screens

---

AlphaWallet/Redeem/ViewControllers/RedeemTokenCardQuantitySelectionViewController.swift
AlphaWallet/Redeem/ViewControllers/TokenCardRedemptionViewController.swift
AlphaWallet/Sell/ViewControllers/EnterSellTokensCardPriceQuantityViewController.swift
AlphaWallet/Sell/ViewControllers/SetSellTokensCardExpiryDateViewController.swift
AlphaWallet/Tokens/Coordinators/SingleChainTokenCoordinator.swift
AlphaWallet/Tokens/Helpers/TokenAdaptor.swift
AlphaWallet/Tokens/Types/OpenSeaNonFungibleTokenHandling.swift
AlphaWallet/Tokens/ViewControllers/TokenInstanceActionViewController.swift
AlphaWallet/Tokens/ViewControllers/TokenInstanceViewController.swift
AlphaWallet/Tokens/ViewControllers/TokensCardViewController.swift
AlphaWallet/Transfer/ViewControllers/ChooseTokenCardTransferModeViewController.swift
AlphaWallet/Transfer/ViewControllers/SetTransferTokensCardExpiryDateViewController.swift
AlphaWallet/Transfer/ViewControllers/TransferTokensCardQuantitySelectionViewController.swift
AlphaWallet/Transfer/ViewControllers/TransferTokensCardViaWalletAddressViewController.swift

Fix: TokenScript files should override behavior of ERC721 tokens fetched from OpenSea too

---

AlphaWallet/AlphaWallet.entitlements
AlphaWallet/Browser/ViewModel/Dapps.swift
AlphaWallet/EtherClient/OpenSea.swift
AlphaWallet/Localization/en.lproj/Localizable.strings
AlphaWallet/Settings/Coordinators/ServersCoordinator.swift
AlphaWallet/Settings/Types/ConfigExplorer.swift
AlphaWallet/Settings/Types/Constants.swift
AlphaWallet/Settings/Types/RPCServers.swift
AlphaWallet/Tokens/Coordinators/SingleChainTokenCoordinator.swift
AlphaWallet/Tokens/Types/TokenCollection.swift
AlphaWallet/Tokens/Types/TokensDataStore.swift
AlphaWallet/Tokens/ViewControllers/TokenInstanceActionViewController.swift
AlphaWallet/Transactions/Coordinators/SingleChainTransactionDataCoordinator.swift
AlphaWallet/UI/Views/AmountTextField.swift

Website: https://artis.eco
Block explorers: https://explorer.sigma1.artis.network/ http://explorer.tau1.artis.network/
slip0044: [246529](https://github.com/satoshilabs/slips/pull/495) (sigma1) & [246785](https://github.com/satoshilabs/slips/pull/495) (tau1)
chainIds: [246529](https://github.com/lab10-coop/sigma1/blob/1881ea80b475c10765d7a763ca6afd93df005b52/spec.json#L30) (sigma1) & [246785](https://github.com/lab10-coop/tau1/blob/master/spec.json#L30) (tau1)
This code ist untested..
RPCServers.swift may be incomplete: priceID, blockChainName, was not sure how to set these.
( Android: https://github.com/AlphaWallet/alpha-wallet-android/pull/803 )

add ARTIS network https://artis.eco (untested)

---

AlphaWallet/Settings/Types/Constants.swift

make only xDai and Eth default

---

AlphaWallet/Transfer/ViewControllers/TransferTokensCardViaWalletAddressViewController.swift
AlphaWallet/Transfer/ViewModels/TransferTokensCardViaWalletAddressViewControllerViewModel.swift

Fix: Address label of address (like in transfer) disappears after pasting

---

AlphaWallet/Localization/en.lproj/Localizable.strings
AlphaWallet/Localization/es.lproj/Localizable.strings
AlphaWallet/Localization/ja.lproj/Localizable.strings
AlphaWallet/Localization/ko.lproj/Localizable.strings
AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings
AlphaWallet/Settings/ViewControllers/ServersViewController.swift
AlphaWallet/Settings/ViewModels/ServersViewModel.swift

Add an instruction at DApp Browser network selection

---

AlphaWallet/Browser/Coordinators/DappBrowserCoordinator.swift

Allow changing network in dapp browser even if no page has been loaded yet

---

AlphaWallet/TokenScriptClient/Models/TokenScriptSignatureVerifier.swift

Fixes #1464 
The device probably did not have connectivity (or the API might be down).
This combined with #1476 (to be fixed separately) which causes invalid TokenScript signatures to not be displayed to the user for fungible tokens (whereas NFTs show it correctly), gives off the impression that the TokenScript file has vanished.

Fix: should not consider failure to connect to signature verification API as signature failed validation

---

AlphaWallet/Browser/ViewModel/Dapps.swift

Add MoveCastle

---

AlphaWallet/EtherClient/TrustClient/AlphaWalletService.swift

Because additional cases needs to be added and switch-cased with for the other project for different behavior

Add switch with explicit cases to make handling diffs/merging easier

---

AlphaWallet/TokenScriptClient/Models/FunctionOrigin.swift
AlphaWallet/TokenScriptClient/Models/Origin.swift
AlphaWallet/TokenScriptClient/Models/TokenScript.swift

sets a default bitmask for 2019/10 TokenScripts

---

AlphaWallet/Tokens/Helpers/TokenAdaptor.swift

gets the XML attributes as well as OpenSea attributes 

---

AlphaWallet/Settings/Types/Constants.swift

Update URL in share screen

---

AlphaWallet/Transfer/Controllers/TransactionConfigurator.swift

Fixes #1518 & https://github.com/AlphaWallet/alpha-wallet-ios/issues/1438

fix encoding of params for NFT encodings

---

AlphaWallet/Info.plist

Update NSCameraUsageDescription in Info.plist because App review rejected us (maybe not clear enough?)

---

AlphaWallet/KeyManagement/EtherKeystore.swift

Don't allow users to watch an Ethereum address if it is already in the wallet list (watched, keystore, seed, the entire list)

---

AlphaWallet/Extensions/UIAlertController.swift
AlphaWallet/Tokens/ViewControllers/TokenInstanceActionViewController.swift

Fix: tapping TokenScript action confirmation button on iPad crashes

---

AlphaWallet/Market/Coordinators/UniversalLinkCoordinator.swift
AlphaWallet/Settings/Types/Constants.swift

Needed for spawnable UEFA tickets which will depend on the paymaster only

add support for spawnable paymaster queries

---

AlphaWallet/Sell/ViewModels/GenerateTransferMagicLinkViewControllerViewModel.swift

Fix: text colors in dialog to confirm generate MagicLinks

---

AlphaWallet/Localization/en.lproj/Localizable.strings
AlphaWallet/Localization/es.lproj/Localizable.strings
AlphaWallet/Localization/ja.lproj/Localizable.strings
AlphaWallet/Localization/ko.lproj/Localizable.strings
AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings
AlphaWallet/UI/WhereIsWalletAddressFoundOverlayView.swift

Add missing localization strings: Continue button

---

AlphaWallet/Settings/Types/Constants.swift
AlphaWallet/Tokens/Coordinators/SingleChainTokenCoordinator.swift
AlphaWallet/Tokens/Coordinators/TokensCoordinator.swift

Checks for the UEFA token upon startup and switching to a wallet; and only adds the token to the Wallet tab if balance > 0

Auto detect UEFA token if it has a balance

---

AlphaWallet/InCoordinator.swift

So have to manually copy and paste with Xcode unfortunately.

Improve debugging log printed for database and document path, so it's clickable in AppCode

---

AlphaWallet/Tokens/ViewControllers/TokensCardViewController.swift
AlphaWallet/Tokens/Views/TokenInstanceWebView.swift

Still slower than desirable, but much better.
First time will still be slow unfortunately for new users.

Improve performance of TokenScript view rendering by caching height values across app launches

---

AlphaWallet/Browser/ViewModel/Dapps.swift

added 1inch.exchange

---

AlphaWallet/Redeem/Helpers/CreateRedeem.swift

Consistent with https://github.com/AlphaWallet/alpha-wallet-android/pull/1039

upgrade QR code format for 721 tickets

---

AlphaWallet/Tokens/Views/TokenViewControllerHeaderView.swift
Podfile
Podfile.lock

Builds with Xcode 11 too, but needs code changes like modal presentation style and fixing Realm crashes to work correctly.

Update codebase so it's Swift 4 and thus can be used with Xcode 10.2 and 10.3

---

AlphaWallet/Transfer/ViewControllers/TransferTokensCardViaWalletAddressViewController.swift

Fix: while transferring a token with a long TokenScript view (especially on a short device), the textbox is hidden by the keyboard

---

AlphaWallet/Style/AppStyle.swift

Fix: tabbar tint color

---

AlphaWallet/Localization/en.lproj/Localizable.strings
AlphaWallet/Localization/es.lproj/Localizable.strings
AlphaWallet/Localization/ja.lproj/Localizable.strings
AlphaWallet/Localization/ko.lproj/Localizable.strings
AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings
AlphaWallet/Settings/ViewControllers/SettingsViewController.swift
AlphaWallet/TokenScriptClient/Models/TokenScript.swift

Add TokenScript branding in Settings screen

---

AlphaWallet/AppCoordinator.swift
AlphaWallet/InCoordinator.swift
AlphaWallet/Settings/Coordinators/ConsoleCoordinator.swift
AlphaWallet/TokenScriptClient/Models/AssetDefinitionBackingStore.swift
AlphaWallet/TokenScriptClient/Models/AssetDefinitionDiskBackingStore.swift
AlphaWallet/TokenScriptClient/Models/AssetDefinitionDiskBackingStoreWithOverrides.swift
AlphaWallet/TokenScriptClient/Models/AssetDefinitionInMemoryBackingStore.swift
AlphaWallet/TokenScriptClient/Models/AssetDefinitionStore.swift

For TokenScript debugging. PR adds "[Overrides]":

Indicate in Console screen whether TokenScript conflict is in the repo or overrides

---

AlphaWallet/Tokens/ViewControllers/TokenViewController.swift

Fix: make TokenScript indicator show up for ERC20 token in TokenScript

---

AlphaWallet/Redeem/ViewControllers/TokenCardRedemptionViewController.swift

Tweak redeem screen margin and place content in scrollview to support shorter screens better

---

AlphaWallet.xcodeproj/project.pbxproj
AlphaWallet/Accounts/ViewModels/AccountViewModel.swift
AlphaWallet/Accounts/ViewModels/AccountsViewController.swift
AlphaWallet/Accounts/Views/AccountViewCell.swift
AlphaWallet/Core/Types/AlphaWalletAddress.swift
AlphaWallet/RPC/Commands/web3swift-pod/ENSReverseLookupEncode.swift
AlphaWallet/Tokens/Coordinators/ENSReverseLookupCoordinator.swift

Add support for ENS reverse lookup and show ENS name beside addresses in wallet list screen

---

AlphaWallet/TokenScriptClient/Models/AssetDefinitionStore.swift
AlphaWallet/TokenScriptClient/Models/TokenScriptFileIndices.swift
AlphaWallet/Tokens/Coordinators/SingleChainTokenCoordinator.swift
AlphaWallet/Tokens/Types/TokensDataStore.swift
AlphaWallet/Tokens/ViewControllers/TokensCardViewController.swift
AlphaWallet/Tokens/Views/OpenSea/OpenSeaNonFungibleTokenCardRowView.swift
AlphaWallet/Tokens/Views/TokenInstanceWebView.swift
AlphaWallet/UI/Views/TokenCardRowView.swift
AlphaWallet/UI/Views/TokenCardRowViewProtocol.swift

Speed up TokenScript view rendering

---

AlphaWallet/Transfer/Types/GasLimitConfiguration.swift

Closes #1666 
Really we should be doing #1667

increase gas limit on TokenScript calls

---

AlphaWallet/Tokens/ViewControllers/TokenInstanceViewController.swift
AlphaWallet/Tokens/Views/TokenCardsViewControllerHeader.swift
AlphaWallet/UI/Views/TokenCardRowView.swift

This PR fixes rendering problems related to height in this screen with the TokenScrip action buttons:

Fix: TokenScript view rendering in token instance screen

---

AlphaWallet/InCoordinator.swift
AlphaWallet/TokenScriptClient/Models/FunctionOrigin.swift
AlphaWallet/Transfer/Controllers/TransactionConfigurator.swift

gets the gas price from the node rather than guessing

---

AlphaWallet/UI/Views/AmountTextField.swift

rounds USD figures to 18 decimals

---

AlphaWallet/Transfer/ViewControllers/RequestViewController.swift
AlphaWallet/Transfer/ViewModels/RequestViewModel.swift

One step towards implementing #1664
-|-

Show ENS in receive/My Wallet screen

---

AlphaWallet/Transfer/Controllers/TransactionConfigurator.swift

Fixes #1563 
Successfully opened a CDP vault with this tx by using this PR: https://etherscan.io/tx/0xcfb06154d20e17025421ff844e8f438995f6565ca0ddbd0973aada2c8c22a834

prevents excessive gas limtis set by dapp browser

---

AlphaWallet/Transfer/Types/TransferType.swift
AlphaWallet/Transfer/ViewControllers/SendViewController.swift

Fix: ETH amount in Send screen gets cleared after scanning QR code with only address and further editing gets cleared too

---

AlphaWallet/Settings/ViewControllers/LocalesViewController.swift
AlphaWallet/Settings/ViewModels/LocaleViewModel.swift
AlphaWallet/Settings/Views/LocaleViewCell.swift
AlphaWallet/Style/AppStyle.swift

Tweak Change Language screen UI

---

AlphaWallet/Settings/Coordinators/EnabledServersCoordinator.swift
AlphaWallet/Settings/Coordinators/SettingsCoordinator.swift
AlphaWallet/Settings/ViewControllers/EnabledServersViewController.swift
AlphaWallet/Settings/ViewModels/ServerViewModel.swift
AlphaWallet/Settings/Views/ServerViewCell.swift

Tweak Enable networks screen UI

---

AlphaWallet/Accounts/Coordinators/AccountsCoordinator.swift
AlphaWallet/AlphaWalletHelp/ViewControllers/HelpViewController.swift
AlphaWallet/Browser/Coordinators/DappBrowserCoordinator.swift
AlphaWallet/Export/Coordinators/BackupCoordinator.swift
AlphaWallet/InCoordinator.swift
AlphaWallet/Lock/Coordinators/LockCreatePasscodeCoordinator.swift
AlphaWallet/Redeem/ViewControllers/TokenCardRedemptionViewController.swift
AlphaWallet/Settings/Coordinators/EnabledServersCoordinator.swift
AlphaWallet/Settings/Coordinators/SettingsCoordinator.swift
AlphaWallet/Settings/ViewControllers/SettingsViewController.swift
AlphaWallet/Style/AppStyle.swift
AlphaWallet/Tokens/Coordinators/SingleChainTokenCoordinator.swift
AlphaWallet/Tokens/Views/TokenListFormatRowView.swift
AlphaWallet/Transactions/Coordinators/TokensCardCoordinator.swift
AlphaWallet/Transactions/Coordinators/TransactionCoordinator.swift
AlphaWallet/Transfer/Coordinators/SendCoordinator.swift
AlphaWallet/Transfer/ViewControllers/ConfirmPaymentViewController.swift
AlphaWallet/Wallet/Coordinators/BackupSeedPhraseCoordinator.swift
AlphaWallet/Wallet/Coordinators/ElevateWalletSecurityCoordinator.swift
AlphaWallet/Wallet/Coordinators/EnterPasswordCoordinator.swift
AlphaWallet/Wallet/Coordinators/WalletCoordinator.swift
AlphaWallet/Wallet/ViewControllers/ShowSeedPhraseViewController.swift

Closes  #1633. Last from Fiji for a while.
-|-

Show big titles for Wallet, Transactions and Settings tab

---

AlphaWallet/Market/Coordinators/UniversalLinkCoordinator.swift

cast parameters address correctly to add it

---

AlphaWallet/Tokens/ViewModels/TokensViewModel.swift

allows searching via TokenScript localised name

---

AlphaWallet/Settings/Types/Constants.swift
AlphaWallet/Settings/Types/RPCServers.swift

Unless we want to keep it updated :)

Remove ENS registrar for xDai

---

AlphaWallet/Settings/Views/ServerViewCell.swift

This gray background which animates in and out when a cell is selected, like the locale screen:

Animate selection/deselection of cells in Enable Networks screen

---

AlphaWallet.xcodeproj/project.pbxproj
AlphaWallet/Tokens/Helpers/CallSmartContractFunction.swift
AlphaWalletTests/Tokens/Helpers/SmartContractHelperTests.swift

add function and test to get filtered events

---

AlphaWallet/EtherClient/CoinMarket/Types/CoinTicker.swift
AlphaWallet/EtherClient/TrustClient/AlphaWalletService.swift
AlphaWallet/Settings/Types/Config.swift
AlphaWallet/Tokens/ViewModels/EthCurrencyHelper.swift
AlphaWallet/Tokens/ViewModels/TokenViewControllerViewModel.swift
AlphaWallet/Tokens/ViewModels/TokensViewModel.swift
AlphaWallet/Transactions/ViewModels/BalanceViewModel.swift
AlphaWallet/Transfer/ViewModels/SendViewModel.swift

upgrade API to coingecko

---

AlphaWallet/Transfer/ViewControllers/SendViewController.swift

prevent zero input on address scan

---

AlphaWallet/Tokens/Views/TokenInstanceWebView.swift

enable scrolling in TS views

---

AlphaWallet/Browser/ViewModel/BrowserHistoryCellViewModel.swift
AlphaWallet/Browser/ViewModel/MyDappCellViewModel.swift

This issue fixed #1726
- Change URL colour
Bookmarks | History | Output
-|-|-

URL in bookmarks and history list not visible because they are have the same color (white) as the background #1726

---

AlphaWallet.xcodeproj/project.pbxproj
AlphaWallet/TokenScriptClient/Models/TokenScriptFilterParser.swift
AlphaWallet/TokenScriptClient/Models/TokenScriptSelection.swift
AlphaWallet/TokenScriptClient/Models/XMLHandler.swift
AlphaWallet/Tokens/Types/TokenInstanceAction.swift
AlphaWallet/Tokens/ViewControllers/TokenInstanceViewController.swift
AlphaWallet/Tokens/ViewControllers/TokenViewController.swift
AlphaWallet/Tokens/ViewControllers/TokensCardViewController.swift
AlphaWallet/Tokens/ViewModels/TokenViewControllerViewModel.swift
AlphaWalletTests/TokenScriptClient/TokenScriptFilterParserTests.swift

Closes #1776
@James-Sangalli would you refer to #1776 for what is in-scope/out-of-scope and buzz me if there's something unexpected in the scope?
Have included test cases for the parser: `TokenScriptFilterParserTests`

Support <selection> for filtering actions

---

AlphaWallet/TokenScriptClient/Models/Origin.swift
AlphaWallet/TokenScriptClient/Models/TokenIdOrigin.swift
AlphaWallet/TokenScriptClient/Models/UserEntryOrigin.swift

https://github.com/AlphaWallet/TokenScript/issues/349

add e6 multiplier

---

AlphaWallet/Browser/Factory/WKWebViewConfiguration.swift
AlphaWallet/TokenScriptClient/Models/AssetAttribute.swift
AlphaWallet/TokenScriptClient/Models/AssetAttributeSyntax.swift
AlphaWallet/TokenScriptClient/Models/AssetAttributeSyntaxValue.swift
AlphaWallet/TokenScriptClient/Models/AssetAttributeValueUsableAsFunctionArguments.swift
AlphaWallet/TokenScriptClient/Models/AssetFunctionCall.swift
AlphaWallet/TokenScriptClient/Models/AssetInternalValue.swift
AlphaWallet/TokenScriptClient/Models/FunctionOrigin.swift
AlphaWallet/TokenScriptClient/Models/Origin.swift
AlphaWallet/TokenScriptClient/Models/UserEntryOrigin.swift
AlphaWallet/TokenScriptClient/Models/XMLHandler.swift
AlphaWallet/Tokens/Types/TokenInstanceAction.swift
AlphaWallet/Tokens/ViewControllers/TokenInstanceActionViewController.swift
AlphaWallet/Tokens/Views/TokenInstanceWebView.swift
AlphaWallet/UI/Views/TokenCardRowView.swift

Closes  #1790
@James-Sangalli Left a couple of comments that might cause this PR to not work as expected:

Support local-ref

---

AlphaWallet/Browser/Factory/WKWebViewConfiguration.swift
AlphaWallet/Tokens/Views/TokenInstanceWebView.swift

Closes #1808 
After this PR, setProps() should still work without the callback.

Add error callback to setProps() to trigger when props names clash with card attributes 

---

AlphaWallet/Transfer/ViewControllers/RequestViewController.swift

Closes #1806
Make entire address and ENS name labels tappable to trigger the copy action
Add tap gesture recogizer for ens and address labels

Make entire address and ENS name labels tappable to trigger the copy action

---

AlphaWallet/TokenScriptClient/Models/AssetAttribute.swift
AlphaWallet/TokenScriptClient/Models/FunctionOrigin.swift
AlphaWallet/TokenScriptClient/Models/XMLHandler.swift
AlphaWalletTests/TokenScriptClient/XMLHandlerTest.swift
xDaiTokenScript/XDAI-bridge.tsml

upgrade to use new attribute syntax [TokenScript schema 2020/06]

---

AlphaWallet/Localization/en.lproj/howDoIGetMyMoneyInfo.html
AlphaWallet/Localization/en.lproj/howDoITransferETHIntoMyWalletInfo.html
AlphaWallet/Localization/en.lproj/privacyPolicy.html
AlphaWallet/Localization/en.lproj/redeemInfo.html
AlphaWallet/Localization/en.lproj/sellInfo.html
AlphaWallet/Localization/en.lproj/termsOfService.html
AlphaWallet/Localization/en.lproj/whatIsEthereumInfo.html
AlphaWallet/Tokens/ViewControllers/StaticHTMLViewController.swift

Closes #1685 
Typical error is "Invalid Binary".

Replace UIWebView with WebKit for static pages. Needed now because appstoreconnect is rejecting its use

---

AlphaWallet/Settings/Types/Constants.swift
AlphaWallet/Tokens/Coordinators/TokensCoordinator.swift

remove discovery token

---

AlphaWallet/Accounts/Coordinators/AccountsCoordinator.swift
AlphaWallet/AppCoordinator.swift
AlphaWallet/Tokens/Coordinators/TokensCoordinator.swift
AlphaWallet/Transfer/Coordinators/PaymentCoordinator.swift
AlphaWallet/Transfer/Coordinators/SendCoordinator.swift
AlphaWallet/Wallet/Coordinators/InitialWalletCreationCoordinator.swift
AlphaWallet/Wallet/Coordinators/WalletCoordinator.swift

Broken because a PR that broke the suite was merged.

Fix: test suite broken. No functional change

---

AlphaWallet/Transfer/Controllers/TransactionConfigurator.swift
AlphaWallet/Transfer/Types/GasPriceConfiguration.swift

add an extra gwei to the gas estimate to prevent hanging transactions

---

AlphaWallet/Transfer/ViewControllers/SendViewController.swift

Prevent sending more ERC20 tokens than you have

---

AlphaWallet/Tokens/ViewControllers/TokensViewController.swift

Make Wallet tab table background white when there are not enough tokens to fill the screen #1818

---

AlphaWallet/Core/Initializers/MigrationInitializerForOneChainPerDatabase.swift
AlphaWallet/Market/Coordinators/UniversalLinkCoordinator.swift
AlphaWallet/Sell/ViewModels/EnterSellTokensCardPriceQuantityViewControllerViewModel.swift
AlphaWallet/Sell/ViewModels/GenerateSellMagicLinkViewControllerViewModel.swift
AlphaWallet/Sell/ViewModels/GenerateTransferMagicLinkViewControllerViewModel.swift
AlphaWallet/Sell/ViewModels/SetSellTokensCardExpiryDateViewControllerViewModel.swift
AlphaWallet/TokenScriptClient/Coordinators/EventSourceCoordinator.swift
AlphaWallet/TokenScriptClient/Models/AssetImplicitAttributes.swift
AlphaWallet/TokenScriptClient/Models/XMLHandler.swift
AlphaWallet/Tokens/Helpers/TokenAdaptor.swift
AlphaWallet/Tokens/Types/TokenObject.swift
AlphaWallet/Tokens/Views/TokenInstanceWebView.swift
AlphaWallet/Transfer/Coordinators/TransferNFTCoordinator.swift

use label not name in implicit props

---

AlphaWallet/Localization/en.lproj/Localizable.strings
AlphaWallet/Localization/es.lproj/Localizable.strings
AlphaWallet/Localization/ja.lproj/Localizable.strings
AlphaWallet/Localization/ko.lproj/Localizable.strings
AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings

Update "TokenScript Standard" text in Settings tab #1781

---

AlphaWallet/Tokens/Types/TokensDataStore.swift

Delete the redundant comment: "//We should refresh balance of the ETH every 10 seconds." #1847

---

AlphaWallet/TokenScriptClient/Models/AssetAttribute.swift
AlphaWallet/TokenScriptClient/Models/Origin.swift
AlphaWallet/TokenScriptClient/Models/XMLHandler+XPaths.swift
AlphaWallet/TokenScriptClient/Models/XMLHandler.swift

Tweak 2020 06 selections event syntax

---

AlphaWallet/TokenScriptClient/Models/XMLHandler+XPaths.swift

[TokenScript schema 2020/03] Fix: xDai (action-only) bridge TokenScript isn't picked up

---

AlphaWallet/TokenScriptClient/Models/XMLHandler+XPaths.swift

fix broken value param in TS

---

AlphaWallet.xcodeproj/project.pbxproj
AlphaWallet/Localization/en.lproj/Localizable.strings
AlphaWallet/Localization/es.lproj/Localizable.strings
AlphaWallet/Localization/ja.lproj/Localizable.strings
AlphaWallet/Localization/ko.lproj/Localizable.strings
AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings
AlphaWallet/Tokens/ViewModels/SendViewSectionHeaderViewModel.swift
AlphaWallet/Tokens/Views/SendViewSectionHeader.swift
AlphaWallet/Transfer/ViewControllers/SendViewController.swift
AlphaWallet/Transfer/ViewModels/SendViewModel.swift
AlphaWallet/UI/AddressTextField.swift
AlphaWallet/UI/Views/AmountTextField.swift

Implement send screen design for native cryptocurrency and ERC20 #1162

---

AlphaWallet/Transfer/ViewControllers/SendViewController.swift

Wrong textField validation when paste address SendViewController #1877

---

AlphaWallet/Tokens/ViewControllers/TokensCardViewController.swift

Fix: tapping token card at bottom of token cards screen doesn't register #1879

---

AlphaWallet/Localization/en.lproj/Localizable.strings
AlphaWallet/Localization/es.lproj/Localizable.strings
AlphaWallet/Localization/ja.lproj/Localizable.strings
AlphaWallet/Localization/ko.lproj/Localizable.strings
AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings
AlphaWallet/Settings/Types/ConfigExplorer.swift
AlphaWallet/Transactions/ViewControllers/TransactionViewController.swift
AlphaWallet/Transactions/ViewModels/TransactionDetailsViewModel.swift
AlphaWallet/UI/Form/TransactionAppearance.swift

Add copy button to Transaction Details + rename "More Details" to "View in Etherscan"

---

package.json
yarn.lock

* CVE-2020-7598
* CVE-2019-20149

Fix: GitHub security warning for JavaScript packages

---

AlphaWallet/Sell/ViewControllers/EnterSellTokensCardPriceQuantityViewController.swift
AlphaWallet/Transfer/ViewControllers/SendViewController.swift
AlphaWallet/UI/Views/AmountTextField.swift

Tweak Next and Done buttons for textboxes in Send eth/ERC20 screen #1890

---

AlphaWallet/TokenScriptClient/Models/XMLHandler.swift
AlphaWallet/Tokens/ViewModels/EthTokenViewCellViewModel.swift
AlphaWallet/Tokens/ViewModels/FungibleTokenViewCellViewModel.swift
AlphaWallet/Tokens/ViewModels/NonFungibleTokenViewCellViewModel.swift
AlphaWallet/Tokens/ViewModels/TokensCardViewControllerHeaderViewModel.swift
AlphaWallet/Tokens/ViewModels/TokensCardViewControllerHeaderViewModelWithIntroduction.swift
AlphaWallet/Tokens/Views/EthTokenViewCell.swift
AlphaWallet/Tokens/Views/FungibleTokenViewCell.swift
AlphaWallet/Tokens/Views/NonFungibleTokenViewCell.swift
AlphaWallet/Tokens/Views/TokenCardsViewControllerHeader.swift
AlphaWallet/Transfer/ViewModels/SendHeaderViewViewModel.swift
AlphaWallet/Transfer/ViewModels/SendHeaderViewViewModelWithIntroduction.swift
AlphaWallet/Transfer/Views/SendHeaderView.swift
AlphaWallet/Transfer/Views/SendHeaderViewWithIntroduction.swift

https://github.com/AlphaWallet/alpha-wallet-android/issues/1453

remove issuer label

---

AlphaWallet/Settings/ViewControllers/SettingsViewController.swift
AlphaWallet/Settings/ViewModels/SettingsViewModel.swift

Display ENS name (if available) and Ethereum address for current wallet under "Change / Add Wallet" in Settings screen #1887

---

AlphaWallet/Settings/ViewControllers/SettingsViewController.swift

Remove or replace unnecessary `default:` in `SettingsViewController` #1899

---

AlphaWallet/Browser/Coordinators/ScanQRCodeCoordinator.swift
AlphaWallet/Extensions/UIAlertController.swift
AlphaWallet/Localization/en.lproj/Localizable.strings
AlphaWallet/Localization/es.lproj/Localizable.strings
AlphaWallet/Localization/ja.lproj/Localizable.strings
AlphaWallet/Localization/ko.lproj/Localizable.strings
AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings
AlphaWallet/Transfer/ViewControllers/SendViewController.swift

Display an error message when QR code for EIP681 link has invalid contract #1874

---

AlphaWallet/Settings/Views/SettingTableViewCell.swift

Title of cell in Settings tab is sometimes clipped at the bottom when there is a subtitle #1896

---

AlphaWallet/Core/Formatters/CurrencyFormatter.swift
AlphaWallet/Settings/Types/Constants.swift
AlphaWallet/Style/AppStyle.swift
AlphaWallet/Tokens/ViewControllers/AddHideTokensViewController.swift
AlphaWallet/Tokens/ViewControllers/TokensViewController.swift
AlphaWallet/Tokens/ViewModels/EthCurrencyHelper.swift
AlphaWallet/Tokens/ViewModels/EthTokenViewCellViewModel.swift
AlphaWallet/Tokens/ViewModels/FungibleTokenViewCellViewModel.swift
AlphaWallet/Tokens/Views/EthTokenViewCell.swift
AlphaWallet/Tokens/Views/FungibleTokenViewCell.swift
AlphaWallet/Tokens/Views/NonFungibleTokenViewCell.swift
AlphaWallet/Transactions/ViewModels/BalanceViewModel.swift

Update Wallet tab cell's layout #1903

---

AlphaWallet/Browser/Factory/WKWebViewConfiguration.swift

Remove "if #available(iOS 11.0, *) {" since we support >= 11 #1911

---

AlphaWallet/Core/Formatters/CurrencyFormatter.swift
AlphaWallet/Localization/en.lproj/Localizable.strings
AlphaWallet/Localization/es.lproj/Localizable.strings
AlphaWallet/Localization/ja.lproj/Localizable.strings
AlphaWallet/Localization/ko.lproj/Localizable.strings
AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings
AlphaWallet/Transfer/ViewControllers/SendViewController.swift
AlphaWallet/Transfer/ViewModels/SendViewModel.swift
AlphaWallet/UI/Views/AmountTextField.swift

Show "Available: <eth/token balance>" in send screen #1886

---

AlphaWallet/Browser/ViewControllers/BrowserViewController.swift
AlphaWallet/EtherClient/CoinMarket/Types/CoinTicker.swift
AlphaWallet/InCoordinator.swift
AlphaWallet/Market/OrderHandler.swift
AlphaWallet/Settings/ViewControllers/SupportViewController.swift
AlphaWallet/TokenScriptClient/Models/EventOrigin.swift
AlphaWallet/TokenScriptClient/Models/EventsDataStore.swift
AlphaWallet/TokenScriptClient/Models/FunctionOrigin.swift
AlphaWallet/TokenScriptClient/Models/TokenScriptFilterParser.swift
AlphaWallet/TokenScriptClient/Models/XMLHandler+XPaths.swift
AlphaWallet/Tokens/Coordinators/AddHideTokensCoordinator.swift
AlphaWallet/Tokens/Coordinators/SingleChainTokenCoordinator.swift
AlphaWallet/Tokens/Models/WalletFilter.swift
AlphaWallet/Tokens/Types/TokenObject.swift
AlphaWallet/Tokens/Types/TokensDataStore.swift
AlphaWallet/Tokens/ViewControllers/AddHideTokensViewController.swift
AlphaWallet/Tokens/ViewControllers/StaticHTMLViewController.swift
AlphaWallet/Tokens/ViewControllers/TokenInstanceViewController.swift
AlphaWallet/Tokens/ViewControllers/TokenViewController.swift
AlphaWallet/Tokens/ViewControllers/TokensCardViewController.swift
AlphaWallet/Tokens/ViewModels/TokenViewControllerViewModel.swift
AlphaWallet/Tokens/Views/TokenInstanceWebView.swift
AlphaWallet/Transfer/ViewControllers/SendViewController.swift
AlphaWallet/UI/Views/AmountTextField.swift
AlphaWallet/Wallet/ViewControllers/ImportWalletViewController.swift
AlphaWalletTests/TokenScriptClient/FakeEventsDataStore.swift
AlphaWalletTests/TokenScriptClient/XMLHandlerTest.swift

Fix: SwiftLint warnings

---

AlphaWallet/Transfer/Controllers/TransactionConfigurator.swift

use node gas price on dapp transactions

---

AlphaWallet.xcodeproj/project.pbxproj
AlphaWallet/Sell/ViewControllers/EnterSellTokensCardPriceQuantityViewController.swift
AlphaWallet/Tokens/Coordinators/TokensCoordinator.swift
AlphaWallet/Tokens/Types/TokenObject.swift
AlphaWallet/Tokens/ViewModels/EthTokenViewCellViewModel.swift
AlphaWallet/Tokens/ViewModels/FungibleTokenViewCellViewModel.swift
AlphaWallet/Tokens/ViewModels/NonFungibleTokenViewCellViewModel.swift
AlphaWallet/Transfer/Types/TransferType.swift
AlphaWallet/Transfer/ViewControllers/SendViewController.swift
AlphaWallet/Transfer/ViewModels/SendViewModel.swift
AlphaWallet/UI/SelectCurrencyButton.swift
AlphaWallet/UI/TokenObject+UI.swift
AlphaWallet/UI/Views/AmountTextField.swift
AlphaWalletTests/Coordinators/InCoordinatorTests.swift
AlphaWalletTests/Coordinators/SendCoordinatorTests.swift
AlphaWalletTests/Factories/UnconfirmedTransaction.swift
AlphaWalletTests/ViewControllers/PaymentCoordinatorTests.swift

Closes #1924 
Just using the same approach/sources. A followup PR(s) to add sources for token icons.
-|-

Use token icons from wallet tab in send screen

---

AlphaWallet/UI/ButtonsBar.swift

Fixes #1925 
This is caused by this sequence of events:
1. Tap more button to show action sheet
2. UI refreshes and buttons B are replaced with B'
3. User tap button X in action sheet
4. We use B to send the action, which is no longer there. We need to find B' instead
So we have to figure out the button in the current set of buttons after refresh.

Fix: TokenScript actions offered in the actionsheet after tapping the more button sometimes do nothing

---

AlphaWallet/Transfer/ViewControllers/SendViewController.swift
AlphaWallet/UI/AddressTextField.swift

Typing/pasting an Ethereum address into the address field in send ERC20/ETH screen should also do reverse ENS lookup #1914

---

AlphaWallet/Settings/ViewControllers/AdvancedSettingsViewController.swift
AlphaWallet/Tokens/ViewControllers/TokensViewController.swift
AlphaWallet/Tokens/ViewModels/TokensViewModel.swift
AlphaWallet/Transactions/ViewModels/TransactionsViewModel.swift

Background color revealed in Wallet and Transactions tab when pulling down to refresh is wrong #1912

---

AlphaWallet/Welcome/ViewModels/OnboardingPageViewModel.swift

Replace #imageLiteral with R.image.xxx #1946

---

AlphaWallet/UI/AddressTextField.swift
AlphaWallet/UI/NumberStepper.swift
AlphaWallet/Welcome/ViewControllers/WelcomeViewController.swift

Replace all `button.backgroundColor = ` with `setBackgroundColor(_:forState:)` #1955

---

AlphaWallet/Style/AppStyle.swift
AlphaWallet/UI/AddressTextField.swift

Tweak how result of resolving ENS name (-> address) in Send screen is displayed

---

AlphaWallet/Extensions/UIView.swift
AlphaWallet/Settings/ViewControllers/AdvancedSettingsViewController.swift
AlphaWallet/Settings/ViewControllers/ConsoleViewController.swift
AlphaWallet/Settings/ViewControllers/EnabledServersViewController.swift
AlphaWallet/Settings/ViewControllers/LocalesViewController.swift
AlphaWallet/Settings/ViewControllers/ServersViewController.swift
AlphaWallet/Settings/ViewControllers/SettingsViewController.swift
AlphaWallet/Settings/ViewControllers/SupportViewController.swift
AlphaWallet/Style/AppStyle.swift
AlphaWallet/TokenScriptClient/ViewControllers/AssetDefinitionsOverridesViewController.swift
AlphaWallet/Tokens/ViewControllers/TokensViewController.swift

Replace UITableView backgound with AlabasterColor #1947

---

AlphaWallet/TokenScriptClient/Models/XMLHandler+XPaths.swift

https://github.com/AlphaWallet/TokenScript-Examples/pull/93

add type to asnx:module syntax

---

AlphaWallet/Sell/ViewControllers/EnterSellTokensCardPriceQuantityViewController.swift
AlphaWallet/Sell/ViewModels/EnterSellTokensCardPriceQuantityViewControllerViewModel.swift

Price per token should be ETH not the token name #1961

---

AlphaWallet/Tokens/Coordinators/AddHideTokensCoordinator.swift
AlphaWallet/Tokens/Coordinators/SingleChainTokenCoordinator.swift
AlphaWallet/Tokens/Types/TokensDataStore.swift
AlphaWallet/Tokens/ViewControllers/AddHideTokensViewController.swift
AlphaWallet/Tokens/ViewModels/AddHideTokensViewModel.swift

Fix add a custom token in Add / Hide Tokens screen does not show the token in the first list #1968

---

AlphaWallet.xcodeproj/project.pbxproj
AlphaWallet/Core/Views/AddressOrEnsNameLabel.swift
AlphaWallet/Tokens/ViewControllers/NewTokenViewController.swift
AlphaWallet/Transfer/ViewControllers/SendViewController.swift
AlphaWallet/Transfer/ViewControllers/TransferTokensCardViaWalletAddressViewController.swift
AlphaWallet/UI/AddressTextField.swift
AlphaWallet/Wallet/ViewControllers/ImportWalletViewController.swift

Closes #1950, closes #1213, closes #1977

Extract a UILabel wrapper or subclass which displays Ethereum address and/or ENS name #1950

---

AlphaWallet/Accounts/ViewModels/AccountsViewController.swift

Swipe menus remove the cell in the "Change Wallet" screen even if the wallet is not deleted #1976

---

AlphaWallet/Accounts/Coordinators/AccountsCoordinator.swift
AlphaWallet/Settings/Coordinators/SettingsCoordinator.swift

Make tap "Change / Add Wallet" in Settings push instead of present modal #1980

---

AlphaWallet/Tokens/Coordinators/SingleChainTokenCoordinator.swift
AlphaWallet/Tokens/ViewControllers/TokenViewController.swift
AlphaWallet/Tokens/ViewControllers/TokensCardViewController.swift
AlphaWallet/Tokens/ViewControllers/TokensViewController.swift
AlphaWallet/Transactions/Coordinators/TokensCardCoordinator.swift

Make tap token in Wallet tab push instead of present modal #1956

---

AlphaWallet/Core/Formatters/CurrencyFormatter.swift
AlphaWallet/Export/ViewModels/PromptBackupWalletAfterExceedingThresholdViewViewModel.swift
AlphaWallet/Foundation/EtherNumberFormatter.swift
AlphaWallet/Settings/Types/Constants.swift
AlphaWallet/Tokens/ViewModels/EthCurrencyHelper.swift
AlphaWallet/Tokens/ViewModels/TokensViewModel.swift
AlphaWallet/Transactions/ViewModels/BalanceViewModel.swift
AlphaWallet/Transfer/Types/CurrencyRate+Fee.swift
AlphaWallet/Transfer/ViewModels/SendViewModel.swift

Reduce number of NumberFormatter and EtherNumberFormatter defined, if possible #1954

---

AlphaWallet/Tokens/ViewModels/EthCurrencyHelper.swift
AlphaWallet/Tokens/ViewModels/EthTokenViewCellViewModel.swift
AlphaWallet/Tokens/Views/EthTokenViewCell.swift

Show current market price instead of price diff in wallet tab #1981

---

AlphaWallet.xcodeproj/project.pbxproj
AlphaWallet/Style/AppStyle.swift
AlphaWallet/Tokens/ViewModels/BlockchainTagLabelViewModel.swift
AlphaWallet/Tokens/ViewModels/EthTokenViewCellViewModel.swift
AlphaWallet/Tokens/ViewModels/FungibleTokenViewCellViewModel.swift
AlphaWallet/Tokens/ViewModels/NonFungibleTokenViewCellViewModel.swift
AlphaWallet/Tokens/Views/BlockchainTagLabel.swift
AlphaWallet/Tokens/Views/EthTokenViewCell.swift
AlphaWallet/Tokens/Views/FungibleTokenViewCell.swift
AlphaWallet/Tokens/Views/NonFungibleTokenViewCell.swift

Show testnet label in cells if testnet in Wallet tab #1984

---

AlphaWallet/Core/Initializers/MigrationInitializer.swift
AlphaWallet/TokenScriptClient/Models/AssetAttribute.swift
AlphaWallet/Transactions/Views/TransactionsEmptyView.swift
AlphaWallet/Transfer/ViewControllers/SendViewController.swift
AlphaWallet/UI/EmptyView.swift
AlphaWallet/UI/FloatLabelCell.swift
AlphaWallet/UI/Views/AmountTextField.swift

Refactor: replace `if let _ = <something>` with `if <something> != nil`

---

AlphaWallet/UI/AddressTextField.swift

Clean up possibly redundant code #1988

---

AlphaWallet/Accounts/ViewModels/AccountsViewController.swift
AlphaWallet/Accounts/Views/AccountViewTableSectionHeader.swift

Make list of wallets screen's headers stick to top when scrolling #1987

---

AlphaWallet/Wallet/ViewControllers/ImportWalletViewController.swift

Hide seed phrase word count in Import Wallet screen when the selected tab is not "Seed" #2000

---

AlphaWallet/Transfer/Coordinators/TransferNFTCoordinator.swift

use gas price from node for NFT transfers

---

AlphaWallet/Localization/en.lproj/Localizable.strings
AlphaWallet/Localization/es.lproj/Localizable.strings
AlphaWallet/Localization/ja.lproj/Localizable.strings
AlphaWallet/Localization/ko.lproj/Localizable.strings
AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings

Change "Network Fee" in transaction confirmation page to "Estimate Network Fee" #2010

---

AlphaWallet/Transfer/ViewControllers/TransferTokensCardViaWalletAddressViewController.swift
AlphaWallet/Transfer/ViewModels/TransferTokensCardViaWalletAddressViewControllerViewModel.swift

Make address text field and auxiliary UI components in Transfer NFT screen look like Send screen #1991

---

AlphaWallet/Localization/en.lproj/Localizable.strings
AlphaWallet/Localization/es.lproj/Localizable.strings
AlphaWallet/Localization/ja.lproj/Localizable.strings
AlphaWallet/Localization/ko.lproj/Localizable.strings
AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings
AlphaWallet/Wallet/ViewControllers/SeedPhraseBackupIntroductionViewController.swift
AlphaWallet/Wallet/ViewModels/SeedPhraseBackupIntroductionViewModel.swift

Similar to https://github.com/AlphaWallet/alpha-wallet-android/pull/1510

add warning message to prevent users sharing their seed phrase with scammers

---

AlphaWallet.xcodeproj/project.pbxproj
AlphaWallet/Core/Coordinators/FilterTokensCoordinator.swift
AlphaWallet/Localization/en.lproj/Localizable.strings
AlphaWallet/Localization/es.lproj/Localizable.strings
AlphaWallet/Localization/ja.lproj/Localizable.strings
AlphaWallet/Localization/ko.lproj/Localizable.strings
AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings
AlphaWallet/Tokens/Models/WalletFilter.swift
AlphaWallet/Tokens/ViewControllers/TokensViewController.swift
AlphaWallet/Tokens/ViewModels/TokensViewModel.swift
AlphaWallet/Tokens/Views/SegmentedControl.swift
AlphaWalletTests/Core/Coordinators/FilterTokensCoordinatorTests.swift

Finances tab in iOS to show all defi related tokens #2029

---

AlphaWallet/Wallet/ViewControllers/SeedPhraseBackupIntroductionViewController.swift
AlphaWallet/Wallet/ViewControllers/ShowSeedPhraseViewController.swift
AlphaWallet/Wallet/ViewModels/SeedPhraseBackupIntroductionViewModel.swift

backup seed phrase screen doesn't fit in iPhone 5s #2033

---

AlphaWallet/Browser/Coordinators/DappBrowserCoordinator.swift
AlphaWallet/Browser/ViewControllers/BrowserViewController.swift
AlphaWallet/Browser/Views/NativeCryptoCurrencyBalanceView.swift
AlphaWallet/Core/Collection+UIView.swift
AlphaWallet/Core/Helpers/withRetry.swift
AlphaWallet/Extensions/UITextFieldAdditions.swift
AlphaWallet/Extensions/UIViewInspectableEnhancements.swift
AlphaWallet/Settings/Types/Constants.swift
AlphaWallet/Settings/ViewControllers/ServersViewController.swift
AlphaWallet/Tokens/Models/WalletFilter.swift
AlphaWallet/Tokens/Types/TokensDataStore.swift
AlphaWallet/Tokens/ViewControllers/AddHideTokensViewController.swift
AlphaWallet/Tokens/ViewControllers/TokenInstanceActionViewController.swift
AlphaWallet/Tokens/Views/TokenInstanceWebView.swift
AlphaWallet/Transfer/Controllers/TransactionConfigurator.swift
AlphaWallet/Transfer/Coordinators/TransferNFTCoordinator.swift
AlphaWallet/Transfer/ViewControllers/ConfirmPaymentViewController.swift
AlphaWallet/Transfer/ViewControllers/TransferTokensCardViaWalletAddressViewController.swift
AlphaWallet/Transfer/Views/SendHeaderViewWithIntroduction.swift
AlphaWallet/UI/Form/SliderTextFieldRow.swift
AlphaWallet/UI/TokenObject+UI.swift
AlphaWallet/Wallet/Coordinators/BackupSeedPhraseCoordinator.swift
AlphaWallet/Wallet/Views/CollectionViewLeftAlignedFlowLayout.swift

Reduce SwiftLint warnings #2045

---

AlphaWallet/Browser/Coordinators/DappBrowserCoordinator.swift
AlphaWallet/Browser/Views/NativeCryptoCurrencyBalanceView.swift
AlphaWallet/InCoordinator.swift

Remove dapp-browser code that are commented out or otherwise disabled #2052

---

AlphaWallet/Settings/Types/ServiceProvider.swift
AlphaWallet/Settings/ViewControllers/SupportViewController.swift
AlphaWallet/Settings/ViewModels/SupportViewModel.swift

Add Customer Support channel to Settings #2051

---

AlphaWallet/Settings/Types/Constants.swift
AlphaWallet/Tokens/Coordinators/SingleChainTokenCoordinator.swift

Add Aave-related contracts automatically in Wallet tab #2065

---

AlphaWallet/HardcodedTokenCards/ViewControllers/HardcodedTokenCardViewController.swift
AlphaWallet/TokenScriptClient/Models/TokenScriptSignatureVerifier.swift

Show signature verification status in hardcoded token card screen

---

AlphaWallet/Activities/Coordinators/ActivitiesCoordinator.swift

Speed up activity

---

AlphaWallet/HardcodedTokenCards/ViewModels/AaveDebtTokenViewControllerViewModel.swift
AlphaWallet/Localization/en.lproj/Localizable.strings
AlphaWallet/Localization/es.lproj/Localizable.strings
AlphaWallet/Localization/ja.lproj/Localizable.strings
AlphaWallet/Localization/ko.lproj/Localizable.strings
AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings

Closes https://github.com/AlphaWallet/TokenScript-Examples/issues/124

Show percent symbol for interest rate in hardcoded debt token card

---

AlphaWallet/Tokens/ViewControllers/TokenViewController.swift
AlphaWallet/Tokens/Views/TokenViewControllerHeaderView.swift

Moved "Verified by xxx" into navigation bar #2018

---

AlphaWallet/Localization/en.lproj/Localizable.strings
AlphaWallet/Localization/es.lproj/Localizable.strings
AlphaWallet/Localization/ja.lproj/Localizable.strings
AlphaWallet/Localization/ko.lproj/Localizable.strings
AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings
AlphaWallet/Style/AppStyle.swift
AlphaWallet/Tokens/Coordinators/SingleChainTokenCoordinator.swift
AlphaWallet/Tokens/Types/TokenObject.swift
AlphaWallet/Tokens/ViewControllers/TokenViewController.swift
AlphaWallet/Tokens/Views/EthTokenViewCell.swift
AlphaWallet/Tokens/Views/TokenViewControllerHeaderView.swift
AlphaWallet/Transfer/ViewModels/SendHeaderViewViewModel.swift
AlphaWallet/Transfer/Views/SendHeaderView.swift

Update header for native crypto / ERC 20 token screens #2007

---

AlphaWallet/Browser/Factory/WKWebViewConfiguration.swift
AlphaWallet/Browser/ViewControllers/BrowserViewController.swift
AlphaWallet/Tokens/Views/TokenInstanceWebView.swift

Getting rid of that unused arg which affects some future changes

Remove unused func arg

---

AlphaWallet/TokenScriptClient/Models/AssetAttribute.swift
AlphaWallet/TokenScriptClient/Models/EventOrigin.swift
AlphaWallet/TokenScriptClient/Models/Origin.swift
AlphaWallet/TokenScriptClient/Models/XMLHandler+XPaths.swift

Refactor for future support of using events for Activities

---

AlphaWallet/InCoordinator.swift
AlphaWallet/TokenScriptClient/Models/FunctionOrigin.swift
AlphaWallet/Tokens/Coordinators/SingleChainTokenCoordinator.swift
AlphaWallet/Tokens/Coordinators/TokensCoordinator.swift
AlphaWallet/Tokens/ViewControllers/TokenInstanceActionViewController.swift
AlphaWallet/Transactions/Coordinators/TokensCardCoordinator.swift

Show pending transactions posted with TokenScript actions

---

AlphaWallet/Transfer/ViewControllers/ConfigureTransactionViewController.swift

wallet doesn't allow the nonce of 0? #2083

---

AlphaWallet/Settings/ViewControllers/SettingsViewController.swift

Toggling passcode on/off in Settings screen does nothing #2085

---

AlphaWallet.xcodeproj/project.pbxproj
AlphaWallet/Style/AppStyle.swift
AlphaWallet/Wallet/ViewControllers/SeedPhraseBackupIntroductionViewController.swift
AlphaWalletTests/ViewControllers/SeedPhraseBackupIntroductionViewControllerTests.swift

Write test case to make sure backup seed phrase screen fits in current simulator/device #2034

---

AlphaWallet/Tokens/ViewControllers/TokenViewController.swift

Expand on #2014 and automatically cycle through the value/market price etc every 5 secs #2082

---

AlphaWallet/Transfer/Types/ConfigureTransaction.swift

Increase max gas fee to 0.2ETH from 0.1ETH

---

AlphaWallet/Transfer/ViewControllers/SendViewController.swift
AlphaWallet/Transfer/ViewModels/SendViewModel.swift

allow zero value native transactions so data can be attached

---

AlphaWallet/AppCoordinator.swift
AlphaWallet/InCoordinator.swift
AlphaWallet/Localization/en.lproj/Localizable.strings
AlphaWallet/Localization/es.lproj/Localizable.strings
AlphaWallet/Localization/ja.lproj/Localizable.strings
AlphaWallet/Localization/ko.lproj/Localizable.strings
AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings
AlphaWallet/TokenScriptClient/Coordinators/AssetDefinitionStoreCoordinator.swift

Lack confirmation message when a developer opened/imported a TSML file into αW #2079

---

AlphaWallet/Tokens/ViewControllers/TokensViewController.swift
AlphaWallet/Tokens/Views/AddHideTokensView.swift
AlphaWallet/Tokens/Views/TokensViewControllerTableViewSectionHeader.swift

Make Add/Hide Tokens easier to tap #2113

---

AlphaWallet.xcodeproj/project.pbxproj
AlphaWallet/Browser/Coordinators/DappBrowserCoordinator.swift
AlphaWallet/InCoordinator.swift
AlphaWallet/Localization/en.lproj/Localizable.strings
AlphaWallet/Localization/es.lproj/Localizable.strings
AlphaWallet/Localization/ja.lproj/Localizable.strings
AlphaWallet/Localization/ko.lproj/Localizable.strings
AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings
AlphaWallet/Tokens/Coordinators/SingleChainTokenCoordinator.swift
AlphaWallet/Tokens/Coordinators/TokensCoordinator.swift
AlphaWallet/Tokens/Types/TokenInstanceAction.swift
AlphaWallet/Tokens/Types/UniswapERC20Token.swift
AlphaWallet/Tokens/Types/UniswapHolder.swift
AlphaWallet/Tokens/ViewControllers/TokenInstanceViewController.swift
AlphaWallet/Tokens/ViewControllers/TokenViewController.swift
AlphaWallet/Tokens/ViewControllers/TokensCardViewController.swift
AlphaWallet/Tokens/ViewModels/TokenViewControllerViewModel.swift
AlphaWallet/Transactions/Coordinators/TokensCardCoordinator.swift

Add default TokenScript action for opening Uniswap to supported ERC20 tokens #2103

---

AlphaWallet/Style/AppStyle.swift
AlphaWallet/Tokens/ViewControllers/TokensViewController.swift
AlphaWallet/Tokens/Views/TokenViewControllerHeaderView.swift
AlphaWallet/Transfer/ViewModels/SendHeaderViewViewModel.swift
AlphaWallet/Transfer/Views/SendHeaderView.swift
AlphaWallet/UI/ButtonsBar.swift

iPhone 5s, ButtonsBar, adjust button width #2118

---

AlphaWallet/Transfer/Types/GasPriceConfiguration.swift
AlphaWalletTests/Transfer/Types/GasPriceConfigurationTests.swift

Hit this myself, the max gas price is way too low for today's traffic. Increasing from 100 GWEI to 300 GWEI

increase max gas price to 300 GWEI

---

AlphaWallet/Transfer/Types/GasPriceConfiguration.swift
AlphaWalletTests/Transfer/Types/GasPriceConfigurationTests.swift

Closes #2125
as seen here https://github.com/ethereum/go-ethereum/blob/master/eth/gasprice/gasprice.go#L32

increase gas price to 500 gwei which is the limit set by GETH

---

AlphaWallet/AlphaWallet.entitlements
AlphaWallet/EtherClient/OpenSea.swift
AlphaWallet/EtherClient/TrustClient/AlphaWalletService.swift
AlphaWallet/Localization/en.lproj/Localizable.strings
AlphaWallet/Localization/es.lproj/Localizable.strings
AlphaWallet/Localization/ja.lproj/Localizable.strings
AlphaWallet/Localization/ko.lproj/Localizable.strings
AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings
AlphaWallet/Market/Coordinators/UniversalLinkCoordinator.swift
AlphaWallet/Settings/Coordinators/ServersCoordinator.swift
AlphaWallet/Settings/Types/ConfigExplorer.swift
AlphaWallet/Settings/Types/Constants.swift
AlphaWallet/Settings/Types/RPCServers.swift
AlphaWallet/Tokens/Coordinators/SingleChainTokenCoordinator.swift
AlphaWallet/Tokens/Types/TokenCollection.swift
AlphaWallet/Tokens/Types/TokensDataStore.swift
AlphaWallet/Tokens/Types/UniswapERC20Token.swift
AlphaWallet/Transactions/Coordinators/SingleChainTransactionEtherscanDataCoordinator.swift
AlphaWallet/Transfer/Controllers/TransactionConfigurator.swift

add binance chain

---

AlphaWallet/Core/Helpers/KeyboardChecker.swift
AlphaWallet/Tokens/ViewControllers/AddHideTokensViewController.swift

Make "Add / Hide Tokens screen" table resize when keyboard is shown/hidden for searching #1990

---

AlphaWallet/Tokens/ViewControllers/TokensViewController.swift

Make Wallet tab table resize when keyboard is shown/hidden for searching #1989

---

AlphaWallet/Tokens/Views/AddHideTokensView.swift

Fix add hide tokens header background color #2113

---

AlphaWallet/Style/AppStyle.swift
AlphaWallet/Tokens/ViewControllers/TokenInstanceViewController.swift
AlphaWallet/Tokens/ViewControllers/TokenViewController.swift
AlphaWallet/Tokens/ViewControllers/TokensCardViewController.swift
AlphaWallet/UI/ButtonsBar.swift

Add white background behind TS buttons #1930

---

AlphaWallet/Tokens/ViewControllers/TokensViewController.swift

Large title in Wallet tab become normal after we push Add / Hide tokens screen and pop back #1859

---

AlphaWallet/Settings/Types/Constants.swift
AlphaWallet/Tokens/Coordinators/SingleChainTokenCoordinator.swift

Auto detect FIFA and Car Token (Rinkey) if there is a non-zero balance

---

AlphaWallet/Tokens/Types/UniswapERC20Token.swift

1. Tap Wallet tab
2. Tap UNI token [1]
3. Tap "..."/More button
4. "Exchange with Uniswap" is now available
[1] https://etherscan.io/token/0x1f9840a85d5af5bf1d1762f925bdaddc4201f984

Add swap with Uniswap action to UNI token

---

package.json
yarn.lock

* CVE-2020-8116
* CVE-2019-20149
* GHSA-p9pc-299p-vxgp
https://github.com/AlphaWallet/alpha-wallet-ios/network/alerts

Fix: GitHub security warning for JavaScript packages caught by Dependabot

---

Gemfile
Gemfile.lock

https://github.com/AlphaWallet/alpha-wallet-ios/network/alerts

Fix: GitHub security warning for Rubygem caught by Dependabot 

---

AlphaWallet/AppCoordinator.swift
AlphaWallet/AppDelegate.swift
AlphaWallet/InCoordinator.swift
AlphaWallet/Info.plist
AlphaWallet/Tokens/Coordinators/TokensCoordinator.swift

Add universal QR scanner to homescreen quick actions

---

AlphaWallet/Core/Coordinators/FilterTokensCoordinator.swift

Type `uniswap` in Wallet tab to list tokens that has Uniswap support

---

AlphaWallet/Activities/Coordinators/ActivitiesCoordinator.swift
AlphaWallet/Activities/ViewControllers/ActivityViewController.swift
AlphaWallet/InCoordinator.swift

Make tapping token icon in Activity view open Etherscan for contract

---

AlphaWallet/UI/Form/SliderTextFieldRow.swift

Fix: sliders broken

---

AlphaWallet/Tokens/ViewControllers/NewTokenViewController.swift

Fix: Using universal QR scanner to add custom token doesn't trigger token detection

---

AlphaWallet/Tokens/ViewControllers/AddHideTokensViewController.swift

Fix: remove the large title used in add custom token screen, especially important because we don't show a title

---

AlphaWallet.xcodeproj/project.pbxproj
AlphaWallet/Accounts/Coordinators/AccountsCoordinator.swift
AlphaWallet/Accounts/ViewModels/AccountViewModel.swift
AlphaWallet/Accounts/ViewModels/AccountsViewController.swift
AlphaWallet/Accounts/ViewModels/AccountsViewModel.swift
AlphaWallet/Accounts/Views/AccountViewCell.swift
AlphaWallet/KeyManagement/EtherKeystore.swift
AlphaWallet/Localization/en.lproj/Localizable.strings
AlphaWallet/Localization/es.lproj/Localizable.strings
AlphaWallet/Localization/ja.lproj/Localizable.strings
AlphaWallet/Localization/ko.lproj/Localizable.strings
AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings
AlphaWallet/Settings/Coordinators/SettingsCoordinator.swift
AlphaWallet/Settings/Types/Config.swift
AlphaWallet/Settings/ViewControllers/SettingsViewController.swift
AlphaWallet/Settings/ViewModels/SettingsViewModel.swift
AlphaWallet/Tokens/Coordinators/GetWalletNameCoordinator.swift

Refer to first wallet:
Before PR (or no custom name set)|Custom name set|Tap and hold to set/change wallet name
-|-|-

Add wallet names support

---

AlphaWallet/Tokens/ViewControllers/TokenInstanceViewController.swift
AlphaWallet/UI/Views/TokenCardRowView.swift

This screen doesn't scroll before this PR:

Fix: TokenScript view for token view was not scrolling

---

AlphaWallet/Accounts/ViewModels/AccountsViewController.swift
AlphaWallet/Activities/ViewControllers/ActivitiesViewController.swift
AlphaWallet/Browser/ViewControllers/DiscoverDappsViewController.swift
AlphaWallet/Settings/ViewControllers/AdvancedSettingsViewController.swift
AlphaWallet/Settings/ViewControllers/SupportViewController.swift
AlphaWallet/Tokens/ViewControllers/AddHideTokensViewController.swift
AlphaWallet/Tokens/ViewControllers/SelectAssetViewController.swift
AlphaWallet/Tokens/ViewControllers/TokensCardViewController.swift
AlphaWallet/Tokens/ViewControllers/TokensViewController.swift
AlphaWallet/Transactions/ViewControllers/TransactionsViewController.swift
AlphaWallet/Transfer/ViewControllers/TransactionConfirmationViewController.swift

Fix background color of header in add hide token screen

---

AlphaWallet/PushNotificationsCoordinator.swift

Fix crash #2190

---

AlphaWallet/Accounts/ViewModels/AccountsViewController.swift
AlphaWallet/AppCoordinator.swift
AlphaWallet/KeyManagement/EtherKeystore.swift
AlphaWallet/KeyManagement/Keystore.swift
AlphaWalletTests/Factories/FakeKeystore.swift

Add in a check if keys for all wallets are not accessible on startup #2048

---

AlphaWallet/Settings/Types/Constants.swift

Auto detect fTokens

---

TokenScriptFiles/ERC20-TokenScript.tsml
TokenScriptFiles/ERC721-TokenScript.tsml

Switch from using `web3.tokens.data.currentInstance` to `web3.tokens.data` (.card and .tokens) in base ERC20 and ERC721 base TokenScripts

---

.travis.yml

Retry brew update command 3 times to avoid temporary build environment network issue.

Retry brew update if failed.

---

AlphaWallet/TokenScriptClient/Models/XMLHandler.swift

This transfer button isn't displayed before this PR, due to a bug introduced when implementing Activity.

Fix: ERC721 transfer button not showing up after tapping on an ERC721 token instance

---

AlphaWallet/Activities/Coordinators/ActivitiesCoordinator.swift
AlphaWallet/Activities/ViewModels/ActivitiesViewModel.swift
AlphaWallet/Activities/ViewModels/DefaultActivityCellViewModel.swift
AlphaWallet/AppDelegate.swift
AlphaWallet/Core/Initializers/MigrationInitializer.swift
AlphaWallet/TokenScriptClient/Models/SolidityType.swift
AlphaWallet/TokenScriptClient/Models/TokenScriptFilterParser.swift
AlphaWallet/TokenScriptClient/Models/XMLHandler.swift
AlphaWallet/Tokens/Helpers/CallSmartContractFunction.swift
AlphaWallet/Tokens/Models/WalletFilter.swift
AlphaWallet/Tokens/ViewControllers/TokenInstanceActionViewController.swift
AlphaWallet/Transactions/Coordinators/TokensCardCoordinator.swift
AlphaWallet/Transfer/Controllers/ConfirmationTransitionController.swift
AlphaWallet/Transfer/Controllers/TransactionConfigurator.swift
AlphaWallet/UI/TokenImageView.swift
AlphaWallet/Wallet/ViewControllers/CreateInitialWalletViewController.swift

Fix build warnings

---

AlphaWallet/Activities/Coordinators/ActivitiesCoordinator.swift

Fix: Activity view is clipped by navigation bar on iPad

---

AlphaWallet/Activities/ViewControllers/ActivityViewController.swift
AlphaWallet/AlphaWalletHelp/ViewControllers/HelpViewController.swift
AlphaWallet/Browser/Coordinators/DappBrowserCoordinator.swift
AlphaWallet/Browser/Factory/WKWebViewConfiguration.swift
AlphaWallet/Browser/ViewControllers/BrowserViewController.swift
AlphaWallet/Browser/ViewControllers/EditMyDappViewController.swift
AlphaWallet/Browser/Views/DappBrowserNavigationBar.swift
AlphaWallet/Extensions/UIView.swift
AlphaWallet/KeyManagement/Keystore.swift
AlphaWallet/Market/ViewControllers/ImportMagicTokenViewController.swift
AlphaWallet/Redeem/ViewControllers/RedeemTokenCardQuantitySelectionViewController.swift
AlphaWallet/Sell/ViewControllers/EnterSellTokensCardPriceQuantityViewController.swift
AlphaWallet/Sell/ViewControllers/SetSellTokensCardExpiryDateViewController.swift
AlphaWallet/Settings/Types/BiometryAuthenticationType.swift
AlphaWallet/Tokens/ViewControllers/NewTokenViewController.swift
AlphaWallet/Tokens/ViewControllers/TokenInstanceActionViewController.swift
AlphaWallet/Transactions/ViewControllers/TransactionViewController.swift
AlphaWallet/Transfer/ViewControllers/ChooseTokenCardTransferModeViewController.swift
AlphaWallet/Transfer/ViewControllers/ConfirmPaymentViewController.swift
AlphaWallet/Transfer/ViewControllers/SendViewController.swift
AlphaWallet/Transfer/ViewControllers/SetTransferTokensCardExpiryDateViewController.swift
AlphaWallet/Transfer/ViewControllers/TransferTokensCardQuantitySelectionViewController.swift
AlphaWallet/Transfer/ViewControllers/TransferTokensCardViaWalletAddressViewController.swift
AlphaWallet/Wallet/ViewControllers/CreateInitialWalletViewController.swift
AlphaWallet/Wallet/ViewControllers/ElevateWalletSecurityViewController.swift
AlphaWallet/Wallet/ViewControllers/KeystoreBackupIntroductionViewController.swift
AlphaWallet/Wallet/ViewControllers/SeedPhraseBackupIntroductionViewController.swift
AlphaWallet/Wallet/ViewControllers/ShowSeedPhraseViewController.swift
AlphaWallet/Wallet/ViewControllers/VerifySeedPhraseViewController.swift
AlphaWallet/Welcome/ViewControllers/WelcomeViewController.swift

Remove spurious iOS version check and wrapper var using it

---

AlphaWallet/AppDelegate.swift
AlphaWallet/Browser/Factory/WKWebViewConfiguration.swift

remove commented code

---

AlphaWallet/Transactions/Storage/Transaction.swift

Fix: crash when sending eth

---

AlphaWallet/UI/TokenObject+UI.swift

Add repo as icon source for testnet #2095

---

AlphaWallet/Browser/Views/DappBrowserNavigationBar.swift

Make back, forward, "more" button in Browser navigation bar be highlighted like QR scan button in Wallet tab when tapped and held #2246

---

AlphaWallet.xcodeproj/project.pbxproj
AlphaWallet/Activities/Coordinators/ActivitiesCoordinator.swift
AlphaWallet/Browser/Coordinators/DappBrowserCoordinator.swift
AlphaWallet/Extensions/UIAlertController.swift
AlphaWallet/InCoordinator.swift
AlphaWallet/Settings/Coordinators/HelpUsCoordinator.swift
AlphaWallet/Settings/Coordinators/SettingsCoordinator.swift
AlphaWallet/Transactions/Coordinators/TransactionCoordinator.swift
AlphaWallet/Transfer/Coordinators/ConfirmCoordinator.swift
AlphaWallet/Transfer/ViewControllers/SendViewController.swift
AlphaWallet/Transfer/ViewControllers/TransferTokensCardViaWalletAddressViewController.swift
AlphaWallet/Transfer/ViewControllers/UIViewController+ensureHasDeviceAuthorization.swift
AlphaWallet/UI/NavigationController.swift
AlphaWallet/Wallet/ViewControllers/ImportWalletViewController.swift

Refactor: Remove NavigationController if it's no longer needed #2245

---

AlphaWallet/Foundation/StringFormatter.swift
AlphaWallet/Transfer/ViewControllers/SendViewController.swift
AlphaWallet/UI/Views/AmountTextField.swift

Toggling between ETH and USD in Send screen should show the same amounts #2243

---

AlphaWallet/UI/AddressTextField.swift
AlphaWallet/UI/Button.swift

 Make camera button in address textfield follow textfield's background color #2253

---

AlphaWallet/Browser/Coordinators/DappBrowserCoordinator.swift

Vibrate after adding bookmark #2260

---

AlphaWallet.xcodeproj/project.pbxproj
AlphaWallet/Browser/Coordinators/DappBrowserCoordinator.swift
AlphaWallet/Core/Helpers/FeedbackGenerator.swift
AlphaWallet/Transactions/ViewControllers/TransactionViewController.swift
AlphaWallet/Transfer/Coordinators/SignMessageCoordinator.swift
AlphaWallet/Transfer/ViewControllers/ConfirmPaymentViewController.swift
AlphaWallet/Transfer/ViewControllers/RequestViewController.swift
AlphaWallet/UI/SuccessOverlayView.swift
AlphaWallet/UI/WhereIsWalletAddressFoundOverlayView.swift

Refactor: Extract common vibration code and use it #2264

---

AlphaWallet/Activities/ViewControllers/ActivitiesViewController.swift
AlphaWallet/Activities/ViewModels/ActivitiesViewModel.swift
AlphaWallet/Core/Helpers/KeyboardChecker.swift
AlphaWallet/TokenScriptClient/Models/ActivityOrTransaction.swift
AlphaWallet/Tokens/ViewControllers/TokensViewController.swift

Add search functionality to Activity tab #2258

---

AlphaWallet/Foundation/StringFormatter.swift
AlphaWallet/Sell/ViewControllers/EnterSellTokensCardPriceQuantityViewController.swift
AlphaWallet/Transfer/ViewControllers/SendViewController.swift
AlphaWallet/UI/Views/AmountTextField.swift

Update replace Double values with NSDecimalNumber value fix precision loss

---

AlphaWallet.xcodeproj/project.pbxproj
AlphaWallet.xcworkspace/xcshareddata/xcschemes/AlphaWalletShare.xcscheme
AlphaWallet/AlphaWallet.entitlements
AlphaWallet/AppCoordinator.swift
AlphaWallet/Core/Coordinators/CustomUrlSchemeCoordinator.swift
AlphaWallet/InCoordinator.swift
AlphaWallet/Share/ShareContentAction.swift
AlphaWallet/Share/UrlSchemeCoordinator.swift
AlphaWalletShare/AlphaWalletShare.entitlements
AlphaWalletShare/Info.plist
AlphaWalletShare/ItemProviderValueResolver.swift
AlphaWalletShare/ItemType.swift
AlphaWalletShare/ShareContextHandler.swift
AlphaWalletTests/Coordinators/InCoordinatorTests.swift

Add Open in AlphaWallet DApp Browser in iOS Activities #1100

---

AlphaWallet/Analytics/Models/AnalyticsTypes.swift
AlphaWallet/Browser/Coordinators/DappBrowserCoordinator.swift
AlphaWallet/InCoordinator.swift
AlphaWallet/Tokens/Coordinators/SingleChainTokenCoordinator.swift
AlphaWallet/Transactions/Coordinators/TokensCardCoordinator.swift
AlphaWallet/Transfer/Coordinators/SendCoordinator.swift
AlphaWallet/Transfer/Coordinators/TransactionConfirmationCoordinator.swift
AlphaWallet/Transfer/Coordinators/TransferNFTCoordinator.swift
AlphaWallet/Transfer/ViewControllers/TransactionConfirmationViewController.swift

Track events for actionsheet-style confirmation for "normal" transactions #2199

---

AlphaWallet/Activities/ViewControllers/ActivitiesViewController.swift

Crash sometimes when searching in Activity tab #2281

---

.swiftlint.yml
AlphaWallet.xcodeproj/project.pbxproj
AlphaWallet/Core/Types/AlphaWalletAddress.swift
AlphaWallet/KeyManagement/EtherKeystore.swift
AlphaWallet/Market/OrderHandler.swift
AlphaWallet/Tokens/Coordinators/ClaimOrderCoordinator.swift
AlphaWallet/UI/Form/HDWallet+Extension.swift
AlphaWallet/UI/Form/MnemonicInWordListRule.swift
AlphaWallet/UI/Form/MnemonicLengthRule.swift
AlphaWallet/Wallet/ViewControllers/ImportWalletViewController.swift
AlphaWalletTests/Core/Types/HDWalletTest.swift
AlphaWalletTests/EtherClient/EtherKeystoreTests.swift
AlphaWalletTests/Market/ViewControllers/ImportTokenViewControllerTests.swift
AlphaWalletTests/Redeem/CreateRedeemTests.swift
AlphaWalletTests/Sell/ViewControllers/EnterSellTokensCardPriceQuantityViewControllerTests.swift
AlphaWalletTests/Transfer/ViewControllers/TransferTokensCardQuantitySelectionViewControllerTests.swift
Podfile
Podfile.lock

Make project build with Xcode 12 #2143

---

AlphaWallet/UI/Views/AmountTextField.swift

Remove trailing zeros from Amount Text Field added during switch from crypty to native currency #2291

---

AlphaWallet.xcodeproj/project.pbxproj
AlphaWallet/Core/DomainResolver.swift
AlphaWallet/Core/Views/AddressOrEnsNameLabel.swift
AlphaWallet/Tokens/Coordinators/GetENSOwnerCoordinator.swift
Podfile
Podfile.lock

Add support for .crypto (UnstoppableDomains) domain lookup #1931

---

AlphaWallet/Transfer/Types/ConfigureTransaction.swift

Raise gas fee max to 3 ETH

---

AlphaWallet/Tokens/Coordinators/ENSReverseLookupCoordinator.swift
AlphaWallet/Tokens/Coordinators/TokensCoordinator.swift
AlphaWallet/Tokens/ViewControllers/TokensViewController.swift
AlphaWallet/Tokens/ViewModels/TokensViewModel.swift
AlphaWalletTests/Settings/ConfigTests.swift

Display ENS name or local wallet name in Wallet tab #2266

---

AlphaWallet/Browser/Coordinators/DappBrowserCoordinator.swift
AlphaWallet/InCoordinator.swift
AlphaWallet/Tokens/Coordinators/SingleChainTokenCoordinator.swift
AlphaWallet/Transactions/Coordinators/TokensCardCoordinator.swift
AlphaWallet/Transfer/Coordinators/TransactionConfirmationCoordinator.swift
AlphaWallet/Transfer/Coordinators/TransferNFTCoordinator.swift
AlphaWallet/Transfer/ViewControllers/TransactionConfirmationViewController.swift
AlphaWallet/Transfer/ViewModels/TransactionConfirmationViewModel.swift
AlphaWallet/Transfer/Views/TransactionConfirmationHeaderView.swift

Before PR|After PR (default gas configuration)|After PR (custom gas configuration)
-|-|-

Display estimated gas fee (and in fiat too, if available) in actionsheet for transaction confirmation

---

AlphaWallet/Localization/en.lproj/Localizable.strings
AlphaWallet/Localization/es.lproj/Localizable.strings
AlphaWallet/Localization/ja.lproj/Localizable.strings
AlphaWallet/Localization/ko.lproj/Localizable.strings
AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings
AlphaWallet/Transfer/Coordinators/TransactionConfirmationCoordinator.swift
AlphaWallet/Transfer/Coordinators/TransferNFTCoordinator.swift
AlphaWallet/Transfer/ViewModels/TransactionConfirmationViewModel.swift

Display token instance name for NFT transfer in actionsheet

---

AlphaWallet/Transfer/ViewControllers/TransactionConfirmationViewController.swift
AlphaWallet/Transfer/ViewModels/TransactionConfirmationViewModel.swift

Display the ETH value in actionsheet for transaction initiated by dapp

---

.travis.yml
AlphaWalletTests/Foundation/DecimalNumberFormatterTest.swift

Make Travis run against iOS 14 #2307

---

AlphaWallet.xcodeproj/project.pbxproj
AlphaWallet/Accounts/ViewControllers/AccountsViewController.swift
AlphaWallet/Accounts/ViewModels/AccountViewModel.swift
AlphaWallet/Accounts/Views/AccountViewCell.swift
AlphaWallet/Core/Helpers/BlockieGenerator.swift
AlphaWallet/Core/Views/BlockieImageView.swift
AlphaWallet/Tokens/ViewControllers/TokensViewController.swift
Podfile
Podfile.lock

Generate and display blockies for wallets #2294

---

AlphaWallet/Foundation/DecimalFormatter.swift
AlphaWalletTests/Foundation/DecimalNumberFormatterTest.swift

Fix Test for frDecimalFormatter #2319

---

AlphaWallet/Gas/Models/GasNowGasPriceEstimator.swift
AlphaWallet/Tokens/Types/TokensDataStore.swift
AlphaWallet/Transactions/Coordinators/AlphaWalletProviderFactory.swift
AlphaWallet/Transactions/Coordinators/SingleChainTransactionEtherscanDataCoordinator.swift

Add a promise-version of the `request()` function to `MoyaProvider` and use it #2321

---

AlphaWallet/Core/DomainResolver.swift
AlphaWallet/Core/Views/AddressOrEnsNameLabel.swift
AlphaWallet/Tokens/Coordinators/ENSReverseLookupCoordinator.swift
AlphaWallet/Tokens/Coordinators/GetENSOwnerCoordinator.swift

Refactor: reduce use of `EthereumAddress` #2323

---

AlphaWallet.xcodeproj/project.pbxproj
AlphaWallet/Core/DecodedFunctionCall.swift
AlphaWallet/TokenScriptClient/Models/FunctionOrigin.swift
AlphaWallet/Transactions/Storage/Transaction.swift
AlphaWallet/Transfer/Coordinators/TransactionConfirmationCoordinator.swift
AlphaWallet/Transfer/ViewControllers/TransactionConfirmationViewController.swift
AlphaWallet/Transfer/ViewModels/TransactionConfirmationViewModel.swift

Decode ERC20 transfers for dapp-initiated transactions and display in actionsheet

---

AlphaWallet/Transfer/Types/RecipientResolver.swift
AlphaWallet/Transfer/ViewControllers/TransactionConfirmationViewController.swift
AlphaWallet/Transfer/ViewModels/TransactionConfirmationViewModel.swift
AlphaWallet/Transfer/Views/TransactionConfirmationHeaderView.swift

Do not show "ENS" label in Actionsheet for transaction confirmation under Recipient if there is no ENS name resolved (yet) #2310

---

AlphaWallet/Core/Coordinators/FilterTokensCoordinator.swift
AlphaWallet/Core/SwapToken/Oneinch/Oneinch.swift
AlphaWallet/Core/SwapToken/SwapTokenService.swift
AlphaWallet/Core/SwapToken/Uniswap/Uniswap.swift
AlphaWallet/InCoordinator.swift
AlphaWallet/Tokens/Coordinators/SelectAssetCoordinator.swift
AlphaWallet/Tokens/Coordinators/TokensCoordinator.swift
AlphaWalletTests/Coordinators/TokensCoordinatorTests.swift
AlphaWalletTests/Factories/FakeTokensDataStore.swift
AlphaWalletTests/Settings/ConfigTests.swift

Make typing "swap" in Wallet tab search bar filter for tokens that support swapping #2332

---

AlphaWallet/Core/SwapToken/Oneinch/Oneinch.swift

Closes #2338 
Make the target token be USDT (if from ETH), and ETH (otherwise)

Set default tokens to swap for oneinch

---

AlphaWallet.xcodeproj/project.pbxproj
AlphaWallet/EtherClient/Models/GetNextNonce.swift
AlphaWallet/Transfer/Controllers/TransactionConfigurator.swift
AlphaWallet/Transfer/Coordinators/SendTransactionCoordinator.swift
AlphaWallet/Transfer/Coordinators/TransactionConfirmationCoordinator.swift
AlphaWallet/Transfer/Types/TransactionConfiguration.swift
AlphaWallet/Transfer/ViewControllers/ConfigureTransactionViewController.swift

Show automatically generated nonce when editing transaction confirmation

---

AlphaWallet/Activities/Coordinators/ActivitiesCoordinator.swift
AlphaWallet/Activities/ViewModels/ActivitiesViewModel.swift
AlphaWallet/TokenScriptClient/Models/ActivityOrTransaction.swift

Closes #2272 
&nbsp;|&nbsp;|&nbsp;
-|-|-

Make search activities support token symbol

---

AlphaWallet/InCoordinator.swift
AlphaWallet/Tokens/Coordinators/SingleChainTokenCoordinator.swift
AlphaWallet/Tokens/Coordinators/TokensCoordinator.swift
AlphaWallet/Transfer/Coordinators/TransactionConfirmationCoordinator.swift
AlphaWallet/Transfer/ViewControllers/ConfigureTransactionViewController.swift

Remove tab bar appearing briefly after tapping "Go to Token" to show token #2342

---

AlphaWallet/Settings/Types/ConfigExplorer.swift
AlphaWallet/Settings/Types/Constants.swift
AlphaWallet/Settings/Types/RPCServers.swift

Update binance endpoints

---

AlphaWallet.xcodeproj/project.pbxproj
AlphaWallet/EtherClient/ChainState.swift
AlphaWallet/EtherClient/Models/GetNextNonce.swift
AlphaWallet/Extensions/Session+PromiseKit.swift
AlphaWallet/Tokens/Coordinators/GetNativeCryptoCurrencyBalanceCoordinator.swift
AlphaWallet/Transactions/Coordinators/SingleChainTransactionEtherscanDataCoordinator.swift
AlphaWallet/Transfer/Controllers/TransactionConfigurator.swift
AlphaWallet/Transfer/Coordinators/SendTransactionCoordinator.swift

Nicer flow. Code within the Promise handlers can be improved by extracting them. Not included in this PR.

Refactor: create promise-based wrapper for Session.send() and use it

---

AlphaWallet/Browser/Coordinators/ScanQRCodeCoordinator.swift
AlphaWallet/Wallet/Coordinators/WalletCoordinator.swift

Followup to getting #2352, #2353 merged into master

Fix: Crash if tap camera button while importing a wallet while onboarding #2352

---

AlphaWallet/Transfer/Coordinators/TransactionConfirmationCoordinator.swift
AlphaWallet/Transfer/ViewControllers/TransactionConfirmationViewController.swift
AlphaWallet/Transfer/Views/TransactionConfirmationHeaderView.swift

Expand hit-test area for Edit button in actionsheet for transaction confirmation to the entire cell

---

AlphaWallet/Transfer/ViewModels/GasSpeedTableViewCellViewModel.swift
AlphaWallet/Transfer/ViewModels/TransactionConfirmationTableHeaderViewModel.swift
AlphaWallet/Transfer/ViewModels/TransactionConfirmationViewModel.swift
AlphaWallet/Transfer/Views/GasSpeedTableViewCell.swift
AlphaWallet/Transfer/Views/TransactionConfirmationHeaderView.swift

Tweak actionsheet font layout

---

AlphaWallet/Core/Initializers/MigrationInitializer.swift

Fix memory leak in MigrationInitializer #2372

---

AlphaWallet/Transfer/ViewModels/GasSpeedTableViewCellViewModel.swift
AlphaWallet/Transfer/Views/GasSpeedTableViewCell.swift

Show gas price in actionsheet edit gas

---

AlphaWallet/Transactions/Storage/TransactionsStorage.swift

Closes #2341, Closes #2340, Closes #1334

Crash with large wallet #2341

---

AlphaWallet/InCoordinator.swift
AlphaWallet/Settings/ViewControllers/SettingsViewController.swift
AlphaWallet/Transfer/Coordinators/PaymentCoordinator.swift
AlphaWallet/Transfer/Coordinators/RequestCoordinator.swift
AlphaWalletTests/Coordinators/InCoordinatorTests.swift

Push instead of present modal the Wallet Address screen (the one with QR code) #2375

---

AlphaWallet/Tokens/Views/TextField.swift

    Make text color red in textfields in actionsheet if there are warnings/earrors while editing gas settings

---

AlphaWallet/Browser/Coordinators/QRCodeResolutionCoordinator.swift
AlphaWallet/Extensions/String.swift
AlphaWallet/Tokens/Coordinators/TokensCoordinator.swift
AlphaWallet/Tokens/Views/SegmentedControl.swift
AlphaWallet/Wallet/Coordinators/WalletCoordinator.swift
AlphaWallet/Wallet/ViewControllers/ImportWalletViewController.swift

After scanning QR code during import wallet during onboarding, switch to the appropriate tab #2354

---

AlphaWallet/Settings/Types/RPCServers.swift

Follow up to https://github.com/AlphaWallet/alpha-wallet-ios/pull/2399#issuecomment-747944899

Label Binance testnet as testnet for clarity

---

AlphaWallet/Localization/en.lproj/Localizable.strings
AlphaWallet/Tokens/ViewControllers/TokensViewController.swift
AlphaWallet/Tokens/Views/ActiveWalletSessionView.swift

Also switch to plural form (connections) when there are more than 1 session

Tweak label in cell to show WalletConnect sessions in Wallet tab

---

AlphaWallet/UI/Views/AmountTextField.swift

Send 10 tokens but only receives 1 #2408

---

AlphaWallet/AppCoordinator.swift
AlphaWallet/Core/Initializers/MigrationInitializer.swift
AlphaWallet/InCoordinator.swift
AlphaWallet/Tokens/Coordinators/SingleChainTokenCoordinator.swift

Move Realm migration from inCoordinator to Migration Initializer, to clean up it #2433

---

Podfile
Podfile.lock

Closes #2426
Tap "sign typed datav3" in https://danfinlay.github.io/js-eth-personal-sign-examples/

Support EIP712v3 in dapp browser

---

AlphaWallet/Settings/Types/ConfigExplorer.swift

Update Heco scan URL #2447

---

AlphaWallet.xcodeproj/project.pbxproj
AlphaWallet/WalletConnect/Types/RawTransactionBridge.swift
AlphaWalletTests/Factories/UnconfirmedTransaction.swift
AlphaWalletTests/Transfer/TransactionConfiguratorTransactionsTests.swift

Add test case(s) to check ERC20 send token transactions are sent to contract, and not to the recipient #2416

---

AlphaWallet/WalletConnect/Types/EIP712TypedData.swift

The "sign typed data v4" in https://danfinlay.github.io/js-eth-personal-sign-examples/

Support EIP712v4. i.e. arrays

---

AlphaWallet/AppDelegate.swift
AlphaWallet/Core/Initializers/MigrationInitializer.swift
AlphaWallet/Core/Initializers/SkipBackupFilesInitializer.swift
AlphaWallet/Extensions/Dictionary.swift
AlphaWallet/Extensions/String.swift
AlphaWallet/Tokens/Types/TokensDataStore.swift
AlphaWallet/Transactions/Coordinators/SingleChainTransactionEtherscanDataCoordinator.swift
AlphaWallet/WalletConnect/Types/EIP712TypedData.swift
fastlane/SnapshotHelper.swift

Replaced print()s with proper error handling #2429

---

AlphaWallet/Activities/Coordinators/ActivitiesCoordinator.swift
AlphaWallet/TokenScriptClient/Models/AssetAttributeValues.swift
AlphaWallet/UI/ButtonsBar.swift
AlphaWallet/WalletConnect/Coordinator/WalletConnectCoordinator.swift
AlphaWallet/WalletConnect/Coordinator/WalletConnectSessionCoordinator.swift

Resolve memory leak issue #2460

---

AlphaWallet/Accounts/Coordinators/AccountsCoordinator.swift
AlphaWallet/AlphaWalletHelp/ViewControllers/HelpContentsViewController.swift
AlphaWallet/AlphaWalletHelp/ViewControllers/HelpViewController.swift
AlphaWallet/Browser/Coordinators/QRCodeResolutionCoordinator.swift
AlphaWallet/InCoordinator.swift
AlphaWallet/Transactions/Coordinators/TokensCardCoordinator.swift
AlphaWallet/Transactions/Coordinators/TransactionCoordinator.swift
AlphaWallet/Wallet/Coordinators/InitialWalletCreationCoordinator.swift
AlphaWallet/Wallet/Coordinators/WalletCoordinator.swift
AlphaWallet/Wallet/ViewControllers/ImportWalletViewController.swift

Update view controllers to be either presented modally (still full screen) or pushed onto a navigation controller #1748

---

AlphaWallet/Core/Types/RateLimiter.swift

Fix memory Ratelimitter leak #2471

---

AlphaWallet/Extensions/UIViewController.swift
AlphaWallet/InCoordinator.swift
AlphaWallet/WalletConnect/Coordinator/WalletConnectCoordinator.swift
AlphaWallet/WalletConnect/WalletConnect+UserDefaults.swift
AlphaWallet/WalletConnect/WalletConnectServer.swift

WalletConnect doesn't work for certain TX Signing, build 3.14(370) #2462

---

AlphaWallet/InCoordinator.swift
AlphaWallet/Settings/Coordinators/SettingsCoordinator.swift
AlphaWallet/WalletConnect/Coordinator/WalletConnectCoordinator.swift
AlphaWallet/WalletConnect/WalletConnectServer.swift

Should selectively auto disconnect all WalletConnect sessions when restarting wallet #2474

---

AlphaWallet/Browser/Coordinators/DappBrowserCoordinator.swift
AlphaWallet/InCoordinator.swift
AlphaWallet/Localization/en.lproj/Localizable.strings
AlphaWallet/Localization/es.lproj/Localizable.strings
AlphaWallet/Localization/ja.lproj/Localizable.strings
AlphaWallet/Localization/ko.lproj/Localizable.strings
AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings
AlphaWallet/Settings/Types/Constants.swift
AlphaWallet/TokenScriptClient/Models/AssetDefinitionDiskBackingStore.swift
AlphaWallet/Tokens/Coordinators/SingleChainTokenCoordinator.swift
AlphaWallet/Tokens/Coordinators/TokensCoordinator.swift
AlphaWallet/Tokens/Types/TokenInstanceAction.swift
AlphaWallet/Tokens/ViewControllers/TokenInstanceViewController.swift
AlphaWallet/Tokens/ViewControllers/TokenViewController.swift
AlphaWallet/Tokens/ViewControllers/TokensCardViewController.swift
AlphaWallet/Tokens/ViewModels/TokenViewControllerViewModel.swift
AlphaWallet/Transactions/Coordinators/TokensCardCoordinator.swift
AlphaWalletTests/Settings/Coordinators/SettingsCoordinatorTests.swift

Replace xdai bridge with dapp

---

AlphaWallet/Transfer/Coordinators/SendCoordinator.swift

Fixes #2487
Screenshots of Before PR
and After PR if it's applicable (sometimes this make it much faster/easier to review):

Display pretty error for failed transaction #2487

---

AlphaWallet/Activities/Coordinators/ActivitiesCoordinator.swift
AlphaWallet/Activities/ViewControllers/ActivitiesViewController.swift
AlphaWallet/Activities/ViewControllers/ActivityViewController.swift
AlphaWallet/Tokens/ViewControllers/TokenViewController.swift
AlphaWallet/Tokens/ViewControllers/TokensViewController.swift

Navigation bar (Activity tab) #2493

---

AlphaWallet/Browser/ViewModel/Dapps.swift

Added Eporio DAPP

---

AlphaWallet.xcodeproj/project.pbxproj
AlphaWallet/Browser/Coordinators/DappBrowserCoordinator.swift
AlphaWallet/Browser/Factory/WKWebViewConfiguration.swift
AlphaWallet/Browser/Types/DappAction.swift
AlphaWallet/Browser/Types/DappCommand.swift
AlphaWallet/Browser/Types/Method.swift
AlphaWallet/EtherClient/Requests/EthCalllRequest.swift
AlphaWallet/Tokens/Views/TokenInstanceWebView.swift
Podfile
Podfile.lock

EIP1193's `request()`, including `eth_requestAccounts` (without prompting user), `eth_chainId` and `eth_call`

---

AlphaWallet/Browser/Coordinators/DappBrowserCoordinator.swift
AlphaWallet/Browser/Views/DappBrowserNavigationBar.swift
AlphaWallet/Extensions/UINavigationController.swift
AlphaWallet/Settings/Coordinators/ServersCoordinator.swift
AlphaWallet/Tokens/Coordinators/NewTokenCoordinator.swift

Push `servers` view controller instead present it modally.

---

AlphaWallet/Browser/Coordinators/ScanQRCodeCoordinator.swift

Push `RequestCoordinator` root view controller instead presend it modally

---

AlphaWallet/Transactions/Coordinators/TransactionCoordinator.swift

Push `TransactionViewController` instead present it modally

---

AlphaWallet/Browser/Coordinators/DappBrowserCoordinator.swift
AlphaWallet/Browser/ViewControllers/EditMyDappViewController.swift

Push `EditMyDappViewController` instead present it modally

---

AlphaWallet/Browser/Coordinators/DappBrowserCoordinator.swift
AlphaWallet/Browser/Factory/WKWebViewConfiguration.swift
AlphaWallet/EtherClient/Requests/EthCalllRequest.swift
Podfile
Podfile.lock

Fixes #2516 
Verify with https://app.uniswap.org/#/swap:
Before PR: the ETH balance wouldn't show up
After PR: the ETH balance shows up (so hitting the MAX button after it does works)

Fix: dapp web3 provider broken by introduction of EIP1193 support

---

AlphaWallet/InCoordinator.swift
AlphaWallet/Settings/Coordinators/ConsoleCoordinator.swift
AlphaWallet/Settings/Coordinators/SettingsCoordinator.swift
AlphaWallet/Settings/ViewControllers/ConsoleViewController.swift
AlphaWalletTests/Settings/Coordinators/SettingsCoordinatorTests.swift

Push `ConsoleViewController` instead present it modally

---

AlphaWallet/Browser/Coordinators/DappBrowserCoordinator.swift
AlphaWallet/Extensions/Data.swift
AlphaWallet/Extensions/String.swift
AlphaWallet/Transfer/ViewControllers/ConfirmSignMessageViewController.swift
AlphaWallet/Transfer/ViewModels/ConfirmSignMessageViewControllerViewModel.swift

If the message to sign is very long for personal_sign, it isn't displayed correctly #2455

---

AlphaWallet/Core/Helpers/KeyboardChecker.swift
AlphaWallet/Tokens/ViewControllers/TokensViewController.swift

Fixes #2466
before PR
after PR

Fix unexpected bottom inset which appears while resuming from background #2466

---

AlphaWallet/InCoordinator.swift
AlphaWallet/Transfer/Coordinators/PaymentCoordinator.swift
AlphaWallet/Transfer/Coordinators/RequestCoordinator.swift
AlphaWallet/Transfer/Coordinators/SendCoordinator.swift
AlphaWalletTests/Coordinators/InCoordinatorTests.swift

Push `SendViewController` instead present it modally

---

AlphaWallet/Transfer/ViewControllers/ConfirmSignMessageViewController.swift

Disable editing state for `ConfirmSignMessageViewController` for text view #2522

---

AlphaWallet/EtherClient/TransactionSigning.swift
AlphaWallet/KeyManagement/EtherKeystore.swift
AlphaWallet/Localization/en.lproj/Localizable.strings
AlphaWallet/Localization/es.lproj/Localizable.strings
AlphaWallet/Localization/ja.lproj/Localizable.strings
AlphaWallet/Localization/ko.lproj/Localizable.strings
AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings
AlphaWallet/Transactions/ViewModels/BalanceBaseViewModel.swift
AlphaWallet/Transactions/ViewModels/BalanceViewModel.swift
AlphaWallet/Transfer/Controllers/TransactionConfigurator.swift
AlphaWallet/Transfer/Coordinators/SendCoordinator.swift
AlphaWallet/Transfer/Coordinators/TransactionConfirmationCoordinator.swift
AlphaWallet/Transfer/ViewControllers/SendViewController.swift
AlphaWallet/Transfer/ViewModels/TransactionConfirmationViewModel.swift
AlphaWallet/UI/AddressTextField.swift
AlphaWallet/UI/Views/AmountTextField.swift
AlphaWalletTests/EtherClient/TransactionSigningTests.swift

Add send all funds button #2450

---

AlphaWallet/Localization/en.lproj/Localizable.strings
AlphaWallet/Localization/es.lproj/Localizable.strings
AlphaWallet/Localization/ja.lproj/Localizable.strings
AlphaWallet/Localization/ko.lproj/Localizable.strings
AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings
AlphaWallet/Transfer/ViewControllers/TransactionConfirmationViewController.swift
AlphaWallet/Transfer/ViewModels/TransactionConfirmationTableHeaderViewModel.swift
AlphaWallet/Transfer/ViewModels/TransactionConfirmationViewModel.swift
AlphaWallet/Transfer/Views/TransactionConfirmationHeaderView.swift

action sheets need to show which network I am using for the current TX #2518

---

AlphaWallet/Browser/Coordinators/DappBrowserCoordinator.swift

Fix: tapping on Swap (token) button switches to dapp browser. But if it already displays another site, it wouldn't load 1inch

---

AlphaWallet/Localization/en.lproj/Localizable.strings
AlphaWallet/Localization/es.lproj/Localizable.strings
AlphaWallet/Localization/ja.lproj/Localizable.strings
AlphaWallet/Localization/ko.lproj/Localizable.strings
AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings
AlphaWallet/Settings/Types/Constants.swift
AlphaWallet/Tokens/Coordinators/SingleChainTokenCoordinator.swift
AlphaWallet/Tokens/Types/TokenInstanceAction.swift
AlphaWallet/Tokens/ViewControllers/TokenInstanceViewController.swift
AlphaWallet/Tokens/ViewControllers/TokenViewController.swift
AlphaWallet/Tokens/ViewControllers/TokensCardViewController.swift
AlphaWallet/Tokens/ViewModels/TokenViewControllerViewModel.swift
AlphaWallet/Transactions/Coordinators/TokensCardCoordinator.swift

Support buying xdai with Ramp

---

AlphaWallet.xcodeproj/project.pbxproj
AlphaWallet/Extensions/String.swift
AlphaWallet/Localization/en.lproj/Localizable.strings
AlphaWallet/Localization/es.lproj/Localizable.strings
AlphaWallet/Localization/ja.lproj/Localizable.strings
AlphaWallet/Localization/ko.lproj/Localizable.strings
AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings
AlphaWallet/Tokens/ViewControllers/TokensViewController.swift
AlphaWallet/WalletConnect/Controllers/TransactionInProgressCoordinatorBridgeToPromise.swift
AlphaWallet/WalletConnect/Controllers/WalletConnectToSessionCoordinatorBridgeToPromise.swift
AlphaWallet/WalletConnect/Coordinator/WalletConnectCoordinator.swift
AlphaWallet/WalletConnect/Coordinator/WalletConnectSessionCoordinator.swift
AlphaWallet/WalletConnect/Coordinator/WalletConnectToSessionCoordinator.swift
AlphaWallet/WalletConnect/ViewController/WalletConnectSessionsViewController.swift
AlphaWallet/WalletConnect/ViewController/WalletConnectToSessionViewController.swift
AlphaWallet/WalletConnect/ViewModel/WalletConnectToSessionViewModel.swift
AlphaWallet/WalletConnect/WalletConnectServer.swift

Need to show WalletConnect is loading instead of not showing anything #2517

---

AlphaWallet/InCoordinator.swift

Disable update `chainstate` for disabled RPC servers #2526

---

AlphaWallet/Browser/Coordinators/DappBrowserCoordinator.swift
AlphaWallet/Browser/Types/DappAction.swift
AlphaWallet/EtherClient/EthTypedData.swift
AlphaWallet/Extensions/Data.swift
AlphaWallet/Extensions/String.swift
AlphaWallet/TokenScriptClient/Models/AssetAttributeValueUsableAsFunctionArguments.swift
AlphaWallet/Tokens/Coordinators/ClaimPaidOrderCoordinator.swift
AlphaWallet/Tokens/Views/TokenInstanceWebView.swift
AlphaWallet/Transfer/Controllers/TransactionConfigurator.swift
AlphaWallet/UI/Form/HDWallet+Extension.swift
AlphaWallet/WalletConnect/Coordinator/WalletConnectCoordinator.swift
AlphaWallet/WalletConnect/Types/EIP712TypedData.swift

Fix incorrect Data(hex: ) #2541

---

AlphaWallet.xcodeproj/project.pbxproj
AlphaWallet/Core/SwapToken/HoneySwap/HoneySwap.swift
AlphaWallet/Core/SwapToken/HoneySwap/HoneySwapERC20Token.swift
AlphaWallet/Core/SwapToken/SwapTokenService.swift
AlphaWallet/EtherClient/TrustClient/AlphaWalletService.swift
AlphaWallet/InCoordinator.swift
AlphaWallet/Localization/en.lproj/Localizable.strings
AlphaWallet/Localization/es.lproj/Localizable.strings
AlphaWallet/Localization/ja.lproj/Localizable.strings
AlphaWallet/Localization/ko.lproj/Localizable.strings
AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings
AlphaWallet/Settings/Types/Config.swift

Implement deep links for xDAI Honeyswap #2537

---

AlphaWallet/Transfer/Coordinators/TransactionConfirmationCoordinator.swift
AlphaWallet/Transfer/ViewControllers/TransactionConfirmationViewController.swift

Updates value (all funds) to send according with updated configuration #2547

---

AlphaWallet/Core/SwapToken/Oneinch/Oneinch.swift
AlphaWallet/Core/SwapToken/SwapTokenService.swift
AlphaWallet/Core/SwapToken/Uniswap/Uniswap.swift
AlphaWallet/InCoordinator.swift

Launch swap service from token to dapp browser should always switch to correct chain

---

AlphaWallet.xcodeproj/project.pbxproj
AlphaWallet/Core/Helpers/RemoteLogger.swift
AlphaWallet/Extensions/Session+PromiseKit.swift
AlphaWallet/Settings/Types/Constants+Credentials.swift
Podfile
Podfile.lock

Log RPC node error messages (to build a list to improve them later)

---

AlphaWallet/Browser/Views/DappBrowserNavigationBar.swift
AlphaWallet/Tokens/Views/TokensViewControllerTableViewSectionHeader.swift
AlphaWallet/Transfer/Views/GasSpeedTableViewHeaderView.swift

Reduce broken constraints warnings, tableHeaderView background warnings #2566

---

AlphaWallet/AppCoordinator.swift
AlphaWallet/Protection/ViewControllers/SplashViewController.swift
AlphaWallet/Wallet/Coordinators/InitialWalletCreationCoordinator.swift
AlphaWallet/Wallet/Coordinators/WalletCoordinator.swift
AlphaWallet/Wallet/Types/WalletEntryPoint.swift
AlphaWalletTests/Coordinators/AppCoordinatorTests.swift
AlphaWalletTests/Coordinators/InitialWalletCreationCoordinatorTests.swift
AlphaWalletTests/Coordinators/WalletCoordinatorTests.swift

Remove App Intro Slides #2552

---

AlphaWallet.xcodeproj/project.pbxproj
AlphaWallet/Analytics/Coordinators/AnalyticsService.swift
AlphaWallet/Analytics/Coordinators/MixpanelCoordinator.swift
AlphaWallet/Analytics/Models/AnalyticsEventPropertyValue.swift
AlphaWallet/AppCoordinator.swift
AlphaWallet/AppDelegate.swift
AlphaWalletTests/Coordinators/AppCoordinatorTests.swift
AlphaWalletTests/Coordinators/MixpanelCoordinatorTests.swift

add AnalyticsService Wrapper #2562

---

AlphaWallet/Extensions/Session+PromiseKit.swift

Tweak error logging to be more granular

---

AlphaWallet/Protection/ViewControllers/SplashViewController.swift
AlphaWalletTests/Coordinators/AppCoordinatorTests.swift

Fix currently redundant test/assert #2570

---

AlphaWallet/Browser/Coordinators/ScanQRCodeCoordinator.swift
AlphaWallet/InCoordinator.swift
AlphaWallet/Tokens/ViewControllers/TokenViewController.swift
AlphaWallet/Transfer/Coordinators/TransactionConfirmationCoordinator.swift

Easier to maintain and track after PR

Refactor: Separate out client code that logs to analytics

---

AlphaWallet/Analytics/Models/AnalyticsTypes.swift
AlphaWallet/Browser/Coordinators/DappBrowserCoordinator.swift

Log browser events

---

AlphaWallet/Browser/ViewModel/Dapps.swift

Hoping to add our dapp to the xDai browser tab on alpha wallet!
Here are our hosted logo Asset links URL/URIs for whom it applies:
SVG URI: s3://affinityharmonics/Cloud/Rare-SVG.svg
PNG URI: s3://affinityharmonics/Cloud/Rare-SVG.svg
SVG URL: https://affinityharmonics.s3.ca-central-1.amazonaws.com/Cloud/Rare-SVG.svg
PNG URL: https://affinityharmonics.s3.ca-central-1.amazonaws.com/Cloud/rare-logo-multi.png

Add" Rare Coin" to browser list ios

---

AlphaWallet/Settings/Types/ServiceProvider.swift
AlphaWallet/Settings/ViewControllers/SupportViewController.swift
AlphaWallet/Settings/ViewModels/SupportViewModel.swift

Deeplink FAQ from the Settings to AlphaWallet.com/faq #2583

---

AlphaWallet/Market/Coordinators/UniversalLinkCoordinator.swift
AlphaWallet/Tokens/Coordinators/GetBlockTimestampCoordinator.swift
Podfile
Podfile.lock

Fix web3swift memory leaks #2584

---

AlphaWallet.xcodeproj/project.pbxproj
AlphaWallet/Core/BuyToken/BuyTokenService.swift
AlphaWallet/Core/BuyToken/Ramp/Ramp.swift
AlphaWallet/Core/Coordinators/FilterTokensCoordinator.swift
AlphaWallet/Core/SwapToken/HoneySwap/HoneySwap.swift
AlphaWallet/Core/SwapToken/Oneinch/Oneinch.swift
AlphaWallet/Core/SwapToken/SwapTokenService.swift
AlphaWallet/Core/SwapToken/Uniswap/Uniswap.swift
AlphaWallet/EtherClient/TrustClient/AlphaWalletService.swift
AlphaWallet/InCoordinator.swift
AlphaWallet/Settings/Types/Constants.swift
AlphaWallet/Tokens/Coordinators/SingleChainTokenCoordinator.swift
AlphaWallet/Tokens/Coordinators/TokensCoordinator.swift
AlphaWallet/Tokens/Types/TokenInstanceAction.swift
AlphaWallet/Tokens/ViewControllers/TokenInstanceViewController.swift
AlphaWallet/Tokens/ViewControllers/TokenViewController.swift
AlphaWallet/Tokens/ViewControllers/TokensCardViewController.swift
AlphaWallet/Tokens/ViewModels/TokenViewControllerViewModel.swift
AlphaWallet/Transactions/Coordinators/TokensCardCoordinator.swift
AlphaWalletTests/Coordinators/TokensCoordinatorTests.swift
AlphaWalletTests/Factories/FakeTokensDataStore.swift
AlphaWalletTests/Settings/ConfigTests.swift

Make Ramp (by crypto with fiat) available for other tokens #2587

---

AlphaWallet/InCoordinator.swift
AlphaWallet/Tokens/Coordinators/SingleChainTokenCoordinator.swift

Sometimes crashes when disabling a chain in Settings #2597

---

AlphaWallet/Tokens/Coordinators/SingleChainTokenCoordinator.swift
AlphaWallet/Tokens/ViewControllers/TokenViewController.swift

TokenViewController is not released after popping #2595

---

AlphaWallet/WalletConnect/WalletConnectServer.swift

WalletConnect memory leaks #2602

---

AlphaWallet/InCoordinator.swift
AlphaWallet/Tokens/Coordinators/SingleChainTokenCoordinator.swift
AlphaWallet/Tokens/Coordinators/TokensCoordinator.swift

Reduce TransactionsStorage instances #2605

---

AlphaWallet/TokenScriptClient/Models/AssetAttributeValues.swift

Fixes #2610 
This PR introduces a memory leak. Add a TODO to fix in the future.

Fix: TokenScript attributes are not resolved

---

AlphaWallet.xcodeproj/project.pbxproj
AlphaWallet/AppCoordinator.swift
AlphaWallet/Core/Coordinators/ServerUnavailableCoordinator.swift
AlphaWallet/Extensions/UIViewController.swift
AlphaWallet/Localization/en.lproj/Localizable.strings
AlphaWallet/Localization/es.lproj/Localizable.strings
AlphaWallet/Localization/ja.lproj/Localizable.strings
AlphaWallet/Localization/ko.lproj/Localizable.strings
AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings
AlphaWallet/Market/Coordinators/UniversalLinkCoordinator.swift
AlphaWallet/Settings/Types/Constants.swift

WalletConnect using mobile linking crashes if the chain is disabled #2609

---

AlphaWallet/Activities/Coordinators/ActivitiesCoordinator.swift
AlphaWallet/Transactions/Coordinators/SingleChainTransactionEtherscanDataCoordinator.swift
AlphaWallet/Transactions/Storage/TransactionsStorage.swift

Similar problem to BC, but with added complexity due to an optimisation in the `Activity` tab to not refresh unnecessarily.

Fix: pending transactions in Activity tab was not transitioning to completed even when the state change has been detected

---

AlphaWallet/AppCoordinator.swift
AlphaWallet/Browser/Coordinators/DappBrowserCoordinator.swift
AlphaWallet/Browser/ViewControllers/BrowserViewController.swift
AlphaWallet/InCoordinator.swift
AlphaWallet/Share/ShareContentAction.swift
AlphaWallet/Share/UrlSchemeCoordinator.swift

Might also be useful if we need to use custom URL scheme for #2621

Support awallet: custom URL scheme for just switching to app and doing nothing else

---

AlphaWallet/Activities/Coordinators/ActivitiesCoordinator.swift
AlphaWallet/Activities/ViewControllers/ActivityViewController.swift
AlphaWallet/Activities/Views/ActivityViewCell.swift
AlphaWallet/Analytics/Models/AnalyticsTypes.swift
AlphaWallet/AppCoordinator.swift
AlphaWallet/Browser/Coordinators/DappBrowserCoordinator.swift
AlphaWallet/InCoordinator.swift
AlphaWallet/Market/Coordinators/UniversalLinkCoordinator.swift
AlphaWallet/Market/ViewControllers/ImportMagicTokenViewController.swift
AlphaWallet/Redeem/ViewControllers/RedeemTokenCardQuantitySelectionViewController.swift
AlphaWallet/Redeem/ViewControllers/TokenCardRedemptionViewController.swift
AlphaWallet/Sell/ViewControllers/EnterSellTokensCardPriceQuantityViewController.swift
AlphaWallet/Sell/ViewControllers/SetSellTokensCardExpiryDateViewController.swift
AlphaWallet/Tokens/Coordinators/SingleChainTokenCoordinator.swift
AlphaWallet/Tokens/ViewControllers/TokenInstanceActionViewController.swift
AlphaWallet/Tokens/ViewControllers/TokenInstanceViewController.swift
AlphaWallet/Tokens/ViewControllers/TokensCardViewController.swift
AlphaWallet/Tokens/Views/TokenInstanceWebView.swift
AlphaWallet/Transactions/Coordinators/TokensCardCoordinator.swift
AlphaWallet/Transfer/Coordinators/SignMessageCoordinator.swift
AlphaWallet/Transfer/ViewControllers/ChooseTokenCardTransferModeViewController.swift
AlphaWallet/Transfer/ViewControllers/SetTransferTokensCardExpiryDateViewController.swift
AlphaWallet/Transfer/ViewControllers/TransferTokensCardQuantitySelectionViewController.swift
AlphaWallet/Transfer/ViewControllers/TransferTokensCardViaWalletAddressViewController.swift
AlphaWallet/UI/Views/TokenCardRowView.swift
AlphaWallet/WalletConnect/Controllers/SignMessageCoordinatorBridgeToPromise.swift
AlphaWallet/WalletConnect/Coordinator/WalletConnectCoordinator.swift

Log sign messages

---

AlphaWallet/Settings/Coordinators/ServersCoordinator.swift
AlphaWallet/WalletConnect/Coordinator/WalletConnectCoordinator.swift
AlphaWallet/WalletConnect/Coordinator/WalletConnectToSessionCoordinator.swift
AlphaWallet/WalletConnect/ViewController/WalletConnectToSessionViewController.swift

Closes #2644, Closes #2643, Fixes #2642

Closes wallet connect issues

---

AlphaWallet/Analytics/Models/AnalyticsTypes.swift
AlphaWallet/Settings/Coordinators/ServersCoordinator.swift
AlphaWallet/WalletConnect/Controllers/WalletConnectToSessionCoordinatorBridgeToPromise.swift
AlphaWallet/WalletConnect/Coordinator/WalletConnectCoordinator.swift
AlphaWallet/WalletConnect/Coordinator/WalletConnectSessionCoordinator.swift
AlphaWallet/WalletConnect/Coordinator/WalletConnectToSessionCoordinator.swift

Log to analytics WalletConnect

---

AlphaWallet/Localization/en.lproj/Localizable.strings
AlphaWallet/Localization/es.lproj/Localizable.strings
AlphaWallet/Localization/ja.lproj/Localizable.strings
AlphaWallet/Localization/ko.lproj/Localizable.strings
AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings

Tweak back up seed phrase introduction copy #2649

---

AlphaWallet/Core/Features.swift
AlphaWallet/Foundation/EtherNumberFormatter.swift
AlphaWallet/Foundation/StringFormatter.swift
AlphaWallet/Transactions/Storage/Session.swift
AlphaWallet/Transfer/Coordinators/SendCoordinator.swift
AlphaWallet/Transfer/Coordinators/TransactionConfirmationCoordinator.swift
AlphaWallet/Transfer/ViewControllers/SendViewController.swift
AlphaWallet/Transfer/ViewModels/SendViewModel.swift
AlphaWallet/Transfer/ViewModels/TransactionConfirmationViewModel.swift
AlphaWallet/UI/Views/AmountTextField.swift

build3.17（381）send "All Fund" will add "," in numbers which breaks the send function #2590

---

AlphaWallet/AppCoordinator.swift
AlphaWallet/WalletConnect/Controllers/WalletConnectToSessionCoordinatorBridgeToPromise.swift
AlphaWallet/WalletConnect/Coordinator/WalletConnectCoordinator.swift
AlphaWallet/WalletConnect/Coordinator/WalletConnectToSessionCoordinator.swift

Show error message if dapp selects a chain for WalletConnect that is disabled in the app #2652

---

AlphaWallet.xcodeproj/project.pbxproj
AlphaWallet/Activities/ViewModels/DefaultActivityCellViewModel.swift
AlphaWallet/Activities/Views/DefaultActivityItemViewCell.swift
AlphaWallet/Assets.xcassets/azure_sending.colorset/Contents.json
AlphaWallet/Assets.xcassets/loadingBackground.colorset/Contents.json
AlphaWallet/Core/Views/LoadingIndicatorView.swift
AlphaWallet/Transfer/Views/ActivityIndicatorControl.swift

Improve Pending Transaction icon & Background in Activity tab #2650

---

AlphaWallet.xcodeproj/project.pbxproj
AlphaWallet/Extensions/String.swift
AlphaWallet/Foundation/DecimalFormatter.swift
AlphaWallet/Foundation/EtherNumberFormatter.swift
AlphaWallet/InCoordinator.swift
AlphaWallet/Settings/Types/AppLocale.swift
AlphaWallet/Settings/Types/Config.swift
AlphaWallet/Transactions/Coordinators/BalanceCoordinator.swift
AlphaWallet/Transactions/Storage/Session.swift
AlphaWallet/Transfer/ViewControllers/SendViewController.swift
AlphaWallet/UI/Views/AmountTextField.swift
AlphaWalletTests/Factories/WalletSession.swift
AlphaWalletTests/Settings/Coordinators/SettingsCoordinatorTests.swift
AlphaWalletTests/Transfer/ViewControllers/SendViewControllerTests.swift

Add test case to check AmountTextField displays correctly formatted string #2612

---

AlphaWallet/Settings/Coordinators/EnabledServersCoordinator.swift
AlphaWallet/Settings/ViewControllers/EnabledServersViewController.swift

Remove "Save" button from Select Active Networks #2660

---

AlphaWallet/Settings/Coordinators/SettingsCoordinator.swift
AlphaWallet/Settings/ViewControllers/AdvancedSettingsViewController.swift
AlphaWallet/Settings/ViewControllers/SettingsViewController.swift
AlphaWallet/Settings/ViewModels/AdvancedSettingsViewModel.swift
AlphaWallet/Settings/ViewModels/SettingsViewModel.swift

Move TaiChi option to advanced settings section #2658

---

AlphaWallet/Settings/Types/Config.swift
AlphaWallet/Transfer/ViewControllers/SendViewController.swift
AlphaWallet/Transfer/ViewModels/TransactionConfirmationViewModel.swift
AlphaWalletTests/Transfer/ViewControllers/SendViewControllerTests.swift

Wrong amount in Send actionsheet #2661

---

AlphaWallet/Info.plist

Fix: crash when taking a video during KYC for ramp.network

---

AlphaWallet/Activities/Views/ActivityStateView.swift

Remove animation when ActivityLoadingIndicatorView is hidden #2699

---

Podfile
Podfile.lock

Crash in web3swift's Dictionary.subscript.getter according to Xcode. Can't be sure what's the cause though.

Attempt to fix crash in web3swift

---

AlphaWallet/EtherClient/TrustClient/Models/RawTransaction.swift

improve TransactionInstance creation #2707

---

AlphaWallet/Core/BuyToken/Ramp/Ramp.swift
AlphaWallet/Core/SwapToken/Oneinch/Oneinch.swift

Log errors accessing Ramp and Oneinch remotely

---

AlphaWallet/Analytics/Models/AnalyticsTypes.swift
AlphaWallet/Transfer/Coordinators/TransactionConfirmationCoordinator.swift

* Log use of 'All Funds'
* Log when user taps button to attempt to rectify send transaction error

Add analytics

---

AlphaWallet.xcodeproj/project.pbxproj
AlphaWallet/Core/ViewControllers/PromptViewController.swift
AlphaWallet/Core/ViewModels/PromptViewModel.swift
AlphaWallet/Localization/en.lproj/Localizable.strings
AlphaWallet/Localization/es.lproj/Localizable.strings
AlphaWallet/Localization/ja.lproj/Localizable.strings
AlphaWallet/Localization/ko.lproj/Localizable.strings
AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings
AlphaWallet/Settings/Types/Constants.swift
AlphaWallet/Settings/ViewControllers/EnabledServersViewController.swift
AlphaWallet/Settings/ViewModels/EnabledServersViewModel.swift
AlphaWallet/Settings/Views/EnableServersHeaderView.swift

Closes #2710 
This is to prevent users from confusing them and hopefully lessen the possibility of users being scammed by thinking tesetnet balances have non-zero fiat value.

Make enabling testnets and mainnets be exclusive

---

AlphaWallet/UI/TokenObject+UI.swift

Closes #2680 
Fallback to the other repo if image isn't found

Use our own token image repo for all chains instead of just for testnets

---

AlphaWallet/Accounts/ViewControllers/AccountsViewController.swift

Project compilation issue #2767

---

AlphaWallet/Localization/en.lproj/Localizable.strings
AlphaWallet/Localization/es.lproj/Localizable.strings
AlphaWallet/Localization/ja.lproj/Localizable.strings
AlphaWallet/Localization/ko.lproj/Localizable.strings
AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings
AlphaWallet/Settings/Types/RPCServers.swift

Make it explict that Binance is BSC #2780

---

AlphaWallet/Core/SwapToken/Oneinch/Oneinch.swift

Move oneinchs execution to background queue #2787

---

AlphaWallet/Style/AppStyle.swift
AlphaWallet/Transfer/ViewControllers/SendViewController.swift
AlphaWallet/UI/AddressTextField.swift

Pasting something into AddressTextField should clear error state displayed if it's not an error #2781

---

AlphaWallet/AppCoordinator.swift
AlphaWallet/InCoordinator.swift
AlphaWallet/Transfer/Coordinators/PaymentCoordinator.swift
AlphaWallet/Transfer/Coordinators/RequestCoordinator.swift
AlphaWallet/Transfer/Coordinators/SendCoordinator.swift
AlphaWalletTests/Coordinators/InCoordinatorTests.swift

Improve presenting payment coordinator #2785

---

.travis.yml

More updated. Related to: https://github.com/AlphaWallet/alpha-wallet-ios/pull/2791#issuecomment-846842795

Make Travis use Xcode 12.5, was 12.4

---

AlphaWallet/Transfer/Coordinators/TransactionConfirmationCoordinator.swift

Prompt user to rate app after sending a transaction successfully

---

AlphaWallet/Browser/ViewModel/Dapps.swift

Add dapp Levinswap to index

---

AlphaWallet/Tokens/ViewControllers/AddHideTokensViewController.swift
AlphaWallet/Tokens/ViewControllers/SelectAssetViewController.swift
AlphaWallet/Tokens/ViewControllers/TokensViewController.swift
AlphaWallet/Tokens/ViewModels/EthTokenViewCellViewModel.swift
AlphaWallet/Tokens/ViewModels/FungibleTokenViewCellViewModel.swift
AlphaWallet/Tokens/ViewModels/NonFungibleTokenViewCellViewModel.swift
AlphaWallet/Tokens/Views/EthTokenViewCell.swift
AlphaWallet/Tokens/Views/FungibleTokenViewCell.swift
AlphaWallet/Tokens/Views/NonFungibleTokenViewCell.swift

[Samoa] Modify Wallet tab cells look and feel (no group/section) #2754

---

AlphaWallet/Tokens/Views/TokenCardsViewControllerHeader.swift

The title label in the screen showing a non-fungible screen should have a maximum width #2814

---

AlphaWallet/Tokens/ViewModels/EthTokenViewCellViewModel.swift
AlphaWallet/Tokens/Views/EthTokenViewCell.swift
AlphaWallet/Tokens/Views/FungibleTokenViewCell.swift

Should not display fiat value for non-mainnets tokens #2811

---

AlphaWallet/Settings/Types/RPCServers.swift

The `?` delimiting the query string was wrongly encoded as `%3F`.
Expect:
> https://api-cn.etherscan.com/api/%3Fmodule=account&...
Observed:
> https://api-cn.etherscan.com/api?module=account&...

Fix: fetching transactions is broken because URLs are not formed correctly

---

AlphaWallet/Tokens/ViewModels/TokensViewModel.swift

Remove spurious tokens from Wallet tab

---

AlphaWallet/Analytics/Models/AnalyticsTypes.swift
AlphaWallet/AppCoordinator.swift
AlphaWallet/Wallet/Coordinators/WalletCoordinator.swift

Log when these 3 buttons are tapped (so if the user changes their mind and choose are different tab after they chose import/watch, it wouldn't be accurate).

Log what is the first action (create, import, watch wallet) for new installs

---

AlphaWallet/Core/BuyToken/Ramp/Ramp.swift
AlphaWallet/Core/CoinTicker/CoinTickersFetcher.swift
AlphaWallet/Core/DomainResolver.swift
AlphaWallet/Core/SwapToken/HoneySwap/HoneySwap.swift
AlphaWallet/Core/SwapToken/Oneinch/Oneinch.swift
AlphaWallet/Core/SwapToken/Uniswap/UniswapERC20Token.swift
AlphaWallet/EtherClient/OpenSea.swift
AlphaWallet/EtherClient/TrustClient/AlphaWalletService.swift
AlphaWallet/InCoordinator.swift
AlphaWallet/Localization/en.lproj/Localizable.strings
AlphaWallet/Market/Coordinators/UniversalLinkCoordinator.swift
AlphaWallet/Settings/Coordinators/ServersCoordinator.swift
AlphaWallet/Settings/Types/ConfigExplorer.swift
AlphaWallet/Settings/Types/Constants.swift
AlphaWallet/Settings/Types/RPCServers.swift
AlphaWallet/Tokens/Coordinators/GetContractInteractions.swift
AlphaWallet/Tokens/Coordinators/SingleChainTokenCoordinator.swift
AlphaWallet/Tokens/Types/TokenCollection.swift
AlphaWallet/Tokens/ViewModels/TokenViewControllerViewModel.swift
AlphaWallet/Transactions/Coordinators/SingleChainTransactionEtherscanDataCoordinator.swift
AlphaWallet/Transfer/Controllers/TransactionConfigurator.swift
AlphaWallet/Transfer/Coordinators/SendTransactionCoordinator.swift

Closes #2792
After #2838 is merged as it contains commits from it.

Add Optimistic and Optimistic Kovan chains

---

AlphaWallet/Settings/Types/Constants.swift

Enable Polgyon chain by default

---

AlphaWallet/Core/BuyToken/BuyTokenService.swift
AlphaWallet/Core/BuyToken/Ramp/Ramp.swift
AlphaWallet/Core/Coordinators/FilterTokensCoordinator.swift
AlphaWallet/Core/SwapToken/HoneySwap/HoneySwap.swift
AlphaWallet/Core/SwapToken/Oneinch/Oneinch.swift
AlphaWallet/Core/SwapToken/SwapTokenService.swift
AlphaWallet/Core/SwapToken/Uniswap/Uniswap.swift
AlphaWallet/Core/SwapToken/Uniswap/UniswapERC20Token.swift
AlphaWallet/Tokens/ViewControllers/TokenViewController.swift
AlphaWallet/Tokens/ViewModels/TokenViewControllerViewModel.swift
AlphaWallet/Transfer/Coordinators/TransactionConfirmationCoordinator.swift

Replace using TokenObject with TokenActionsServiceKey

---

AlphaWallet/Core/BuyToken/Ramp/Ramp.swift

Move ramp execution to background queue #2862

---

AlphaWallet/InCoordinator.swift
AlphaWallet/Transactions/Coordinators/SingleChainTransactionEtherscanDataCoordinator.swift
AlphaWalletTests/Coordinators/AppCoordinatorTests.swift
AlphaWalletTests/Coordinators/InCoordinatorTests.swift
AlphaWalletTests/Coordinators/TokensCoordinatorTests.swift
AlphaWalletTests/Settings/Coordinators/SettingsCoordinatorTests.swift

Tests broken #2818

---

AlphaWallet/AppCoordinator.swift

Fix adding incorrect coordinator while changing wallets #2869

---

AlphaWallet/Style/AppStyle.swift
AlphaWallet/Tokens/Types/TokenObject.swift
AlphaWallet/Tokens/ViewModels/EthCurrencyHelper.swift
AlphaWallet/Tokens/ViewModels/EthTokenViewCellViewModel.swift
AlphaWallet/Tokens/ViewModels/FungibleTokenViewCellViewModel.swift
AlphaWallet/Tokens/Views/EthTokenViewCell.swift
AlphaWallet/Tokens/Views/FungibleTokenViewCell.swift

Tweak Wallet tab price display #2864

---

AlphaWallet/InCoordinator.swift

Reduce realm instances creation in incordinator #2875

---

AlphaWallet/Localization/en.lproj/Localizable.strings
AlphaWallet/Localization/es.lproj/Localizable.strings
AlphaWallet/Localization/ja.lproj/Localizable.strings
AlphaWallet/Localization/ko.lproj/Localizable.strings
AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings
AlphaWallet/Tokens/ViewControllers/AddHideTokensViewController.swift

Clean up comments from AddHideTokensViewController #2886

---

AlphaWallet/Accounts/Coordinators/AccountsCoordinator.swift
AlphaWallet/Assets.xcassets/add_hide_tokens.imageset/Contents.json
AlphaWallet/Assets.xcassets/iconsSystemPlus.imageset/Contents.json
AlphaWallet/Browser/Coordinators/ScanQRCodeCoordinator.swift
AlphaWallet/Tokens/ViewControllers/AddHideTokensViewController.swift
AlphaWallet/Transfer/ViewControllers/TransactionConfirmationViewController.swift

tweak add button in navigation bur #2885

---

AlphaWallet.xcodeproj/project.pbxproj
AlphaWallet/Core/CoinTicker/CoinTickersFetcher.swift
AlphaWallet/Core/CoinTicker/CoinTickersFetcherCache.swift
AlphaWallet/Tokens/Types/AddressAndRPCServer.swift
AlphaWallet/Tokens/Types/ChartHistory.swift

add coin ticker file caching #2882

---

AlphaWallet/EtherClient/OpenSea.swift
AlphaWallet/Tokens/Coordinators/GetContractInteractions.swift

Fix ERC721 balance fetching

---

AlphaWallet.xcodeproj/project.pbxproj
AlphaWallet/Extensions/URL.swift
AlphaWallet/Tokens/Types/TokensDataStore.swift
AlphaWallet/Tokens/Views/OpenSea/WebImageView.swift

Otherwise the ERC721 images that are ipfs: aren't displayed in the app

Access ipfs: URLs via https://ipfs.io for ERC721 meta JSON uri and images in them

---

AlphaWallet/Activities/Coordinators/ActivitiesCoordinator.swift

Closes #2903. Ref #2902 
FYI @JamesSmartCell

Replace all "Swap" in Activity tab with "Contract Execution" because heuristics was bad

---

AlphaWallet/Tokens/Views/OpenSea/OpenSeaNonFungibleTokenCardRowView.swift
AlphaWallet/Tokens/Views/OpenSea/OpenSeaNonFungibleTokenViewCell.swift
AlphaWallet/Tokens/Views/OpenSea/WebImageView.swift

Contains commits from #2905
-|-

Fix: NFT SVG display

---

AlphaWallet/Browser/Coordinators/DappRequestSwitchCustomChainCoordinator.swift
AlphaWallet/Settings/Models/AddCustomChain.swift

Show error message to user when dapp uses EIP3085 to add a chain and the blockchain explorer root is invalid (or down)

---

AlphaWallet/Analytics/Models/AnalyticsTypes.swift
AlphaWallet/InCoordinator.swift

To see if we ought to support it.

Log analytics: user's Dynamic Type setting

---

AlphaWallet/Settings/Types/RPCServers.swift

Fewer switch statements to edit when adding built-in chains.

Simplify code. Easier maintenance

---

AlphaWallet/Settings/Types/RPCServers.swift

Fix: blockchain explorer endpoint for xDai. So no transactions were downloaded and token auto detection was broken

---

AlphaWallet.xcodeproj/project.pbxproj
AlphaWallet/Extensions/URL.swift
AlphaWalletTests/Extensions/URLTests.swift

Map both:
```
ipfs://ipfs/QmbZzG343A7JGmHGwnrv3wimHYkB98azcBH1ojzWmVeDty
ipfs://QmbZzG343A7JGmHGwnrv3wimHYkB98azcBH1ojzWmVeDty
```
to:
```
https://ipfs.io/ipfs/QmbZzG343A7JGmHGwnrv3wimHYkB98azcBH1ojzWmVeDty
```

Improve ipfs: URL rewriting to be more forgiving

---

AlphaWallet/Settings/Types/RPCServers.swift

Based on:
* https://docs.binance.org/smart-chain/developer/rpc.html
* https://www.xdaichain.com/for-developers/developer-resources

Update Binance and xDai RPC server nodes to recommended ones

---

AlphaWallet/Activities/Coordinators/ActivitiesCoordinator.swift
AlphaWallet/Activities/ViewControllers/ActivitiesViewController.swift

Cautious to not move for moving sake. Might want to refactor or re-write parts of this or especially the related logic parts later.

Refactor: move code that doesn't mutate state

---

AlphaWallet/Core/BuyToken/Ramp/Ramp.swift
AlphaWallet/Core/CoinTicker/CoinTickersFetcher.swift
AlphaWallet/Core/DomainResolver.swift
AlphaWallet/Core/SwapToken/HoneySwap/HoneySwap.swift
AlphaWallet/Core/SwapToken/Oneinch/Oneinch.swift
AlphaWallet/Core/SwapToken/Uniswap/UniswapERC20Token.swift
AlphaWallet/EtherClient/OpenSea.swift
AlphaWallet/EtherClient/TrustClient/AlphaWalletService.swift
AlphaWallet/Localization/en.lproj/Localizable.strings
AlphaWallet/Localization/es.lproj/Localizable.strings
AlphaWallet/Localization/ja.lproj/Localizable.strings
AlphaWallet/Localization/ko.lproj/Localizable.strings
AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings
AlphaWallet/Market/Coordinators/UniversalLinkCoordinator.swift
AlphaWallet/Settings/Coordinators/ServersCoordinator.swift
AlphaWallet/Settings/Types/ConfigExplorer.swift
AlphaWallet/Settings/Types/Constants.swift
AlphaWallet/Settings/Types/RPCServers.swift
AlphaWallet/Tokens/Coordinators/SingleChainTokenCoordinator.swift
AlphaWallet/Tokens/Types/TokenCollection.swift
AlphaWallet/Tokens/ViewModels/TokenViewControllerViewModel.swift
AlphaWallet/Transactions/Coordinators/SingleChainTransactionEtherscanDataCoordinator.swift
AlphaWallet/Transfer/Controllers/TransactionConfigurator.swift
AlphaWallet/Transfer/Coordinators/SendTransactionCoordinator.swift

Add support for Cronos testnet

---

AlphaWallet.xcodeproj/project.pbxproj
AlphaWallet/AlphaWalletHelp/Views/ContactUsBannerView.swift
AlphaWallet/Core/Helpers/DeviceModel.swift
AlphaWallet/Extensions/UIDevice.swift

Fix: https://github.com/AlphaWallet/alpha-wallet-ios/issues/992

Support email doesn't include i os device model #992

---

AlphaWalletTests/Settings/RPCServerTests.swift

Add test case for `RPCServer.displayOrderPriority`

---

AlphaWallet/Tokens/ViewControllers/AddHideTokensViewController.swift
AlphaWallet/Tokens/ViewModels/AddHideTokensViewModel.swift

Crash when tap to show a Hidden Token in Add / Hide Tokens screen #2933

---

AlphaWallet.xcodeproj/project.pbxproj
AlphaWallet/Browser/Coordinators/ScanQRCodeCoordinator.swift
AlphaWallet/Extensions/UIBarButtonItem.swift
AlphaWallet/Settings/ViewControllers/EnabledServersViewController.swift
AlphaWallet/Settings/ViewControllers/ServersViewController.swift
AlphaWallet/Settings/ViewModels/ServerViewModel.swift
AlphaWallet/Settings/Views/ServerViewCell.swift
AlphaWallet/Tokens/ViewControllers/TokensViewController.swift
AlphaWallet/Tokens/ViewModels/TokensViewModel.swift
AlphaWallet/Transfer/ViewControllers/ConfigureTransactionViewController.swift

Group tokens by chain in Wallet tab #2957

---

AlphaWallet/Accounts/Coordinators/AccountsCoordinator.swift
AlphaWallet/AppCoordinator.swift
AlphaWallet/AppDelegate.swift
AlphaWallet/Core/Coordinators/WalletBalance/WalletBalanceFetcher.swift
AlphaWallet/InCoordinator.swift
AlphaWallet/Settings/Coordinators/SettingsCoordinator.swift
AlphaWallet/Tokens/Types/TokenObject.swift
AlphaWallet/Transactions/Storage/Session.swift
AlphaWallet/Transactions/Storage/TransactionsStorage.swift
AlphaWallet/Transactions/Types/TransactionsTracker.swift

Swipe to show swipe menu not working in Wallets screen opened from Wallet tab #2916

---

AlphaWallet/Settings/ViewControllers/AddRPCServerViewController.swift
AlphaWallet/Tokens/ViewControllers/NewTokenViewController.swift
AlphaWallet/Tokens/ViewModels/NewTokenViewModel.swift

Update the design of Add Custom Token #2995

---

AlphaWallet/Style/AppStyle.swift
AlphaWallet/Wallet/ViewControllers/ShowSeedPhraseIntroductionViewController.swift

Improve the alignment of the graphic and text on the Seed Phrase intro screen #2986

---

AlphaWallet/Settings/ViewControllers/AdvancedSettingsViewController.swift
AlphaWallet/Settings/ViewControllers/ConsoleViewController.swift
AlphaWallet/Settings/ViewControllers/ServersViewController.swift
AlphaWallet/Settings/ViewControllers/SettingsViewController.swift
AlphaWallet/Settings/ViewControllers/SupportViewController.swift
AlphaWallet/UI/RoundedBackground.swift

Add some extra space below the Testnet button #2997

---

AlphaWallet/Tokens/Views/TextField.swift
AlphaWallet/UI/Views/TextView.swift
AlphaWallet/Wallet/ViewControllers/ImportWalletViewController.swift

Add a paste button for importing private key and keystore JSON #2815

---

AlphaWallet/Transactions/ViewModels/TransactionViewModel.swift

Fix: single transaction screens not taking decimals into account when displaying transaction value. Activity screen does

---

AlphaWallet/AppCoordinator.swift
AlphaWallet/InCoordinator.swift
AlphaWallet/Settings/Coordinators/SettingsCoordinator.swift
AlphaWallet/Transactions/Storage/TransactionsStorage.swift
AlphaWallet/Transactions/Types/TransactionsTracker.swift

Move `deleteAllTransactions, resetFetchingState` functions from immutable definition #3015

---

AlphaWallet/Settings/Types/RPCServers.swift
AlphaWallet/Transfer/Controllers/TransactionConfigurator.swift
AlphaWallet/Transfer/ViewControllers/TransactionConfirmationViewController.swift
AlphaWallet/Transfer/ViewModels/TransactionConfirmationViewModel.swift

Part of #2979 
Based on:
* https://community.optimism.io/docs/users/fees.html
* https://community.optimism.io/docs/developers/fees.html

Fix: Users should not be allowed to change the gas price and limit on Optimistic chains

---

AlphaWallet/Analytics/Models/AnalyticsTypes.swift
AlphaWallet/InCoordinator.swift
AlphaWallet/Settings/Coordinators/HelpUsCoordinator.swift
AlphaWallet/Transfer/Coordinators/TransactionConfirmationCoordinator.swift

Log analytics user's choice when prompted to subscribe to email newsletter

---

AlphaWallet/TokenScriptClient/Coordinators/EventSourceCoordinator.swift

It doesn't happen immediately since this particular instance is only triggered after event fetching is done (while could take a while) might be the cause of #3011

Fix: Realm crash because: "Realm accessed from incorrect thread."

---

AlphaWallet/UI/Views/TextView.swift
AlphaWallet/Wallet/ViewControllers/ImportWalletViewController.swift

After tapping Paste button to paste privacy key for importing, Import button should be enabled #3030

---

AlphaWallet/Wallet/ViewControllers/SeedPhraseBackupIntroductionViewController.swift

Improve the alignment of the graphic and text on the Backup intro screen #2985

---

AlphaWallet/Wallet/ViewControllers/ImportWalletViewController.swift

Watching an invalid Ethereum address should not crash #3029

---

AlphaWallet.xcodeproj/project.pbxproj
AlphaWallet/AppDelegate.swift
AlphaWallet/Core/Ethereum/ABI/DecodedFunctionCall+Decode.swift
AlphaWalletTests/Core/Ethereum/ABI/DecodedFunctionCall+DecodeTests.swift

Fix: crash in transaction data decoding

---

AlphaWallet.xcodeproj/project.pbxproj
AlphaWallet/Core/SwapToken/QuickSwap/QuickSwap.swift
AlphaWallet/InCoordinator.swift
AlphaWallet/Localization/en.lproj/Localizable.strings
AlphaWallet/Localization/es.lproj/Localizable.strings
AlphaWallet/Localization/ja.lproj/Localizable.strings
AlphaWallet/Localization/ko.lproj/Localizable.strings
AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings

Add Custom Linking to Quickswap for tokens on Polygon #2808

---

AlphaWallet/Activities/ViewModels/ActivitiesViewModel.swift

Fix sorting activities by dates #3042

---

AlphaWallet/Activities/ViewModels/ActivitiesViewModel.swift

Crash when fetching events #3046

---

AlphaWallet/Activities/ViewModels/ActivitiesViewModel.swift

Apply approach in #3043 again #3052

---

AlphaWallet/InCoordinator.swift
AlphaWallet/Tokens/Coordinators/SingleChainTokenCoordinator.swift
AlphaWallet/Tokens/Coordinators/TokensCoordinator.swift
AlphaWallet/Tokens/ViewControllers/TokenViewController.swift

Tapping send button doesn't work in TokenViewController presented from activities list #3056

---

AlphaWallet/Activities/Views/ActivityStateView.swift
AlphaWallet/Activities/Views/DefaultActivityItemViewCell.swift

Animation stops while scrolling cell for view ActivityStateView #3058

---

AlphaWallet/Browser/Coordinators/DappBrowserCoordinator.swift
AlphaWallet/InCoordinator.swift
AlphaWallet/Tokens/Coordinators/ClaimPaidOrderCoordinator.swift
AlphaWallet/Tokens/Coordinators/SingleChainTokenCoordinator.swift
AlphaWallet/Transactions/Coordinators/ReplaceTransactionCoordinator.swift
AlphaWallet/Transactions/Coordinators/TokensCardCoordinator.swift
AlphaWallet/Transactions/Coordinators/TransactionDataCoordinator.swift
AlphaWallet/Transfer/Coordinators/PaymentCoordinator.swift
AlphaWallet/Transfer/Coordinators/SendCoordinator.swift
AlphaWallet/Transfer/Coordinators/TransactionConfirmationCoordinator.swift
AlphaWallet/Transfer/Coordinators/TransferNFTCoordinator.swift
AlphaWallet/WalletConnect/Controllers/TransactionConfirmationCoordinatorBridgeToPromise.swift
AlphaWallet/WalletConnect/Coordinator/WalletConnectCoordinator.swift

Improve adding transaction to db, remove `waiting for closing ui screens` #3061

---

AlphaWallet/InCoordinator.swift
AlphaWallet/Tokens/Types/TokenCollection.swift
AlphaWallet/Tokens/Types/TokensDataStore.swift
AlphaWalletTests/Factories/FakeTokensDataStore.swift

Refactor: Remove token sorting duplication #3066

---

AlphaWallet/Tokens/Types/TokensDataStore.swift

Refactoring extracted from work on ERC1155 support

Refactor: use Promise instead of completion

---

AlphaWallet/Core/Coordinators/WalletBalance/PrivateBalanceFetcher.swift
AlphaWallet/Core/Coordinators/WalletBalance/PrivateTokensDataStoreType.swift
AlphaWallet/Core/Coordinators/WalletBalance/WalletBalanceFetcher.swift
AlphaWallet/Tokens/ViewControllers/TokensViewController.swift
AlphaWallet/Transactions/Storage/TransactionsStorage.swift

Refactor: Update WalletBalanceFetcher with updated code base from TokensDatastore #3068

---

AlphaWallet/Activities/ViewControllers/ActivitiesViewController.swift
AlphaWallet/TokenScriptClient/Coordinators/EventSourceCoordinatorForActivities.swift
AlphaWallet/Transactions/Views/ActivityPageView.swift

Resolve ref cycle for activities view #3011

---

AlphaWallet/Transfer/Coordinators/PaymentCoordinator.swift
AlphaWallet/Transfer/Coordinators/SendCoordinator.swift
AlphaWallet/Transfer/ViewControllers/SendViewController.swift
AlphaWalletTests/Coordinators/SendCoordinatorTests.swift
AlphaWalletTests/Transfer/ViewControllers/SendViewControllerTests.swift

Refactor: `SendCoordinator` remove unused dependencies #3075

---

AlphaWallet/Activities/ActivitiesService.swift

Fix index out of range crash on tokenHolders[0] inActivitiesService #3073

---

AlphaWallet/Tokens/ViewControllers/TokensViewController.swift

Refactor: Improve updating `walletSummaryView` view #3078

---

AlphaWallet/Tokens/ViewModels/TokensViewModel.swift

Fix: crash when tap on Collectibles sub-tab in Wallet tab

---

AlphaWallet/Browser/Factory/WKWebViewConfiguration.swift
AlphaWallet/Browser/ViewControllers/BrowserViewController.swift

Fix: URL shown in dapp browser not tracking changes if the site uses History API to change location

---

AlphaWallet.xcodeproj/project.pbxproj
AlphaWallet/Browser/Coordinators/QRCodeResolutionCoordinator.swift
AlphaWallet/Core/Coordinators/CustomUrlSchemeCoordinator.swift
AlphaWallet/Tokens/Coordinators/SingleChainTokenCoordinator.swift
AlphaWallet/Tokens/Logic/ContractDataDetector.swift
AlphaWallet/Transfer/Coordinators/SendCoordinator.swift

Had wanted to split the fix and refactoring into 2 separate commits, but was too late. Sorry!

Fix contract detection (of name, symbol, decimals, balance) to handle ERC721 not having name and symbol. Also refactoring

---

AlphaWallet.xcodeproj/project.pbxproj
AlphaWallet/Browser/Coordinators/QRCodeResolutionCoordinator.swift
AlphaWallet/Core/Coordinators/CustomUrlSchemeCoordinator.swift
AlphaWallet/Core/Coordinators/WalletBalance/PrivateBalanceFetcher.swift
AlphaWallet/Core/Types/TokenProviderType.swift
AlphaWallet/EtherClient/TrustClient/Models/RawTransaction.swift
AlphaWallet/Market/Coordinators/UniversalLinkCoordinator.swift
AlphaWallet/Tokens/Coordinators/SingleChainTokenCoordinator.swift
AlphaWallet/Tokens/Logic/ContractDataDetector.swift
AlphaWallet/Tokens/Types/TokensDataStore.swift
AlphaWallet/Transactions/Coordinators/SingleChainTransactionEtherscanDataCoordinator.swift
AlphaWallet/Transfer/Coordinators/SendCoordinator.swift

Refactoring: Extract non datastore related code from TokenDatastore #3104

---

AlphaWallet/Accounts/Views/WalletSummaryView.swift
AlphaWallet/Extensions/UIView.swift
AlphaWallet/Tokens/Coordinators/AddHideTokensCoordinator.swift
AlphaWallet/Tokens/ViewControllers/TokensViewController.swift
AlphaWallet/Tokens/ViewModels/TokensViewModel.swift
AlphaWallet/WalletConnect/Coordinator/WalletConnectCoordinator.swift

Hide additional sections (wallet summary, add/hide tokens) while searching on tokens view controller #3102

---

AlphaWallet/Transfer/Coordinators/SendCoordinator.swift
AlphaWallet/Transfer/ViewControllers/SendViewController.swift
AlphaWalletTests/Transfer/ViewControllers/SendViewControllerTests.swift

Refactoring: Remove unused dependencies in SendViewController #3109

---

AlphaWallet/Core/Coordinators/WalletBalance/WalletBalanceCoordinator.swift
AlphaWallet/Export/Coordinators/PromptBackupCoordinator.swift
AlphaWallet/Foundation/Subscribable.swift
AlphaWallet/InCoordinator.swift
AlphaWallet/Tokens/Coordinators/AddHideTokensCoordinator.swift
AlphaWallet/Tokens/Coordinators/TokensCoordinator.swift
AlphaWallet/Tokens/Types/TokenCollection.swift
AlphaWallet/Tokens/Types/TokensDataStore.swift
AlphaWallet/Tokens/ViewControllers/SelectAssetViewController.swift
AlphaWallet/Tokens/ViewControllers/TokenViewController.swift
AlphaWallet/Tokens/ViewControllers/TokensViewController.swift
AlphaWallet/Tokens/ViewModels/SelectAssetViewModel.swift
AlphaWallet/Tokens/ViewModels/TokenViewControllerViewModel.swift
AlphaWallet/Tokens/ViewModels/TokensViewModel.swift
AlphaWallet/Transactions/Coordinators/BalanceCoordinator.swift
AlphaWallet/Transactions/Storage/Session.swift
AlphaWallet/Transactions/ViewControllers/TransactionViewController.swift
AlphaWallet/Transactions/ViewModels/BalanceBaseViewModel.swift
AlphaWallet/Transfer/ViewControllers/SendViewController.swift
AlphaWallet/Transfer/ViewControllers/TransactionConfirmationViewController.swift
AlphaWallet/Transfer/ViewModels/ConfigureTransactionViewModel.swift
AlphaWallet/Transfer/ViewModels/SendViewModel.swift
AlphaWalletTests/Factories/FakeKeystore.swift
AlphaWalletTests/Factories/FakeTokensDataStore.swift
AlphaWalletTests/Factories/WalletSession.swift
AlphaWalletTests/Settings/Coordinators/SettingsCoordinatorTests.swift

Refactoring: Replace retrieving coin tickers from `WalletBalanceCoordinator` #3107

---

AlphaWallet/Extensions/UIView.swift
AlphaWallet/Tokens/ViewModels/TokensViewModel.swift
AlphaWallet/UI/TokenObject+UI.swift
AlphaWallet/UI/Views/AmountTextField.swift

Fix: token icons flashing (because they are switching rapidly between programmatically generated ones and downloaded from OpenSea/GitHub)

---

AlphaWallet/Core/CoinTicker/CoinTickersFetcher.swift
AlphaWallet/Core/CoinTicker/CoinTickersFetcherCache.swift
AlphaWalletTests/Coordinators/InCoordinatorTests.swift

Move tickers caching related code #3115

---

AlphaWallet/UI/TokenObject+UI.swift

Remove duplicate code #3113

---

AlphaWallet/TokenScriptClient/Coordinators/EventSourceCoordinatorForActivities.swift

@vladyslav-iosdev is that true though? Applies for Heco too?

Fix typo in comment

---

AlphaWallet/AppCoordinator.swift
AlphaWallet/Core/Coordinators/WalletBalance/PrivateBalanceFetcher.swift
AlphaWallet/Core/Coordinators/WalletBalance/WalletBalanceCoordinator.swift
AlphaWallet/Core/Coordinators/WalletBalance/WalletBalanceFetcher.swift

Reduce chance of conflict when the big one comes.

Non-functional change for now. Adding an arg to be used for another bigger PR (ERC1155)

---

AlphaWallet/Core/Types/TokenProviderType.swift

`TokenProviderType` add promise version of function #3134

---

AlphaWallet/Tokens/Coordinators/GetERC20BalanceCoordinator.swift
AlphaWallet/Tokens/Coordinators/GetERC875BalanceCoordinator.swift
AlphaWallet/Tokens/Coordinators/GetSymbolCoordinator.swift
AlphaWallet/Tokens/Types/AddressAndRPCServer.swift

Add promise version of functions #3136

---

AlphaWallet/Core/Types/ThreadSafeDictionary.swift
AlphaWallet/Foundation/Subscribable.swift

Applying thread safe for subscribable #3140

---

AlphaWallet/Core/Types/TokenProviderType.swift

Add promise version of functions #3149

---

AlphaWallet/Tokens/Types/TokenCollection.swift

Applying caching for tokens #3143

---

AlphaWallet/EtherClient/TrustClient/Models/RawTransaction.swift
AlphaWallet/InCoordinator.swift
AlphaWallet/Tokens/Coordinators/SingleChainTokenCoordinator.swift
AlphaWallet/Tokens/Types/TokensDataStore.swift
AlphaWallet/Tokens/Types/TransactionCollection.swift
AlphaWallet/Transactions/Coordinators/SingleChainTransactionEtherscanDataCoordinator.swift
AlphaWallet/Transactions/Storage/TransactionsStorage.swift

move realm updates for transactions [part of 3125] #3147

---

AlphaWallet/Activities/ActivitiesService.swift
AlphaWallet/InCoordinator.swift
AlphaWallet/TokenScriptClient/Coordinators/EventSourceCoordinator.swift
AlphaWallet/TokenScriptClient/Coordinators/EventSourceCoordinatorForActivities.swift
AlphaWallet/TokenScriptClient/Models/EventsActivityDataStore.swift
AlphaWallet/TokenScriptClient/Models/EventsDataStore.swift

move realm updates for events [part of 3125] #3145

---

AlphaWallet/Transactions/Storage/Transaction.swift

remove threadSafe from decodeOperations #3151

---

AlphaWallet/Market/Coordinators/UniversalLinkCoordinator.swift
AlphaWalletTests/Coordinators/AppCoordinatorTests.swift
AlphaWalletTests/Factories/FakeKeystore.swift
AlphaWalletTests/Factories/FakeTokensDataStore.swift
AlphaWalletTests/Settings/Coordinators/SettingsCoordinatorTests.swift

Fix tests #3153

---

AlphaWallet/Activities/ActivitiesService.swift
AlphaWallet/Activities/ViewModels/ActivitiesViewModel.swift
AlphaWallet/InCoordinator.swift
AlphaWallet/TokenScriptClient/Models/EventsActivityDataStore.swift

update to ActivitiesService to work on .main queue #3155

---

AlphaWallet/InCoordinator.swift
AlphaWallet/Tokens/Coordinators/GetContractInteractions.swift
AlphaWallet/Tokens/Coordinators/SingleChainTokenCoordinator.swift
AlphaWallet/Tokens/Types/TokensDataStore.swift

Update SingleChainTokenCoordinator with promises #3157

---

AlphaWallet/Core/Coordinators/WalletBalance/WalletBalanceCoordinator.swift
AlphaWallet/Core/Coordinators/WalletBalance/WalletBalanceFetcher.swift
AlphaWallet/InCoordinator.swift

Remove dublication of TransactionsStorage #3159

---

AlphaWallet.xcodeproj/project.pbxproj
AlphaWallet/Core/Coordinators/WalletBalance/PrivateBalanceFetcher.swift
AlphaWallet/Core/Coordinators/WalletBalance/WalletBalanceCoordinator.swift
AlphaWallet/Core/Coordinators/WalletBalance/WalletBalanceFetcher.swift
AlphaWallet/InCoordinator.swift
AlphaWallet/Tokens/Coordinators/SingleChainTokenCoordinator.swift
AlphaWallet/Tokens/Types/TokensDataStore.swift

Update BalanceFetcher with updating tokens using .main queue #3125

---

AlphaWallet/Core/Coordinators/WalletBalance/PrivateBalanceFetcher.swift
AlphaWallet/Core/Coordinators/WalletBalance/WalletBalanceFetcher.swift

Remove unused code #3162

---

AlphaWallet/Tokens/ViewControllers/TokensViewController.swift
AlphaWallet/Tokens/ViewModels/ShowAddHideTokensViewModel.swift
AlphaWallet/Tokens/Views/AddHideTokensView.swift
AlphaWallet/Tokens/Views/SegmentedControl.swift

Make the background behind "Add/Hide Tokens" white #3170

---

AlphaWallet/Tokens/ViewControllers/Collectibles/Coordinators/TokensCardCollectionCoordinator.swift
AlphaWallet/Transactions/Coordinators/TokensCardCoordinator.swift

Is send button wrongly enabled for ERC721/1155 on watched wallet? #3175

---

AlphaWallet/Accounts/ViewModels/WalletSummaryViewModel.swift
AlphaWallet/Accounts/Views/WalletSummaryTableViewCell.swift
AlphaWallet/Accounts/Views/WalletSummaryView.swift
AlphaWallet/Core/Types/WalletSummary.swift
AlphaWallet/Tokens/ViewControllers/TokensViewController.swift
AlphaWallet/Tokens/ViewModels/EthCurrencyHelper.swift
AlphaWallet/Tokens/Views/SegmentedControl.swift
AlphaWallet/Tokens/Views/TokensViewControllerTableViewSectionHeader.swift

Make the space between "Wallet Value Number" and the "Portfolio change in last 24h" bigger #3168

---

AlphaWallet/UI/TokenObject+UI.swift

Token icons are not loading up in the Wallet tab #3167

---

AlphaWallet/Settings/ViewModels/ServerViewModel.swift
AlphaWallet/Settings/Views/ServerViewCell.swift

Make the Network name headline according to the design #3169

---

AlphaWallet/Activities/ActivitiesService.swift
AlphaWallet/InCoordinator.swift

Remove unused links #3185

---

AlphaWallet/Browser/ViewModel/Dapps.swift

If bug:
Fixes #
If not a bug:
Closes #

Update Dapps.swift, Add das.la tool

---

AlphaWallet/Transactions/Coordinators/SingleChainTransactionEtherscanDataCoordinator.swift

Resolve memory leaks #3187

---

AlphaWallet/Core/Coordinators/WalletBalance/PrivateBalanceFetcher.swift
AlphaWallet/EtherClient/OpenSea.swift
AlphaWallet/Tokens/Types/TokensDataStore.swift

A wallet’s NFTs appear in B wallet #3132

---

AlphaWallet/KeyManagement/EtherKeystore.swift

Fix crash while creating a new wallet #3193

---

AlphaWallet/Tokens/Types/TokenObject.swift
AlphaWallet/Tokens/ViewModels/EthTokenViewCellViewModel.swift
AlphaWallet/Tokens/ViewModels/FungibleTokenViewCellViewModel.swift
AlphaWallet/Tokens/ViewModels/NonFungibleTokenViewCellViewModel.swift

Tweak name/symbol display in Wallet #3182

---

AlphaWallet.xcodeproj/project.pbxproj
AlphaWallet/Core/EmailList.swift
AlphaWallet/Core/ViewControllers/ModalViewController.swift
AlphaWallet/Localization/en.lproj/Localizable.strings
AlphaWallet/Localization/es.lproj/Localizable.strings
AlphaWallet/Localization/ja.lproj/Localizable.strings
AlphaWallet/Localization/ko.lproj/Localizable.strings
AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings
AlphaWallet/Settings/Coordinators/HelpUsCoordinator.swift
AlphaWallet/Settings/ViewControllers/CollectUsersEmailViewController.swift
AlphaWallet/Transfer/ViewModels/ConfirmationHeaderViewModel.swift
AlphaWallet/Transfer/Views/ConfirmationHeaderView.swift

Prompt and collect user emails #2807

---

AlphaWallet.xcworkspace/xcshareddata/xcschemes/AlphaWallet.xcscheme
AlphaWallet/KeyManagement/EtherKeystore.swift

Fix crash while adding a new watch wallet #3198

---

AlphaWallet/Tokens/Coordinators/SingleChainTokenCoordinator.swift
AlphaWallet/Tokens/Types/TokensDataStore.swift
AlphaWallet/Tokens/ViewControllers/TokenViewController.swift
AlphaWallet/Tokens/ViewModels/TokenViewControllerViewModel.swift

Fix compilation errors, code refactor. #3201

---

AlphaWallet/Foundation/Subscribable.swift

Add ability to subscribe on queue for Subscribable #3207

---

AlphaWallet/Localization/en.lproj/Localizable.strings
AlphaWallet/Localization/es.lproj/Localizable.strings
AlphaWallet/Localization/ko.lproj/Localizable.strings
AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings

Used in the ERC1155 UI design, but affects ERC721 too

Change "Transfer" button title for sending tokens to "Send"

---

AlphaWallet/Browser/Coordinators/DappRequestSwitchCustomChainCoordinator.swift
AlphaWallet/Extensions/UIAlertController.swift
AlphaWallet/InCoordinator.swift
AlphaWallet/Localization/en.lproj/Localizable.strings
AlphaWallet/Localization/es.lproj/Localizable.strings
AlphaWallet/Localization/ja.lproj/Localizable.strings
AlphaWallet/Localization/ko.lproj/Localizable.strings
AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings
AlphaWallet/Settings/Coordinators/AddRPCServerCoordinator.swift
AlphaWallet/Settings/Models/AddCustomChain.swift

EIP 3085 doesn't work #2966

---

AlphaWallet.xcodeproj/project.pbxproj
AlphaWallet/Browser/Coordinators/DappRequestSwitchCustomChainCoordinator.swift
AlphaWallet/Browser/ViewControllers/SwitchChainRequestViewController.swift
AlphaWallet/Browser/ViewModel/SwitchChainRequestViewModel.swift
AlphaWallet/Localization/en.lproj/Localizable.strings
AlphaWallet/Localization/es.lproj/Localizable.strings
AlphaWallet/Localization/ja.lproj/Localizable.strings
AlphaWallet/Localization/ko.lproj/Localizable.strings
AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings
AlphaWallet/Settings/Coordinators/AddRPCServerCoordinator.swift

Implement designed Prompts for EIP3085 wallet_addEthereumChain support #2908

---

AlphaWallet/Core/Coordinators/WalletBalance/PrivateBalanceFetcher.swift
AlphaWallet/Core/Features.swift
AlphaWallet/EtherClient/OpenSea.swift

Make sure it's not activated for app store submission

Add `Features.isErc1155Enabled = false`

---

AlphaWallet/Tokens/Coordinators/SingleChainTokenCoordinator.swift

Popular tokens add button not working #3218

---

package.json
yarn.lock

Fixed one, another appears :joy:

Fix: vulnerability found by GitHub: CVE-2021-3807

---

AlphaWallet/Transfer/ViewControllers/TransactionConfirmationViewController.swift
AlphaWallet/Transfer/Views/TransactionConfirmationRowInfoView.swift

Tap recipient in transaction confirmation action sheet to review ENS and address broken #3222

---

AlphaWallet/Activities/ActivitiesService.swift
AlphaWallet/Core/SwapToken/SwapTokenService.swift
AlphaWallet/InCoordinator.swift
AlphaWallet/Tokens/Coordinators/SingleChainTokenCoordinator.swift
AlphaWallet/Tokens/Coordinators/TokensCoordinator.swift
AlphaWallet/Tokens/ViewControllers/Collectibles/Coordinators/TokensCardCollectionCoordinator.swift
AlphaWallet/Tokens/ViewControllers/Collectibles/ViewControllers/Erc1155TokenInstanceViewController.swift
AlphaWallet/Tokens/ViewControllers/TokenInstanceViewController.swift
AlphaWallet/Tokens/ViewControllers/TokenViewController.swift
AlphaWallet/Tokens/ViewControllers/TokensCardViewController.swift
AlphaWallet/Tokens/ViewModels/TokenViewControllerViewModel.swift
AlphaWallet/Transactions/Coordinators/ReplaceTransactionCoordinator.swift
AlphaWallet/Transfer/Controllers/TransactionConfigurator.swift
AlphaWallet/Transfer/Coordinators/SendCoordinator.swift
AlphaWallet/Transfer/Types/TransactionType.swift
AlphaWallet/Transfer/ViewControllers/SendViewController.swift
AlphaWallet/Transfer/ViewControllers/TransactionConfirmationViewController.swift
AlphaWallet/Transfer/ViewModels/ConfigureTransactionViewModel.swift
AlphaWallet/Transfer/ViewModels/SendHeaderViewViewModel.swift
AlphaWallet/Transfer/ViewModels/SendViewModel.swift
AlphaWallet/Transfer/ViewModels/TransactionConfirmationViewModel.swift
AlphaWalletTests/Transfer/TransactionConfiguratorTransactionsTests.swift
AlphaWalletTests/Transfer/ViewControllers/SendViewControllerTests.swift

Bugging me for a long time. Especially bad because we had to add one for ERC1155 :)

Rename enum-cases to start with lowercase. Idiomatic

---

AlphaWallet/Settings/Types/Config.swift

To explain the unfortunate situation 😂

Add comment for clarity

---

AlphaWallet/Core/Helpers/RemoteLogger.swift
AlphaWallet/Core/Initializers/MigrationInitializer.swift
AlphaWallet/Tokens/ViewControllers/Collectibles/Coordinators/TokensCardCollectionCoordinator.swift
AlphaWallet/Transactions/Coordinators/SingleChainTransactionEtherscanDataCoordinator.swift
AlphaWalletTests/Redeem/CreateRedeemTests.swift
AlphaWalletTests/Redeem/EventsRestTest.swift
Podfile
Podfile.lock

Add a logging library #3204

---

AlphaWallet/Browser/Views/DappBrowserNavigationBar.swift

The Browser home icon should not disappear when coming back from address input #3252

---

AlphaWallet/Gas/Models/GasNowGasPriceEstimator.swift
AlphaWallet/Gas/Models/GasNowPriceEstimates.swift
AlphaWallet/Settings/Types/RPCServers.swift
AlphaWallet/Transfer/Controllers/TransactionConfigurator.swift
AlphaWallet/Transfer/ViewControllers/ConfigureTransactionViewController.swift

Switch from Gasnow to Etherscan for gas price estimates #3250

---

AlphaWallet/Browser/Views/DappBrowserNavigationBar.swift

Move the Browser Home button to the left (10pt) #3256

---

AlphaWallet/Tokens/ViewControllers/TokensViewController.swift

Move QR Code Scanner camera to the right (10 pt) #3255

---

AlphaWallet/Tokens/Views/OpenSea/WebImageView.swift

WebImageView should probably have at most 1 of its subview visible at any time? #3267

---

AlphaWallet/Analytics/Models/AnalyticsTypes.swift
AlphaWallet/Localization/en.lproj/Localizable.strings
AlphaWallet/Localization/es.lproj/Localizable.strings
AlphaWallet/Localization/ja.lproj/Localizable.strings
AlphaWallet/Localization/ko.lproj/Localizable.strings
AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings
AlphaWallet/WalletConnect/Coordinator/WalletConnectSessionCoordinator.swift
AlphaWallet/WalletConnect/ViewController/WalletConnectSessionDetailsViewController.swift
AlphaWallet/WalletConnect/ViewModel/WalletConnectSessionDetailsViewModel.swift
AlphaWallet/WalletConnect/WalletConnectServer.swift

Add option to switch network in active WalletConnect session #3383

---

AlphaWallet/Core/Helpers/RemoteLogger.swift

Accidentally committed some debugging markers

Fix: spurious debug log changes

---

AlphaWallet/UI/AddressTextField.swift
AlphaWallet/Wallet/ViewControllers/ImportWalletViewController.swift

Vertical alignment for avatar and address under address field (eg in Import wallet screen) is off #3401

---

AlphaWallet/Browser/Coordinators/DappBrowserCoordinator.swift
AlphaWallet/Core/ViewModels/PromptViewModel.swift
AlphaWallet/Localization/en.lproj/Localizable.strings
AlphaWallet/Localization/es.lproj/Localizable.strings
AlphaWallet/Localization/ja.lproj/Localizable.strings
AlphaWallet/Localization/ko.lproj/Localizable.strings
AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings
AlphaWallet/Tokens/Views/TokenInstanceWebView.swift
AlphaWallet/Transfer/Coordinators/SignMessageCoordinator.swift
AlphaWallet/Transfer/Coordinators/TransactionConfirmationCoordinator.swift
AlphaWallet/Transfer/ViewControllers/SignatureConfirmationViewController.swift
AlphaWallet/Transfer/ViewControllers/TransactionConfirmationViewController.swift
AlphaWallet/Transfer/ViewModels/ConfirmationHeaderViewModel.swift
AlphaWallet/Transfer/ViewModels/SignatureConfirmationConfirmationViewModel.swift
AlphaWallet/Transfer/ViewModels/TransactionConfirmationViewModel.swift
AlphaWallet/Transfer/Views/ConfirmationHeaderView.swift
AlphaWallet/WalletConnect/Controllers/SignMessageCoordinatorBridgeToPromise.swift
AlphaWallet/WalletConnect/Coordinator/WalletConnectCoordinator.swift
AlphaWallet/WalletConnect/ViewController/WalletConnectSessionDetailsViewController.swift
AlphaWallet/WalletConnect/ViewController/WalletConnectToSessionViewController.swift
AlphaWallet/WalletConnect/ViewModel/WalletConnectSessionDetailsViewModel.swift
AlphaWallet/WalletConnect/ViewModel/WalletConnectToSessionViewModel.swift
AlphaWallet/WalletConnect/WalletConnectServer.swift

Make WalletConnect signature request be clearer about where it's coming from #3289

---

AlphaWallet/Accounts/Views/AccountViewCell.swift
AlphaWallet/Core/Helpers/BlockieGenerator.swift
AlphaWallet/Core/Views/AddressOrEnsNameLabel.swift
AlphaWallet/Core/Views/BlockieImageView.swift
AlphaWallet/Tokens/Views/OpenSea/WebImageView.swift

Support SVGs for ENS avatar text records #3342

---

AlphaWallet/WalletConnect/WalletConnectServer.swift

Empty WalletConnect cell on iOS 15 device right after connecting #3385

---

CONTRIBUTING.md

Add details (WIP) for contributing guide

---

AlphaWallet.xcodeproj/project.pbxproj
AlphaWallet/Browser/Coordinators/DappRequestSwitchCustomChainCoordinator.swift
AlphaWallet/InCoordinator.swift
AlphaWallet/Localization/en.lproj/Localizable.strings
AlphaWallet/Localization/es.lproj/Localizable.strings
AlphaWallet/Localization/ja.lproj/Localizable.strings
AlphaWallet/Localization/ko.lproj/Localizable.strings
AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings
AlphaWallet/Models/RestartTaskQueue.swift
AlphaWallet/Settings/Coordinators/AddRPCServerCoordinator.swift
AlphaWallet/Settings/Coordinators/EditCustomRPCCoordinator.swift
AlphaWallet/Settings/Coordinators/EnabledServersCoordinator.swift
AlphaWallet/Settings/Models/AddCustomChain.swift
AlphaWallet/Settings/ViewControllers/EditCustomRpcViewController.swift
AlphaWallet/Settings/ViewControllers/EnabledServersViewController.swift
AlphaWallet/Settings/ViewModels/EditCustomRpcViewModel.swift
AlphaWallet/Settings/Views/EditCustomRpcView.swift

Add support for editing custom RPC servers

---

AlphaWallet/Transactions/Views/TokenHistoryChartView.swift

Add thin gray lines behind the chart with edge values #3418

---

AlphaWallet/Settings/Models/AddCustomChain.swift

Spurious (2nd) dialog after hitting cancel when manually adding a network #3421

---

AlphaWallet/Transfer/Views/TransactionConfirmationHeaderView.swift

Fix chevron icon on confirmation screen #3432

---

AlphaWallet/Core/Views/AddressOrEnsNameLabel.swift

Hide empty ens image view if there is no resolved ens icon, (on initial state) #3433

---

AlphaWallet/Transfer/Coordinators/RequestCoordinator.swift

Wallet QR code screen should not show tab bar

---

package.json
yarn.lock

Not used in the app. Just by `danger` utility

Fix vulnerabilities by GitHub for jsonpointer CVE-2021-23807

---

AlphaWallet.xcodeproj/project.pbxproj
AlphaWallet/Analytics/Models/AnalyticsTypes.swift
AlphaWallet/AppCoordinator.swift
AlphaWallet/AppDelegate.swift
AlphaWallet/Donations/WalletQrCodeDonation.swift
AlphaWallet/InCoordinator.swift
AlphaWallet/Info.plist
AlphaWallet/Localization/en.lproj/Localizable.strings
AlphaWallet/Localization/es.lproj/Localizable.strings
AlphaWallet/Localization/ja.lproj/Localizable.strings
AlphaWallet/Localization/ko.lproj/Localizable.strings
AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings

Donate shortcut for wallet QR code

---

AlphaWallet/InCoordinator.swift
AlphaWallet/Models/RestartTaskQueue.swift
AlphaWallet/Settings/Coordinators/EnabledServersCoordinator.swift
AlphaWallet/Settings/Coordinators/SettingsCoordinator.swift
AlphaWallet/Settings/ViewControllers/EnabledServersViewController.swift
AlphaWalletTests/Settings/Coordinators/SettingsCoordinatorTests.swift

When selecting/deselecting networks on the chain list screen, enable/disable changes are not saved if the new chain is saved #3420

---

AlphaWallet.xcodeproj/project.pbxproj
AlphaWallet/Analytics/Models/AnalyticsTypes.swift
AlphaWallet/Localization/en.lproj/Localizable.strings
AlphaWallet/Localization/es.lproj/Localizable.strings
AlphaWallet/Localization/ja.lproj/Localizable.strings
AlphaWallet/Localization/ko.lproj/Localizable.strings
AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings
AlphaWallet/Settings/Coordinators/SettingsCoordinator.swift
AlphaWallet/Settings/Models/SendPrivateTransactionsProvider.swift
AlphaWallet/Settings/Types/Config.swift
AlphaWallet/Settings/ViewControllers/AdvancedSettingsViewController.swift
AlphaWallet/Settings/ViewControllers/ChooseSendPrivateTransactionsProviderViewController.swift
AlphaWallet/Settings/ViewModels/AdvancedSettingsViewModel.swift
AlphaWallet/Settings/ViewModels/ChooseSendPrivateTransactionsProviderViewModel.swift
AlphaWallet/Settings/ViewModels/SwitchTableViewCellViewModel.swift
AlphaWallet/Settings/Views/SelectionTableViewCell.swift
AlphaWallet/Transfer/Coordinators/SendTransactionCoordinator.swift
AlphaWallet/Transfer/Coordinators/TransactionConfirmationCoordinator.swift

Like it was for Ethermine, now the user has another choice

Add support for sending transactions private using Eden (for mainnet and Ropsten)

---

AlphaWallet/Accounts/Coordinators/AccountsCoordinator.swift
AlphaWallet/Accounts/ViewControllers/AccountsViewController.swift
AlphaWallet/Accounts/ViewModels/AccountViewModel.swift
AlphaWallet/Accounts/ViewModels/AccountsViewModel.swift
AlphaWallet/Analytics/Models/AnalyticsTypes.swift
AlphaWallet/Core/Helpers/BlockieGenerator.swift
AlphaWallet/Core/Views/AddressOrEnsNameLabel.swift
AlphaWallet/Core/Views/BlockieImageView.swift
AlphaWallet/Tokens/Coordinators/TokensCoordinator.swift
AlphaWallet/Tokens/ViewControllers/TokensViewController.swift
AlphaWalletTests/Settings/ConfigTests.swift

Have to be careful not to do it for watched wallets as well as places where an address is used but not owned by the wallet, eg. in the send screen.

Log analytics user with ens avatar

---

AlphaWallet/Settings/Types/RPCServers.swift

Update xDai blockscout RPC endpoint according to the `301`

---

AlphaWallet/Extensions/UIBarButtonItem.swift
AlphaWallet/Tokens/Coordinators/TokensCoordinator.swift
AlphaWallet/Tokens/ViewControllers/TokensViewController.swift
AlphaWallet/Tokens/ViewModels/TokensViewModel.swift
AlphaWalletTests/Settings/ConfigTests.swift

Move the search bar down, move Add/Hide Tokens #3444

---

AlphaWallet.xcodeproj/project.pbxproj
AlphaWallet/InCoordinator.swift
AlphaWallet/Tokens/Coordinators/TokensCoordinator.swift
AlphaWallet/Tokens/ViewControllers/TokensViewController.swift
AlphaWallet/WhatsNew/Coordinators/WhatsNewExperimentCoordinator.swift
AlphaWallet/WhatsNew/ViewControllers/WhatsNewListingViewController.swift

Displays at launch, once only.
Comment out this line to display again:
```
guard !hasRan else {
delegate?.didEnd(in: self)
return
}
```

Show What's new UI to let user know about wallet QR code being accessible in Spotlight/Siri

---

AlphaWallet.xcodeproj/project.pbxproj
AlphaWallet/Analytics/Models/AnalyticsTypes.swift
AlphaWallet/Localization/en.lproj/Localizable.strings
AlphaWallet/Localization/es.lproj/Localizable.strings
AlphaWallet/Localization/ja.lproj/Localizable.strings
AlphaWallet/Localization/ko.lproj/Localizable.strings
AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings
AlphaWallet/Settings/Coordinators/PingInfuraCoordinator.swift
AlphaWallet/Settings/Coordinators/SettingsCoordinator.swift
AlphaWallet/Settings/ViewControllers/AdvancedSettingsViewController.swift
AlphaWallet/Settings/ViewModels/AdvancedSettingsViewModel.swift

Just tap to trigger a request to fetch the block number from Ethereum mainnet. For support requests.

Add diagnostic action in Settings > Advanced > Ping Infura

---

AlphaWallet/Analytics/Models/AnalyticsTypes.swift
AlphaWallet/Localization/en.lproj/Localizable.strings
AlphaWallet/Localization/es.lproj/Localizable.strings
AlphaWallet/Localization/ja.lproj/Localizable.strings
AlphaWallet/Localization/ko.lproj/Localizable.strings
AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings
AlphaWallet/Tokens/Coordinators/TokensCoordinator.swift

Add fiat on ramp to Wallet tab

---

AlphaWallet/WhatsNew/ViewControllers/WhatsNewListingViewController.swift

Closes #3520
1. Delete app.
2. Install new copy of app.
3. Start app.
4. Create new wallet.
5. Tap X on "WhatsNewListing".
6. **Expects** "WhatsNewListing" to be dismissed.
7. Tap CONTINUE.
8. **Expects** "Back up" to be dismissed.

Corrected code that dismisses WhatsNewListingViewController but prevents other views from receiving user interaction

---

AlphaWallet/Style/AppStyle.swift
AlphaWallet/Tokens/ViewControllers/TokensViewController.swift

Increase Wallet main screen non-header rows height to 80 points.

---

.travis.yml

Changed travis_retry to travis_wait in .travis.yml file

---

AlphaWallet/Core/Features.swift
AlphaWallet/KeyManagement/EtherKeystore.swift
AlphaWallet/KeyManagement/Keystore.swift
AlphaWallet/Settings/ViewModels/ExportJsonKeystoreFileViewModel.swift
AlphaWalletTests/Factories/FakeKeystore.swift

Add support to export JSON Keystore files of private key for 0th address derived from seed

---

AlphaWallet/Core/Coordinators/FilterTokensCoordinator.swift

Sort tokens Value: Descending in the Wallet tab by default #3528

---

AlphaWallet/Style/AppStyle.swift
AlphaWallet/Tokens/ViewControllers/TokensViewController.swift
AlphaWallet/Tokens/ViewModels/TokensViewModel.swift
AlphaWallet/Tokens/Views/OpenSea/OpenSeaNonFungibleTokenViewCell.swift
AlphaWallet/Tokens/Views/OpenSea/WebImageView.swift

Reduce image reloading, if it hasn't changed #3525

---

AlphaWallet/Settings/ViewControllers/ExportJsonKeystoreFileViewController.swift

Closes #3563 
https://user-images.githubusercontent.com/1050309/146351295-1011d926-e1fa-4539-9a62-da11bc27f044.MP4

Pop ExportJsonKeystoreFileViewController after user taps on Error Message Alert's ok button

---

AlphaWallet/Analytics/Coordinators/AnalyticsCoordinator.swift
AlphaWallet/Analytics/Coordinators/AnalyticsService.swift
AlphaWallet/Analytics/Coordinators/MixpanelCoordinator.swift
AlphaWallet/Analytics/Models/AnalyticsTypes.swift
AlphaWallet/Tokens/Views/TokenInstanceWebView.swift
AlphaWallet/Transfer/Coordinators/SendTransactionCoordinator.swift
AlphaWallet/Transfer/Coordinators/TransactionConfirmationCoordinator.swift
AlphaWallet/WalletConnect/Coordinator/WalletConnectCoordinator.swift
AlphaWalletTests/Coordinators/AppCoordinatorTests.swift

Includes starting a new type of analytics — errors.

Add analytics log for nonce too low error when sending transactions

---

.travis.yml

Closes #3570
Closes #3573
The [cache](https://app.travis-ci.com/github/AlphaWallet/alpha-wallet-ios/caches).
The [result](https://app.travis-ci.com/github/AlphaWallet/alpha-wallet-ios/builds/243689730).

Modified .travis.yml to use a matrix and the default install scripts

---

AlphaWallet/Settings/ViewControllers/ExportJsonKeystorePasswordViewController.swift

Delayed setting UITextField as first responder via viewDidAppear instead of viewDidLoad

---

AlphaWalletShare/ShareContextHandler.swift

Warning about UIApplication.shared being accessed in ShareContextHandler #3562

---

AlphaWallet/Localization/en.lproj/Localizable.strings
AlphaWallet/Localization/es.lproj/Localizable.strings
AlphaWallet/Localization/ja.lproj/Localizable.strings
AlphaWallet/Localization/ko.lproj/Localizable.strings
AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings
AlphaWallet/Tokens/ViewControllers/TokensViewController.swift

Added place holder text to search bar in TokenViewController

---

AlphaWallet/Tokens/Views/OpenSea/WebImageView.swift
AlphaWallet/WebImage/web_image.html

Improve WebImage Displaying #3593

---

AlphaWallet.xcodeproj/project.pbxproj
AlphaWallet/Browser/Views/NativeCryptoCurrencyBalanceView.swift
AlphaWallet/Core/Coordinators/ServerUnavailableCoordinator.swift
AlphaWallet/Settings/ViewControllers/ExportJsonKeystoreFileViewController.swift
AlphaWallet/Tokens/Views/TokensViewControllerTableViewSectionHeader.swift
AlphaWallet/Transfer/Coordinators/SignMessageCoordinator.swift
AlphaWallet/Transfer/Coordinators/TransactionConfirmationCoordinator.swift
AlphaWallet/UI/SuccessOverlayView.swift
AlphaWallet/UI/WhereIsWalletAddressFoundOverlayView.swift
AlphaWallet/WalletConnect/Coordinator/WalletConnectCoordinator.swift
AlphaWallet/WalletConnect/Coordinator/WalletConnectToSessionCoordinator.swift

Remove deprecation warnings UIApplication.shared.keyWindow #3589

---

AlphaWallet/Tokens/Collectibles/ViewControllers/TokensCardCollectionViewController.swift
AlphaWallet/Tokens/Collectibles/Views/AssetsPageView.swift

Configure layout for collectibles tokens #3606

---

AlphaWallet/Core/Features.swift
AlphaWallet/KeyManagement/EtherKeystore.swift
AlphaWallet/Localization/en.lproj/Localizable.strings
AlphaWallet/Localization/es.lproj/Localizable.strings
AlphaWallet/Localization/ja.lproj/Localizable.strings
AlphaWallet/Localization/ko.lproj/Localizable.strings
AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings
AlphaWallet/UI/Form/HDWallet+Extension.swift
AlphaWallet/UI/Form/MnemonicLengthRule.swift
AlphaWalletTests/EtherClient/EtherKeystoreTests.swift

Closes #3447
This branch is for testing the 24 word seed import feature and what other UI it might impact.

24 word seed phrase feature

---

AlphaWallet/Wallet/ViewControllers/ImportWalletViewController.swift

Fixes #3624
**Test**
1. Write seed phrase in notepad. Add extra return at the end of the seed phrase. Copy seed phrase with extra linefeed/carriage returns
2. Go to app and import a wallet. Paste the copied seed phrase with extra line feeds/carriage returns into the text area. 
3. Press import button.
**Expects**
4. Wallet to be imported.

Fixed newlines bug in ImportWalletViewController

---

AlphaWallet/Core/Coordinators/WalletBalance/PrivateBalanceFetcher.swift

Fetching ERC1155 (and probably ERC721) tokens owned using OpenSea API is broken? #3654

---

AlphaWallet/Tokens/Coordinators/AddHideTokensCoordinator.swift
AlphaWallet/Tokens/ViewControllers/AddHideTokensViewController.swift

Add code that auto populates the Add Custom Token screen when the search string is a valid address

---

AlphaWallet/Activities/ViewControllers/ActivitiesViewController.swift
AlphaWallet/Core/Coordinators/WalletBalance/PrivateBalanceFetcher.swift
AlphaWallet/Core/Helpers/KeyboardChecker.swift
AlphaWallet/Core/ViewControllers/ModalViewController.swift
AlphaWallet/Core/Views/AddressOrEnsNameLabel.swift
AlphaWallet/Market/ViewControllers/ImportMagicTokenViewController.swift
AlphaWallet/Market/ViewControllers/StatusViewController.swift
AlphaWallet/Tokens/Collectibles/ViewControllers/TokenCardSelectionViewController.swift
AlphaWallet/Tokens/ViewControllers/AddHideTokensViewController.swift
AlphaWallet/Tokens/ViewControllers/TokensViewController.swift
AlphaWallet/Transfer/ViewControllers/ConfigureTransactionViewController.swift
AlphaWallet/Transfer/ViewControllers/SendTransactionErrorViewController.swift
AlphaWallet/Transfer/ViewControllers/SignatureConfirmationViewController.swift
AlphaWallet/Transfer/ViewControllers/TransactionConfirmationViewController.swift
AlphaWallet/UI/LoadingView.swift
AlphaWallet/UI/WhereIsWalletAddressFoundOverlayView.swift
AlphaWallet/WalletConnect/ViewController/WalletConnectSessionsViewController.swift
AlphaWallet/WalletConnect/ViewController/WalletConnectToSessionViewController.swift

Reduce iOS 13 warnings #3665

---

AlphaWallet/Core/Coordinators/WalletBalance/PrivateBalanceFetcher.swift

Fix Erc1155TokenIdsFetcher memory leaks #3670

---

AlphaWallet/UI/TokenObject+UI.swift

Apply caching for Subscribable<TokenImage> #3674

---

AlphaWallet/Core/Coordinators/WalletBalance/WalletBalanceFetcher.swift

Fiat value not appearing for all tokens at the same time #3644

---

AlphaWallet/Accounts/ViewControllers/AccountsViewController.swift
AlphaWallet/Core/Coordinators/WalletBalance/WalletBalanceCoordinator.swift
AlphaWallet/Transactions/Coordinators/BalanceCoordinator.swift

Fix AccountsViewController memory leaks #3672

---

AlphaWallet/Core/Coordinators/WalletBalance/WalletBalanceCoordinator.swift

Fix build error #3682

---

AlphaWallet/Settings/Types/RPCServers.swift

Fix broken build

---

AlphaWallet/Activities/ViewControllers/ActivitiesViewController.swift
AlphaWallet/Tokens/ViewControllers/AddHideTokensViewController.swift
AlphaWallet/Tokens/ViewControllers/TokensViewController.swift

After searching in Wallet tab, can't tap search results in iOS 13.7. Works in iOS 15 #3681

---

AlphaWallet/Tokens/ViewControllers/AddHideTokensViewController.swift
AlphaWallet/Tokens/ViewModels/WalletTokenViewCellViewModel.swift

Balance incorrect on Add/Hide token page #3645

---

AlphaWallet/Settings/Models/AddCustomChain.swift

improve building Blockchain Explorer URL #3677

---

AlphaWallet.xcodeproj/project.pbxproj
Podfile
Podfile.lock

Remove unused pods #3693

---

AlphaWallet/Tokens/Coordinators/SingleChainTokenCoordinator.swift
AlphaWallet/Transactions/Coordinators/TokensCardCoordinator.swift

Remove unused rump code #3695

---

AlphaWallet.xcodeproj/project.pbxproj
AlphaWallet/Core/Device.swift
AlphaWallet/Core/Helpers/ScreenChecker.swift
AlphaWallet/Core/ViewControllers/ModalViewController.swift
AlphaWallet/Settings/Types/RPCServers.swift
Podfile
Podfile.lock

Empty new features view #3684

---

AlphaWallet/Activities/ActivitiesService.swift
AlphaWallet/Extensions/UIBarButtonItem.swift
AlphaWallet/Tokens/Collectibles/Coordinators/TokensCardCollectionCoordinator.swift
AlphaWallet/Tokens/Coordinators/SingleChainTokenCoordinator.swift
AlphaWallet/Tokens/ViewControllers/TokensCardViewController.swift
AlphaWallet/Transactions/Coordinators/TokensCardCoordinator.swift

Missing activities for erc721, erc1155 tokens #3667

---

AlphaWallet/Tokens/ViewControllers/TokensViewController.swift

Improve the transition to Search Box at the top #3529

---

AlphaWallet/Localization/en.lproj/Localizable.strings
AlphaWallet/Localization/es.lproj/Localizable.strings
AlphaWallet/Localization/ja.lproj/Localizable.strings
AlphaWallet/Localization/ko.lproj/Localizable.strings
AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings
AlphaWallet/Tokens/Coordinators/TokensCoordinator.swift

Add option to rename wallet straight from a dotted menu in the top right #3689

---

AlphaWallet/Browser/Coordinators/DappBrowserCoordinator.swift

Fix: repeated error popups when user accesses a dapp which makes `eth_call` with a watch wallet

---

AlphaWallet/UI/ContainerViewWithShadow.swift

Dapp browser fallback icons have square focus on initial appearance #3517

---

Makefile
Podfile
Podfile.lock

Closes #3715
**Testing**
```
make clean && make bootstrap && make test
```
**Expects**
All tests to pass.

Add test options to Makefile

---

AlphaWallet/AppCoordinator.swift
AlphaWallet/Settings/Models/LiveLocaleSwitcherBundle.swift

Closes: #3651 and closes: #3680

Fixed LiveLocaleSwitcherBundle Localization Bug

---

AlphaWallet/Tokens/Types/TokenObject.swift

App crashes on launch #3699

---

AlphaWallet/Assets.xcassets/activities_empty_list.imageset/Contents.json
AlphaWallet/Localization/en.lproj/Localizable.strings
AlphaWallet/Localization/es.lproj/Localizable.strings
AlphaWallet/Localization/ja.lproj/Localizable.strings
AlphaWallet/Localization/ko.lproj/Localizable.strings
AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings
AlphaWallet/Settings/Views/EmptyTableView.swift
AlphaWallet/Tokens/ViewControllers/TokensViewController.swift

Closes #3566
When there are no assets or collectibles, the `EmptyTableView` will be displayed with the corresponding message.
When searching tokens and there are no tokens matching the search criteria, the `EmptyTableView` will be displayed with the corresponding message. The `EmptyTableView` is currently added to the `tableView`.
There is however another `EmptyView` which is part of `StatefulViewController` but I have no idea how to change and trigger it.

Added code to display EmptyTableView when there are no items or the search filter did not turn up anything

---

AlphaWallet/AppCoordinator.swift
AlphaWallet/Browser/ViewControllers/BrowserViewController.swift
AlphaWallet/Market/Coordinators/UniversalLinkCoordinator.swift

Add support for universal link with embedded URL so that when the link is is tapped, URL is opened in dapp browser #3708

---

AlphaWallet/Settings/Types/RPCServers.swift

Change block range <eth_getLogs> for Polygon network #3734

---

AlphaWallet/AppCoordinator.swift
AlphaWallet/Core/BuyToken/Ramp/Ramp.swift
AlphaWallet/Core/SwapToken/SwapTokenService.swift
AlphaWallet/InCoordinator.swift
AlphaWalletTests/Coordinators/InCoordinatorTests.swift
AlphaWalletTests/Coordinators/TokensCoordinatorTests.swift

Move `tokenActionsService` initialization to `AppCoordinator` #3731

---

AlphaWalletTests/Market/UniversalLinkCoordinatorTests.swift

Tests broken on master #3736

---

AlphaWallet/Browser/Types/Favicon.swift
AlphaWallet/Browser/Views/BrowserHistoryCell.swift

Favicons detection looks broken #3534

---

AlphaWallet/Core/Coordinators/WalletBalance/WalletBalanceFetcher.swift

Wallet fiat total don't get refreshed after enabling/disabling chain until app is restarted #3738

---

AlphaWallet/Settings/Types/ServiceProvider.swift

Fixed bug in ServiceProvider where MFMailComposeViewController won't respond after sending/cancelling a previous email.

---

AlphaWallet.xcodeproj/project.pbxproj
AlphaWallet/AppCoordinator.swift
AlphaWallet/Core/Enjin/EnjinProvider.swift
AlphaWallet/Core/Enjin/EnjinUserManagementInterceptor.swift
AlphaWallet/EtherClient/OpenSea.swift
AlphaWallet/TokenScriptClient/Coordinators/AssetDefinitionStoreCoordinator.swift

Refactor Enjin OpenSea providers #3757

---

AlphaWallet/Accounts/ViewControllers/AccountsViewController.swift
AlphaWallet/Accounts/Views/AccountViewTableSectionHeader.swift
AlphaWallet/Style/AppStyle.swift

Adjusted height and font of AccountViewTableSectionHeader in AccountsViewController #3764

---

AlphaWallet/Settings/ViewControllers/SettingsViewController.swift
AlphaWallet/Style/AppStyle.swift

Changed height of Change/Add Wallet row in SettingsViewController to 80.0 #3772

---

AlphaWallet/Assets.xcassets/icons-system-arrow-right.imageset/Contents.json
AlphaWallet/Settings/Views/SettingTableViewCell.swift

Removed accessoryType and added chevron image view as accessoryView to SettingTableViewCell #3771

---

AlphaWallet/Style/AppStyle.swift
AlphaWallet/Transfer/ViewModels/SendHeaderViewViewModel.swift

Changed appreciated/depreciated colours in TokenInfoPageViewModel #3768

---

AlphaWallet/InCoordinator.swift
AlphaWallet/Style/AppStyle.swift

Change the font in UITabBarItem appearance #3760

---

AlphaWallet/Style/AppStyle.swift
AlphaWallet/Tokens/ViewControllers/TokensCardViewController.swift
AlphaWallet/Tokens/ViewControllers/TokensViewController.swift
AlphaWallet/Wallet/ViewControllers/SeedPhraseBackupIntroductionViewController.swift

Closes #3767
Merge after #3778

Added show/hideNavigationBarTopSeparatorLineInScrollEdgeAppearance functions and changed ScrollEdgeAppearance behaviour in TokensViewController #3767

---

AlphaWallet/Tokens/ViewControllers/TokensViewController.swift
AlphaWallet/Tokens/Views/OpenSea/OpenSeaNonFungibleTokenViewCell.swift

Right after importing a wallet and going to the Collectibles tab and waiting for a short while, the app shows this (a vertical gap) #3795

---

AlphaWallet/Settings/Types/RPCServers.swift

Check/Replace the RPC for Fantom #3776

---

AlphaWallet/Settings/Views/EmptyTableView.swift

Text for No Browse Networks Available is missing #3791

---

AlphaWallet/Activities/ViewModels/ActivityStateViewViewModel.swift
AlphaWallet/Activities/Views/DefaultActivityItemViewCell.swift
AlphaWallet/Transactions/ViewModels/TransactionRowCellViewModel.swift

Remove green sent/received icons from the Activity #3770

---

AlphaWallet/AddMultipleCustomRpc/AddMultipleCustomRpcView.swift
AlphaWallet/AppCoordinator.swift
AlphaWallet/Core/Device.swift
AlphaWallet/Core/SwapToken/HoneySwap/HoneySwap.swift
AlphaWallet/Core/SwapToken/Uniswap/Uniswap.swift
AlphaWallet/Donations/WalletQrCodeDonation.swift
AlphaWallet/Rpc Network/AvailableRpcNetwork.swift
AlphaWallet/Style/AppStyle.swift
AlphaWallet/TokenScriptClient/Coordinators/EventSourceCoordinator.swift
AlphaWallet/Tokens/Collectibles/Views/AssetsPageView.swift

Remove all checks for iOS13 in code #3761

---

AlphaWallet/Settings/ViewControllers/SaveCustomRpcBrowseViewController.swift
AlphaWallet/Settings/Views/SaveCustomRpcBrowseView.swift

Modified code to squeeze some more space out from SaveCustomRpcBrowseViewController

---

AlphaWallet/Tokens/Collectibles/ViewModels/AssetsPageViewModel.swift
AlphaWallet/Tokens/Collectibles/Views/AssetsPageView.swift
AlphaWallet/Transactions/Views/TokenPagesContainerView.swift

Tweak bottom insets for `Assets` view #3796

---

AlphaWallet/Core/Views/WebImageView.swift

Fix memory leak in WebImageView #3823

---

AlphaWallet/Core/Types/TokenProviderType.swift
AlphaWallet/Tokens/Coordinators/GetDecimalsCoordinator.swift
AlphaWallet/Tokens/Coordinators/GetERC20BalanceCoordinator.swift
AlphaWallet/Tokens/Coordinators/GetERC721BalanceCoordinator.swift
AlphaWallet/Tokens/Coordinators/GetERC721ForTicketsBalanceCoordinator.swift
AlphaWallet/Tokens/Coordinators/GetIsERC1155ContractCoordinator.swift
AlphaWallet/Tokens/Coordinators/GetIsERC721ContractCoordinator.swift
AlphaWallet/Tokens/Coordinators/GetIsERC721ForTicketsContractCoordinator.swift
AlphaWallet/Tokens/Coordinators/GetIsERC875ContractCoordinator.swift
AlphaWallet/Tokens/Coordinators/GetNameCoordinator.swift
AlphaWallet/Tokens/Coordinators/GetSymbolCoordinator.swift
AlphaWallet/Tokens/Coordinators/SingleChainTokenCoordinator.swift
AlphaWallet/Tokens/Logic/ContractDataDetector.swift
AlphaWallet/Transfer/Collectibles/Coordinators/TransferCollectiblesCoordinator.swift

Refactor TokenProviderType removing unused callback implementations #3821

---

AlphaWallet/Core/Features.swift

@oa-s do you see any problems if we enable it?

Enable importing 24-word seed phrases

---

AlphaWallet/Tokens/ViewControllers/TokenInstanceViewController.swift

Removed gray line under navigation bar of TokenInstanceViewController #3798

---

AlphaWallet/Tokens/Collectibles/ViewControllers/TokensCardCollectionViewController.swift
AlphaWallet/Tokens/Collectibles/ViewModels/TokensCardCollectionViewControllerViewModel.swift
AlphaWallet/Tokens/ViewControllers/TokensCardViewController.swift
AlphaWallet/Tokens/ViewModels/TokensCardViewModel.swift
AlphaWallet/Transactions/Views/TokenPagesContainerView.swift

When you open ERC721 or ERC 1155 collection, Assets tab should be opened by default #3826

---

AlphaWallet.xcodeproj/project.pbxproj
AlphaWallet/Accounts/Coordinators/AccountsCoordinator.swift
AlphaWallet/Accounts/ViewControllers/AccountsViewController.swift
AlphaWallet/Core/UnstoppableDomains/AddressOrEnsResolution.swift
AlphaWallet/Core/UnstoppableDomains/DomainResolutionService.swift
AlphaWallet/Core/UnstoppableDomains/UnstoppableDomainsV1Resolver.swift
AlphaWallet/Core/UnstoppableDomains/UnstoppableDomainsV2Resolver.swift
AlphaWallet/Core/Views/AddressOrEnsNameLabel.swift
AlphaWallet/Settings/Types/Constants+Credentials.swift
AlphaWallet/Settings/Types/Constants.swift
AlphaWallet/Tokens/Coordinators/ENSReverseLookupCoordinator.swift
AlphaWallet/Tokens/Coordinators/GetENSOwnerCoordinator.swift
AlphaWallet/Tokens/Coordinators/GetWalletNameCoordinator.swift
AlphaWallet/Transfer/Types/RecipientResolver.swift
AlphaWallet/Transfer/ViewControllers/RequestViewController.swift
AlphaWallet/Transfer/ViewModels/TransactionConfirmationViewModel.swift
AlphaWallet/UI/AddressTextField.swift
AlphaWallet/Wallet/ViewControllers/RenameWalletViewController.swift

Unstoppable Domains name resolution deprecation/changes #3722

---

AlphaWallet/Transfer/ViewControllers/ConfigureTransactionViewController.swift
AlphaWallet/Transfer/Views/SlidableTextField.swift

Changed input view of SlidableTextField to .numberpad and added coded to allow entry of only numbers or an empty field.

---

AlphaWallet/Tokens/Collectibles/ViewControllers/TokensCardCollectionViewController.swift
AlphaWallet/Tokens/ViewControllers/TokensCardViewController.swift

Remove unwanted layout animation if tap NFT in Wallet search results #3861

---

AlphaWallet/Browser/Types/DappAction.swift
AlphaWallet/Browser/ViewControllers/BrowserViewController.swift
AlphaWallet/Core/Coordinators/WalletBalance/PrivateBalanceFetcher.swift
AlphaWallet/Core/Helpers/RemoteLogger.swift
AlphaWallet/Core/Initializers/MigrationInitializer.swift
AlphaWallet/Core/Views/WebImageView.swift
AlphaWallet/Donations/WalletQrCodeDonation.swift
AlphaWallet/EtherClient/OpenSea.swift
AlphaWallet/Extensions/Session+PromiseKit.swift
AlphaWallet/Settings/ViewControllers/SaveCustomRpcBrowseViewController.swift
AlphaWallet/TokenScriptClient/Coordinators/AssetDefinitionStoreCoordinator.swift
AlphaWallet/Tokens/Coordinators/DASNameLookupCoordinator.swift
AlphaWallet/Tokens/Coordinators/GetENSOwnerCoordinator.swift
AlphaWallet/Transactions/Coordinators/SingleChainTransactionEtherscanDataCoordinator.swift
AlphaWallet/Transactions/Storage/TransactionsStorage.swift
AlphaWallet/Transfer/Controllers/TransactionConfigurator.swift
AlphaWallet/Transfer/Coordinators/SendTransactionCoordinator.swift
AlphaWallet/Transfer/Coordinators/TransactionConfirmationCoordinator.swift
AlphaWallet/UI/TokenObject+UI.swift
AlphaWallet/WalletConnect/Coordinator/WalletConnectCoordinator.swift
AlphaWallet/WalletConnect/Providers/v1/WalletConnectV1Provider.swift
AlphaWallet/WalletConnect/Providers/v2/WalletConnectV2Provider.swift
AlphaWallet/WalletConnect/Types/WalletConnectRequestConverter.swift
AlphaWalletTests/Redeem/CreateRedeemTests.swift

eg. we can search across the project with the regex: `[gone]log\(`.
Or in the file for "log("

Rename debug logging functions to have a postfix so it's easier to search for them

---

AlphaWallet/Foundation/Formatter.swift
AlphaWalletTests/Models/EtherTests.swift

Tests broken #3865

---

AlphaWallet/Tokens/Collectibles/Coordinators/TokensCardCollectionCoordinator.swift
AlphaWallet/Transactions/Coordinators/TokensCardCoordinator.swift

Tweak back button for TokenInstanceViewController #3879

---

AlphaWallet/Core/CoinTicker/CoinTickersFetcher.swift

Update CoinTickersFetcher with removing creating AlphaWallet.Address for Ticker as its expensive operation #3881

---

AlphaWallet/Tokens/Views/OpenSea/OpenSeaNonFungibleTokenViewCell.swift
AlphaWallet/UI/TokenObject+UI.swift

Set token icons loading priority order: `.alphaWallet`, `OpenSea`, `.thirdParty` #3828

---

AlphaWallet/Settings/ViewControllers/EnabledServersViewController.swift

Avoid trigger UI after go back without changing enabled chains #3890

---

AlphaWallet/Activities/Coordinators/ActivitiesCoordinator.swift
AlphaWallet/AppCoordinator.swift
AlphaWallet/InCoordinator.swift
AlphaWallet/Settings/Coordinators/SettingsCoordinator.swift
AlphaWallet/Style/AppStyle.swift
AlphaWallet/Tokens/Coordinators/TokensCoordinator.swift
AlphaWallet/Transactions/Coordinators/TransactionCoordinator.swift

Grayed navigation bar after creating or watching a new wallet #3912

---

AlphaWallet/Core/BuyToken/Ramp/Ramp.swift
AlphaWallet/Core/CoinTicker/CoinTickersFetcher.swift
AlphaWallet/Core/Enjin/EnjinProvider.swift
AlphaWallet/Core/SwapToken/HoneySwap/HoneySwap.swift
AlphaWallet/Core/SwapToken/Oneinch/Oneinch.swift
AlphaWallet/Core/SwapToken/QuickSwap/QuickSwap.swift
AlphaWallet/Core/SwapToken/Uniswap/UniswapERC20Token.swift
AlphaWallet/EtherClient/OpenSea.swift
AlphaWallet/EtherClient/TrustClient/AlphaWalletService.swift
AlphaWallet/Gas/Models/GasPriceEstimator.swift
AlphaWallet/Localization/en.lproj/Localizable.strings
AlphaWallet/Localization/es.lproj/Localizable.strings
AlphaWallet/Localization/fi.lproj/Localizable.strings
AlphaWallet/Localization/ja.lproj/Localizable.strings
AlphaWallet/Localization/ko.lproj/Localizable.strings
AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings
AlphaWallet/Market/Coordinators/ImportMagicLinkCoordinator.swift
AlphaWallet/Settings/Coordinators/ServersCoordinator.swift
AlphaWallet/Settings/Models/SendPrivateTransactionsProvider.swift
AlphaWallet/Settings/Types/ConfigExplorer.swift
AlphaWallet/Settings/Types/Constants.swift
AlphaWallet/Settings/Types/RPCServers.swift
AlphaWallet/Tokens/Coordinators/SingleChainTokenCoordinator.swift
AlphaWallet/Tokens/Types/TokenCollection.swift
AlphaWallet/Tokens/ViewModels/TokenViewControllerViewModel.swift
AlphaWallet/Transactions/Coordinators/SingleChainTransactionEtherscanDataCoordinator.swift
AlphaWallet/Transfer/Controllers/TransactionConfigurator.swift
AlphaWallet/UI/TokenObject+UI.swift

Add support for Arbitrum Rinkey, testnet
